stages:
  - deploy

generate_json:
  stage: deploy
  script:
    #- sh -x test.sh
    - |
      MY_ARRAY=(1 2 3 4 5 6 )
      for i in ${MY_ARRAY[@]}; do
        echo "Building $i";
        # Do something with $i
      done  
      
      
  artifacts:
    paths:
      - changed_files.txt
  only:
    - stage
  tags:
    - kunlun-runner