drop table if exists dim.dim_short_video_account_device_info;
create table dim.dim_short_video_account_device_info (
     product_id                INT            not null default ""  comment "产品id"
    ,user_id                   BIGINT         not null             comment "用户Id"
    ,account                   VARCHAR(765)   not null default ""  comment "用户账号"
    ,nick                      VARCHAR(765)   not null default ""  comment "昵称"
    ,sex                       INT            not null default "0" comment "性别"
    ,create_tm                 DATETIME       not null             comment "创建时间"
    ,last_login_tm             DATETIME       not null             comment "最后登录时间"
    ,chl2                      VARCHAR(765)   not null default ""  comment "初始渠道id"
    ,chl                       VARCHAR(765)   not null default ""  comment "最新渠道id"
    ,mt                        INT            not null default "0" comment "最新平台号,1为ios 4为安卓"
    ,mt2                       INT            not null default "0" comment "初始平台号,1为ios 4为安卓"
    ,unique_cdreader_id        VARCHAR(765)                        comment "畅读唯一设备号"
    ,current_language2         INT                                 comment "包初始语言"
    ,current_language          INT                                 comment "最新用户使用语言"
    ,corever                   INT                                 comment "core,默认1,注册时core"
    ,corever2                  INT                                 comment "core,默认1,当前core"
    ,ad_id                     VARCHAR(765)                        comment "广告id"
    ,status                    INT            default "0"          comment "用户状态：0 正常，1 禁用，2 审核中，3 审核拒绝"
    ,reg_country               VARCHAR(765)                        comment "注册国家"
    ,row_update_time           DATETIME                            comment "数据更新时间"
    ,version                   INT                                 comment "当前版本"
    ,is_delete                 TINYINT                             comment "是否删除"
    ,avatar                    VARCHAR(765)                        comment "用户头像 url"
    ,install_date              DATETIME                            comment ""
    ,source_chl                VARCHAR(150)                        comment "渠道值"
    ,idfa                      VARCHAR(300)                        comment "idfa"
    ,email                     VARCHAR(765)                        comment ""
    ,is_official               TINYINT        default "0"          comment "是否正式用户"
    ,unique_id                 VARCHAR(300)                        comment "三方登陆id"
    ,third_party_id            TINYINT        default "0"          comment "三方登陆类型枚举"
    ,country                   VARCHAR(65533)                      comment "当前国家"
    ,app_ver                   VARCHAR(50)                         comment "app版本号"
    ,locale                    VARCHAR(50)                         comment "区域设置"
    ,userid                    VARCHAR(255)                        comment "用户id"
    ,langid                    INT                                 comment "语言id"
    ,time_stamp                BIGINT                              comment "时间戳"
    ,ver                       INT                                 comment "版本"
    ,device2                   VARCHAR(50)                         comment "设备型号"
    ,sys_language              VARCHAR(50)                         comment "系统语言"
    ,mt_device                 VARCHAR(50)                         comment "类型"
    ,os_ver                    VARCHAR(50)                         comment "操作系统版本"
    ,appid                     VARCHAR(50)                         comment "应用id"
    ,x                         VARCHAR(50)                         comment "x"
    ,utc_offset                INT                                 comment "utc偏移量"
    ,guid                      VARCHAR(255)                        comment "guid"
    ,support_utc_time          INT                                 comment "支持utc时间"
    ,device                    VARCHAR(50)                         comment "设备"
    ,android_id                VARCHAR(50)                         comment "android id"
    ,device_token              VARCHAR(255)                        comment ""
    ,sign_notify               TINYINT        default "0"          comment "是否开启签到推送"
    ,app_notify                TINYINT        default "0"          comment "是否开启推送"
    ,region_id                 SMALLINT       default "1"          comment "归属区域 id，1：香港，2：北美；"
    ,real_time_activity_notify INT                                 comment "实时活动启用状态：1不支持，2支持未开启，3支持未授权，4支持"
    ,etl_tm                    DATETIME                            comment ""
)
primary key(product_id, user_id)
distributed by hash(user_id)
properties (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);