drop table if exists dim.dim_sv_user_device_im_open_status_df;
create table dim.dim_sv_user_device_im_open_status_df (
     dt                           date      not null    comment "日期"
    ,id                           bigint    not null    comment "id"
    ,app_ver                      varchar(50)           comment "app版本号"
    ,sign                         varchar(255)          comment "签名"
    ,core                         varchar(50)           comment "核心版本"
    ,locale                       varchar(50)           comment "区域设置"
    ,user_id                      varchar(255)          comment "用户ID"
    ,sid                          varchar(50)           comment "会话ID"
    ,sh                           int                   comment "高度"
    ,language_id                  int                   comment "语言ID"
    ,uniquecdreader_id            varchar(50)           comment "唯一读卡器ID，UNI索引"
    ,timestamp                    bigint                comment "时间戳"
    ,from_timestamp               datetime              comment "创建时间"
    ,ver                          int                   comment "版本"
    ,sendid                       varchar(50)           comment "发送ID"
    ,device2                      varchar(50)           comment "设备型号"
    ,sw                           int                   comment "宽度"
    ,chl                          varchar(255)          comment "渠道"
    ,syslanguage                  varchar(50)           comment "系统语言"
    ,mt                           varchar(50)           comment "类型"
    ,osver                        varchar(50)           comment "操作系统版本"
    ,build                        varchar(50)           comment "构建版本"
    ,app_id                       varchar(50)           comment "应用ID"
    ,utcoffset                    int                   comment "UTC偏移量"
    ,guid                         varchar(255)          comment "GUID"
    ,supportutctime               int                   comment "支持UTC时间"
    ,device                       varchar(50)           comment "设备"
    ,androidid                    varchar(50)           comment "Android ID"
    ,device_token                 varchar(255)          comment "device_token"
    ,sign_notify                  tinyint               comment "是否开启签到推送"
    ,app_notify                   tinyint               comment "是否开启推送"
    ,region_id                    smallint              comment "归属区域 id，1：香港，2：北美；"
    ,real_time_activity_notify    int                   comment "实时活动启用状态：1不支持，2支持未开启，3支持未授权，4支持"
    ,countrycode                  varchar(100)          comment "国家代码"
    ,playwindow                   tinyint               comment "小窗播放通知权限"
    ,apptimesensitivestate        tinyint               comment "即时通信(实时活动)通知权限：1-开启,0-关闭"
    ,devicetokenupdatetime        datetime              comment "deviceToken 上报时间"
    ,etl_time                     datetime              comment "ETL时间"
)
primary key (dt, id)
comment "短剧当日是否开启即时通信状态日表"
partition by date_trunc("month", dt)
distributed by hash (id)
properties (
    "replication_num" = "3"
   ,"bloom_filter_columns" = "device2"
   ,"in_memory" = "false"
   ,"enable_persistent_index" = "true"
   ,"replicated_storage" = "true"
   ,"compression" = "lz4"
)
;