drop table if exists dim.dim_user_all_info;
create table dim.dim_user_all_info (
     product_id                        int            not null comment "产品id"
    ,user_id                           bigint         not null comment "用户id"
    ,account                           string                  comment "账户id"
    ,nick                              string                  comment "昵称"
    ,sex                               int                     comment "性别0未知 1男 2女 3保密"
    ,create_tm_account                 datetime                comment "用户的注册时间"
    ,last_login_tm                     datetime                comment "上次登录时间"
    ,chl                               string                  comment "渠道值"
    ,mt                                int                     comment "平台 0未知 1iphone 4安卓 9书城"
    ,imei                              string                  comment "国际移动设备识别码"
    ,imsi                              string                  comment "国际移动用户识别码"
    ,mac                               string                  comment "硬件地址"
    ,money                             int                     comment "当前剩余阅币"
    ,phone                             string                  comment "手机号"
    ,device_guid                       string                  comment "设备guid"
    ,device_token                      string                  comment "关联的设备推送token"
    ,email                             string                  comment "电子邮箱"
    ,is_has_charge                     tinyint                 comment "是否充过值"
    ,province                          string                  comment "省份"
    ,city                              string                  comment "城市"
    ,birthday                          datetime                comment "生日"
    ,country                           string                  comment "国家，会变化，从用户最新ip地址解析而来"
    ,prod_id                           string                  comment "产品id"
    ,code                              string                  comment "邀请码,邀请新用户注册的"
    ,gift_money                        int                     comment "礼券数量"
    ,award_money                       int                     comment "赠送币数量"
    ,chl2                              string                  comment "初始渠道值"
    ,ip                                string                  comment "用户最后一次使用ip"
    ,point                             int                     comment "积分"
    ,app_ver                           string                  comment "app版本"
    ,ver                               int                     comment "客户端版本号"
    ,id_fa                             string                  comment "广告主标识符"
    ,ad_id                             string                  comment "deeplink 统计需要： 广告id"
    ,ad_type                           int                     comment "deeplink 统计需要： 广告类型 0=facebook 1=adwords"
    ,android_id                        string                  comment "deeplink 统计需要 安卓id"
    ,reg_ip                            string                  comment "注册ip"
    ,reg_country                       string                  comment "注册时国家，不会变化"
    ,is_has_bound_email                tinyint                 comment "是否绑定过邮箱"
    ,email_bound_status                tinyint                 comment "邮箱绑定状态 true 已绑定 false 未绑定"
    ,jifen                             int                     comment "积分"
    ,corever                           int                     comment "版本号"
    ,is_firebase                       tinyint                 comment "deeplink 是否是firebase数据"
    ,app_id                            int                     comment "项目id，core，语言"
    ,app_id2                           int                     comment "首次登陆的appid"
    ,current_language                  int                     comment "用户当前语言"
    ,row_update_tm_account             datetime                comment "行数据更新了就会变更时间"
    ,android_id_fordevice_guid         string                  comment "安卓设备id"
    ,mt2                               int                     comment "注册时的终端"
    ,corever2                          int                     comment "注册时的corever"
    ,deep_link_platform_account        int                     comment "deeplink来源平台：-1不是动态链接，0：fb，1：firebase，2：appsflyer"
    ,reg_country2                      string                  comment "注册国家，从华总的kochava来的，if_user_installreferrer,会变化"
    ,book_id_account                   string                  comment "广告bookid"
    ,unique_cdreader_id                string                  comment "注册时设备号"
    ,current_language2                 int                     comment "注册时语言"
    ,is_has_change_lang                int                     comment "是否修改过，注册时候的语言"
    ,ads_type                          varchar(60)             comment "用户广告标签ADSTYPE"
    ,ads_quality                       int                     comment "用户广告标签"
    ,default_into_page_type            int                     comment "默认进入页面"
    ,default_into_page_time            datetime                comment "分组时间"
    ,is_negative_user                  int                     comment "是否白嫖用户"
    ,remarketing_time                  datetime                comment "再召回时间"
    ,low_vip_seconds_start_tm          datetime                comment "vip活动赠送开始时间"
    ,low_vip_expire_tm                 datetime                comment "会员过期时间"
    ,low_vip_expire_time_seconds       bigint                  comment "会员过期时间,vip活动赠送的剩余秒数"
    ,last_buy_bonussign_card_tm        datetime                comment "上次购买福利包时间"
    ,last_buybonussign_cardplus_tm     datetime                comment "上次购买plus福利包时间"
    ,bonussign_card_tm                 datetime                comment "阅币福利包到期时间"
    ,bonussign_cardplus_tm             datetime                comment "阅币福利包plus到期时间"
    ,user_maxcharge_amount             decimal(10, 0)          comment "最高充值档位"
    ,level                             string                  comment "reg_country注册时国家等级"
    ,user_type                         varchar(100)            comment "1IAA 2纯白嫖 3付费白嫖 4非白嫖"
    ,etl_tm                            datetime                comment ""
    ,ram                               int                     comment "手机内存"
    ,sys_releasever                    string                  comment "固件版本"
    ,device                            string                  comment "设备号"
    ,brand                             string                  comment "手机品牌"
    ,continue_sign_num                 int                     comment "连续签到天数"
    ,medal                             int                     comment "勋章数"
    ,medal_min_expire_time             datetime                comment "勋章最早过期时间"
    ,daily_jifen_to_gift_flag          double                  comment "每日积分自动兑换礼券标记"
    ,has_invite_friends                int                     comment "是否有邀请"
    ,total_read_times                  bigint                  comment ""
    ,last_country_name                 string                  comment ""
    ,user_ad_source                    int                     comment "广告投流用户：0：正常用户，1：vip投流用户"
)
primary key(product_id, user_id)
comment "用户维度信息表"
distributed by hash(product_id, user_id)
properties ("replication_num" = "3",
            "bloom_filter_columns" = "user_id, create_tm_account",
            "colocate_with" = "productid_userid_group",
            "in_memory" = "false",
            "enable_persistent_index" = "true",
            "replicated_storage" = "true",
            "compression" = "LZ4"
)
;