DROP TABLE IF EXISTS dim.dim_short_video_user_accountinfo;
CREATE TABLE dim.dim_short_video_user_accountinfo (
     dt                                 DATE           NOT NULL                  COMMENT "日期"
    ,user_id                            BIGINT(20)     NOT NULL                  COMMENT "用户id"
    ,product_id                         INT(11)        NOT NULL                  COMMENT "产品id"
    ,account                            VARCHAR(765)   NOT NULL DEFAULT ""       COMMENT "用户账号"
    ,nick                               VARCHAR(765)   NOT NULL DEFAULT ""       COMMENT "昵称"
    ,sex                                INT(11)        NOT NULL DEFAULT "0"      COMMENT "性别"
    ,create_time                        DATETIME       NOT NULL                  COMMENT "创建时间"
    ,last_login_time                    DATETIME       NOT NULL                  COMMENT "最后登录时间"
    ,chl2                               VARCHAR(765)   NOT NULL DEFAULT ""       COMMENT "初始渠道id"
    ,chl                                VARCHAR(765)   NOT NULL DEFAULT ""       COMMENT "最新渠道id"
    ,mt                                 INT(11)        NOT NULL DEFAULT "0"      COMMENT "最新平台号,1为ios 4为安卓"
    ,mt2                                INT(11)        NOT NULL DEFAULT "0"      COMMENT "初始平台号,1为ios 4为安卓"
    ,unique_cdreader_id                 VARCHAR(765)                             COMMENT "畅读唯一设备号"
    ,current_language2                  INT(11)                                  COMMENT "包初始语言"
    ,current_language                   INT(11)                                  COMMENT "最新用户使用语言"
    ,corever                            INT(11)                                  COMMENT "core,默认1"
    ,corever2                           INT(11)                                  COMMENT "core,默认1"
    ,adid                               VARCHAR(765)                             COMMENT "广告id"
    ,status                             INT(11)        DEFAULT "0"               COMMENT "用户状态：0 正常，1 禁用，2 审核中，3 审核拒绝"
    ,reg_country                        VARCHAR(765)                             COMMENT "注册国家"
    ,row_update_time                    DATETIME                                 COMMENT "数据更新时间"
    ,version                            INT(11)                                  COMMENT "当前版本"
    ,is_delete                          TINYINT(4)                               COMMENT "是否删除"
    ,avatar                             VARCHAR(765)                             COMMENT "用户头像 url"
    ,install_date                       DATETIME                                 COMMENT ""
    ,source_chl                         VARCHAR(150)                             COMMENT "渠道值"
    ,idfa                               VARCHAR(300)                             COMMENT "idfa"
    ,email                              VARCHAR(765)                             COMMENT "是fb那些第三方渠道的"
    ,is_official                        TINYINT(4)     DEFAULT "0"               COMMENT "是否正式用户"
    ,unique_id                          VARCHAR(300)                             COMMENT "三方登陆id"
    ,third_party_id                     TINYINT(4)     DEFAULT "0"               COMMENT "三方登陆类型枚举"
    ,sign_notify                        TINYINT(4)                               COMMENT "是否开启签到提醒"
    ,last_active_time                   BIGINT(20)                               COMMENT "最近活跃时间"
    ,app_notify                         TINYINT(4)                               COMMENT "用户app是否开启推送"
    ,level                              INT(11)                                  COMMENT "用户等级,0 普通用户, 1 svip"
    ,expire_time                        BIGINT(20)                               COMMENT "过期时间"
    ,vip_status                         INT(11)                                  COMMENT "vip状态"
    ,change_dl                          TINYINT(4)                               COMMENT "dl是否被修改过,author:201910"
    ,region_id                          SMALLINT(6)                              COMMENT "归属区域 id，1：香港，2：北美；"
    ,ban_shopping                       TINYINT(4)                               COMMENT "是否被禁止消费"
    ,money_first_date                   DATETIME                                 COMMENT "首次获得阅币时间"
    ,gift_first_date                    DATETIME                                 COMMENT "首次获得礼券时间"
    ,has_delete                         TINYINT(4)                               COMMENT "是否删除"
    ,latest_attributionts               BIGINT(20)                               COMMENT "最近一次归因时间"
    ,drop_attributionts                 BIGINT(20)                               COMMENT "归因丢弃时间"
    ,ad_series_id                       BIGINT(20)                               COMMENT "归因短剧 id"
    ,ad_quality                         INT(11)                                  COMMENT "归因用户质量"
    ,login_bonus_getted                 TINYINT(4)                               COMMENT "登录奖励是否被领取"
    ,comment_bonus_getted               TINYINT(4)                               COMMENT "评论奖励是否被领取"
    ,pass_word                          VARCHAR(65533)                           COMMENT "加密后的登录密码"
    ,bind_email                         VARCHAR(65533)                           COMMENT "登录绑定邮箱(bind是用户自己绑的)"
    ,app_ver                            VARCHAR(65533)                           COMMENT "版本号"
    ,ip                                 VARCHAR(65533)                           COMMENT "ip地址"
    ,font_size                          DECIMAL(24, 8)                           COMMENT "字体大小"
    ,create_password_time               DATETIME                                 COMMENT "初次设置密码时的时间"
    ,third_login_time                   DATETIME                                 COMMENT "初次三方登录的时间"
    ,locale                             VARCHAR(65533)                           COMMENT "区域设置"
    ,lang_id                            INT(11)                                  COMMENT "语言id"
    ,timestamp                          BIGINT(20)                               COMMENT "时间戳"
    ,ver                                INT(11)                                  COMMENT "版本"
    ,device2                            VARCHAR(65533)                           COMMENT "设备型号"
    ,sys_language                       VARCHAR(65533)                           COMMENT "系统语言"
    ,os_ver                             VARCHAR(65533)                           COMMENT "操作系统版本"
    ,app_id                             VARCHAR(65533)                           COMMENT "应用id"
    ,x                                  VARCHAR(65533)                           COMMENT "x"
    ,utc_offset                         INT(11)                                  COMMENT "utc偏移量"
    ,guid                               VARCHAR(65533)                           COMMENT "guid"
    ,support_utc_time                   INT(11)                                  COMMENT "支持utc时间"
    ,device                             VARCHAR(65533)                           COMMENT "设备"
    ,android_id                         VARCHAR(65533)                           COMMENT "android_id"
    ,device_token                       VARCHAR(65533)                           COMMENT ""
    ,etl_time                           DATETIME       DEFAULT CURRENT_TIMESTAMP COMMENT "etl清洗时间"
)
PRIMARY KEY(dt, user_id, product_id)
COMMENT "短剧用户注册信息维度表"
DISTRIBUTED BY HASH(user_id)
PROPERTIES ("replication_num" = "3",
            "bloom_filter_columns" = "unique_cdreader_id, create_time, row_update_time, account",
            "in_memory" = "false",
            "enable_persistent_index" = "true",
            "replicated_storage" = "true",
            "compression" = "LZ4"
)
;