CREATE OR REPLACE VIEW `dim_trade_pay_item_info_view` (
  `id` COMMENT "自增id",
  `apply_type` COMMENT "应用场景（1App,2Edm）",
  `merchandise_type` COMMENT "商品类型（0充值）",
  `price` COMMENT "价格（美元）",
  `lang_id` COMMENT "App语言",
  `product_id` COMMENT "充值产品Id",
  `corever` COMMENT "Core（1core1，2core2，3core3，4core4）",
  `pay_type` COMMENT "支付渠道（1GooglePay，2GooglePay，华为_鸿蒙（海外））",
  `item_id` COMMENT "ItemId",
  `is_show` COMMENT "审核期间是否显示（0否，1是）",
  `status` COMMENT "状态（0禁用，1启用）",
  `is_delete` COMMENT "是否删除（0否，1是）",
  `create_time` COMMENT "创建时间",
  `update_time` COMMENT "更新时间",
  `pay_config_id` COMMENT "PayConfig表关联Id",
  `first_charge_type` COMMENT "首充属性",
  `validity` COMMENT "有效期 (0:无,1:1月,3:1季,12:1年)(月)",
  `first_validity` COMMENT "首充有效期(天)",
  `first_price` COMMENT "首充价格",
  `priority` COMMENT "档位优先级",
  `apple_price_point` COMMENT "苹果正常的价格点",
  `first_apple_price_point` COMMENT "苹果首充的价格点",
  `new_first_price` COMMENT "新首充价格",
  `subscribe_mode` COMMENT "订阅模式（0：普通自动续订，1：分期付款订阅）",
  `installment_period` COMMENT "承诺期（月数，仅3或12，用于分期付款订阅）",
  `ios_installment_price` COMMENT "iOS分期价格",
  `sr_createtime` COMMENT "starrocks数据注入时间",
  `sr_updatetime` COMMENT "starrocks数据更新时间"
)
COMMENT "阅读-充值项item信息" AS
SELECT `ods`.`ods_tidb_readernovel_tidb_tag_center_merchandise_item`.`Id`,
       `ods`.`ods_tidb_readernovel_tidb_tag_center_merchandise_item`.`ApplyType` AS `apply_type`,
       `ods`.`ods_tidb_readernovel_tidb_tag_center_merchandise_item`.`MerchandiseType` AS `merchandise_type`,
       `ods`.`ods_tidb_readernovel_tidb_tag_center_merchandise_item`.`ActualPrice` AS `price`,
       `ods`.`ods_tidb_readernovel_tidb_tag_center_merchandise_item`.`LangId` AS `lang_id`,
       `ods`.`ods_tidb_readernovel_tidb_tag_center_merchandise_item`.`ProductId` AS `product_id`,
       `ods`.`ods_tidb_readernovel_tidb_tag_center_merchandise_item`.`core` AS `corever`,
       `ods`.`ods_tidb_readernovel_tidb_tag_center_merchandise_item`.`PayType` AS `pay_type`,
       `ods`.`ods_tidb_readernovel_tidb_tag_center_merchandise_item`.`ItemId` AS `item_id`,
       `ods`.`ods_tidb_readernovel_tidb_tag_center_merchandise_item`.`IsShow` AS `is_show`,
       `ods`.`ods_tidb_readernovel_tidb_tag_center_merchandise_item`.`status`,
       `ods`.`ods_tidb_readernovel_tidb_tag_center_merchandise_item`.`IsDelete` AS `is_delete`,
       `ods`.`ods_tidb_readernovel_tidb_tag_center_merchandise_item`.`CreateTime` AS `create_time`,
       `ods`.`ods_tidb_readernovel_tidb_tag_center_merchandise_item`.`UpdateTime` AS `update_time`,
       `ods`.`ods_tidb_readernovel_tidb_tag_center_merchandise_item`.`PayConfigId` AS `pay_config_id`,
       `ods`.`ods_tidb_readernovel_tidb_tag_center_merchandise_item`.`FirstChargeType` AS `first_charge_type`,
       `ods`.`ods_tidb_readernovel_tidb_tag_center_merchandise_item`.`Validity` AS `validity`,
       `ods`.`ods_tidb_readernovel_tidb_tag_center_merchandise_item`.`FirstValidity` AS `first_validity`,
       `ods`.`ods_tidb_readernovel_tidb_tag_center_merchandise_item`.`FirstPrice` AS `first_price`,
       `ods`.`ods_tidb_readernovel_tidb_tag_center_merchandise_item`.`Priority` AS `priority`,
       `ods`.`ods_tidb_readernovel_tidb_tag_center_merchandise_item`.`ApplePricePoint` AS `apple_price_point`,
       `ods`.`ods_tidb_readernovel_tidb_tag_center_merchandise_item`.`FirstApplePricePoint` AS `first_apple_price_point`,
       `ods`.`ods_tidb_readernovel_tidb_tag_center_merchandise_item`.`NewFirstPrice` AS `new_first_price`,
       `ods`.`ods_tidb_readernovel_tidb_tag_center_merchandise_item`.`SubscribeMode` AS `subscribe_mode`,
       `ods`.`ods_tidb_readernovel_tidb_tag_center_merchandise_item`.`InstallmentPeriod` AS `installment_period`,
       `ods`.`ods_tidb_readernovel_tidb_tag_center_merchandise_item`.`IosInstallmentPrice` AS `ios_installment_price`,
       `ods`.`ods_tidb_readernovel_tidb_tag_center_merchandise_item`.`sr_createtime`,
       `ods`.`ods_tidb_readernovel_tidb_tag_center_merchandise_item`.`sr_updatetime`
FROM `ods`.`ods_tidb_readernovel_tidb_tag_center_merchandise_item`;
