CREATE OR REPLACE VIEW `dim_sv_recharge_item_info_view` (
  `id` COMMENT "唯一ID",
  `goods_type` COMMENT "商品类型：0普通充值，1vip充值，2签到卡充值",
  `usage_scenario` COMMENT "应用场景",
  `price` COMMENT "价格",
  `decimal_price` COMMENT "价格(小数)",
  `effective_time` COMMENT "有效时间",
  `shop_item_id` COMMENT "区分不同充值类型：（0：充值，800：签到卡，810：SVIP，830:福利包，840：新福利包）",
  `vip_type` COMMENT "1 月卡 2 季卡 3 年卡 4 周卡",
  `first_vip_type` COMMENT "首充周期:1 月卡 2 季卡 3 年卡 4 周卡 5 天卡",
  `first_effective_time` COMMENT "首充有效期",
  `first_price` COMMENT "首充价格",
  `first_decimal_price` COMMENT "首充价格(小数)",
  `goods_attribute` COMMENT "商品属性",
  `price_title` COMMENT "展示价格Price-0.01后的价格",
  `ori_title` COMMENT "原价格",
  `pay_config_id` COMMENT "支付配置表ID",
  `item_id` COMMENT "申请ID",
  `mt` COMMENT "客户端，区分ios 1， android 4",
  `is_on_off` COMMENT "是否启用，启用：1，禁用：0",
  `create_time` COMMENT "创建时间",
  `update_time` COMMENT "修改时间",
  `is_remove` COMMENT "标识是否删除：1删除，0正常",
  `pay_type` COMMENT "支付渠道（1AppStore,2GooglePay，5华为_鸿蒙（海外））",
  `lang_id` COMMENT "App语言",
  `product_id` COMMENT "充值产品ID，阅读每种语言对应一个APP",
  `is_show` COMMENT "审核期间是否显示 (0否，1是)",
  `core` COMMENT "Core (1core1,2core2,3core3,4core4)",
  `app_type` COMMENT "1：阅读，2：短剧",
  `apply_type` COMMENT "应用场景（1App,2Edm）",
  `priority` COMMENT "优先级，暂时就aca有",
  `coupon_money` COMMENT "优惠券金额",
  `to_aca_item_id` COMMENT "aca原档位itemID",
  `coupon_id` COMMENT "优惠券id",
  `subscription_model` COMMENT "订阅模式 0普通自动续订、1分期付款订阅",
  `total_price` COMMENT "总价，目前分期价格使用此字段",
  `installment_count` COMMENT "分期数",
  `installment_switch` COMMENT "分期开关：0-关闭，1-开启",
  `installment_price` COMMENT "分期月付金额",
  `sr_createtime` COMMENT "starrocks数据注入时间",
  `sr_updatetime` COMMENT "starrocks数据更新时间"
)
COMMENT "海剧，充值套餐配置表,充值类型" AS
SELECT `ods`.`ods_tidb_short_video_goods`.`Id`,
       `ods`.`ods_tidb_short_video_goods`.`GoodsType`,
       `ods`.`ods_tidb_short_video_goods`.`UsageScenario`,
       `ods`.`ods_tidb_short_video_goods`.`Price`,
       `ods`.`ods_tidb_short_video_goods`.`DecimalPrice` AS `decimal_price`,
       `ods`.`ods_tidb_short_video_goods`.`EffectiveTime`,
       `ods`.`ods_tidb_short_video_goods`.`ShopItemId`,
       `ods`.`ods_tidb_short_video_goods`.`VipType`,
       `ods`.`ods_tidb_short_video_goods`.`FirstVipType` AS `first_vip_type`,
       `ods`.`ods_tidb_short_video_goods`.`FirstEffectiveTime`,
       `ods`.`ods_tidb_short_video_goods`.`FirstPrice`,
       `ods`.`ods_tidb_short_video_goods`.`FirstDecimalPrice` AS `first_decimal_price`,
       `ods`.`ods_tidb_short_video_goods`.`GoodsAttribute`,
       `ods`.`ods_tidb_short_video_goods`.`PriceTitle`,
       `ods`.`ods_tidb_short_video_goods`.`OriTitle`,
       `ods`.`ods_tidb_short_video_goods`.`PayConfigId`,
       `ods`.`ods_tidb_short_video_goods`.`ItemId`,
       `ods`.`ods_tidb_short_video_goods`.`Mt`,
       `ods`.`ods_tidb_short_video_goods`.`IsOnOff`,
       `ods`.`ods_tidb_short_video_goods`.`CreateTime`,
       `ods`.`ods_tidb_short_video_goods`.`UpdateTime`,
       `ods`.`ods_tidb_short_video_goods`.`IsRemove`,
       `ods`.`ods_tidb_short_video_goods`.`PayType`,
       `ods`.`ods_tidb_short_video_goods`.`LangId`,
       `ods`.`ods_tidb_short_video_goods`.`ProductId`,
       `ods`.`ods_tidb_short_video_goods`.`IsShow`,
       `ods`.`ods_tidb_short_video_goods`.`Core`,
       `ods`.`ods_tidb_short_video_goods`.`AppType`,
       `ods`.`ods_tidb_short_video_goods`.`ApplyType`,
       `ods`.`ods_tidb_short_video_goods`.`Priority` AS `priority`,
       `ods`.`ods_tidb_short_video_goods`.`CouponMoney` AS `coupon_money`,
       `ods`.`ods_tidb_short_video_goods`.`ToACAItemId` AS `to_aca_item_id`,
       `ods`.`ods_tidb_short_video_goods`.`CouponId` AS `coupon_id`,
       `ods`.`ods_tidb_short_video_goods`.`SubscriptionModel` AS `subscription_model`,
       `ods`.`ods_tidb_short_video_goods`.`TotalPrice` AS `total_price`,
       `ods`.`ods_tidb_short_video_goods`.`InstallmentCount` AS `installment_count`,
       `ods`.`ods_tidb_short_video_goods`.`InstallmentSwitch` AS `installment_switch`,
       `ods`.`ods_tidb_short_video_goods`.`InstallmentPrice` AS `installment_price`,
       `ods`.`ods_tidb_short_video_goods`.`sr_createtime`,
       `ods`.`ods_tidb_short_video_goods`.`sr_updatetime`
FROM `ods`.`ods_tidb_short_video_goods`;
