CREATE TABLE `ods_tidb_sharpengine_ads_global_AdHtml5Config` (
  `Id` int(11) NOT NULL COMMENT "Id",
  `TemplateType` int(11) NOT NULL COMMENT "模板类型",
  `Title` varchar(1024) NULL COMMENT "标题",
  `ContentUrl` varchar(256) NULL COMMENT "文本存放路径",
  `ImageUrl` varchar(256) NULL COMMENT "图片存放路径",
  `BtnText` varchar(256) NULL COMMENT "按钮文字",
  `BtnSize` varchar(256) NULL COMMENT "按钮大小",
  `BtnUrl` varchar(1024) NULL COMMENT "按钮跳转文字",
  `Size` int(11) NULL COMMENT "H5尺寸",
  `Width` int(11) NULL COMMENT "宽",
  `Height` int(11) NULL COMMENT "长",
  `CreateTime` datetime NULL COMMENT "创建时间",
  `UpdateTime` datetime NULL COMMENT "更新时间",
  `FileTitle` varchar(256) NULL COMMENT "生成文件名",
  `PixelId` varchar(256) NULL COMMENT "",
  `BookId` varchar(256) NULL COMMENT "",
  `MarketId` varchar(256) NULL COMMENT "",
  `IOSUrl` varchar(1024) NULL COMMENT "",
  `GoogleUrl` varchar(1024) NULL COMMENT "",
  `SizeType` varchar(256) NULL COMMENT "",
  `AdId` varchar(256) NULL COMMENT "",
  `Test1` varchar(256) NULL COMMENT "",
  `Test2` varchar(256) NULL COMMENT "",
  `Test3` varchar(256) NULL COMMENT "",
  `Test4` varchar(256) NULL COMMENT "",
  `Test5` varchar(256) NULL COMMENT "",
  `Core` int(11) NULL COMMENT "",
  `ParentId` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `ConfigType` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `ImageUrl2` varchar(256) NULL COMMENT "图片存放路径2",
  `IsCustom` tinyint(4) NULL DEFAULT "0" COMMENT "",
  `CustomStr` varchar(65533) NULL COMMENT "",
  `ModifyRate` decimal(6, 2) NULL COMMENT "修改率(去掉%的值)",
  `UploadTime` datetime NULL COMMENT "上传时间",
  `JsVer` varchar(1024) NULL COMMENT "js版本号",
  `ShowClickImage` tinyint(4) NULL DEFAULT "0" COMMENT "",
  `ClickImage` varchar(256) NULL COMMENT "",
  `ImageId` bigint(20) NULL COMMENT "图片Id",
  `NonImageId` bigint(20) NULL COMMENT "非标图片Id",
  `ButtonId` bigint(20) NULL COMMENT "按钮Id",
  `TextId` bigint(20) NULL COMMENT "文案Id",
  `HotText` varchar(65533) NULL COMMENT "",
  `ProductId` int(11) NULL COMMENT "",
  `ToggleTopLogo` int(11) NULL COMMENT "是否展示顶部logo",
  `AssetShowType` int(11) NULL COMMENT "素材展示类型",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据注入时间",
  `sr_updatetime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据更新时间"
) ENGINE=OLAP 
PRIMARY KEY(`Id`)
COMMENT "H5页面制作"
DISTRIBUTED BY HASH(`Id`) BUCKETS 1 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
