CREATE EXTERNAL TABLE `ods_sensors_order_pay_process` (
  `rid` varchar(1048576) NULL COMMENT "神策日志唯一id，rid",
  `user_id` bigint(20) NULL COMMENT "用户id",
  `core` smallint(6) NULL COMMENT "app、包",
  `mt` varchar(1048576) NULL COMMENT "mt 端",
  `app_version` varchar(1048576) NULL COMMENT "appVersion",
  `step` varchar(1048576) NULL COMMENT "标识支付链路的哪个步骤 111110010：点击挡位；111110020：创建订单；111110030：连接谷歌服务时；111110040：调起谷歌支付弹窗时；111110050：谷歌支付返回时；111110060：向谷歌执行消费/确认时；111110070：订单回传时；111111010：对应订单第三方扣款成功，业务奖励发放到账",
  `uuid` varchar(1048576) NULL COMMENT "支付链路串联唯一标识 类似tradeid",
  `page_id` varchar(1048576) NULL COMMENT "页面ID",
  `page_name` varchar(1048576) NULL COMMENT "页面名称",
  `item_id` varchar(1048576) NULL COMMENT "档位id-ItemId",
  `recharge_amount` int(11) NULL COMMENT "充值货币金额",
  `present_gift` int(11) NULL COMMENT "赠送货币金额",
  `real_recharge` int(11) NULL COMMENT "支付金额",
  `parent_group_id` varchar(1048576) NULL COMMENT "用户集合ID",
  `group_id` varchar(1048576) NULL COMMENT "用户集合ID",
  `pay_id` varchar(1048576) NULL COMMENT "支付渠道",
  `pay_type` smallint(6) NULL COMMENT "充值类型,充值、订阅",
  `order_id` varchar(1048576) NULL COMMENT "业务订单号id",
  `jump_url` varchar(1048576) NULL COMMENT "订单回传url",
  `is_success` boolean NULL COMMENT "是否成功",
  `error_parameter` varchar(1048576) NULL COMMENT "失败原因",
  `pay_source` varchar(1048576) NULL COMMENT "充值信息",
  `payment_method` varchar(1048576) NULL COMMENT "支付方式，记录用户的充值方式，谷歌支付/苹果支付/三方支付···",
  `recharge_type` varchar(1048576) NULL COMMENT "充值类型,货币/订阅充值、810、820、830",
  `subscription_days` bigint(20) NULL COMMENT "订阅天数",
  `current_coin` int(11) NULL COMMENT "当前账户付费货币余额",
  `current_gift` int(11) NULL COMMENT "当前账户免费货币余额",
  `event_time` datetime NULL COMMENT "事件时间",
  `sr_createtime` datetime NULL COMMENT "数据写入时间",
  `product_id` varchar(1048576) NULL COMMENT "产品id",
  `dt` varchar(1048576) NULL COMMENT "分区"
) ENGINE=HIVE 
COMMENT "PARTITION BY (dt)"
PROPERTIES (
"database" = "ods",
"table" = "ods_sensors_order_pay_process",
"resource" = "hive0",
"hive.table.serde.lib"  =  "org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe",
"last_modified_time"  =  "1706253345",
"hive.table.column.names"  =  "rid,user_id,core,mt,app_version,step,uuid,page_id,page_name,item_id,recharge_amount,present_gift,real_recharge,parent_group_id,group_id,pay_id,pay_type,order_id,jump_url,is_success,error_parameter,pay_source,payment_method,recharge_type,subscription_days,current_coin,current_gift,event_time,sr_createtime,product_id",
"hive.table.column.types"  =  "string#bigint#smallint#string#string#string#string#string#string#string#int#int#int#string#string#string#smallint#string#string#boolean#string#string#string#string#bigint#int#int#timestamp#timestamp#string",
"transient_lastDdlTime"  =  "1706253345",
"hive.table.input.format"  =  "org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat",
"last_modified_by"  =  "hadoop",
"hive.metastore.uris"  =  "thrift://node21:9083,thrift://node22:9083"
);
