CREATE TABLE `ods_tidb_short_video_accountinfo_1` (
  `Id` bigint(20) NOT NULL COMMENT "用户Id",
  `Account` varchar(765) NOT NULL DEFAULT "" COMMENT "用户账号",
  `Nick` varchar(765) NOT NULL DEFAULT "" COMMENT "昵称",
  `Sex` int(11) NOT NULL DEFAULT "0" COMMENT "性别",
  `CreateTime` datetime NOT NULL COMMENT "创建时间",
  `LastLoginTime` datetime NOT NULL COMMENT "最后登录时间",
  `Chl2` varchar(765) NOT NULL DEFAULT "" COMMENT "初始渠道Id",
  `Chl` varchar(765) NOT NULL DEFAULT "" COMMENT "最新渠道id",
  `Mt` int(11) NOT NULL DEFAULT "0" COMMENT "最新平台号,1为iOS 4为安卓",
  `Mt2` int(11) NOT NULL DEFAULT "0" COMMENT "初始平台号,1为iOS 4为安卓",
  `UniqueCdReaderId` varchar(765) NULL COMMENT "畅读唯一设备号",
  `CurrentLanguage2` int(11) NULL COMMENT "包初始语言",
  `CurrentLanguage` int(11) NULL COMMENT "最新用户使用语言",
  `CoreVer` int(11) NULL COMMENT "Core,默认1",
  `CoreVer2` int(11) NULL COMMENT "Core,默认1",
  `AdId` varchar(765) NULL COMMENT "广告Id",
  `Status` int(11) NULL DEFAULT "0" COMMENT "用户状态：0 正常，1 禁用，2 审核中，3 审核拒绝",
  `RegCountry` varchar(765) NULL COMMENT "注册国家",
  `row_update_time` datetime NULL COMMENT "数据更新时间",
  `Version` int(11) NULL COMMENT "当前版本",
  `IsDelete` tinyint(4) NULL COMMENT "是否删除",
  `Avatar` varchar(765) NULL COMMENT "用户头像 url",
  `InstallDate` datetime NULL COMMENT "",
  `SourceChl` varchar(150) NULL COMMENT "渠道值",
  `IDFA` varchar(300) NULL COMMENT "IDFA",
  `Email` varchar(765) NULL COMMENT "",
  `IsOfficial` tinyint(4) NULL DEFAULT "0" COMMENT "是否正式用户",
  `UniqueId` varchar(300) NULL COMMENT "三方登陆id",
  `ThirdPartyId` tinyint(4) NULL DEFAULT "0" COMMENT "三方登陆类型枚举",
  `SignNotify` tinyint(4) NULL COMMENT "是否开启签到提醒",
  `LastActiveTime` bigint(20) NULL COMMENT "最近活跃时间",
  `AppNotify` tinyint(4) NULL COMMENT "用户app是否开启推送",
  `Level` int(11) NULL COMMENT "用户等级,0 普通用户, 1 svip",
  `ExpireTime` bigint(20) NULL COMMENT "过期时间",
  `VipStatus` int(11) NULL COMMENT "vip状态",
  `ChangeDl` tinyint(4) NULL COMMENT "dl是否被修改过,author:201910",
  `regionId` smallint(6) NULL COMMENT "归属区域 id，1：香港，2：北美；",
  `BanShopping` tinyint(4) NULL COMMENT "是否被禁止消费",
  `moneyfirstdate` datetime NULL COMMENT "",
  `giftfirstdate` datetime NULL COMMENT "",
  `HasDelete` tinyint(4) NULL COMMENT "是否删除",
  `LatestAttributionTs` bigint(20) NULL COMMENT "最近一次归因时间",
  `DropAttributionTs` bigint(20) NULL COMMENT "归因丢弃时间",
  `AdSeriesId` bigint(20) NULL COMMENT "归因短剧 id",
  `AdQuality` int(11) NULL COMMENT "归因用户质量",
  `LoginBonusGetted` tinyint(4) NULL COMMENT "登录奖励是否被领取",
  `CommentBonusGetted` tinyint(4) NULL COMMENT "评论奖励是否被领取",
  `pass_word` varchar(65533) NULL COMMENT "加密后的登录密码",
  `BindEmail` varchar(65533) NULL COMMENT "登录绑定邮箱",
  `Appver` varchar(65533) NULL COMMENT "版本号",
  `Ip` varchar(65533) NULL COMMENT "ip地址",
  `Country` varchar(65533) NULL COMMENT "当前国家",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据注入时间",
  `sr_updatetime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据更新时间"
) ENGINE=OLAP 
PRIMARY KEY(`Id`)
COMMENT "短剧用户注册信息表"
DISTRIBUTED BY HASH(`Id`) BUCKETS 105 
PROPERTIES (
"replication_num" = "3",
"bloom_filter_columns" = "Account, CreateTime, row_update_time, UniqueCdReaderId",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
