CREATE TABLE `ods_tidb_short_video_admin_source_series` (
  `SeriesId` bigint(20) NOT NULL COMMENT "剧集ID",
  `SeriesName` varchar(1000) NULL COMMENT "剧集名称",
  `Language` int(11) NULL COMMENT "语言id",
  `CreateTime` datetime NULL COMMENT "创建时间",
  `UpdateTime` datetime NULL COMMENT "更新时间",
  `IsComplete` tinyint(4) NULL COMMENT "分集是否完整 1 完整 0 缺失",
  `IsDelete` tinyint(4) NULL COMMENT "是否删除 1 删除 0 未删除",
  `SeriesCode` varchar(500) NULL COMMENT "代码",
  `CooperateType` int(11) NULL COMMENT "作方式(1买断、2分成、3保底分成)",
  `RightsHolderId` bigint(20) NULL COMMENT "版权方Id",
  `ShareRatio` decimal(18, 2) NULL COMMENT "分成比例",
  `BeginDate` date NULL COMMENT "开始日期",
  `EndDate` date NULL COMMENT "结束日期",
  `IsHidden` int(11) NULL COMMENT "是否隐藏 1是 0不是",
  `RelationshipsUrl` varchar(2000) NULL COMMENT "人物关系",
  `LangIds` varchar(200) NULL COMMENT "结算语言id,逗号分隔 ",
  `Coef` decimal(18, 2) NULL COMMENT "分成系数",
  `IsMain` tinyint(4) NULL COMMENT "是否是主剧",
  `MainSeriesId` bigint(20) NULL COMMENT "主原始剧id",
  `AllEpis` int(11) NULL COMMENT "总集数",
  `HasSubTitle` tinyint(4) NULL COMMENT "是否有字幕",
  `EnableLowPriority` tinyint(4) NULL COMMENT "是否开启闲时转码任务，true：开启，false：关闭",
  `RemoveSubtitleEnableLowPriority` tinyint(4) NULL COMMENT "抹除字幕，是否开启闲时转码任务，true：开启，false：关闭",
  `MigrationStatus` tinyint(4) NULL COMMENT "迁移状态，-1新剧 0未迁移 1已迁移",
  `IsOcr` tinyint(4) NULL COMMENT "是否提取字幕",
  `LocalType` int(11) NULL COMMENT "类型 1外文剧 2 中文剧",
  `LocalSubType` int(11) NULL COMMENT "短剧子类型：1-本土剧-ai短剧",
  `VectorTime` datetime NULL COMMENT "向量化 时间",
  `AwsSyncStatus` tinyint(4) NULL COMMENT "AWS同步状态：0未同步，1发起同步",
  `CdnSwitch` tinyint(4) NULL COMMENT "CDN切换：0默认腾讯的CDN，1AWS的CDN",
  `AudioType` int(11) NULL COMMENT "音轨类型 1 原声剧 2 配音剧",
  `AudioLanguage` int(11) NULL COMMENT "音轨语言",
  `DubbedType` int(11) NULL COMMENT "配音类型 1 人工配音 2 AI配音",
  `IsRemoveSubtitle` tinyint(4) NULL COMMENT "是否发起抹除任务",
  `IsAsr` tinyint(4) NULL COMMENT "是否音频提取字幕",
  `PrepareStatus` int(11) NULL COMMENT "筹备状态: 1筹备中、2 筹备完成",
  `LimitIAAds` tinyint(4) NULL COMMENT "是否限制IAA解锁",
  `LimitIAAdsPercent` int(11) NULL COMMENT "IAA集数上限百分比",
  `KunlunId` varchar(500) NULL COMMENT "昆仑id",
  `KunlunSrId` bigint(20) NULL COMMENT "昆仑源片id",
  `RightsHolderType` int(11) NULL COMMENT "版权类别 1引入 2自研 3分销",
  `FirstSeriesCode` varchar(500) NULL COMMENT "一级剧集代号",
  `SecondSeriesCode` varchar(500) NULL COMMENT "二级剧集代号",
  `RemoveType` int(11) NULL COMMENT "抹除类型 1：火山 2：腾讯",
  `TransType` int(11) NULL COMMENT "转码方式: 1火山云, 2腾讯云",
  `FirstPublicationTime` datetime NULL COMMENT "首发时间",
  `SeriesLevel` int(11) NULL COMMENT "等级 1.S 2.A 3.B 4.C",
  `WorkType` int(11) NULL COMMENT "作品类型 1.男频  2.女频 3.双番",
  `RivalType` int(11) NULL COMMENT "竞品在投: 0否, 1是",
  `Core` varchar(500) NULL COMMENT "多个用逗号隔开(1core1，2core2，3core3，4core4)",
  `sr_updatetime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "ods同步时间",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据注入时间",
  `AllowYoutubeFull` int(11) NULL COMMENT "是否允许YouTube全集 1-允许 0-不允许",
  `IsSoldOut` int(11) NULL COMMENT "剧源是否售出 0、未售出 1、售出",
  `IsSyncToYoutube` int(11) NULL COMMENT "是否同步youtube上传列表 0，未同步 1，同步",
  `AppType` int(11) NULL COMMENT "类型 1短剧 2阅读",
  `PayEpisFrom` int(11) NULL COMMENT "起始付费集数",
  `CreateFrom` int(11) NOT NULL DEFAULT "0" COMMENT "剧壳创建来源，0-内容后台手动，1-制片系统"
) ENGINE=OLAP 
PRIMARY KEY(`SeriesId`)
COMMENT "海外短剧源表"
DISTRIBUTED BY HASH(`SeriesId`) BUCKETS 1 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
