CREATE TABLE `ods_tidb_shuangwen_en_objectbook_1` (
  `productid` smallint(6) NOT NULL COMMENT "产品id",
  `SwBookId` bigint(20) NOT NULL COMMENT "翻译书籍Id",
  `ToLanguage` int(11) NOT NULL COMMENT "输出语言",
  `Id` int(11) NOT NULL COMMENT "自增id",
  `BookName` varchar(500) NULL COMMENT "书籍名称",
  `BookId` bigint(20) NULL COMMENT "来源书籍Id",
  `AuthorId` bigint(20) NULL COMMENT "作者Id",
  `CretaeTime` datetime NULL COMMENT "创建时间",
  `GroupId` int(11) NULL COMMENT "",
  `ChapterNum` int(11) NULL COMMENT "",
  `Status` int(11) NULL COMMENT "状态",
  `AuthorName` varchar(500) NULL COMMENT "作者名称",
  `Coefficient` decimal(18, 2) NULL COMMENT "稿费系数",
  `StartNum` int(11) NULL COMMENT "常规加更",
  `EndNum` int(11) NULL COMMENT "加更上限",
  `Reward` int(11) NULL COMMENT "",
  `CeilingReward` int(11) NULL COMMENT "",
  `LadderReward` varchar(500) NULL COMMENT "",
  `ChapterTime` varchar(200) NULL COMMENT "章节发布时间",
  `ChapterTimeNum` int(11) NULL COMMENT "",
  `ReceiveGroupId` int(11) NULL COMMENT "",
  `RewardExplain` varchar(65533) NULL COMMENT "",
  `KindleChapterNum` int(11) NULL COMMENT "章节系数",
  `WeekWordCount` int(11) NULL COMMENT "周更单词",
  `AutomaticStatus` int(11) NULL COMMENT "是否自动发布章节 0 关闭 1 开启",
  `SelfDay` int(11) NULL COMMENT "自校完成天数",
  `ProofreadingDay` int(11) NULL COMMENT "校对延期时间",
  `ForeignProofreadDay` int(11) NULL COMMENT "外校延期时间",
  `BookType` int(11) NULL COMMENT "书籍类型 0 中文图书 1 英文图书",
  `LastChapter` int(11) NULL COMMENT "最后发布章节序号",
  `IsRobot` int(11) NULL COMMENT "是否机翻",
  `RobotChapterCount` int(11) NULL COMMENT "机翻章节数",
  `IsRollBack` int(11) NULL COMMENT "是否驳回",
  `RollBackNumber` int(11) NULL COMMENT "最后驳回序号",
  `CommentTime` datetime NULL COMMENT "打赏评论时间",
  `MachineRatio` decimal(5, 2) NULL COMMENT "机翻修改比例",
  `ModifyRatio` decimal(5, 2) NULL COMMENT "外校修改比例",
  `UnlockFlow` int(11) NULL COMMENT "解锁流程",
  `IsAnewRobot` int(11) NULL COMMENT "是否重新机翻",
  `IsStopUpdate` boolean NULL COMMENT "是否停更",
  `StopUpdateDay` int(11) NULL COMMENT "停更天数",
  `StopUpdateTime` datetime NULL COMMENT "停更时间",
  `StopUpdatePerformedTime` datetime NULL COMMENT "",
  `FromLanguage` int(11) NULL COMMENT "输入语言",
  `IsCustom` tinyint(4) NULL COMMENT "是否定制文",
  `IsSelf` tinyint(4) NULL COMMENT "是否跳过自校 0不是，1是",
  `SignType` int(11) NULL COMMENT "签约类型",
  `RobotType` int(11) NULL COMMENT "机翻类型0：百度，1谷歌，2chatgpt",
  `IsParagraph` int(11) NULL COMMENT "是否分段",
  `BookCode` varchar(250) NULL COMMENT "书籍代号",
  `ObjectBookType` int(11) NULL COMMENT "图书书籍类型,0-网文 1-短剧",
  `IsCostRate` int(11) NULL COMMENT "是否计算成本率,0-否 1-是",
  `IsShortVideo` tinyint(4) NOT NULL DEFAULT "0" COMMENT "是否来源短剧",
  `StoryType` int(11) NOT NULL DEFAULT "0" COMMENT "类型0长篇小说 1短篇小说",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据注入时间",
  `sr_updatetime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据更新时间"
) ENGINE=OLAP 
PRIMARY KEY(`productid`, `SwBookId`, `ToLanguage`, `Id`)
COMMENT "翻译书籍表"
DISTRIBUTED BY HASH(`productid`, `SwBookId`, `ToLanguage`) BUCKETS 3 
PROPERTIES (
"replication_num" = "3",
"bloom_filter_columns" = "SwBookId",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
