CREATE TABLE `ods_tidb_readernovel_tidb_tag_center_group_setting` (
  `dt` datetime NOT NULL COMMENT "日期",
  `Id` int(11) NOT NULL COMMENT "",
  `GroupId` int(11) NULL COMMENT "",
  `Remainder` int(11) NULL COMMENT "",
  `DayCount` int(11) NULL COMMENT "",
  `StartTime` datetime NULL COMMENT "",
  `EndTime` datetime NULL COMMENT "",
  `Core` varchar(65533) NULL COMMENT "",
  `Mt` varchar(65533) NULL COMMENT "",
  `MainLangId` varchar(65533) NULL COMMENT "",
  `InterfaceLangId` varchar(65533) NULL COMMENT "",
  `PromoteLangId` varchar(65533) NULL COMMENT "",
  `MaxVer` int(11) NULL COMMENT "",
  `MinVer` int(11) NULL COMMENT "",
  `IntoType` int(11) NULL COMMENT "",
  `IsPay` tinyint(4) NULL COMMENT "",
  `IsNegativeUser` tinyint(4) NULL COMMENT "",
  `CreateTime` datetime NULL COMMENT "",
  `UpdateTime` datetime NULL COMMENT "",
  `ActiveType` int(11) NULL COMMENT "",
  `DayStart` int(11) NULL COMMENT "",
  `DayEnd` int(11) NULL COMMENT "",
  `IsRepeated` tinyint(4) NULL COMMENT "",
  `UserType` varchar(100) NULL COMMENT "",
  `ExcludeUserType` varchar(100) NULL COMMENT "",
  `SubscribeType` varchar(10) NULL COMMENT "",
  `MoneySurplus` int(11) NULL COMMENT "阅币余额",
  `HaveRecharge` int(11) NULL COMMENT "有充值情况",
  `NoRecharge` int(11) NULL COMMENT "无充值情况",
  `HaveConsume` int(11) NULL COMMENT "有消费情况",
  `NoConsume` int(11) NULL COMMENT "无消费情况",
  `FirstChargeAmount` varchar(65533) NULL COMMENT "首充金额",
  `ReadDayAvg` varchar(65533) NULL COMMENT "日均阅读时长",
  `PayUserLevel` varchar(65533) NULL COMMENT "",
  `NationLevel` int(11) NULL COMMENT "国家等级0 全部，1 T1，2 T2",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据注入时间",
  `sr_updatetime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据更新时间"
) ENGINE=OLAP 
PRIMARY KEY(`dt`, `Id`)
DISTRIBUTED BY HASH(`Id`) BUCKETS 5 
PROPERTIES (
"replication_num" = "3",
"bloom_filter_columns" = "CreateTime",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
