CREATE TABLE `ods_tidb_cdvideo_tidb_xcx_sync_uni_id_users` (
  `Id` bigint(20) NOT NULL COMMENT "主键ID",
  `_id` varchar(65533) NULL COMMENT "_id",
  `wx_openid` varchar(65533) NULL COMMENT "微信openid",
  `my_invite_code` varchar(65533) NULL COMMENT "邀请码",
  `register_env` varchar(65533) NULL COMMENT "注册环境变量",
  `dcloud_appid` varchar(65533) NULL COMMENT "dcloud_appid",
  `create_time` datetime NULL COMMENT "添加时间",
  `sync_update_time` datetime NULL COMMENT "数据更新时间戳",
  `register_date` datetime NULL COMMENT "注册日期",
  `token` varchar(65533) NULL COMMENT "登录token",
  `ad_id` varchar(65533) NULL COMMENT "ad_id",
  `advertiser_id` varchar(65533) NULL COMMENT "广告id",
  `appid` varchar(65533) NULL COMMENT "appid",
  `appname` varchar(65533) NULL COMMENT "小程序名称",
  `balance` int(11) NULL COMMENT "金豆余额",
  `clickid` varchar(65533) NULL COMMENT "clickid",
  `clue_token` varchar(65533) NULL COMMENT "clue_token",
  `finish` varchar(65533) NULL COMMENT "finish",
  `had_youhui` int(11) NULL COMMENT "是否优惠",
  `invite_code` varchar(65533) NULL COMMENT "邀请码",
  `last_login_date` datetime NULL COMMENT "最后登录日期",
  `mentor_id` varchar(65533) NULL COMMENT "mentor_id",
  `middleman_id` varchar(65533) NULL COMMENT "middleman_id",
  `os` varchar(65533) NULL COMMENT "系统",
  `platform` varchar(65533) NULL COMMENT "平台",
  `plus_expire_time` datetime NULL COMMENT "会员过期时间",
  `plus_type` int(11) NULL COMMENT "会员类型",
  `project_id` varchar(65533) NULL COMMENT "project_id",
  `promotion_id` varchar(65533) NULL COMMENT "promotion_id",
  `reback` int(11) NULL COMMENT "reback",
  `req_id` varchar(65533) NULL COMMENT "请求id",
  `reward_times` int(11) NULL COMMENT "reward_times",
  `status` int(11) NULL COMMENT "用户状态：0 正常，1 禁用，2 审核中，3 审核拒绝",
  `tfid` varchar(65533) NULL COMMENT "投放id",
  `tg_pt` varchar(65533) NULL COMMENT "tg_pt",
  `tv_id` varchar(65533) NULL COMMENT "剧集id",
  `username` varchar(65533) NULL COMMENT "用户名",
  `reback_active_time` datetime NULL COMMENT "回传激活时间 ",
  `reback_time` datetime NULL COMMENT "回传时间 ",
  `rebacklog` varchar(65533) NULL COMMENT "回传日志",
  `update_time` datetime NULL COMMENT "更新时间",
  `is_paid` int(11) NULL COMMENT "is_paid",
  `agent` int(11) NULL COMMENT "渠道商标识，来自uni-id-users.agent，>=0为渠道商",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "sr入库时间",
  `sr_updatetime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "sr更新时间"
) ENGINE=OLAP 
PRIMARY KEY(`Id`)
COMMENT "用户：抓取uni-id-users,author:510161"
DISTRIBUTED BY HASH(`Id`) BUCKETS 3 
PROPERTIES (
"replication_num" = "3",
"bloom_filter_columns" = "create_time, register_date, _id, status",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
