CREATE TABLE `ods_tidb_readernovel_tidb_xx_popinfo` (
  `productid` int(11) NOT NULL COMMENT "",
  `AutoID` int(11) NOT NULL COMMENT "",
  `Title` varchar(300) NULL COMMENT "",
  `Url` varchar(65533) NULL COMMENT "",
  `Img_src1` varchar(1500) NULL COMMENT "",
  `Img_src2` varchar(1500) NULL COMMENT "",
  `Img_src3` varchar(1500) NULL COMMENT "",
  `Img_src4` varchar(1500) NULL COMMENT "",
  `Img_src5` varchar(1500) NULL COMMENT "",
  `StartTime` datetime NULL COMMENT "",
  `EndTime` datetime NULL COMMENT "",
  `CreateTime` datetime NULL COMMENT "",
  `Chl` varchar(928) NULL COMMENT "",
  `Platform` varchar(300) NULL COMMENT "",
  `Status` int(11) NULL COMMENT "",
  `Type` int(11) NULL DEFAULT "1" COMMENT "",
  `ProdId` varchar(750) NULL COMMENT "",
  `PopDay` int(11) NULL DEFAULT "0" COMMENT "",
  `Ver` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `lessver` int(11) NULL DEFAULT "0" COMMENT "",
  `IsHide` int(11) NULL COMMENT "",
  `BanChl` varchar(1500) NULL COMMENT "",
  `Sex` varchar(150) NULL COMMENT "",
  `Country` varchar(955) NULL COMMENT "",
  `ExcludeCountry` varchar(65533) NULL COMMENT "",
  `BanProdId` varchar(1500) NULL COMMENT "",
  `Filters` varchar(3000) NULL COMMENT "",
  `Tag` varchar(65533) NULL COMMENT "",
  `ActivitySchedulingTimeId` int(11) NULL COMMENT "",
  `CoreVer` int(11) NOT NULL DEFAULT "1" COMMENT "",
  `AppId` varchar(65533) NULL COMMENT "",
  `RuleKey` varchar(300) NULL COMMENT "",
  `ShowUserType` int(11) NULL COMMENT "用户显示类型：0：全部显示，1：旧充值用户，2，新充值用户",
  `Sort` int(11) NULL COMMENT "",
  `IsFilterExposure` tinyint(4) NULL COMMENT "",
  `IsDelete` int(11) NULL DEFAULT "0" COMMENT "",
  `row_update_time` datetime NULL COMMENT "",
  `SyncLanguage` varchar(600) NULL COMMENT "",
  `Language` int(11) NULL DEFAULT "0" COMMENT "",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "",
  `sr_updatetime` datetime NULL COMMENT ""
) ENGINE=OLAP 
PRIMARY KEY(`productid`, `AutoID`)
DISTRIBUTED BY HASH(`AutoID`) BUCKETS 3 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
