CREATE TABLE `ods_book_user_accountinfo_old` (
  `productid` int(11) NOT NULL COMMENT "产品id",
  `Id` bigint(20) NOT NULL COMMENT "用户id",
  `CreateTime` datetime NOT NULL COMMENT "用户的注册时间",
  `Account` varchar(65533) NULL COMMENT "账户id",
  `Nick` varchar(65533) NULL COMMENT "昵称",
  `Sex` int(11) NULL COMMENT "性别0未知 1男 2女 3保密",
  `HeadId` int(11) NULL COMMENT "头像图片序号",
  `LastLoginTime` datetime NULL COMMENT "上次登录时间",
  `Chl` varchar(65533) NULL COMMENT "渠道值",
  `MT` int(11) NULL COMMENT "平台 0未知 1iphone 4安卓 9书城",
  `IMEI` varchar(65533) NULL COMMENT "国际移动设备识别码",
  `IMSI` varchar(65533) NULL COMMENT "国际移动用户识别码",
  `MAC` varchar(65533) NULL COMMENT "硬件地址",
  `Money` int(11) NULL COMMENT "当前剩余阅币",
  `Phone` varchar(65533) NULL COMMENT "手机号",
  `LastSignTime` datetime NULL COMMENT "最后签到时间",
  `ContinueSignNum` int(11) NULL COMMENT "连续签到天数",
  `ContinueLoginNum` int(11) NULL COMMENT "ContinueLoginNum",
  `DeviceGUID` varchar(65533) NULL COMMENT "设备GUID",
  `ConsumeLevel` int(11) NULL COMMENT "消费等级",
  `LastStatTime` datetime NULL COMMENT "最后签到时间",
  `SendRewardNum` int(11) NULL COMMENT "打赏金额剩余值",
  `Ticket` int(11) NULL COMMENT "月票数量",
  `TicketTime` datetime NULL COMMENT "月票时间",
  `CurMonthConsume` int(11) NULL COMMENT "本月消费",
  `LastMonthConsume` int(11) NULL COMMENT "上月消费",
  `CurMonthReward` int(11) NULL COMMENT "本月打赏",
  `LastMonthReward` int(11) NULL COMMENT "上月打赏",
  `DeviceToken` varchar(65533) NULL COMMENT "关联的设备推送token",
  `CurMonthTicket` int(11) NULL COMMENT "本月获得月票",
  `Acc` int(11) NULL COMMENT "积分",
  `EMail` varchar(65533) NULL COMMENT "电子邮箱",
  `ClientId` varchar(65533) NULL COMMENT "",
  `IsAutoAccount` tinyint(4) NULL COMMENT "是否是自动分配的账号",
  `HasCharge` tinyint(4) NULL COMMENT "是否充过值",
  `HasSentWelcome` tinyint(4) NULL COMMENT "是否已发送私信欢迎信息",
  `LastWeekConsume` int(11) NULL COMMENT "已删除无用",
  `LvStatus` int(11) NULL COMMENT "已删除无用",
  `XD` int(11) NULL COMMENT "已删除无用",
  `TotalXD` int(11) NULL COMMENT "已删除无用",
  `Exp` int(11) NULL COMMENT "经验值",
  `MoneyFirstDate` datetime NULL COMMENT "首充的时间",
  `GiftFirstDate` datetime NULL COMMENT "已删除无用",
  `Province` varchar(65533) NULL COMMENT "省份",
  `City` varchar(65533) NULL COMMENT "城市",
  `Birthday` datetime NULL COMMENT "生日",
  `LastWeekGiftConsume` int(11) NULL COMMENT "已删除无用",
  `Country` varchar(65533) NULL COMMENT "国家",
  `ProdId` varchar(65533) NULL COMMENT "产品Id",
  `SendGiftConsume` int(11) NULL COMMENT "已删除无用",
  `SendGiftConsumeTotal` int(11) NULL COMMENT "消费送礼物活动剩余消费总额",
  `LastRankGiftTime` datetime NULL COMMENT "已删除无用",
  `UsedAcc` int(11) NULL COMMENT "已删除无用",
  `IsFirst` tinyint(4) NULL COMMENT "是否设备首账号",
  `BenefitsEnd` datetime NULL COMMENT "新手福利结束时间",
  `Code` varchar(65533) NULL COMMENT "邀请码,邀请新用户注册的",
  `OperateOver` tinyint(4) NULL COMMENT "是否操作过绑定手机",
  `GiftMoney` int(11) NULL COMMENT "礼券数量",
  `GiftMoneyEx` datetime NULL COMMENT "礼券数需要重算的时间",
  `AwardMoney` int(11) NULL COMMENT "赠送币数量",
  `AwardMoneyEx` datetime NULL COMMENT "赠送币需要重算的时间",
  `Chl2` varchar(65533) NULL COMMENT "初始渠道值",
  `IP` varchar(65533) NULL COMMENT "用户最后一次使用IP",
  `TotalCoin` bigint(20) NULL COMMENT "历史获得礼券",
  `HeadImageUrl` varchar(65533) NULL COMMENT "头像地址Url",
  `NeedPushShelfBook` tinyint(4) NULL COMMENT "壳版本迁移用户是否需要下发书架上的书",
  `HasGetMoveReward` tinyint(4) NULL COMMENT "已删除无用",
  `ReadNum` int(11) NULL COMMENT "阅读数",
  `RechargeType` int(11) NULL COMMENT "充值类型 0:未定义，1:包年",
  `RechargeTypeExpireTime` datetime NULL COMMENT "充值类型过期时间",
  `UserId_91` varchar(65533) NULL COMMENT "已删除无用",
  `FixIMEI` varchar(65533) NULL COMMENT "已删除无用",
  `Point` int(11) NULL COMMENT "积分",
  `AppVer` varchar(65533) NULL COMMENT "app版本",
  `Ver` int(11) NULL COMMENT "服务端版本号",
  `SentMsgId` bigint(20) NULL COMMENT "已删除无用",
  `IsSpecialConsumer` tinyint(4) NULL COMMENT "是否先扣礼券用户",
  `Flag` int(11) NULL COMMENT "已删除无用",
  `IsCanConsume` int(11) NULL COMMENT "是否禁止用户消费0:不禁止 1:禁止",
  `IDFA` varchar(65533) NULL COMMENT "广告主标识符",
  `CashMoney` int(11) NULL COMMENT "已删除无用",
  `DistAccount` varchar(65533) NULL COMMENT "已删除无用",
  `DistTime` datetime NULL COMMENT "已删除无用",
  `DisStatus` int(11) NULL COMMENT "已删除无用",
  `DisStatusTime` datetime NULL COMMENT "已删除无用",
  `MonthCardExpireDate` datetime NULL COMMENT "原签到卡的过期时间",
  `SalesManType` int(11) NULL COMMENT "推广员类型",
  `VoiceInviterId` bigint(20) NULL COMMENT "有声推广员类型",
  `IsSalesMan` tinyint(4) NULL COMMENT "已删除无用",
  `IsVoiceSalesMan` tinyint(4) NULL COMMENT "已删除无用",
  `VoiceSalesManType` int(11) NULL COMMENT "有声推广员类型",
  `PhoneBindTime` datetime NULL COMMENT "手机绑定时间",
  `InviterId` bigint(20) NULL COMMENT "已删除无用",
  `SecondAwardRate` double NULL COMMENT "已删除无用",
  `UtcOffset` int(11) NULL COMMENT "用户时区和UTC时间偏移秒数",
  `VoiceSalesManExpireTime` datetime NULL COMMENT "有声推广员过期时间（针对非普通推广员）",
  `SalesManExpireTime` datetime NULL COMMENT "推广员过期时间（针对非普通推广员）",
  `RedPackCashMoney` int(11) NULL COMMENT "已删除无用",
  `VoiceCashMoney` int(11) NULL COMMENT "已删除无用",
  `LastBuyMonthCardDate` datetime NULL COMMENT "最近订购签到卡的日期",
  `LastBuyMonthCardId` int(11) NULL COMMENT "最近订购签到卡的ID",
  `Introduction` varchar(65533) NULL COMMENT "个人简介",
  `ADID` varchar(65533) NULL COMMENT "Deeplink 统计需要： 广告ID",
  `AdType` int(11) NULL COMMENT "Deeplink 统计需要： 广告类型 0=facebook 1=adwords",
  `AndroidId` varchar(65533) NULL COMMENT "Deeplink 统计需要 安卓id",
  `InstallDate` datetime NULL COMMENT "安装日期",
  `RegIP` varchar(65533) NULL COMMENT "注册IP",
  `RegCountry` varchar(65533) NULL COMMENT "注册时国家",
  `Platform` int(11) NULL COMMENT "平台",
  `HasBoundEmail` tinyint(4) NULL COMMENT "是否绑定过邮箱",
  `EmailBoundStatus` tinyint(4) NULL COMMENT "邮箱绑定状态 true 已绑定 false 未绑定",
  `HasBuyOldCard` tinyint(4) NULL COMMENT "是否买过旧的签到卡",
  `Smallpt` int(11) NULL COMMENT "已删除无用",
  `CurrentAdress` varchar(65533) NULL COMMENT "已删除无用",
  `JiFen` int(11) NULL COMMENT "积分",
  `LastReportTime` datetime NULL COMMENT "上次上报启动世间，一个小时内只记录一次",
  `CoreVer` int(11) NULL COMMENT "版本号",
  `BackGoundImgUrl` varchar(65533) NULL COMMENT "个人中心背景图片",
  `HasChargeBefore` int(11) NULL COMMENT "Core2首冲活动时间点之前是否有充值 0:未初始化 1:有充值 2:无充值 ",
  `ConfigVer` int(11) NULL COMMENT "充值配置版本号",
  `IsFirebase` tinyint(4) NULL COMMENT "Deeplink 是否是firebase数据",
  `HasBuyOldVipCard` tinyint(4) NULL COMMENT "是否购买过旧的会员卡",
  `AppId` int(11) NULL COMMENT "项目id，core，语言",
  `AppId2` int(11) NULL COMMENT "首次登陆的appid",
  `CurrentLanguage` int(11) NULL COMMENT "用户当前语言",
  `MonthCardPlusExpireDate` datetime NULL COMMENT "签到卡Plus的过期时间",
  `LastBuyMonthCardPlusDate` datetime NULL COMMENT "最近订购签到卡Plus的日期",
  `LastBuyMonthCardPlusId` int(11) NULL COMMENT "最近订购签到卡Plus的ID",
  `RowUpdateTimestamp` datetime NULL COMMENT "行数据更新了就会变更时间",
  `AndroidIdForDeviceGUID` varchar(65533) NULL COMMENT "安卓设备id",
  `LastItemPrice` decimal(10, 2) NULL COMMENT "上一次普通充值的金额",
  `SourceChl` varchar(65533) NULL COMMENT "已删除无用",
  `MT2` int(11) NULL COMMENT "注册时的终端",
  `CoreVer2` int(11) NULL COMMENT "注册时的corever",
  `DeepLinkPlatform` int(11) NULL COMMENT "DeepLink来源平台：-1不是动态链接，0：FB，1：firebase，2：appsflyer",
  `RegCountry2` varchar(65533) NULL COMMENT "注册国家，从华总的kochava来的",
  `Energy` int(11) NULL COMMENT "能量",
  `TotalEnergy` int(11) NULL COMMENT "总能量",
  `BookId` varchar(65533) NULL COMMENT "广告bookid",
  `ScreenLockTime` datetime NULL COMMENT "锁屏时间",
  `RealLastLoginTime` datetime NULL COMMENT "真正的最后登录时间",
  `UniqueCdReaderId` varchar(65533) NULL COMMENT "注册时设备号",
  `CurrentLanguage2` int(11) NULL COMMENT "注册时语言",
  `HasChangeLang` int(11) NULL COMMENT "是否修改过，注册时候的语言",
  `Medal` int(11) NULL COMMENT "勋章数",
  `MedalMinExpireTime` datetime NULL COMMENT "勋章最早过期时间",
  `DailyJiFenToGiftFlag` double NULL COMMENT "每日积分自动兑换礼券标记",
  `ContinueSignNum2` int(11) NULL COMMENT "连续签到28天",
  `ContinueSignNum3` int(11) NULL COMMENT "连续签到45天",
  `SignRound` int(11) NULL COMMENT "签到轮数",
  `BenginSignRoundTime` datetime NULL COMMENT "开始签到轮数时间",
  `BenginSignTime3` datetime NULL COMMENT "新版开始签到时间45",
  `BenginSignTime2` datetime NULL COMMENT "新版开始签到时间28",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据注入时间",
  `sr_updatetime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据更新时间",
  INDEX index_productid (`productid`) USING BITMAP COMMENT 'index_productid'
) ENGINE=OLAP 
PRIMARY KEY(`productid`, `Id`, `CreateTime`)
COMMENT "用户信息表1"
PARTITION BY date_trunc('month', `CreateTime`)
DISTRIBUTED BY HASH(`productid`, `Id`) BUCKETS 1 
PROPERTIES (
"replication_num" = "3",
"bloom_filter_columns" = "Account, Id",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
