CREATE TABLE `ods_tidb_shuangwen_xx_author` (
  `ProductId` smallint(6) NOT NULL COMMENT "产品id",
  `AccountId` bigint(20) NOT NULL COMMENT "账号id",
  `PenName` varchar(65533) NULL COMMENT "笔名",
  `EMail` varchar(65533) NULL COMMENT "邮箱",
  `QQ` varchar(65533) NULL COMMENT "qq",
  `Phone` varchar(65533) NULL COMMENT "手机号",
  `IDCard` varchar(65533) NULL COMMENT "身份证号",
  `IDPostCode` varchar(65533) NULL COMMENT "邮编",
  `IDAddress` varchar(65533) NULL COMMENT "身份证地址",
  `RealName` varchar(65533) NULL COMMENT "姓名",
  `Address` varchar(65533) NULL COMMENT "地址",
  `PostCode` varchar(65533) NULL COMMENT "邮编",
  `Status` int(11) NULL COMMENT "状态 0:未审核 1:已审核 2:已解约",
  `BankAccount` varchar(65533) NULL COMMENT "银行卡号",
  `BankName` varchar(65533) NULL COMMENT "开户行",
  `GroupId` int(11) NULL COMMENT "组id",
  `BankUserName` varchar(65533) NULL COMMENT "银行用户名称",
  `IDCardFrontPhoto` varchar(65533) NULL COMMENT "身份证正面照片",
  `IDCardVersoPhoto` varchar(65533) NULL COMMENT "身份证背面照片",
  `TollStatus` int(11) NULL COMMENT "审核状态",
  `RefAccount` varchar(65533) NULL COMMENT "关联书城账号 根据,号隔开",
  `AddTime` datetime NULL COMMENT "添加时间",
  `RefAccountId` varchar(65533) NULL COMMENT "作者id",
  `AccountType` int(11) NULL COMMENT "账户类型",
  `Sex` varchar(65533) NULL COMMENT "性别",
  `HomePhone` varchar(65533) NULL COMMENT "家庭电话",
  `AccountName` varchar(65533) NULL COMMENT "账号名称",
  `AcccountName` varchar(65533) NULL COMMENT "书城帐号",
  `PaidType` int(11) NULL COMMENT "支付方式 0:Bank  1:PayPal 2:Payoneer",
  `NameOnBankAccount` varchar(65533) NULL COMMENT "银行账户名称",
  `BankAccountNumber` varchar(65533) NULL COMMENT "银行账户号码",
  `SWIFTCode` varchar(65533) NULL COMMENT "银行代码",
  `AuthorType` int(11) NULL COMMENT "作者类型",
  `ToLanguage` int(11) NULL COMMENT "语言",
  `Language` int(11) NULL COMMENT "语言",
  `Area` varchar(65533) NULL COMMENT "区域",
  `HeadImageUrl` varchar(65533) NULL COMMENT "头像链接",
  `Payoneer` varchar(65533) NULL COMMENT "Payoneer帐号",
  `RowVersion` bigint(20) NULL COMMENT "版本号",
  `Nationality` varchar(65533) NULL COMMENT "国籍",
  `BankOfAccounts` varchar(65533) NULL COMMENT "开户行",
  `BankRemark` varchar(65533) NULL COMMENT "Pmax银行备注",
  `SWIFTCodePMax` varchar(65533) NULL COMMENT "Pmax银行代码",
  `AreaPMax` varchar(65533) NULL COMMENT "Pmax地区",
  `BankNamePMax` varchar(65533) NULL COMMENT "PMax银行",
  `BankOfAccountsPMax` varchar(65533) NULL COMMENT "PMax开户行",
  `BankAccountNumberPMax` varchar(65533) NULL COMMENT "PMax银行卡号",
  `RealNamePMax` varchar(65533) NULL COMMENT "PMax姓名",
  `NowResideAddress` varchar(65533) NULL COMMENT "现居地址",
  `QiwiTypePMax` int(11) NULL COMMENT "pmaxqiwi类型 0bank_transfer 1qiwi",
  `QiwiNumberPmax` varchar(65533) NULL COMMENT "pmaxqiwi账号",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据注入时间",
  `sr_updatetime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据更新时间",
  INDEX index_ProductId (`ProductId`) USING BITMAP COMMENT '产品id索引'
) ENGINE=OLAP 
PRIMARY KEY(`ProductId`, `AccountId`)
DISTRIBUTED BY HASH(`ProductId`, `AccountId`) BUCKETS 3 
PROPERTIES (
"replication_num" = "3",
"bloom_filter_columns" = "AccountId",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
