CREATE TABLE `ods_tidb_cdnovel_tidb_xcx_accountinfo` (
  `Id` bigint(20) NOT NULL COMMENT "自增id",
  `Account` varchar(65533) NOT NULL DEFAULT "" COMMENT "sync_uni_id_users._id 唯一主键",
  `VideoUserId` varchar(65533) NOT NULL DEFAULT "" COMMENT "sync_uni_id_users._id 唯一主键 ,用户id",
  `UniqueCdReaderId` varchar(65533) NULL DEFAULT "" COMMENT "sync_uni_id_users._id 唯一主键",
  `Nick` varchar(65533) NOT NULL DEFAULT "" COMMENT "昵称",
  `Sex` int(11) NOT NULL DEFAULT "0" COMMENT "性别",
  `CreateTime` datetime NOT NULL COMMENT "创建时间（注册时间）",
  `LastLoginTime` datetime NOT NULL COMMENT "最近登录时间, 默认 当前时间",
  `Chl2` varchar(65533) NOT NULL DEFAULT "" COMMENT "渠道值",
  `Mt2` int(11) NOT NULL DEFAULT "0" COMMENT "平台（注册时终端）",
  `CurrentLanguage2` int(11) NULL DEFAULT "1" COMMENT "投放语言",
  `CoreVer2` int(11) NULL DEFAULT "1" COMMENT "core",
  `AdId` varchar(65533) NULL DEFAULT "" COMMENT "广告id",
  `Status` int(11) NULL DEFAULT "0" COMMENT "用户状态：0 正常，1 禁用，2 审核中，3 审核拒绝",
  `SourceChl` varchar(65533) NULL DEFAULT "" COMMENT "媒体渠道值",
  `RegCountry` varchar(65533) NULL DEFAULT "cn" COMMENT "注册国家",
  `Agent` int(11) NULL DEFAULT "-1" COMMENT "渠道商标识，来自uni-id-users.agent，Agent>=0为渠道商",
  `project_id` varchar(65533) NULL DEFAULT "" COMMENT "项目id",
  `promotion_id` varchar(65533) NULL DEFAULT "" COMMENT "广告id",
  `TFID` varchar(65533) NULL DEFAULT "" COMMENT "投放Id",
  `ReqId` varchar(65533) NULL DEFAULT "" COMMENT "req_id",
  `MiddleManId` varchar(65533) NULL DEFAULT "" COMMENT "机构id",
  `PlusType` int(11) NULL COMMENT "会员类型",
  `PlusExpireTime` datetime NULL COMMENT "会员到期时间",
  `LastLoginOS` varchar(100) NULL COMMENT "最后登录的系统",
  `RebackTime` datetime NULL COMMENT "回传时间",
  `RebackActiveTime` datetime NULL COMMENT "回传有效时间",
  `Reback` int(11) NULL COMMENT "回传",
  `AppId` varchar(65533) NULL COMMENT "小程序id",
  `UpdateTime` datetime NOT NULL COMMENT "更新时间",
  `SyncUpdateTime` datetime NOT NULL COMMENT "数据更新时间戳",
  `Platform` varchar(65533) NULL DEFAULT "" COMMENT "平台：weixin - 微信，toutiao - 抖音, 默认 none",
  `AdPlatform` varchar(65533) NULL DEFAULT "" COMMENT "广告平台：jl - 巨量引擎，gdt - 广点通, 默认 none",
  `AgentId` varchar(65533) NULL DEFAULT "" COMMENT "代理商ID, 默认 none",
  `AgencyId` varchar(65533) NULL DEFAULT "" COMMENT "机构ID, 默认 none",
  `BookId` varchar(65533) NULL DEFAULT "" COMMENT "激活书籍ID，关联 sync_book 表, 默认 none",
  `Balance` int(11) NULL DEFAULT "0" COMMENT "金豆余额, 默认 0",
  `IsVip` int(11) NULL DEFAULT "0" COMMENT "是否VIP：1 - 是，0 - 否, 默认 0",
  `RegisterDate` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "注册时间, 默认 当前时间",
  `ClickId` varchar(65533) NULL DEFAULT "" COMMENT "广告点击ID",
  `ClueToken` varchar(65533) NULL DEFAULT "" COMMENT "资产化token",
  `IsEchoed` int(11) NULL DEFAULT "0" COMMENT "是否回传：1 - 回传过 0 -未回传过",
  `OS` varchar(65533) NULL COMMENT "操作系统",
  `UserType` int(11) NULL DEFAULT "0" COMMENT "类型：1-管理员，2-机构，3-代理商，4-版权方，5-C端用户",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据注入时间",
  `sr_updatetime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据更新时间"
) ENGINE=OLAP 
PRIMARY KEY(`Id`)
COMMENT "国内小程序阅读-用户注册信息表"
DISTRIBUTED BY HASH(`Id`) BUCKETS 1 
PROPERTIES (
"replication_num" = "3",
"bloom_filter_columns" = "CreateTime",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"storage_medium" = "SSD",
"compression" = "ZSTD"
);
