CREATE TABLE `ods_tidb_readernovel_tidb_XX_feedback` (
  `Id` int(11) NOT NULL COMMENT "主键ID",
  `UserId` bigint(20) NOT NULL COMMENT "用户ID",
  `ClientId` varchar(1024) NULL COMMENT "客户端ID",
  `Message` string NULL COMMENT "反馈内容",
  `CreateTime` datetime NOT NULL COMMENT "创建时间",
  `MT` int(11) NULL COMMENT "平台号",
  `Ver` int(11) NULL COMMENT "版本号",
  `ToUserId` bigint(20) NULL COMMENT "目标用户ID",
  `IsIgnore` int(11) NOT NULL COMMENT "是否忽略：0-否，1-是",
  `appver` varchar(200) NULL COMMENT "应用版本",
  `chl` varchar(200) NULL COMMENT "渠道",
  `device` varchar(200) NULL COMMENT "设备",
  `sysreleasever` varchar(200) NULL COMMENT "系统版本",
  `BookId` bigint(20) NULL COMMENT "书籍ID",
  `ChapterId` bigint(20) NULL COMMENT "章节ID",
  `BookName` varchar(500) NULL COMMENT "书籍名称",
  `ChapterName` varchar(1000) NULL COMMENT "章节名称",
  `ErrorType` varchar(200) NULL COMMENT "错误类型",
  `BackChapterErrorId` bigint(20) NULL COMMENT "章节错误反馈ID",
  `NetWorkType` varchar(1000) NULL COMMENT "网络类型",
  `OperatorId` bigint(20) NOT NULL COMMENT "操作人ID",
  `OperatorName` varchar(200) NULL COMMENT "操作人名称",
  `IsCustomerService` int(11) NOT NULL COMMENT "是否客服：0-否，1-是",
  `IsRead` int(11) NULL COMMENT "是否已读",
  `ChatGuid` varchar(80) NULL COMMENT "会话GUID",
  `UserGuid` varchar(280) NULL COMMENT "用户GUID",
  `CoreVer` int(11) NULL COMMENT "Core版本",
  `IsAutoRep` int(11) NOT NULL COMMENT "是否自动回复：0-否，1-是",
  `SmallPt` varchar(20) NULL COMMENT "小平台",
  `IsAnyReply` int(11) NULL COMMENT "是否有回复",
  `IsClose` int(11) NULL COMMENT "是否关闭",
  `IsAppraiseUp` int(11) NULL COMMENT "是否好评",
  `TypeName` varchar(510) NULL COMMENT "类型名称",
  `ParentName` varchar(510) NULL COMMENT "父级名称",
  `ParentTypeId` int(11) NULL COMMENT "父级类型ID",
  `TypeId` int(11) NULL COMMENT "类型ID",
  `IsExpire` tinyint(4) NULL COMMENT "是否过期",
  `Language` int(11) NULL COMMENT "语言",
  `IsAIReply` tinyint(4) NULL COMMENT "是否AI回复",
  `AIReplyType` int(11) NULL COMMENT "AI回复类型",
  `AiToManualStatus` int(11) NULL COMMENT "AI转人工状态：null/0=正常，1=待处理，2=已处理",
  `AiToManualReason` varchar(1000) NULL COMMENT "AI转人工原因",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据注入时间",
  `sr_updatetime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据更新时间"
) ENGINE=OLAP 
PRIMARY KEY(`Id`)
COMMENT "用户反馈表"
DISTRIBUTED BY HASH(`Id`) BUCKETS 8
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
