CREATE TABLE ods.ods_tidb_sharpengine_ads_global_FbAdRoiInstallReferrerTimeZone_di (
  Id bigint(20) NOT NULL COMMENT "主键",
  AdId varchar(65533) NULL COMMENT "广告id",
  CreateTime varchar(65533) NULL COMMENT "创建时间",
  PayList varchar(65533) NULL COMMENT "",
  RegNum int(11) NULL COMMENT "",
  Impressions bigint(20) NULL COMMENT "曝光量",
  LinkClicks bigint(20) NULL COMMENT "点击量",
  Installs bigint(20) NULL COMMENT "安装量",
  CostAmount decimal(10, 2) NULL COMMENT "",
  ProductId int(11) NULL COMMENT "产品id",
  PayNum int(11) NULL COMMENT "",
  UpdateTime datetime NULL COMMENT "",
  PayListByDays varchar(65533) NULL COMMENT "",
  CheckSum bigint(20) NULL COMMENT "",
  LoginNum2 int(11) NULL COMMENT "",
  LoginNum3 int(11) NULL COMMENT "",
  LoginNum7 int(11) NULL COMMENT "",
  Core int(11) NULL COMMENT "",
  Mt int(11) NULL COMMENT "",
  FbAccount varchar(65533) NULL COMMENT "",
  AdSetId varchar(65533) NULL COMMENT "",
  AdCampId varchar(65533) NULL COMMENT "",
  DevNum int(11) NULL COMMENT "",
  GroupId int(11) NULL COMMENT "",
  SourceChl varchar(65533) NULL COMMENT "",
  Chl2 varchar(65533) NULL COMMENT "",
  RowVersion bigint(20) NULL COMMENT "",
  CurrentLanguage2 int(11) NULL COMMENT "",
  AdsQuality int(11) NULL COMMENT "",
  Updater varchar(65533) NULL COMMENT "",
  Day0Amount decimal(10, 4) NULL COMMENT "",
  Day1Amount decimal(10, 4) NULL COMMENT "",
  Day2Amount decimal(10, 4) NULL COMMENT "",
  Day3Amount decimal(10, 4) NULL COMMENT "",
  Day4Amount decimal(10, 4) NULL COMMENT "",
  Day5Amount decimal(10, 4) NULL COMMENT "",
  Day6Amount decimal(10, 4) NULL COMMENT "",
  Day7Amount decimal(10, 4) NULL COMMENT "",
  Day8Amount decimal(10, 4) NULL COMMENT "",
  Day9Amount decimal(10, 4) NULL COMMENT "",
  Day10Amount decimal(10, 4) NULL COMMENT "",
  Day11Amount decimal(10, 4) NULL COMMENT "",
  Day12Amount decimal(10, 4) NULL COMMENT "",
  Day13Amount decimal(10, 4) NULL COMMENT "",
  Day14Amount decimal(10, 4) NULL COMMENT "",
  Day15Amount decimal(10, 4) NULL COMMENT "",
  Day16Amount decimal(10, 4) NULL COMMENT "",
  Day17Amount decimal(10, 4) NULL COMMENT "",
  Day18Amount decimal(10, 4) NULL COMMENT "",
  Day19Amount decimal(10, 4) NULL COMMENT "",
  Day20Amount decimal(10, 4) NULL COMMENT "",
  Day21Amount decimal(10, 4) NULL COMMENT "",
  Day22Amount decimal(10, 4) NULL COMMENT "",
  Day23Amount decimal(10, 4) NULL COMMENT "",
  Day24Amount decimal(10, 4) NULL COMMENT "",
  Day25Amount decimal(10, 4) NULL COMMENT "",
  Day26Amount decimal(10, 4) NULL COMMENT "",
  Day27Amount decimal(10, 4) NULL COMMENT "",
  Day28Amount decimal(10, 4) NULL COMMENT "",
  Day29Amount decimal(10, 4) NULL COMMENT "",
  Day30Amount decimal(10, 4) NULL COMMENT "",
  Day31Amount decimal(10, 4) NULL COMMENT "",
  Day32Amount decimal(10, 4) NULL COMMENT "",
  Day33Amount decimal(10, 4) NULL COMMENT "",
  Day34Amount decimal(10, 4) NULL COMMENT "",
  Day35Amount decimal(10, 4) NULL COMMENT "",
  Day36Amount decimal(10, 4) NULL COMMENT "",
  Day37Amount decimal(10, 4) NULL COMMENT "",
  Day38Amount decimal(10, 4) NULL COMMENT "",
  Day39Amount decimal(10, 4) NULL COMMENT "",
  Day40Amount decimal(10, 4) NULL COMMENT "",
  Day41Amount decimal(10, 4) NULL COMMENT "",
  Day42Amount decimal(10, 4) NULL COMMENT "",
  Day43Amount decimal(10, 4) NULL COMMENT "",
  Day44Amount decimal(10, 4) NULL COMMENT "",
  Day45Amount decimal(10, 4) NULL COMMENT "",
  Day46Amount decimal(10, 4) NULL COMMENT "",
  Day47Amount decimal(10, 4) NULL COMMENT "",
  Day48Amount decimal(10, 4) NULL COMMENT "",
  Day49Amount decimal(10, 4) NULL COMMENT "",
  Day50Amount decimal(10, 4) NULL COMMENT "",
  Day51Amount decimal(10, 4) NULL COMMENT "",
  Day52Amount decimal(10, 4) NULL COMMENT "",
  Day53Amount decimal(10, 4) NULL COMMENT "",
  Day54Amount decimal(10, 4) NULL COMMENT "",
  Day55Amount decimal(10, 4) NULL COMMENT "",
  Day56Amount decimal(10, 4) NULL COMMENT "",
  Day57Amount decimal(10, 4) NULL COMMENT "",
  Day58Amount decimal(10, 4) NULL COMMENT "",
  Day59Amount decimal(10, 4) NULL COMMENT "",
  Day60Amount decimal(10, 4) NULL COMMENT "",
  Day61Amount decimal(10, 4) NULL COMMENT "",
  Day62Amount decimal(10, 4) NULL COMMENT "",
  Day63Amount decimal(10, 4) NULL COMMENT "",
  Day64Amount decimal(10, 4) NULL COMMENT "",
  Day65Amount decimal(10, 4) NULL COMMENT "",
  Day66Amount decimal(10, 4) NULL COMMENT "",
  Day67Amount decimal(10, 4) NULL COMMENT "",
  Day68Amount decimal(10, 4) NULL COMMENT "",
  Day69Amount decimal(10, 4) NULL COMMENT "",
  Day70Amount decimal(10, 4) NULL COMMENT "",
  Day71Amount decimal(10, 4) NULL COMMENT "",
  Day72Amount decimal(10, 4) NULL COMMENT "",
  Day73Amount decimal(10, 4) NULL COMMENT "",
  Day74Amount decimal(10, 4) NULL COMMENT "",
  Day75Amount decimal(10, 4) NULL COMMENT "",
  Day76Amount decimal(10, 4) NULL COMMENT "",
  Day77Amount decimal(10, 4) NULL COMMENT "",
  Day78Amount decimal(10, 4) NULL COMMENT "",
  Day79Amount decimal(10, 4) NULL COMMENT "",
  Day80Amount decimal(10, 4) NULL COMMENT "",
  Day81Amount decimal(10, 4) NULL COMMENT "",
  Day82Amount decimal(10, 4) NULL COMMENT "",
  Day83Amount decimal(10, 4) NULL COMMENT "",
  Day84Amount decimal(10, 4) NULL COMMENT "",
  Day85Amount decimal(10, 4) NULL COMMENT "",
  Day86Amount decimal(10, 4) NULL COMMENT "",
  Day87Amount decimal(10, 4) NULL COMMENT "",
  Day88Amount decimal(10, 4) NULL COMMENT "",
  Day89Amount decimal(10, 4) NULL COMMENT "",
  Day90Amount decimal(10, 4) NULL COMMENT "",
  Day120Amount decimal(10, 4) NULL COMMENT "",
  Day150Amount decimal(10, 4) NULL COMMENT "",
  Day180Amount decimal(10, 4) NULL COMMENT "",
  Day210Amount decimal(10, 4) NULL COMMENT "",
  Day240Amount decimal(10, 4) NULL COMMENT "",
  Day270Amount decimal(10, 4) NULL COMMENT "",
  Day300Amount decimal(10, 4) NULL COMMENT "",
  Day330Amount decimal(10, 4) NULL COMMENT "",
  Day360Amount decimal(10, 4) NULL COMMENT "",
  Day0AmountByAd decimal(10, 4) NULL COMMENT "",
  Day1AmountByAd decimal(10, 4) NULL COMMENT "",
  Day2AmountByAd decimal(10, 4) NULL COMMENT "",
  Day3AmountByAd decimal(10, 4) NULL COMMENT "",
  Day4AmountByAd decimal(10, 4) NULL COMMENT "",
  Day5AmountByAd decimal(10, 4) NULL COMMENT "",
  Day6AmountByAd decimal(10, 4) NULL COMMENT "",
  Day7AmountByAd decimal(10, 4) NULL COMMENT "",
  Day8AmountByAd decimal(10, 4) NULL COMMENT "",
  Day9AmountByAd decimal(10, 4) NULL COMMENT "",
  Day10AmountByAd decimal(10, 4) NULL COMMENT "",
  Day11AmountByAd decimal(10, 4) NULL COMMENT "",
  Day12AmountByAd decimal(10, 4) NULL COMMENT "",
  Day13AmountByAd decimal(10, 4) NULL COMMENT "",
  Day14AmountByAd decimal(10, 4) NULL COMMENT "",
  Day15AmountByAd decimal(10, 4) NULL COMMENT "",
  Day16AmountByAd decimal(10, 4) NULL COMMENT "",
  Day17AmountByAd decimal(10, 4) NULL COMMENT "",
  Day18AmountByAd decimal(10, 4) NULL COMMENT "",
  Day19AmountByAd decimal(10, 4) NULL COMMENT "",
  Day20AmountByAd decimal(10, 4) NULL COMMENT "",
  Day21AmountByAd decimal(10, 4) NULL COMMENT "",
  Day22AmountByAd decimal(10, 4) NULL COMMENT "",
  Day23AmountByAd decimal(10, 4) NULL COMMENT "",
  Day24AmountByAd decimal(10, 4) NULL COMMENT "",
  Day25AmountByAd decimal(10, 4) NULL COMMENT "",
  Day26AmountByAd decimal(10, 4) NULL COMMENT "",
  Day27AmountByAd decimal(10, 4) NULL COMMENT "",
  Day28AmountByAd decimal(10, 4) NULL COMMENT "",
  Day29AmountByAd decimal(10, 4) NULL COMMENT "",
  Day30AmountByAd decimal(10, 4) NULL COMMENT "",
  Day31AmountByAd decimal(10, 4) NULL COMMENT "",
  Day32AmountByAd decimal(10, 4) NULL COMMENT "",
  Day33AmountByAd decimal(10, 4) NULL COMMENT "",
  Day34AmountByAd decimal(10, 4) NULL COMMENT "",
  Day35AmountByAd decimal(10, 4) NULL COMMENT "",
  Day36AmountByAd decimal(10, 4) NULL COMMENT "",
  Day37AmountByAd decimal(10, 4) NULL COMMENT "",
  Day38AmountByAd decimal(10, 4) NULL COMMENT "",
  Day39AmountByAd decimal(10, 4) NULL COMMENT "",
  Day40AmountByAd decimal(10, 4) NULL COMMENT "",
  Day41AmountByAd decimal(10, 4) NULL COMMENT "",
  Day42AmountByAd decimal(10, 4) NULL COMMENT "",
  Day43AmountByAd decimal(10, 4) NULL COMMENT "",
  Day44AmountByAd decimal(10, 4) NULL COMMENT "",
  Day45AmountByAd decimal(10, 4) NULL COMMENT "",
  Day46AmountByAd decimal(10, 4) NULL COMMENT "",
  Day47AmountByAd decimal(10, 4) NULL COMMENT "",
  Day48AmountByAd decimal(10, 4) NULL COMMENT "",
  Day49AmountByAd decimal(10, 4) NULL COMMENT "",
  Day50AmountByAd decimal(10, 4) NULL COMMENT "",
  Day51AmountByAd decimal(10, 4) NULL COMMENT "",
  Day52AmountByAd decimal(10, 4) NULL COMMENT "",
  Day53AmountByAd decimal(10, 4) NULL COMMENT "",
  Day54AmountByAd decimal(10, 4) NULL COMMENT "",
  Day55AmountByAd decimal(10, 4) NULL COMMENT "",
  Day56AmountByAd decimal(10, 4) NULL COMMENT "",
  Day57AmountByAd decimal(10, 4) NULL COMMENT "",
  Day58AmountByAd decimal(10, 4) NULL COMMENT "",
  Day59AmountByAd decimal(10, 4) NULL COMMENT "",
  Day60AmountByAd decimal(10, 4) NULL COMMENT "",
  Day61AmountByAd decimal(10, 4) NULL COMMENT "",
  Day62AmountByAd decimal(10, 4) NULL COMMENT "",
  Day63AmountByAd decimal(10, 4) NULL COMMENT "",
  Day64AmountByAd decimal(10, 4) NULL COMMENT "",
  Day65AmountByAd decimal(10, 4) NULL COMMENT "",
  Day66AmountByAd decimal(10, 4) NULL COMMENT "",
  Day67AmountByAd decimal(10, 4) NULL COMMENT "",
  Day68AmountByAd decimal(10, 4) NULL COMMENT "",
  Day69AmountByAd decimal(10, 4) NULL COMMENT "",
  Day70AmountByAd decimal(10, 4) NULL COMMENT "",
  Day71AmountByAd decimal(10, 4) NULL COMMENT "",
  Day72AmountByAd decimal(10, 4) NULL COMMENT "",
  Day73AmountByAd decimal(10, 4) NULL COMMENT "",
  Day74AmountByAd decimal(10, 4) NULL COMMENT "",
  Day75AmountByAd decimal(10, 4) NULL COMMENT "",
  Day76AmountByAd decimal(10, 4) NULL COMMENT "",
  Day77AmountByAd decimal(10, 4) NULL COMMENT "",
  Day78AmountByAd decimal(10, 4) NULL COMMENT "",
  Day79AmountByAd decimal(10, 4) NULL COMMENT "",
  Day80AmountByAd decimal(10, 4) NULL COMMENT "",
  Day81AmountByAd decimal(10, 4) NULL COMMENT "",
  Day82AmountByAd decimal(10, 4) NULL COMMENT "",
  Day83AmountByAd decimal(10, 4) NULL COMMENT "",
  Day84AmountByAd decimal(10, 4) NULL COMMENT "",
  Day85AmountByAd decimal(10, 4) NULL COMMENT "",
  Day86AmountByAd decimal(10, 4) NULL COMMENT "",
  Day87AmountByAd decimal(10, 4) NULL COMMENT "",
  Day88AmountByAd decimal(10, 4) NULL COMMENT "",
  Day89AmountByAd decimal(10, 4) NULL COMMENT "",
  Day90AmountByAd decimal(10, 4) NULL COMMENT "",
  Day120AmountByAd decimal(10, 4) NULL COMMENT "",
  Day150AmountByAd decimal(10, 4) NULL COMMENT "",
  Day180AmountByAd decimal(10, 4) NULL COMMENT "",
  Day210AmountByAd decimal(10, 4) NULL COMMENT "",
  Day240AmountByAd decimal(10, 4) NULL COMMENT "",
  Day270AmountByAd decimal(10, 4) NULL COMMENT "",
  Day300AmountByAd decimal(10, 4) NULL COMMENT "",
  Day330AmountByAd decimal(10, 4) NULL COMMENT "",
  Day360AmountByAd decimal(10, 4) NULL COMMENT "",
  Day0FirstPayNum int(11) NULL COMMENT "",
  Day1FirstPayNum int(11) NULL COMMENT "",
  Day2FirstPayNum int(11) NULL COMMENT "",
  Day3FirstPayNum int(11) NULL COMMENT "",
  Day4FirstPayNum int(11) NULL COMMENT "",
  Day5FirstPayNum int(11) NULL COMMENT "",
  Day6FirstPayNum int(11) NULL COMMENT "",
  Day7FirstPayNum int(11) NULL COMMENT "",
  Day8FirstPayNum int(11) NULL COMMENT "",
  Day9FirstPayNum int(11) NULL COMMENT "",
  Day10FirstPayNum int(11) NULL COMMENT "",
  Day11FirstPayNum int(11) NULL COMMENT "",
  Day12FirstPayNum int(11) NULL COMMENT "",
  Day13FirstPayNum int(11) NULL COMMENT "",
  Day14FirstPayNum int(11) NULL COMMENT "",
  Day15FirstPayNum int(11) NULL COMMENT "",
  Day16FirstPayNum int(11) NULL COMMENT "",
  Day17FirstPayNum int(11) NULL COMMENT "",
  Day18FirstPayNum int(11) NULL COMMENT "",
  Day19FirstPayNum int(11) NULL COMMENT "",
  Day20FirstPayNum int(11) NULL COMMENT "",
  Day21FirstPayNum int(11) NULL COMMENT "",
  Day22FirstPayNum int(11) NULL COMMENT "",
  Day23FirstPayNum int(11) NULL COMMENT "",
  Day24FirstPayNum int(11) NULL COMMENT "",
  Day25FirstPayNum int(11) NULL COMMENT "",
  Day26FirstPayNum int(11) NULL COMMENT "",
  Day27FirstPayNum int(11) NULL COMMENT "",
  Day28FirstPayNum int(11) NULL COMMENT "",
  Day29FirstPayNum int(11) NULL COMMENT "",
  Day30FirstPayNum int(11) NULL COMMENT "",
  Day31FirstPayNum int(11) NULL COMMENT "",
  Day32FirstPayNum int(11) NULL COMMENT "",
  Day33FirstPayNum int(11) NULL COMMENT "",
  Day34FirstPayNum int(11) NULL COMMENT "",
  Day35FirstPayNum int(11) NULL COMMENT "",
  Day36FirstPayNum int(11) NULL COMMENT "",
  Day37FirstPayNum int(11) NULL COMMENT "",
  Day38FirstPayNum int(11) NULL COMMENT "",
  Day39FirstPayNum int(11) NULL COMMENT "",
  Day40FirstPayNum int(11) NULL COMMENT "",
  Day41FirstPayNum int(11) NULL COMMENT "",
  Day42FirstPayNum int(11) NULL COMMENT "",
  Day43FirstPayNum int(11) NULL COMMENT "",
  Day44FirstPayNum int(11) NULL COMMENT "",
  Day45FirstPayNum int(11) NULL COMMENT "",
  Day46FirstPayNum int(11) NULL COMMENT "",
  Day47FirstPayNum int(11) NULL COMMENT "",
  Day48FirstPayNum int(11) NULL COMMENT "",
  Day49FirstPayNum int(11) NULL COMMENT "",
  Day50FirstPayNum int(11) NULL COMMENT "",
  Day51FirstPayNum int(11) NULL COMMENT "",
  Day52FirstPayNum int(11) NULL COMMENT "",
  Day53FirstPayNum int(11) NULL COMMENT "",
  Day54FirstPayNum int(11) NULL COMMENT "",
  Day55FirstPayNum int(11) NULL COMMENT "",
  Day56FirstPayNum int(11) NULL COMMENT "",
  Day57FirstPayNum int(11) NULL COMMENT "",
  Day58FirstPayNum int(11) NULL COMMENT "",
  Day59FirstPayNum int(11) NULL COMMENT "",
  Day60FirstPayNum int(11) NULL COMMENT "",
  Day61FirstPayNum int(11) NULL COMMENT "",
  Day62FirstPayNum int(11) NULL COMMENT "",
  Day63FirstPayNum int(11) NULL COMMENT "",
  Day64FirstPayNum int(11) NULL COMMENT "",
  Day65FirstPayNum int(11) NULL COMMENT "",
  Day66FirstPayNum int(11) NULL COMMENT "",
  Day67FirstPayNum int(11) NULL COMMENT "",
  Day68FirstPayNum int(11) NULL COMMENT "",
  Day69FirstPayNum int(11) NULL COMMENT "",
  Day70FirstPayNum int(11) NULL COMMENT "",
  Day71FirstPayNum int(11) NULL COMMENT "",
  Day72FirstPayNum int(11) NULL COMMENT "",
  Day73FirstPayNum int(11) NULL COMMENT "",
  Day74FirstPayNum int(11) NULL COMMENT "",
  Day75FirstPayNum int(11) NULL COMMENT "",
  Day76FirstPayNum int(11) NULL COMMENT "",
  Day77FirstPayNum int(11) NULL COMMENT "",
  Day78FirstPayNum int(11) NULL COMMENT "",
  Day79FirstPayNum int(11) NULL COMMENT "",
  Day80FirstPayNum int(11) NULL COMMENT "",
  Day81FirstPayNum int(11) NULL COMMENT "",
  Day82FirstPayNum int(11) NULL COMMENT "",
  Day83FirstPayNum int(11) NULL COMMENT "",
  Day84FirstPayNum int(11) NULL COMMENT "",
  Day85FirstPayNum int(11) NULL COMMENT "",
  Day86FirstPayNum int(11) NULL COMMENT "",
  Day87FirstPayNum int(11) NULL COMMENT "",
  Day88FirstPayNum int(11) NULL COMMENT "",
  Day89FirstPayNum int(11) NULL COMMENT "",
  Day90FirstPayNum int(11) NULL COMMENT "",
  Day120FirstPayNum int(11) NULL COMMENT "",
  Day150FirstPayNum int(11) NULL COMMENT "",
  Day180FirstPayNum decimal(10, 4) NULL COMMENT "",
  Day210FirstPayNum decimal(10, 4) NULL COMMENT "",
  Day240FirstPayNum decimal(10, 4) NULL COMMENT "",
  Day270FirstPayNum decimal(10, 4) NULL COMMENT "",
  Day300FirstPayNum decimal(10, 4) NULL COMMENT "",
  Day330FirstPayNum decimal(10, 4) NULL COMMENT "",
  Day360FirstPayNum decimal(10, 4) NULL COMMENT "",
  Day0PayNum int(11) NULL COMMENT "",
  Day1PayNum int(11) NULL COMMENT "",
  Day2PayNum int(11) NULL COMMENT "",
  Day3PayNum int(11) NULL COMMENT "",
  Day4PayNum int(11) NULL COMMENT "",
  Day5PayNum int(11) NULL COMMENT "",
  Day6PayNum int(11) NULL COMMENT "",
  Day7PayNum int(11) NULL COMMENT "",
  Day8PayNum int(11) NULL COMMENT "",
  Day9PayNum int(11) NULL COMMENT "",
  Day10PayNum int(11) NULL COMMENT "",
  Day11PayNum int(11) NULL COMMENT "",
  Day12PayNum int(11) NULL COMMENT "",
  Day13PayNum int(11) NULL COMMENT "",
  Day14PayNum int(11) NULL COMMENT "",
  Day15PayNum int(11) NULL COMMENT "",
  Day16PayNum int(11) NULL COMMENT "",
  Day17PayNum int(11) NULL COMMENT "",
  Day18PayNum int(11) NULL COMMENT "",
  Day19PayNum int(11) NULL COMMENT "",
  Day20PayNum int(11) NULL COMMENT "",
  Day21PayNum int(11) NULL COMMENT "",
  Day22PayNum int(11) NULL COMMENT "",
  Day23PayNum int(11) NULL COMMENT "",
  Day24PayNum int(11) NULL COMMENT "",
  Day25PayNum int(11) NULL COMMENT "",
  Day26PayNum int(11) NULL COMMENT "",
  Day27PayNum int(11) NULL COMMENT "",
  Day28PayNum int(11) NULL COMMENT "",
  Day29PayNum int(11) NULL COMMENT "",
  Day30PayNum int(11) NULL COMMENT "",
  Day31PayNum int(11) NULL COMMENT "",
  Day32PayNum int(11) NULL COMMENT "",
  Day33PayNum int(11) NULL COMMENT "",
  Day34PayNum int(11) NULL COMMENT "",
  Day35PayNum int(11) NULL COMMENT "",
  Day36PayNum int(11) NULL COMMENT "",
  Day37PayNum int(11) NULL COMMENT "",
  Day38PayNum int(11) NULL COMMENT "",
  Day39PayNum int(11) NULL COMMENT "",
  Day40PayNum int(11) NULL COMMENT "",
  Day41PayNum int(11) NULL COMMENT "",
  Day42PayNum int(11) NULL COMMENT "",
  Day43PayNum int(11) NULL COMMENT "",
  Day44PayNum int(11) NULL COMMENT "",
  Day45PayNum int(11) NULL COMMENT "",
  Day46PayNum int(11) NULL COMMENT "",
  Day47PayNum int(11) NULL COMMENT "",
  Day48PayNum int(11) NULL COMMENT "",
  Day49PayNum int(11) NULL COMMENT "",
  Day50PayNum int(11) NULL COMMENT "",
  Day51PayNum int(11) NULL COMMENT "",
  Day52PayNum int(11) NULL COMMENT "",
  Day53PayNum int(11) NULL COMMENT "",
  Day54PayNum int(11) NULL COMMENT "",
  Day55PayNum int(11) NULL COMMENT "",
  Day56PayNum int(11) NULL COMMENT "",
  Day57PayNum int(11) NULL COMMENT "",
  Day58PayNum int(11) NULL COMMENT "",
  Day59PayNum int(11) NULL COMMENT "",
  Day60PayNum int(11) NULL COMMENT "",
  Day61PayNum int(11) NULL COMMENT "",
  Day62PayNum int(11) NULL COMMENT "",
  Day63PayNum int(11) NULL COMMENT "",
  Day64PayNum int(11) NULL COMMENT "",
  Day65PayNum int(11) NULL COMMENT "",
  Day66PayNum int(11) NULL COMMENT "",
  Day67PayNum int(11) NULL COMMENT "",
  Day68PayNum int(11) NULL COMMENT "",
  Day69PayNum int(11) NULL COMMENT "",
  Day70PayNum int(11) NULL COMMENT "",
  Day71PayNum int(11) NULL COMMENT "",
  Day72PayNum int(11) NULL COMMENT "",
  Day73PayNum int(11) NULL COMMENT "",
  Day74PayNum int(11) NULL COMMENT "",
  Day75PayNum int(11) NULL COMMENT "",
  Day76PayNum int(11) NULL COMMENT "",
  Day77PayNum int(11) NULL COMMENT "",
  Day78PayNum int(11) NULL COMMENT "",
  Day79PayNum int(11) NULL COMMENT "",
  Day80PayNum int(11) NULL COMMENT "",
  Day81PayNum int(11) NULL COMMENT "",
  Day82PayNum int(11) NULL COMMENT "",
  Day83PayNum int(11) NULL COMMENT "",
  Day84PayNum int(11) NULL COMMENT "",
  Day85PayNum int(11) NULL COMMENT "",
  Day86PayNum int(11) NULL COMMENT "",
  Day87PayNum int(11) NULL COMMENT "",
  Day88PayNum int(11) NULL COMMENT "",
  Day89PayNum int(11) NULL COMMENT "",
  Day90PayNum int(11) NULL COMMENT "",
  Day120PayNum int(11) NULL COMMENT "",
  Day150PayNum int(11) NULL COMMENT "",
  Day180PayNum decimal(10, 4) NULL COMMENT "",
  Day210PayNum decimal(10, 4) NULL COMMENT "",
  Day240PayNum decimal(10, 4) NULL COMMENT "",
  Day270PayNum decimal(10, 4) NULL COMMENT "",
  Day300PayNum decimal(10, 4) NULL COMMENT "",
  Day330PayNum decimal(10, 4) NULL COMMENT "",
  Day360PayNum decimal(10, 4) NULL COMMENT "",
  PayNumByAt int(11) NULL COMMENT "归因时间内付费次数：ADID维度统计到的归因时间内付费人数产生的付费次数；-归因用户在Day N天内付费次数 (一个字段)",
  PayUserByAt int(11) NULL COMMENT "归因时间内付费uv：ADID维度统计到的归因时间内注册uv中产生的付费uv； --充值用户数",
  Day0FirstPayTimes int(11) NULL COMMENT "ADID维度统计到的当日付费uv产生的付费次数； – 首充用户付费次数",
  Minus1Day0Amount decimal(10, 4) NULL COMMENT "昨日D0收入",
  Minus1CostAmount decimal(10, 4) NULL COMMENT "昨日花费",
  Minus2Day0Amount decimal(10, 4) NULL COMMENT "前日D0收入",
  Minus2CostAmount decimal(10, 4) NULL COMMENT "前日花费",
  PayOrderNum int(11) NULL COMMENT "总订单数",
  Minus3Day0Amount decimal(10, 4) NULL COMMENT "往前3天的D0收入",
  Minus3CostAmount decimal(10, 4) NULL COMMENT "往前3天的昨日花费",
  Minus4Day0Amount decimal(10, 4) NULL COMMENT "往前4天的D0收入",
  Minus4CostAmount decimal(10, 4) NULL COMMENT "往前4天的昨日花费",
  Minus5Day0Amount decimal(10, 4) NULL COMMENT "往前5天的D0收入",
  Minus5CostAmount decimal(10, 4) NULL COMMENT "往前5天的昨日花费",
  Minus6Day0Amount decimal(10, 4) NULL COMMENT "往前6天的D0收入",
  Minus6CostAmount decimal(10, 4) NULL COMMENT "往前6天的昨日花费",
  Minus7Day0Amount decimal(10, 4) NULL COMMENT "往前7天的D0收入",
  Minus7CostAmount decimal(10, 4) NULL COMMENT "往前7天的昨日花费",
  sr_createtime datetime NULL COMMENT "sr入库时间",
  sr_updatetime datetime NULL COMMENT "sr更新时间"
) ENGINE=OLAP 
PRIMARY KEY(Id)
COMMENT "分时区广告投放表"
DISTRIBUTED BY HASH(Id) BUCKETS 40 
PROPERTIES (
"replication_num" = "3",
"bloom_filter_columns" = "AdId, CreateTime, ProductId",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);