CREATE TABLE `ods_tidb_sharpengine_ads_global_videoltvdailyinsightbyhour` (
  `Id` bigint(20) NOT NULL COMMENT "自增id",
  `AdId` varchar(65533) NULL COMMENT "广告id",
  `AdStatus` varchar(65533) NULL COMMENT "广告状态",
  `date_start` varchar(65533) NOT NULL COMMENT "投放开始时间",
  `date_stop` varchar(65533) NOT NULL COMMENT "投放结束时间",
  `AdName` varchar(65533) NULL COMMENT "广告名",
  `Spend` decimal(10, 2) NOT NULL COMMENT "花费金额",
  `PutData` varchar(65533) NULL COMMENT "投放数据",
  `Installs` int(11) NOT NULL COMMENT "安装数",
  `Clicks` int(11) NOT NULL COMMENT "点击数",
  `Impressions` int(11) NOT NULL COMMENT "展示数",
  `Cpc` varchar(65533) NULL COMMENT "Cpc",
  `Cpm` varchar(65533) NULL COMMENT "Cpm",
  `Cpp` varchar(65533) NULL COMMENT "Cpp",
  `Ctr` varchar(65533) NULL COMMENT "Ctr",
  `UpdateTime` datetime NOT NULL COMMENT "更新时间",
  `Mt` int(11) NOT NULL COMMENT "平台",
  `Core` int(11) NOT NULL COMMENT "core",
  `ProductId` int(11) NOT NULL COMMENT "产品id",
  `Roas` decimal(10, 2) NOT NULL COMMENT "Roas",
  `AdSetId` varchar(65533) NULL COMMENT "广告系列",
  `AdCampId` varchar(65533) NULL COMMENT "广告组",
  `Country` varchar(65533) NULL COMMENT "国家",
  `Amount` decimal(10, 2) NOT NULL COMMENT "金额",
  `SourceChl` varchar(65533) NULL COMMENT "来源渠道",
  `Chl2` varchar(65533) NULL COMMENT "chl2",
  `CreateUser` varchar(65533) NULL COMMENT "",
  `CreateType` int(11) NOT NULL COMMENT "",
  `CreateNum` int(11) NOT NULL COMMENT "",
  `RowVersion` bigint(20) NULL COMMENT "数据更新版本",
  `CurrentLanguage2` int(11) NULL COMMENT "注册时语言",
  `IsRemarketing` int(11) NULL COMMENT "是否再营销",
  `Account` varchar(65533) NULL COMMENT "广告所属账号",
  `LinkClick` int(11) NULL COMMENT "链接点击数",
  `Conversion` int(11) NOT NULL COMMENT "offsite转换数",
  `Registration` int(11) NOT NULL COMMENT "去重注册数",
  `TempState` int(11) NULL COMMENT "",
  `AccountId` varchar(65533) NULL COMMENT "广告投放账号ID",
  `Actives` int(11) NOT NULL DEFAULT "0" COMMENT "激活数 active",
  `AttrConversion` int(11) NOT NULL DEFAULT "0" COMMENT "转化数（计费时间）attribution_convert_cnt",
  `PayCount` int(11) NOT NULL DEFAULT "0" COMMENT "付费次数 game_pay_count",
  `PayAmount` decimal(10, 2) NOT NULL DEFAULT "0" COMMENT "付费金额（回传时间） stat_pay_amount",
  `Dislikes` int(11) NOT NULL DEFAULT "0" COMMENT "不感兴趣数 ad_dislike_cnt",
  `Reports` int(11) NOT NULL DEFAULT "0" COMMENT "举报数 ad_report_cnt",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据注入时间",
  `sr_updatetime` datetime NULL COMMENT "starrocks数据更新时间"
) ENGINE=OLAP 
PRIMARY KEY(`Id`)
COMMENT "国内短剧投放小时统计表"
DISTRIBUTED BY HASH(`Id`) BUCKETS 1 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
