CREATE TABLE `ods_tidb_short_video_admin_series` (
  `SeriesId` bigint(20) NOT NULL COMMENT "id",
  `Language` int(11) NOT NULL COMMENT "语言",
  `SeriesName` varchar(2000) NULL COMMENT "",
  `Description` varchar(65533) NULL COMMENT "短剧简介",
  `CoverUrl` varchar(512) NULL COMMENT "封面",
  `CreateTime` datetime NULL COMMENT "创建时间",
  `UpdateTime` datetime NULL COMMENT "修改时间",
  `CreateUser` varchar(300) NULL COMMENT "上传人",
  `PublishStatus` int(11) NOT NULL COMMENT "上架状态(1上架 2下架)",
  `PublishedAt` datetime NULL COMMENT "上架时间",
  `UnPublishedAt` datetime NULL COMMENT "下架时间",
  `LastEpis` int(11) NULL COMMENT "更新至第几集",
  `AllEpis` int(11) NULL COMMENT "总集数",
  `PayEpisFrom` int(11) NULL COMMENT "收费起始集数",
  `IsDelete` int(11) NULL COMMENT "是否删除",
  `Producer` varchar(3000) NULL COMMENT "",
  `Recommend` varchar(2000) NULL COMMENT "",
  `SourceSeriesId` bigint(20) NULL COMMENT "源语言短剧",
  `Price` int(11) NULL COMMENT "单集价格（分）",
  `MinutePrice` decimal(18, 2) NULL COMMENT "分钟价格",
  `Ending` int(11) NULL COMMENT "完结状态（1连载中 2已完结）",
  `SeriesNameKey` varchar(4000) NULL COMMENT "",
  `DescriptionKey` varchar(65536) NULL COMMENT "短剧简介转换key",
  `RecommendKey` varchar(2000) NULL COMMENT "",
  `IsSubtitles` int(11) NULL COMMENT "是否需要字幕 1 需要 0 不需要",
  `SubtitlesStatus` int(11) NULL COMMENT "字幕是否完整 1 完整 0 缺失",
  `EpisStatus` int(11) NULL COMMENT "分集是否完成 1 完整 0 缺失",
  `VideoStatus` int(11) NULL COMMENT "分集视频是否完整 1 完整 0 缺失",
  `SeriesLevel` int(11) NULL COMMENT "等级 1.S 2.A 3.B 4.C",
  `OperateLevel` int(11) NULL COMMENT "运营等级 1.S 2.A 3.B 4.C",
  `WorkType` int(11) NULL COMMENT "作品类型 1.男频  2.女频 3.双番",
  `ImageKey` int(11) NULL COMMENT "轮播榜单配图id",
  `ListRecommendKey` varchar(65533) NULL COMMENT "轮播榜单推荐语key",
  `ListRecommend` varchar(65533) NULL COMMENT "轮播榜单推荐语",
  `AdsBeginTime` datetime NULL COMMENT "测推时间",
  `Core` varchar(400) NULL COMMENT "Core ，多个用逗号隔开(1core1，2core2，3core3，4core4)",
  `IsScheduledPublish` int(11) NULL COMMENT "是否定时上架",
  `ScheduledPublishTime` datetime NULL COMMENT "定时上架时间",
  `HighLightPlot` varchar(65536) NULL COMMENT "高光剧情",
  `TurningPoint` varchar(65536) NULL COMMENT "转折点",
  `IsFirstPublish` tinyint(4) NULL DEFAULT "0" COMMENT "是否首发 1 是 0 否",
  `IsPreheat` tinyint(4) NULL COMMENT "是否预热，1-是，0-否",
  `BookId` bigint(20) NULL COMMENT "海阅关联书籍id",
  `AppType` int(11) NULL COMMENT "类型 1短剧 2阅读",
  `sr_createtime` datetime NULL COMMENT "数据创建时间",
  `sr_updatetime` datetime NULL COMMENT "数据更新时间"
) ENGINE=OLAP 
PRIMARY KEY(`SeriesId`)
COMMENT "短集表"
DISTRIBUTED BY HASH(`SeriesId`) BUCKETS 2 
PROPERTIES (
"replication_num" = "3",
"bloom_filter_columns" = "SeriesId, Language",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
