CREATE TABLE `ods_tidb_readernovel_tidb_xx_shelfactivity` (
  `productid` int(11) NOT NULL COMMENT "",
  `Id` bigint(20) NOT NULL COMMENT "",
  `BeginTime` datetime NOT NULL COMMENT "",
  `EndTime` datetime NOT NULL COMMENT "",
  `Url` varchar(65533) NULL COMMENT "",
  `Img1` varchar(900) NULL COMMENT "",
  `Img2` varchar(900) NULL COMMENT "",
  `Img3` varchar(900) NULL COMMENT "",
  `Img4` varchar(900) NULL COMMENT "",
  `ver` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `mt` int(11) NULL DEFAULT "0" COMMENT "",
  `IsHide` int(11) NULL COMMENT "",
  `maxver` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `Additional` int(11) NULL DEFAULT "0" COMMENT "",
  `BanChl` varchar(1500) NULL COMMENT "",
  `Country` varchar(100) NULL COMMENT "",
  `ExcludeCountry` varchar(900) NULL COMMENT "",
  `BanProdId` varchar(1500) NULL COMMENT "",
  `ProdId` varchar(1000) NULL COMMENT "",
  `Chl` varchar(1000) NULL COMMENT "",
  `ShowType` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `BanUserId` varchar(1500) NULL COMMENT "",
  `Title` varchar(300) NULL COMMENT "",
  `Filters` varchar(65533) NULL COMMENT "",
  `Tag` varchar(65533) NULL COMMENT "",
  `ActivitySchedulingTimeId` int(11) NULL COMMENT "",
  `CoreVer` int(11) NOT NULL DEFAULT "1" COMMENT "",
  `AppId` varchar(1512) NULL COMMENT "",
  `RuleKey` varchar(300) NULL COMMENT "",
  `ShowUserType` int(11) NULL COMMENT "用户显示类型：0：全部显示，1：旧充值用户，2，新充值用户",
  `Sort` int(11) NULL COMMENT "",
  `IsFilterExposure` tinyint(4) NULL COMMENT "",
  `IsDelete` int(11) NULL DEFAULT "0" COMMENT "",
  `row_update_time` datetime NULL COMMENT "",
  `SyncLanguage` varchar(600) NULL DEFAULT "" COMMENT "",
  `Language` int(11) NULL DEFAULT "0" COMMENT "",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "",
  `sr_updatetime` datetime NULL COMMENT ""
) ENGINE=OLAP 
PRIMARY KEY(`productid`, `Id`)
DISTRIBUTED BY HASH(`Id`) BUCKETS 3 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
