CREATE TABLE `ods_tidb_shuangwen_xx_authorapply` (
  `ProductId` smallint(6) NOT NULL COMMENT "产品id",
  `ID` int(11) NOT NULL COMMENT "自增id",
  `Email` varchar(65533) NULL COMMENT "申请人邮箱",
  `AuthorName` varchar(65533) NULL COMMENT "申请人名称",
  `BookUrls` varchar(65533) NULL COMMENT "作品地址",
  `BookNames` varchar(65533) NULL COMMENT "作品名称",
  `IsEnglish` tinyint(4) NULL COMMENT "是否英文作品",
  `CanEnglish` tinyint(4) NULL COMMENT "可翻译为英文",
  `Notes` varchar(65533) NULL COMMENT "备注",
  `ApplyTime` datetime NULL COMMENT "申请时间",
  `IP` varchar(65533) NULL COMMENT "申请ip",
  `CheckStatus` tinyint(4) NULL COMMENT "审核状态(0=待审/1=通过/2=拒绝)",
  `UpdateTime` datetime NULL COMMENT "更新时间",
  `EditorNotes` varchar(65533) NULL COMMENT "编辑备注",
  `BookId` int(11) NULL COMMENT "书籍id",
  `ToLanguage` int(11) NULL COMMENT "语言",
  `Introduce` varchar(65533) NULL COMMENT "简介",
  `FontLength` int(11) NULL COMMENT "字数",
  `Source` tinyint(4) NULL COMMENT "来源",
  `ChapterCount` int(11) NULL COMMENT "章节数",
  `IsSign` tinyint(4) NULL COMMENT "是否签约",
  `RealName` varchar(65533) NULL COMMENT "真名",
  `ImageUrl` varchar(65533) NULL COMMENT "图片链接",
  `Auditor` varchar(65533) NULL COMMENT "审核人",
  `SignType` int(11) NULL COMMENT "签约类型",
  `IDCard` varchar(65533) NULL COMMENT "省份证号",
  `IDCardImg` varchar(65533) NULL COMMENT "身份证图像",
  `AccountId` bigint(20) NULL COMMENT "账户id",
  `DocuSignStatus` int(11) NULL COMMENT "合同文件状态",
  `DocuSignEnvelopeId` varchar(65533) NULL COMMENT "合同文件id",
  `RowVersion` bigint(20) NULL COMMENT "版本号",
  `AuditTime` datetime NULL COMMENT "审核时间",
  `DocuSignEnvelopeUrl` varchar(65533) NULL COMMENT "合同文件地址",
  `DocuSignAccount` int(11) NULL COMMENT "合同账号",
  `ExpectedFontLength` int(11) NULL COMMENT "预期字数",
  `ContractStartTime` datetime NULL COMMENT "合同开始时间",
  `ContractEndTime` datetime NULL COMMENT "合同结束时间",
  `ContractRewardType` int(11) NULL COMMENT "合同奖励类型 0无，1独家奖励A 2独家奖励B 3非独家宝石奖励 4早期合同奖金 5独家福利5.31,6独家福利20220901",
  `CommStatus` int(11) NULL COMMENT "审核状态",
  `ReplyReason` varchar(65533) NULL COMMENT "重签理由",
  `ReviewRemark` varchar(65533) NULL COMMENT "编辑评审",
  `EditorReviewRemark` varchar(65533) NULL COMMENT "网编评审",
  `EditorStar` double NULL COMMENT "网编星级",
  `TelPhone` varchar(65533) NULL COMMENT "电话",
  `IDCardImgBack` varchar(65533) NULL COMMENT "身份证背面照片",
  `SignRejectReason` varchar(65533) NULL COMMENT "签约拒绝原因",
  `IsReceiveBook` int(11) NULL COMMENT "是否收书",
  `CompetReadNum` int(11) NULL COMMENT "竞品书阅读量",
  `CompetReadNumImg` varchar(65533) NULL COMMENT "竞品书阅读量截图",
  `CompetPlatform` int(11) NULL COMMENT "竞品平台",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据注入时间",
  `sr_updatetime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据更新时间",
  INDEX index_ProductId (`ProductId`) USING BITMAP COMMENT '产品id索引'
) ENGINE=OLAP 
PRIMARY KEY(`ProductId`, `ID`)
COMMENT "编辑作者招募申请表"
DISTRIBUTED BY HASH(`ProductId`, `ID`) BUCKETS 3 
PROPERTIES (
"replication_num" = "3",
"bloom_filter_columns" = "ID",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
