---------------------------------------------------------------
-- 目标表： ods.ods_book_user_accountinfo
-- 来源实例： old_tidb_source
-- 来源表： 
--        readernovel_tidb_en.accountinfo
--        readernovel_tidb_sp.accountinfo
--        readernovel_tidb_pt.accountinfo
--        readernovel_tidb_fr.accountinfo
--        readernovel_tidb_jp.accountinfo
--        readernovel_tidb_ru.accountinfo
--        readernovel_tidb_id.accountinfo
--        readernovel_tidb_th.accountinfo
--        readernovel_tidb_ft.accountinfo
--        readernovel_tidb_and2.accountinfo
--        readernovel_tidb_cd2.accountinfo
-- 来源负责： 
-- 采集工具： SeaTunnel
-- 开发人： qhr
-- 开发日期： 
----------------------------------------------------------------

DROP TABLE IF EXISTS ods.ods_book_user_accountinfo;
CREATE TABLE IF NOT EXISTS ods.ods_book_user_accountinfo (
     productid                INT(11)        NOT NULL                  COMMENT "产品id"
    ,Id                       BIGINT(20)     NOT NULL                  COMMENT "用户id"
    ,Account                  VARCHAR(65533)                           COMMENT "账户id"
    ,Nick                     VARCHAR(65533)                           COMMENT "昵称"
    ,Sex                      INT(11)                                  COMMENT "性别0未知 1男 2女 3保密"
    ,HeadId                   INT(11)                                  COMMENT "头像图片序号"
    ,CreateTime               DATETIME                                 COMMENT "用户的注册时间"
    ,LastLoginTime            DATETIME                                 COMMENT "上次登录时间"
    ,Chl                      VARCHAR(65533)                           COMMENT "渠道值"
    ,MT                       INT(11)                                  COMMENT "平台 0未知 1iphone 4安卓 9书城"
    ,IMEI                     VARCHAR(65533)                           COMMENT "国际移动设备识别码"
    ,IMSI                     VARCHAR(65533)                           COMMENT "国际移动用户识别码"
    ,MAC                      VARCHAR(65533)                           COMMENT "硬件地址"
    ,Money                    INT(11)                                  COMMENT "当前剩余阅币"
    ,Phone                    VARCHAR(65533)                           COMMENT "手机号"
    ,LastSignTime             DATETIME                                 COMMENT "最后签到时间"
    ,ContinueSignNum          INT(11)                                  COMMENT "连续签到天数"
    ,ContinueLoginNum         INT(11)                                  COMMENT "ContinueLoginNum"
    ,DeviceGUID               VARCHAR(65533)                           COMMENT "设备GUID"
    ,ConsumeLevel             INT(11)                                  COMMENT "消费等级"
    ,LastStatTime             DATETIME                                 COMMENT "最后签到时间"
    ,SendRewardNum            INT(11)                                  COMMENT "打赏金额剩余值"
    ,Ticket                   INT(11)                                  COMMENT "月票数量"
    ,TicketTime               DATETIME                                 COMMENT "月票时间"
    ,CurMonthConsume          INT(11)                                  COMMENT "本月消费"
    ,LastMonthConsume         INT(11)                                  COMMENT "上月消费"
    ,CurMonthReward           INT(11)                                  COMMENT "本月打赏"
    ,LastMonthReward          INT(11)                                  COMMENT "上月打赏"
    ,DeviceToken              VARCHAR(65533)                           COMMENT "关联的设备推送token"
    ,CurMonthTicket           INT(11)                                  COMMENT "本月获得月票"
    ,Acc                      INT(11)                                  COMMENT "积分"
    ,EMail                    VARCHAR(65533)                           COMMENT "电子邮箱"
    ,ClientId                 VARCHAR(65533)                           COMMENT ""
    ,IsAutoAccount            TINYINT(4)                               COMMENT "是否是自动分配的账号"
    ,HasCharge                TINYINT(4)                               COMMENT "是否充过值"
    ,HasSentWelcome           TINYINT(4)                               COMMENT "是否已发送私信欢迎信息"
    ,LastWeekConsume          INT(11)                                  COMMENT "已删除无用"
    ,LvStatus                 INT(11)                                  COMMENT "已删除无用"
    ,XD                       INT(11)                                  COMMENT "已删除无用"
    ,TotalXD                  INT(11)                                  COMMENT "已删除无用"
    ,Exp                      INT(11)                                  COMMENT "经验值"
    ,MoneyFirstDate           DATETIME                                 COMMENT "首充的时间"
    ,GiftFirstDate            DATETIME                                 COMMENT "已删除无用"
    ,Province                 VARCHAR(65533)                           COMMENT "省份"
    ,City                     VARCHAR(65533)                           COMMENT "城市"
    ,Birthday                 DATETIME                                 COMMENT "生日"
    ,LastWeekGiftConsume      INT(11)                                  COMMENT "已删除无用"
    ,Country                  VARCHAR(65533)                           COMMENT "国家"
    ,ProdId                   VARCHAR(65533)                           COMMENT "产品Id"
    ,SendGiftConsume          INT(11)                                  COMMENT "已删除无用"
    ,SendGiftConsumeTotal     INT(11)                                  COMMENT "消费送礼物活动剩余消费总额"
    ,LastRankGiftTime         DATETIME                                 COMMENT "已删除无用"
    ,UsedAcc                  INT(11)                                  COMMENT "已删除无用"
    ,IsFirst                  TINYINT(4)                               COMMENT "是否设备首账号"
    ,BenefitsEnd              DATETIME                                 COMMENT "新手福利结束时间"
    ,Code                     VARCHAR(65533)                           COMMENT "邀请码,邀请新用户注册的"
    ,OperateOver              TINYINT(4)                               COMMENT "是否操作过绑定手机"
    ,GiftMoney                INT(11)                                  COMMENT "礼券数量"
    ,GiftMoneyEx              DATETIME                                 COMMENT "礼券数需要重算的时间"
    ,AwardMoney               INT(11)                                  COMMENT "赠送币数量"
    ,AwardMoneyEx             DATETIME                                 COMMENT "赠送币需要重算的时间"
    ,Chl2                     VARCHAR(65533)                           COMMENT "初始渠道值"
    ,IP                       VARCHAR(65533)                           COMMENT "用户最后一次使用IP"
    ,TotalCoin                BIGINT(20)                               COMMENT "历史获得礼券"
    ,HeadImageUrl             VARCHAR(65533)                           COMMENT "头像地址Url"
    ,NeedPushShelfBook        TINYINT(4)                               COMMENT "壳版本迁移用户是否需要下发书架上的书"
    ,HasGetMoveReward         TINYINT(4)                               COMMENT "已删除无用"
    ,ReadNum                  INT(11)                                  COMMENT "阅读数"
    ,RechargeType             INT(11)                                  COMMENT "充值类型 0:未定义，1:包年"
    ,RechargeTypeExpireTime   DATETIME                                 COMMENT "充值类型过期时间"
    ,UserId_91                VARCHAR(65533)                           COMMENT "已删除无用"
    ,FixIMEI                  VARCHAR(65533)                           COMMENT "已删除无用"
    ,Point                    INT(11)                                  COMMENT "积分"
    ,AppVer                   VARCHAR(65533)                           COMMENT "app版本"
    ,Ver                      INT(11)                                  COMMENT "服务端版本号"
    ,SentMsgId                BIGINT(20)                               COMMENT "已删除无用"
    ,IsSpecialConsumer        TINYINT(4)                               COMMENT "是否先扣礼券用户"
    ,Flag                     INT(11)                                  COMMENT "已删除无用"
    ,IsCanConsume             INT(11)                                  COMMENT "是否禁止用户消费0:不禁止 1:禁止"
    ,IDFA                     VARCHAR(65533)                           COMMENT "广告主标识符"
    ,CashMoney                INT(11)                                  COMMENT "已删除无用"
    ,DistAccount              VARCHAR(65533)                           COMMENT "已删除无用"
    ,DistTime                 DATETIME                                 COMMENT "已删除无用"
    ,DisStatus                INT(11)                                  COMMENT "已删除无用"
    ,DisStatusTime            DATETIME                                 COMMENT "已删除无用"
    ,MonthCardExpireDate      DATETIME                                 COMMENT "原签到卡的过期时间"
    ,SalesManType             INT(11)                                  COMMENT "推广员类型"
    ,VoiceInviterId           BIGINT(20)                               COMMENT "有声推广员类型"
    ,IsSalesMan               TINYINT(4)                               COMMENT "已删除无用"
    ,IsVoiceSalesMan          TINYINT(4)                               COMMENT "已删除无用"
    ,VoiceSalesManType        INT(11)                                  COMMENT "有声推广员类型"
    ,PhoneBindTime            DATETIME                                 COMMENT "手机绑定时间"
    ,InviterId                BIGINT(20)                               COMMENT "已删除无用"
    ,SecondAwardRate          DOUBLE                                   COMMENT "已删除无用"
    ,UtcOffset                INT(11)                                  COMMENT "用户时区和UTC时间偏移秒数"
    ,VoiceSalesManExpireTime  DATETIME                                 COMMENT "有声推广员过期时间（针对非普通推广员）"
    ,SalesManExpireTime       DATETIME                                 COMMENT "推广员过期时间（针对非普通推广员）"
    ,RedPackCashMoney         INT(11)                                  COMMENT "已删除无用"
    ,VoiceCashMoney           INT(11)                                  COMMENT "已删除无用"
    ,LastBuyMonthCardDate     DATETIME                                 COMMENT "最近订购签到卡的日期"
    ,LastBuyMonthCardId       INT(11)                                  COMMENT "最近订购签到卡的ID"
    ,Introduction             VARCHAR(65533)                           COMMENT "个人简介"
    ,ADID                     VARCHAR(65533)                           COMMENT "Deeplink 统计需要： 广告ID"
    ,AdType                   INT(11)                                  COMMENT "Deeplink 统计需要： 广告类型 0=facebook 1=adwords"
    ,AndroidId                VARCHAR(65533)                           COMMENT "Deeplink 统计需要 安卓id"
    ,InstallDate              DATETIME                                 COMMENT "安装日期"
    ,RegIP                    VARCHAR(65533)                           COMMENT "注册IP"
    ,RegCountry               VARCHAR(65533)                           COMMENT "注册时国家"
    ,Platform                 INT(11)                                  COMMENT "平台"
    ,HasBoundEmail            TINYINT(4)                               COMMENT "是否绑定过邮箱"
    ,EmailBoundStatus         TINYINT(4)                               COMMENT "邮箱绑定状态 true 已绑定 false 未绑定"
    ,HasBuyOldCard            TINYINT(4)                               COMMENT "是否买过旧的签到卡"
    ,Smallpt                  INT(11)                                  COMMENT "已删除无用"
    ,CurrentAdress            VARCHAR(65533)                           COMMENT "已删除无用"
    ,JiFen                    INT(11)                                  COMMENT "积分"
    ,LastReportTime           DATETIME                                 COMMENT "上次上报启动世间，一个小时内只记录一次"
    ,CoreVer                  INT(11)                                  COMMENT "版本号"
    ,BackGoundImgUrl          VARCHAR(65533)                           COMMENT "个人中心背景图片"
    ,HasChargeBefore          INT(11)                                  COMMENT "Core2首冲活动时间点之前是否有充值 0:未初始化 1:有充值 2:无充值 "
    ,ConfigVer                INT(11)                                  COMMENT "充值配置版本号"
    ,IsFirebase               TINYINT(4)                               COMMENT "Deeplink 是否是firebase数据"
    ,HasBuyOldVipCard         TINYINT(4)                               COMMENT "是否购买过旧的会员卡"
    ,AppId                    INT(11)                                  COMMENT "项目id，core，语言"
    ,AppId2                   INT(11)                                  COMMENT "首次登陆的appid"
    ,CurrentLanguage          INT(11)                                  COMMENT "用户当前语言"
    ,MonthCardPlusExpireDate  DATETIME                                 COMMENT "签到卡Plus的过期时间"
    ,LastBuyMonthCardPlusDate DATETIME                                 COMMENT "最近订购签到卡Plus的日期"
    ,LastBuyMonthCardPlusId   INT(11)                                  COMMENT "最近订购签到卡Plus的ID"
    ,RowUpdateTimestamp       DATETIME                                 COMMENT "行数据更新了就会变更时间"
    ,AndroidIdForDeviceGUID   VARCHAR(65533)                           COMMENT "安卓设备id"
    ,LastItemPrice            DECIMAL(10, 2)                           COMMENT "上一次普通充值的金额"
    ,SourceChl                VARCHAR(65533)                           COMMENT "已删除无用"
    ,MT2                      INT(11)                                  COMMENT "注册时的终端"
    ,CoreVer2                 INT(11)                                  COMMENT "注册时的corever"
    ,DeepLinkPlatform         INT(11)                                  COMMENT "DeepLink来源平台：-1不是动态链接，0：FB，1：firebase，2：appsflyer"
    ,RegCountry2              VARCHAR(65533)                           COMMENT "注册国家，从华总的kochava来的"
    ,Energy                   INT(11)                                  COMMENT "能量"
    ,TotalEnergy              INT(11)                                  COMMENT "总能量"
    ,BookId                   VARCHAR(65533)                           COMMENT "广告bookid"
    ,ScreenLockTime           DATETIME                                 COMMENT "锁屏时间"
    ,RealLastLoginTime        DATETIME                                 COMMENT "真正的最后登录时间"
    ,UniqueCdReaderId         VARCHAR(65533)                           COMMENT "注册时设备号"
    ,CurrentLanguage2         INT(11)                                  COMMENT "注册时语言"
    ,HasChangeLang            INT(11)                                  COMMENT "是否修改过，注册时候的语言"
    ,Medal                    INT(11)                                  COMMENT "勋章数"
    ,MedalMinExpireTime       DATETIME                                 COMMENT "勋章最早过期时间"
    ,DailyJiFenToGiftFlag     DOUBLE                                   COMMENT "每日积分自动兑换礼券标记"
    ,ContinueSignNum2         INT(11)                                  COMMENT "连续签到28天"
    ,ContinueSignNum3         INT(11)                                  COMMENT "连续签到45天"
    ,SignRound                INT(11)                                  COMMENT "签到轮数"
    ,BenginSignRoundTime      DATETIME                                 COMMENT "开始签到轮数时间"
    ,BenginSignTime3          DATETIME                                 COMMENT "新版开始签到时间45"
    ,BenginSignTime2          DATETIME                                 COMMENT "新版开始签到时间28"
    ,sr_createtime            DATETIME       DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据注入时间"
    ,sr_updatetime            DATETIME       DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据更新时间"
    ,INDEX index_productid (productid) USING BITMAP                    COMMENT 'index_productid'
)
PRIMARY KEY(productid, Id)
COMMENT "用户信息表1"
DISTRIBUTED BY HASH(productid, Id) BUCKETS 300
PROPERTIES (
    "replication_num" = "3",
    "bloom_filter_columns" = "CreateTime, Id",
    "in_memory" = "false",
    "enable_persistent_index" = "true",
    "replicated_storage" = "true",
    "compression" = "LZ4"
)
;