CREATE TABLE `ods_mysql_zhangzhong_xzz_Chapter_090` (
  `ChapterId` bigint(20) NOT NULL COMMENT "章节Id",
  `BookId` int(11) NOT NULL COMMENT "",
  `ChapterName` varchar(255) NOT NULL COMMENT "",
  `ChapterContent` varchar(65533) NOT NULL COMMENT "",
  `PublishTime` datetime NOT NULL COMMENT "发布时间，如果时间未到，表示定时在这个时间发布",
  `Status` int(11) NULL COMMENT "状态 0:草稿 1:提交等待审核 2:已发布",
  `IsReject` tinyint(4) NULL COMMENT "是否审核驳回",
  `RejectReason` varchar(255) NULL COMMENT "驳回原因",
  `IsVip` tinyint(4) NULL COMMENT "是否需要付费",
  `FontLength` int(11) NULL COMMENT "字数",
  `SequenceNum` int(11) NULL COMMENT "章节序号",
  `AuthorComment` varchar(65533) NULL COMMENT "作者的话",
  `DelStatus` int(11) NULL DEFAULT "0" COMMENT "",
  `IsSuccess` int(11) NULL DEFAULT "0" COMMENT "",
  `ModifyType` int(11) NULL DEFAULT "0" COMMENT "",
  `AudityType` int(11) NULL DEFAULT "0" COMMENT "",
  `LockType` int(11) NULL DEFAULT "0" COMMENT "",
  `LockTime` datetime NULL COMMENT "",
  `RepeatId` bigint(20) NULL DEFAULT "0" COMMENT "",
  `RepeatType` int(11) NULL DEFAULT "0" COMMENT "",
  `RepeatName` varchar(500) NULL COMMENT "",
  `Repeat` varchar(2000) NULL COMMENT "",
  `RepeatCover` varchar(500) NULL COMMENT "",
  `RepeatBatch` int(11) NULL DEFAULT "0" COMMENT "",
  `RepeatTime` datetime NULL COMMENT "",
  `CheckContentStatus` double NULL DEFAULT "0" COMMENT "",
  `RowVersion` bigint(20) NULL COMMENT "",
  `IsTiming` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `RollNumber` varchar(50) NULL COMMENT "",
  `VolumeNumber` int(11) NULL COMMENT "",
  `CreateTime` datetime NULL COMMENT "",
  `UpdateTime` datetime NULL COMMENT "",
  `FirstFontLength` int(11) NULL COMMENT "",
  `RejectStatus` int(11) NULL COMMENT "",
  `Translator` varchar(500) NULL DEFAULT "" COMMENT "",
  `Editor` varchar(500) NULL DEFAULT "" COMMENT "",
  `RecommendBookName` varchar(500) NULL DEFAULT "" COMMENT "",
  `RecommendAuthorName` varchar(500) NULL DEFAULT "" COMMENT "",
  `ObjChapterId` bigint(20) NULL DEFAULT "0" COMMENT "",
  `CheckTips` varchar(65533) NULL COMMENT "",
  `CheckLevel` int(11) NULL DEFAULT "0" COMMENT "",
  `IsDuplicate` int(11) NULL DEFAULT "0" COMMENT "",
  `DupBookId` int(11) NULL DEFAULT "0" COMMENT "",
  `CheckTime` datetime NULL COMMENT "",
  `DupChapterSequence` int(11) NULL DEFAULT "0" COMMENT "",
  `EditStatus` int(11) NULL DEFAULT "1" COMMENT "编辑状态 0不可编辑 1可编辑 2编辑拒绝",
  `EditorUpdateTime` datetime NULL COMMENT "编辑修改时间",
  `UpdateCount` int(11) NOT NULL DEFAULT "0" COMMENT "更新次数",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据注入时间",
  `sr_updatetime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据更新时间"
) ENGINE=OLAP 
PRIMARY KEY(`ChapterId`)
COMMENT "凤鸣轩的部分书的章节信息迁移至新掌"
DISTRIBUTED BY HASH(`ChapterId`) BUCKETS 1 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"storage_medium" = "SSD",
"compression" = "ZSTD"
);
