CREATE TABLE `ods_tidb_sharpengine_ads_hk_bak_if_user_attribution_queue` (
  `ProductId` int(11) NOT NULL COMMENT "产品id",
  `Id` bigint(20) NOT NULL COMMENT "自增id",
  `dt` date NULL COMMENT "记录日期",
  `UserId` bigint(20) NULL COMMENT "用户id",
  `Source` varchar(65533) NULL COMMENT "来源",
  `AdId` varchar(65533) NULL COMMENT "广告id",
  `AdType` int(11) NULL COMMENT "广告类型",
  `InstallDate` datetime NULL COMMENT "安装时间",
  `AdAccountId` varchar(65533) NULL COMMENT "广告账户id",
  `AdSetId` varchar(65533) NULL COMMENT "广告系列id",
  `BookId` varchar(65533) NULL COMMENT "书籍id",
  `Creative` varchar(65533) NULL COMMENT "广告创意",
  `InstallOriginalRequest` varchar(65533) NULL COMMENT "安装原始请求",
  `Login` varchar(65533) NULL COMMENT "登录信息",
  `UniqueCdReaderId` varchar(65533) NULL COMMENT "设备信息",
  `Country` varchar(65533) NULL COMMENT "国家",
  `Mt` int(11) NULL COMMENT "终端",
  `Core` int(11) NULL COMMENT "core",
  `DataInsertDate` varchar(65533) NULL COMMENT "插入时间",
  `Networkname` varchar(65533) NULL COMMENT "媒体值",
  `Chl2` varchar(65533) NULL COMMENT "渠道值",
  `CreateTime` datetime NULL COMMENT "新增时间",
  `adgroup_name` varchar(65533) NULL COMMENT "广告组名称",
  `CurrentLanguage2` int(11) NULL COMMENT "注册时语言",
  `RemarketingTime` datetime NULL COMMENT "再营销时间",
  `TraceId` varchar(65533) NULL COMMENT "追踪Id,和 Notify表数据关联",
  `PixelId` varchar(65533) NULL COMMENT "Fb像素Id",
  `AdQualityStatus` int(11) NULL COMMENT "广告质量状态",
  `InstallDateEst` date NULL COMMENT "西五区激活日期",
  `NextAttributeTime` datetime NULL COMMENT "下一次归因时间",
  `NextAttributeAdId` varchar(65533) NULL COMMENT "下一次归因广告id",
  `NextAttributeSource` varchar(65533) NULL COMMENT "下一次归因来源",
  `PreAttributeTime` datetime NULL COMMENT "上一次归因来源时间",
  `PreAttributeAdId` varchar(65533) NULL COMMENT "上一次归因广告id",
  `PreAttributeSource` varchar(65533) NULL COMMENT "上一次归因来源",
  `IsReInstall` int(11) NULL COMMENT "是否再安装",
  `Status` int(11) NULL COMMENT "处理状态",
  `DescInfo` varchar(65533) NULL COMMENT "描述信息",
  `Remark` varchar(65533) NULL COMMENT "备注",
  `IsRemarketing` int(11) NULL COMMENT "是否再营销",
  `DropTimeSendToAppServer` int(11) NULL COMMENT "丢弃通知服务器状态.默认值为null, 0需要发送 1发送成功",
  `row_update_time` datetime NULL COMMENT "",
  `RawDataCreateTime` datetime NULL COMMENT "",
  `RawDataSource` varchar(65533) NULL COMMENT "",
  `c2rtime` datetime NULL COMMENT "广告点击时间",
  `Status2` int(11) NULL COMMENT "",
  `AttributionRawData` varchar(65533) NULL COMMENT "",
  `AppInstallTime` datetime NULL COMMENT "",
  `LastClickTime` datetime NULL COMMENT "",
  `IsDelete` int(11) NULL COMMENT "",
  `Status3` int(11) NULL COMMENT "",
  `AdName` varchar(2000) NULL COMMENT "",
  `AdSetName` varchar(2000) NULL COMMENT "",
  `AdCampName` varchar(2000) NULL COMMENT "",
  `AdCampId` varchar(2000) NULL COMMENT "",
  `SendFlag` varchar(2000) NULL COMMENT "",
  `abtestpageid` varchar(2000) NULL COMMENT "",
  `SendOwnAdsStatus` int(11) NULL COMMENT "",
  `Attributed` int(11) NULL COMMENT "",
  `sr_createtime` datetime NULL COMMENT "",
  `sr_updatetime` datetime NULL COMMENT ""
) ENGINE=OLAP 
PRIMARY KEY(`ProductId`, `Id`)
DISTRIBUTED BY HASH(`Id`) BUCKETS 150 
PROPERTIES (
"replication_num" = "3",
"bloom_filter_columns" = "UserId, CreateTime, InstallDate, UniqueCdReaderId",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
