CREATE TABLE `ods_tidb_sharpengine_ads_global_FbAdDailyInsight` (
  `Id` bigint(20) NOT NULL COMMENT "",
  `AdId` varchar(50) NULL COMMENT "",
  `AdStatus` varchar(50) NULL COMMENT "",
  `FbAccountId` varchar(128) NULL COMMENT "",
  `date_start` varchar(50) NULL COMMENT "",
  `date_stop` varchar(50) NULL COMMENT "",
  `AdName` varchar(500) NULL COMMENT "",
  `Spend` decimal(10, 2) NULL COMMENT "",
  `PutData` varchar(65533) NULL COMMENT "",
  `Installs` int(11) NULL COMMENT "",
  `Clicks` int(11) NULL COMMENT "",
  `Impressions` int(11) NULL COMMENT "",
  `Cpc` varchar(50) NULL COMMENT "",
  `Cpm` varchar(50) NULL COMMENT "",
  `Cpp` varchar(50) NULL COMMENT "",
  `Ctr` varchar(50) NULL COMMENT "",
  `UpdateTime` datetime NULL COMMENT "",
  `Mt` int(11) NULL COMMENT "",
  `ProductId` varchar(50) NULL COMMENT "",
  `Roas` decimal(10, 2) NULL COMMENT "",
  `AdSetId` varchar(128) NULL COMMENT "",
  `AdCampId` varchar(128) NULL COMMENT "",
  `Amount` decimal(10, 2) NULL COMMENT "",
  `FbAmount` decimal(10, 2) NULL COMMENT "",
  `VideoViewCount` int(11) NULL COMMENT "",
  `Video10sViewCount` int(11) NULL COMMENT "",
  `VideoAvgWatchedTime` int(11) NULL COMMENT "",
  `Installs2` int(11) NULL COMMENT "",
  `ImageId` int(11) NULL COMMENT "",
  `RowVersion` bigint(20) NULL COMMENT "",
  `CreateTime` datetime NULL COMMENT "",
  `LinkClick` int(11) NULL COMMENT "",
  `video_p100_watched_actions` int(11) NULL COMMENT "",
  `video_p75_watched_actions` int(11) NULL COMMENT "",
  `video_p50_watched_actions` int(11) NULL COMMENT "",
  `video_p25_watched_actions` int(11) NULL COMMENT "",
  `video_p95_watched_actions` int(11) NULL COMMENT "",
  `Conversion` int(11) NULL COMMENT "",
  `Registration` int(11) NULL COMMENT "",
  `ConvertSpend` decimal(10, 2) NULL COMMENT "广告投放花费（西五区）",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据注入时间",
  `sr_updatetime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据更新时间"
) ENGINE=OLAP 
PRIMARY KEY(`Id`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`Id`) BUCKETS 20 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
