CREATE TABLE `ods_mysql_Fmx_Book` (
  `BookId` int(11) NOT NULL COMMENT "书籍Id",
  `BookName` varchar(65533) NULL COMMENT "书名",
  `AuthorId` bigint(20) NULL COMMENT "作者Id",
  `CreateTime` datetime NULL COMMENT "创建时间",
  `UpdateTime` datetime NULL COMMENT "作品信息最后更新时间",
  `SignType` int(11) NULL COMMENT "签约类型： 0买断 1A签 2B签",
  `Summary` varchar(65533) NULL COMMENT "简介",
  `IsAudit` tinyint(4) NULL COMMENT "是否已审核",
  `IsFull` tinyint(4) NULL COMMENT "是否完本",
  `Channel` int(11) NULL COMMENT "频道 0:男频 1:女频",
  `CategoryId` int(11) NULL COMMENT "分类Id",
  `CoverSrc` varchar(65533) NULL COMMENT "封面图片",
  `ChapterNum` int(11) NULL COMMENT "章节数量",
  `FontLength` int(11) NULL COMMENT "字数",
  `IsPutdown` tinyint(4) NULL COMMENT "是否下架",
  `FontPrice` int(11) NULL COMMENT "价格，xx分每千字",
  `Status` int(11) NULL DEFAULT "0" COMMENT "",
  `PresentSignType` int(11) NULL COMMENT "0 一级全勤 1 二级全勤 2 三级全勤 3 四级全勤",
  `TollStatus` int(11) NULL DEFAULT "0" COMMENT "",
  `StartVip` int(11) NULL DEFAULT "0" COMMENT "",
  `EveryCount` int(11) NULL DEFAULT "0" COMMENT "",
  `EditorCharge` varchar(65533) NULL COMMENT "",
  `ProductionType` int(11) NULL DEFAULT "0" COMMENT "",
  `AccountName` varchar(65533) NULL COMMENT "",
  `BankAccount` varchar(65533) NULL COMMENT "",
  `BankName` varchar(65533) NULL COMMENT "",
  `BankUserName` varchar(65533) NULL COMMENT "",
  `UpdateStatus` int(11) NULL DEFAULT "0" COMMENT "",
  `VipStart` int(11) NULL DEFAULT "0" COMMENT "",
  `VipStatus` int(11) NULL DEFAULT "0" COMMENT "",
  `OutputStatus` int(11) NULL DEFAULT "0" COMMENT "",
  `VipStartTime` datetime NULL COMMENT "",
  `VipEndTime` datetime NULL COMMENT "",
  `UpdateStatusTime` datetime NULL COMMENT "",
  `PlagiarismType` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `ChapterUploadStatus` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `AuthorName` varchar(65533) NULL COMMENT "",
  `QYEditor` varchar(65533) NULL COMMENT "",
  `FullTime` datetime NULL COMMENT "",
  `FS` varchar(65533) NULL COMMENT "",
  `SH` varchar(65533) NULL COMMENT "",
  `FullPrice` int(11) NULL COMMENT "",
  `LockStatus` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `RowVersion` bigint(20) NULL COMMENT "",
  `StartNum` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `EndNum` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `CeilingReward` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `ChapterTime` varchar(65533) NULL COMMENT "",
  `ChapterTimeNum` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `LadderReward` varchar(65533) NULL COMMENT "",
  `ContractImgUrl` varchar(65533) NULL COMMENT "",
  `SARFT_Audit` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `IsPoint` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `IsPkBook` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `ContractID` varchar(65533) NULL COMMENT "",
  `SideBookName` varchar(65533) NULL COMMENT "",
  `SideCoverSrc` varchar(65533) NULL COMMENT "",
  `PresentReward` decimal(18, 2) NULL COMMENT "",
  `IsBadEnd` varchar(65533) NULL DEFAULT "0" COMMENT "",
  `IsChineseSequenceNum` varchar(65533) NULL DEFAULT "0" COMMENT "",
  `IsNeedVolume` varchar(65533) NULL DEFAULT "0" COMMENT "",
  `DelStatus` int(11) NOT NULL COMMENT "",
  `IsSigned` varchar(65533) NULL DEFAULT "0" COMMENT "",
  `CharacterNames` varchar(65533) NULL COMMENT "",
  `IsCanAutoWriting` varchar(65533) NULL DEFAULT "0" COMMENT "",
  `Recommendation` varchar(65533) NULL COMMENT "",
  `IsCustomWriting` int(11) NULL DEFAULT "0" COMMENT "",
  `PutDownTime` datetime NULL COMMENT "",
  `PutDownRemark` varchar(65533) NULL COMMENT "",
  `Remark` varchar(65533) NULL COMMENT "",
  `VipBecomeTime` datetime NULL COMMENT "",
  `LastUpdateTime` datetime NULL COMMENT "",
  `IsSyncSexy` int(11) NULL COMMENT "是否同步涉黄状态到繁体",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "",
  `sr_updatetime` datetime NULL COMMENT ""
) ENGINE=OLAP 
PRIMARY KEY(`BookId`)
COMMENT "凤鸣轩--书籍表"
DISTRIBUTED BY HASH(`BookId`) BUCKETS 1 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
