CREATE TABLE `ods_tidb_readernovel_tidb_xx_userotherinfo` (
  `productid` int(11) NOT NULL COMMENT "产品id",
  `Id` bigint(20) NOT NULL COMMENT "用户id",
  `HeadFrameList` varchar(65533) NULL COMMENT "头像框列表",
  `IsSync` int(11) NULL COMMENT "是否已经同步",
  `IsOnePurchase` int(11) NULL COMMENT "是否充值过1元购",
  `LastGetTime` datetime NULL COMMENT "上次获取时间",
  `OnePurchaseList` varchar(65533) NULL COMMENT "一元购信息",
  `TotalUseGift` int(11) NULL COMMENT "累计消耗礼券",
  `Today` datetime NULL COMMENT "当天时间",
  `TodayUseJiFen` int(11) NULL COMMENT "当天消耗的积分",
  `TodayGetJiFen` int(11) NULL COMMENT "获取今日获得积分",
  `OnePurchaseFirstTime` datetime NULL COMMENT "第一次满足条件的时间",
  `OnePurchaseUrl` varchar(65533) NULL COMMENT "满足条件的ndaction",
  `LastChargeReturnTime` datetime NULL COMMENT "上次充值挽留时间",
  `ReadBackgroundFirstReadTime` datetime NULL COMMENT "阅读背景试用功能第一次阅读时间",
  `ActivityClickRecord` varchar(65533) NULL COMMENT "存储点击过的活动记录",
  `ShopMallEmail` varchar(65533) NULL COMMENT "商城兑换客户留的邮箱",
  `ShopMallFaceBook` varchar(65533) NULL COMMENT "商城兑换客户留的FaceBook联系方式",
  `LastBuyBookId` bigint(20) NULL COMMENT "上一次购买书籍id",
  `LastBuyBookTime` datetime NULL COMMENT "上一次购买书籍时间",
  `LastWatchAdTime` datetime NULL COMMENT "上一次观看广告时间",
  `EmailBoundTime` datetime NULL COMMENT "邮箱绑定时间",
  `TotalPay` int(11) NULL COMMENT "充值累计消费",
  `row_update_time` datetime NULL COMMENT "更新时间",
  `IsNegativeUser` int(11) NULL COMMENT "是否白嫖用户",
  `IsCancleEdmEamil` int(11) NULL COMMENT "是否退订edm邮箱",
  `CancleEdmEamilTime` datetime NULL COMMENT "退订edm邮箱时间",
  `JiFenMinExpTime` datetime NULL COMMENT "积分最早过期时间",
  `HasChargeThirdPayment` int(11) NULL COMMENT "是否充值过第三方",
  `BOOKID` bigint(20) NULL COMMENT "书籍id",
  `ADSBOOKID` bigint(20) NULL COMMENT "广告书籍id",
  `ADSTYPE` varchar(60) NULL COMMENT "用户广告标签ADSTYPE",
  `ADSQUALITY` int(11) NULL COMMENT "用户广告标签",
  `MoneySustainTime` datetime NULL COMMENT "余额持续时间",
  `IsLogOff` int(11) NULL COMMENT "是否注销",
  `ShowChargeReturnCount` int(11) NULL COMMENT "当天充值挽留展示次数",
  `ShowChargeReturnTime` datetime NULL COMMENT "展示充值挽留时间",
  `HasAgreeComment` int(11) NULL COMMENT "是否已同意评论协议",
  `SignPushIsClose` int(11) NULL COMMENT "用户push是否关闭",
  `HalfRuleRechargeMoney` int(11) NULL COMMENT "半屏充值金额",
  `HalfRuleRechargeNum` int(11) NULL COMMENT "半屏充值次数",
  `DailyVideoNotMedalCount` int(11) NULL COMMENT "当日消耗积分数量",
  `LastMedalGetTime` datetime NULL COMMENT "上一次勋章获得时间",
  `DailyVideoCount` int(11) NULL COMMENT "用户每日观看视频数量",
  `CommonChargeCount` int(11) NULL COMMENT "普通充值次数",
  `NearChargePeakValue` int(11) NULL COMMENT "近N天充值的峰值",
  `NearChargePeakValueTime` datetime NULL COMMENT "近N天充值的峰值，充值订单的时间",
  `IsInviteFriendsLink` int(11) NULL COMMENT "是否下发邀请",
  `IsInviteFriendsCodeLink` int(11) NULL COMMENT "是否有填写邀请码链接",
  `HasInviteFriends` int(11) NULL COMMENT "是否有邀请",
  `InviteUserType` int(11) NULL COMMENT "邀请用户类型",
  `InviteFriendsNum` int(11) NULL COMMENT "我的邀请人数",
  `InviteFriendsCode` varchar(150) NULL COMMENT "用户邀请Code",
  `InviteFriendsUserId` bigint(20) NULL COMMENT "用户邀请UserId",
  `HasFirstInviteFriendsLink` int(11) NULL COMMENT "第一次是否下发邀请",
  `HasShareinvitation` int(11) NULL COMMENT "第一次是有剪贴板",
  `LastRechargeAmount` int(11) NULL COMMENT "最近一次充值金额",
  `NewHalfRuleRechargeNum` int(11) NULL COMMENT "新半屏充值金额",
  `NewHalfRuleRechargeMoney` int(11) NULL COMMENT "新半屏充值金额",
  `DefaultIntoPageType` int(11) NULL COMMENT "默认进入页面",
  `DefaultIntoPageTime` datetime NULL COMMENT "分组时间",
  `ExEMail` varchar(65533) NULL COMMENT "第三方账号的邮箱信息",
  `RemarketingTime` datetime NULL COMMENT "再召回时间",
  `TeenMode` int(11) NULL COMMENT "用户是否设置了青少年模式（0：未弹窗确认，1：已开启，2：已关闭））",
  `RealTimeGroups` varchar(65533) NULL COMMENT "实时人群包",
  `OldEmailInfo` varchar(65533) NULL COMMENT "旧的电子邮箱信息",
  `FaceBookBindEmailTime` datetime NULL COMMENT "facebook绑定email时间",
  `IsFaceBookBindEmail` int(11) NULL COMMENT "facebook是否绑定邮箱",
  `IsSyncShelf` int(11) NULL COMMENT "是否同步过书架",
  `LastSendOrderTime` datetime NULL COMMENT "上一次下发到的订单时间",
  `LastSendOrderTimeByCore` varchar(65533) NULL COMMENT "上一次下发到的订单时间，分Core",
  `HasAppEvaluate` int(11) NULL COMMENT "是否反馈评论",
  `LastAppEvaluateTime` datetime NULL COMMENT "上次反馈评论时间",
  `Last30LiveDay` int(11) NULL COMMENT "最近30活跃天数",
  `JiFenExchangeRate` decimal(20, 4) NULL COMMENT "昨日的积分兑换比例",
  `JiFenExchangeExtra` decimal(20, 4) NULL COMMENT "昨日的兑换比例累计增幅",
  `JiFenExchangeRateUse` decimal(20, 4) NULL COMMENT "昨日实际使用的兑换比例",
  `row_create_time` datetime NULL COMMENT "数据生成时间",
  `IsSvipTrial` int(11) NULL COMMENT "是否购买过svip试用",
  `AttributionDropTime` datetime NULL COMMENT "归因丢弃时间",
  `AdSetName` varchar(65533) NULL COMMENT "归因成功的广告组名",
  `AdSetId` varchar(65533) NULL COMMENT "归因成功的广告组Id",
  `AdCampId` varchar(65533) NULL COMMENT "归因成功的广告系列Id",
  `AdCampName` varchar(65533) NULL COMMENT "归因成功的广告系列名",
  `SourceChl` varchar(65533) NULL COMMENT "归因成功的来源渠道",
  `IsRemarketing` int(11) NULL COMMENT "归因成功的是否再营销标记",
  `CoinLotteryReadFreeOutTime` datetime NULL COMMENT "",
  `FreeReadExpireTime` datetime NULL COMMENT "免费阅读过期时间",
  `DelADExpireTime` datetime NULL COMMENT "看激励视频，去除广告过期时间，西五区时间，author:350625",
  `DelAdToday` datetime NULL COMMENT "看激励视频，去除广告当天，西五区时间，author:350625",
  `DelAdTimes` int(11) NULL COMMENT "看激励视频，去除广告当天次数，按西五区时间刷新，author:350625",
  `WatchSignAdLastTime` datetime NULL COMMENT "最近看签到视频时间",
  `CrossChapterEndTime` datetime NULL COMMENT "跨章结束时间",
  `IsLowVipTrial` int(11) NULL COMMENT "是否购买过Vip试用",
  `QuickTokenByPayPal` varchar(65533) NULL COMMENT "paypal免密token",
  `LastNewInstallTime` datetime NULL COMMENT "上次新安装第一次打开的时间",
  `AdPreloadReportNum` int(11) NULL COMMENT "上次新安装后广告预加载上报次数",
  `InterestTags` varchar(1048576) NULL COMMENT "兴趣标签",
  `ShowInterestTags` int(11) NULL COMMENT "是否显示兴趣标签",
  `InviteFriendsCombinId` int(11) NULL COMMENT "组合活动邀请id",
  `TotalActualPay` decimal(18, 2) NULL COMMENT "总支付金额，小数类型",
  `LastRechargeActualAmount` decimal(18, 2) NULL COMMENT "上次充值金额，小数类型",
  `BuiltinRecLangs` varchar(300) NULL COMMENT "书架装机推荐语言id",
  `PushSwitch` int(11) NULL COMMENT "push开关，0未知，1：开启，2：关闭",
  `UserAdSource` int(11) NULL COMMENT "广告投流用户：0：正常用户，1：vip投流用户",
  `DynamicIslandSwitch` int(11) NULL COMMENT "灵动岛开关，0未知，1：开启，2：关闭",
  `BuiltinRecVipUserBooks` varchar(65533) NULL COMMENT "第一次装机推用户VIP投流",
  `IsFristPushesVipUser` int(11) NULL COMMENT "第一次装机推用户VIP投流",
  `IsFristVipUserWorkChange` int(11) NULL COMMENT "是否作业发生VIP投流用户改变 1改变 ，处理完后需要重置为0",
  `UserAdSetSource` int(11) NULL COMMENT "设置来源：0：未知，1：华总通知设置，2:1029接口客户端上报设置，华总通知设置后，1029接口上报不再更新UserAdSource和UserAdVipSourceBookId",
  `UserAdVipSourceBookId` bigint(20) NULL COMMENT "广告投流用户：vip投流用户书籍，非投流设置成0",
  `UserVipBookIdList` varchar(65533) NULL COMMENT "会员vip书籍快照",
  `UserAdSetTime` datetime NULL COMMENT "广告投流用户设置时间",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "",
  `sr_updatetime` datetime NULL COMMENT ""
) ENGINE=OLAP 
PRIMARY KEY(`productid`, `Id`)
COMMENT "用户其他信息"
DISTRIBUTED BY HASH(`Id`) BUCKETS 3 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
