CREATE TABLE `ods_ads_tidb_sharpengine_ads_global_FbAdRoiInstallReferrerByHourTimeZone` (
  `Id` bigint(20) NOT NULL COMMENT "",
  `AdId` varchar(1000) NULL COMMENT "",
  `CreateTime` varchar(200) NULL COMMENT "",
  `CreateHour` int(11) NULL COMMENT "",
  `PayList` varchar(65533) NULL COMMENT "",
  `RegNum` int(11) NULL COMMENT "",
  `Impressions` bigint(20) NULL COMMENT "",
  `LinkClicks` bigint(20) NULL COMMENT "",
  `Installs` bigint(20) NULL COMMENT "",
  `Clicks` bigint(20) NULL COMMENT "",
  `CostAmount` decimal(10, 2) NULL COMMENT "",
  `ProductId` int(11) NULL COMMENT "",
  `PayNum` int(11) NULL COMMENT "",
  `UpdateTime` datetime NULL COMMENT "",
  `PayListByDays` varchar(30000) NULL COMMENT "",
  `CheckSum` bigint(20) NULL COMMENT "",
  `LoginNum2` int(11) NULL COMMENT "",
  `LoginNum3` int(11) NULL COMMENT "",
  `LoginNum7` int(11) NULL COMMENT "",
  `Core` int(11) NULL COMMENT "",
  `Mt` int(11) NULL COMMENT "",
  `FbAccount` varchar(200) NULL COMMENT "",
  `AdSetId` varchar(1000) NULL COMMENT "",
  `AdCampId` varchar(1000) NULL COMMENT "",
  `DevNum` int(11) NULL COMMENT "",
  `GroupId` int(11) NULL COMMENT "",
  `SourceChl` varchar(500) NULL COMMENT "",
  `Chl2` varchar(500) NULL COMMENT "",
  `RowVersion` bigint(20) NULL COMMENT "",
  `CurrentLanguage2` int(11) NULL COMMENT "",
  `AdsQuality` int(11) NULL COMMENT "",
  `Updater` varchar(1000) NULL COMMENT "",
  `Hour0Amount` decimal(10, 4) NULL COMMENT "",
  `Hour1Amount` decimal(10, 4) NULL COMMENT "",
  `Hour2Amount` decimal(10, 4) NULL COMMENT "",
  `Hour3Amount` decimal(10, 4) NULL COMMENT "",
  `Hour4Amount` decimal(10, 4) NULL COMMENT "",
  `Hour5Amount` decimal(10, 4) NULL COMMENT "",
  `Hour6Amount` decimal(10, 4) NULL COMMENT "",
  `Hour7Amount` decimal(10, 4) NULL COMMENT "",
  `Hour8Amount` decimal(10, 4) NULL COMMENT "",
  `Hour9Amount` decimal(10, 4) NULL COMMENT "",
  `Hour10Amount` decimal(10, 4) NULL COMMENT "",
  `Hour11Amount` decimal(10, 4) NULL COMMENT "",
  `Hour12Amount` decimal(10, 4) NULL COMMENT "",
  `Hour13Amount` decimal(10, 4) NULL COMMENT "",
  `Hour14Amount` decimal(10, 4) NULL COMMENT "",
  `Hour15Amount` decimal(10, 4) NULL COMMENT "",
  `Hour16Amount` decimal(10, 4) NULL COMMENT "",
  `Hour17Amount` decimal(10, 4) NULL COMMENT "",
  `Hour18Amount` decimal(10, 4) NULL COMMENT "",
  `Hour19Amount` decimal(10, 4) NULL COMMENT "",
  `Hour20Amount` decimal(10, 4) NULL COMMENT "",
  `Hour21Amount` decimal(10, 4) NULL COMMENT "",
  `Hour22Amount` decimal(10, 4) NULL COMMENT "",
  `Hour23Amount` decimal(10, 4) NULL COMMENT "",
  `Hour0AmountByAd` decimal(10, 4) NULL COMMENT "",
  `Hour1AmountByAd` decimal(10, 4) NULL COMMENT "",
  `Hour2AmountByAd` decimal(10, 4) NULL COMMENT "",
  `Hour3AmountByAd` decimal(10, 4) NULL COMMENT "",
  `Hour4AmountByAd` decimal(10, 4) NULL COMMENT "",
  `Hour5AmountByAd` decimal(10, 4) NULL COMMENT "",
  `Hour6AmountByAd` decimal(10, 4) NULL COMMENT "",
  `Hour7AmountByAd` decimal(10, 4) NULL COMMENT "",
  `Hour8AmountByAd` decimal(10, 4) NULL COMMENT "",
  `Hour9AmountByAd` decimal(10, 4) NULL COMMENT "",
  `Hour10AmountByAd` decimal(10, 4) NULL COMMENT "",
  `Hour11AmountByAd` decimal(10, 4) NULL COMMENT "",
  `Hour12AmountByAd` decimal(10, 4) NULL COMMENT "",
  `Hour13AmountByAd` decimal(10, 4) NULL COMMENT "",
  `Hour14AmountByAd` decimal(10, 4) NULL COMMENT "",
  `Hour15AmountByAd` decimal(10, 4) NULL COMMENT "",
  `Hour16AmountByAd` decimal(10, 4) NULL COMMENT "",
  `Hour17AmountByAd` decimal(10, 4) NULL COMMENT "",
  `Hour18AmountByAd` decimal(10, 4) NULL COMMENT "",
  `Hour19AmountByAd` decimal(10, 4) NULL COMMENT "",
  `Hour20AmountByAd` decimal(10, 4) NULL COMMENT "",
  `Hour21AmountByAd` decimal(10, 4) NULL COMMENT "",
  `Hour22AmountByAd` decimal(10, 4) NULL COMMENT "",
  `Hour23AmountByAd` decimal(10, 4) NULL COMMENT "",
  `Hour0FirstPayNum` int(11) NULL COMMENT "",
  `Hour1FirstPayNum` int(11) NULL COMMENT "",
  `Hour2FirstPayNum` int(11) NULL COMMENT "",
  `Hour3FirstPayNum` int(11) NULL COMMENT "",
  `Hour4FirstPayNum` int(11) NULL COMMENT "",
  `Hour5FirstPayNum` int(11) NULL COMMENT "",
  `Hour6FirstPayNum` int(11) NULL COMMENT "",
  `Hour7FirstPayNum` int(11) NULL COMMENT "",
  `Hour8FirstPayNum` int(11) NULL COMMENT "",
  `Hour9FirstPayNum` int(11) NULL COMMENT "",
  `Hour10FirstPayNum` int(11) NULL COMMENT "",
  `Hour11FirstPayNum` int(11) NULL COMMENT "",
  `Hour12FirstPayNum` int(11) NULL COMMENT "",
  `Hour13FirstPayNum` int(11) NULL COMMENT "",
  `Hour14FirstPayNum` int(11) NULL COMMENT "",
  `Hour15FirstPayNum` int(11) NULL COMMENT "",
  `Hour16FirstPayNum` int(11) NULL COMMENT "",
  `Hour17FirstPayNum` int(11) NULL COMMENT "",
  `Hour18FirstPayNum` int(11) NULL COMMENT "",
  `Hour19FirstPayNum` int(11) NULL COMMENT "",
  `Hour20FirstPayNum` int(11) NULL COMMENT "",
  `Hour21FirstPayNum` int(11) NULL COMMENT "",
  `Hour22FirstPayNum` int(11) NULL COMMENT "",
  `Hour23FirstPayNum` int(11) NULL COMMENT "",
  `Hour0PayNum` int(11) NULL COMMENT "",
  `Hour1PayNum` int(11) NULL COMMENT "",
  `Hour2PayNum` int(11) NULL COMMENT "",
  `Hour3PayNum` int(11) NULL COMMENT "",
  `Hour4PayNum` int(11) NULL COMMENT "",
  `Hour5PayNum` int(11) NULL COMMENT "",
  `Hour6PayNum` int(11) NULL COMMENT "",
  `Hour7PayNum` int(11) NULL COMMENT "",
  `Hour8PayNum` int(11) NULL COMMENT "",
  `Hour9PayNum` int(11) NULL COMMENT "",
  `Hour10PayNum` int(11) NULL COMMENT "",
  `Hour11PayNum` int(11) NULL COMMENT "",
  `Hour12PayNum` int(11) NULL COMMENT "",
  `Hour13PayNum` int(11) NULL COMMENT "",
  `Hour14PayNum` int(11) NULL COMMENT "",
  `Hour15PayNum` int(11) NULL COMMENT "",
  `Hour16PayNum` int(11) NULL COMMENT "",
  `Hour17PayNum` int(11) NULL COMMENT "",
  `Hour18PayNum` int(11) NULL COMMENT "",
  `Hour19PayNum` int(11) NULL COMMENT "",
  `Hour20PayNum` int(11) NULL COMMENT "",
  `Hour21PayNum` int(11) NULL COMMENT "",
  `Hour22PayNum` int(11) NULL COMMENT "",
  `Hour23PayNum` int(11) NULL COMMENT "",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据注入时间",
  `sr_updatetime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据更新时间"
) ENGINE=OLAP 
PRIMARY KEY(`Id`)
DISTRIBUTED BY HASH(`Id`) BUCKETS 200 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
