CREATE TABLE `ods_tidb_kocdb_koc_adltvitem` (
  `Id` bigint(20) NOT NULL COMMENT "主键ID",
  `DateKey` varchar(500) NULL COMMENT "日期yyyy-MM-dd(东八区)",
  `ProductId` int(11) NULL COMMENT "ProductId",
  `AdId` varchar(1000) NULL COMMENT "koc的广告ID",
  `MonthKey` varchar(500) NULL COMMENT "月份yyyy-MM(东八区)",
  `DevNum` int(11) NULL COMMENT "激活用户数",
  `NewDevNum` int(11) NULL COMMENT "新用户数",
  `ActiveDevNum` int(11) NULL COMMENT "活跃用户数",
  `Amount` decimal(16, 4) NULL COMMENT "充值金额",
  `BaseAmount` decimal(16, 4) NULL COMMENT "扣除渠道费充值金额",
  `Income` decimal(16, 4) NULL COMMENT "收入金额",
  `RealDevNum` int(11) NULL COMMENT "激活用户数 机构和达人可见的激活用户数",
  `RealIncome` decimal(16, 4) NULL COMMENT "收入金额 机构和达人可见的收入金额",
  `Core` int(11) NULL COMMENT "Core",
  `Mt` int(11) NULL COMMENT "终端",
  `SourceChl` varchar(500) NULL COMMENT "媒体",
  `Chl` varchar(500) NULL COMMENT "渠道",
  `CurrentLanguage` int(11) NULL COMMENT "投放语言",
  `KocCode` varchar(500) NULL COMMENT "口令",
  `ProjectType` int(11) NULL COMMENT "项目类型 1=书|2=短剧",
  `DataKey` varchar(500) NULL COMMENT "书籍和短剧 项目类型_书籍|短剧ID",
  `DataId` bigint(20) NULL COMMENT "书籍|短剧ID",
  `InstitutionId` bigint(20) NULL COMMENT "机构ID",
  `InstitutionStatus` int(11) NULL COMMENT "状态 0=禁用|1=启用",
  `InstitutionCreatorUid` varchar(500) NULL COMMENT "机构创建人账号ID",
  `StarId` bigint(20) NULL COMMENT "达人ID",
  `StarStatus` int(11) NULL COMMENT "状态 0=禁用|1=启用",
  `AppType` varchar(500) NULL COMMENT "App类型",
  `CooperationType` int(11) NULL COMMENT "合作模式 1=分成合作",
  `SplitRatio` int(11) NULL COMMENT "机构可获得的分成比例 30=30%",
  `TransactionFeeType` int(11) NULL COMMENT "通道费扣除类型 1=约定统一支付通道费|2=自定义支付通道费|3=约定实际支付通道费|4=免除通道费",
  `TransactionFee` int(11) NULL COMMENT "通通道费 30=30%",
  `CostFactorType` int(11) NULL COMMENT "成本系数类型 1=约定统一成本系数|2=自定义成本系数|3=免除成本系数",
  `CostFactor` int(11) NULL COMMENT "成本系数 30=30%",
  `CooperationBeginTime` datetime NULL COMMENT "合作开始时间",
  `CooperationEndTime` datetime NULL COMMENT "合作结束时间",
  `CreateTime` datetime NULL COMMENT "创建时间",
  `UpdateTime` datetime NULL COMMENT "更新时间",
  `LeaderId` bigint(20) NULL COMMENT "队长id",
  `DistribIncome` decimal(16, 4) NULL COMMENT "分销金额",
  `RealDistribIncome` decimal(16, 4) NULL COMMENT "实际分销金额",
  `DistributeType` int(11) NULL COMMENT "分销类型 0=约定统一 1=自定义",
  `DistributeRatio` int(11) NULL COMMENT "分销比例 15=15%",
  `LeaderStatus` int(11) NULL COMMENT "团长状态",
  `BusinessType` int(11) NULL COMMENT "业务模式  0-tob  1-toc",
  `Exchange` decimal(16, 4) NULL COMMENT "汇率",
  `NewRealDevNum` decimal(16, 4) NULL COMMENT "激活用户数-机构和达人可见的激活用户数-新用户",
  `ActiveRealDevNum` decimal(16, 4) NULL COMMENT "激活用户数-机构和达人可见的激活用户数-活跃用户",
  `NewAmount` decimal(16, 4) NULL COMMENT "充值金额-新用户",
  `ActiveAmount` decimal(16, 4) NULL COMMENT "充值金额-活跃用户",
  `NewBaseAmount` decimal(16, 4) NULL COMMENT "扣除渠道费充值金额-新用户",
  `ActiveBaseAmount` decimal(16, 4) NULL COMMENT "扣除渠道费充值金额-活跃用户",
  `NewIncome` decimal(16, 4) NULL COMMENT "收入金额-新用户",
  `ActiveIncome` decimal(16, 4) NULL COMMENT "收入金额-活跃用户",
  `NewRealIncome` decimal(16, 4) NULL COMMENT "收入金额 机构和达人可见的收入金额-新用户",
  `ActiveRealIncome` decimal(16, 4) NULL COMMENT "收入金额 机构和达人可见的收入金额-活跃用户",
  `NewDistribIncome` decimal(16, 4) NULL COMMENT "分销金额-新用户",
  `ActiveDistribIncome` decimal(16, 4) NULL COMMENT "分销金额-活跃用户",
  `NewRealDistribIncome` decimal(16, 4) NULL COMMENT "实际分销金额-新用户",
  `ActiveRealDistribIncome` decimal(16, 4) NULL COMMENT "实际分销金额-活跃用户",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据注入时间",
  `sr_updatetime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据更新时间",
  `OrderNum` int(11) NULL COMMENT "订单数",
  `AmountBy14` decimal(16, 4) NULL COMMENT "14天充值金额",
  `BaseAmountBy14` decimal(16, 4) NULL COMMENT "14天扣除渠道费后充值金额",
  `PlatformRaito` int(11) NULL COMMENT "平台分成比例",
  `OperatorId` varchar(200) NULL COMMENT "商务Id",
  `AdType` int(11) NULL COMMENT "1-广告收入"
) ENGINE=OLAP 
PRIMARY KEY(`Id`)
COMMENT "KOC的每日报表数据"
DISTRIBUTED BY HASH(`Id`) BUCKETS 3 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "false",
"replicated_storage" = "true",
"compression" = "LZ4"
);
