CREATE TABLE `ods_cdmoney_report_tidb_cn_dispute_antom` (
  `id` bigint(20) NOT NULL COMMENT "自增ID",
  `dispute_id` varchar(200) NULL COMMENT "争议id",
  `pay_channel_id` varchar(500) NULL COMMENT "渠道ID",
  `pay_channel_name` varchar(500) NULL COMMENT "渠道名称",
  `coo_order_id` varchar(500) NULL COMMENT ":支付订单号,合作方回传的,paypal提供的,当做唯一标识争议id",
  `order_id` varchar(500) NULL COMMENT "订单表>订单号",
  `order_serialid` varchar(500) NULL COMMENT "order_serialid",
  `account` varchar(1000) NULL COMMENT "订单表>用户账号",
  `user_id` varchar(1000) NULL COMMENT "订单表>用户ID",
  `amount` decimal(18, 2) NULL COMMENT "订单表>订单金额",
  `coins` decimal(18, 2) NULL COMMENT "订单表>代币",
  `product_id` varchar(1000) NULL COMMENT "订单表>产品ID",
  `shop_item_id` varchar(1000) NULL COMMENT "渠道ID",
  `core` int(11) NULL COMMENT "订单表>core",
  `os_type` int(11) NULL COMMENT "订单表>平台,相当于mt,1-iOS,4-安卓,其他",
  `order_create_time` datetime NULL COMMENT "订单表>创建时间",
  `coo_notify_time` datetime NULL COMMENT "订单表>到账时间",
  `coo_order_status` int(11) NULL COMMENT "订单表>合作方扣款状态：1 成功",
  `dispute_fee` decimal(18, 2) NULL COMMENT "争议费用，等同于订单金额",
  `dispute_amount` decimal(18, 2) NULL COMMENT "初始争议金额",
  `dispute_judged_amount` decimal(18, 2) NULL COMMENT "结算争议金额",
  `dispute_judged_fee` decimal(18, 2) NULL COMMENT "结算争议费用",
  `dispute_total_amount` decimal(18, 2) NULL COMMENT "结算总额(结算争议金额+结算争议费用)",
  `currency` varchar(500) NULL COMMENT "货币",
  `status` int(11) NULL COMMENT "争议状态 0待卖家回复 1已回复 2败诉 3胜诉 4审核中 5已退款 6已关闭：买家取消  7RDR争议",
  `final_status` int(11) NULL COMMENT "最终状态 0待处理 1 处理中 2已解决",
  `detail_resp_data` varchar(10000) NULL COMMENT "详情接口响应数据",
  `insert_time` datetime NULL COMMENT "添加时间",
  `evidence_due_by` datetime NULL COMMENT "回复截止时间",
  `update_time` datetime NULL COMMENT "更新时间",
  `handler_status` int(11) NULL COMMENT "处理状态：0 无，2 订单数据缺失，3 自动回复失败，4 自动回复成功，5-人工回复成功",
  `dispute_reason_code` varchar(1000) NULL COMMENT "退款原因",
  `dispute_type` varchar(1000) NULL COMMENT "争议类型",
  `dispute_notification_type` varchar(1000) NULL COMMENT "通知类型",
  `dispute_judged_result` varchar(1000) NULL COMMENT "dispute_judged_result",
  `dispute_reason_msg` varchar(5000) NULL COMMENT "争议的理由",
  `evidence_resp_data` varchar(10000) NULL COMMENT "提供证据接口响应数据",
  `defendable` int(11) NULL COMMENT "表明争议是否可辩护 0否 1是",
  `is_exec` int(11) NULL COMMENT "当前节点是否已执行,流转到下个节点重置为0",
  `auto_send_evidence_count` int(11) NULL COMMENT "自动提交证据次数",
  `send_overtime_warn_count` int(11) NULL COMMENT "超时预警推送次数",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据注入时间",
  `sr_updatetime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据更新时间"
) ENGINE=OLAP 
PRIMARY KEY(`id`)
COMMENT "Antom争议表,author:510161"
DISTRIBUTED BY HASH(`id`) BUCKETS 10 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
