CREATE TABLE `ods_sharpengine_ads_hk_bak_if_user_installreferrer_v3` (
  `Id` bigint(20) NOT NULL COMMENT "",
  `ProductId` int(11) NULL COMMENT "",
  `UserId` bigint(20) NULL COMMENT "",
  `Source` varchar(300) NULL COMMENT "",
  `AdId` varchar(1000) NULL COMMENT "",
  `AdType` int(11) NULL COMMENT "",
  `InstallDate` datetime NULL COMMENT "",
  `AdAccountId` varchar(1000) NULL COMMENT "",
  `AdSetId` varchar(1000) NULL COMMENT "",
  `BookId` varchar(200) NULL COMMENT "",
  `Creative` varchar(15000) NULL COMMENT "",
  `InstallOriginalRequest` varchar(30000) NULL COMMENT "",
  `Login` varchar(1000) NULL COMMENT "",
  `UniqueCdReaderId` varchar(1000) NULL COMMENT "",
  `Country` varchar(1000) NULL COMMENT "",
  `Mt` int(11) NULL COMMENT "",
  `Core` int(11) NULL COMMENT "",
  `DataInsertDate` varchar(200) NULL COMMENT "",
  `Networkname` varchar(1000) NULL COMMENT "",
  `Chl2` varchar(500) NULL COMMENT "",
  `CreateTime` datetime NULL COMMENT "新增时间",
  `adgroup_name` varchar(1500) NULL COMMENT "",
  `CurrentLanguage2` int(11) NULL COMMENT "",
  `RemarketingTime` datetime NULL COMMENT "",
  `AdQualityStatus` int(11) NULL COMMENT "",
  `InstallDateEst` date NULL COMMENT "",
  `ReInstallDate` datetime NULL COMMENT "",
  `AnalysisServerStatus` int(11) NULL COMMENT "",
  `NextAttributeTime` datetime NULL COMMENT "",
  `NextAttributeAdId` varchar(1000) NULL COMMENT "",
  `NextAttributeSource` varchar(1000) NULL COMMENT "",
  `PreAttributeTime` datetime NULL COMMENT "",
  `PreAttributeAdId` varchar(1000) NULL COMMENT "",
  `PreAttributeSource` varchar(1000) NULL COMMENT "",
  `IsReInstall` int(11) NULL COMMENT "",
  `PreAttributeDataId` bigint(20) NULL COMMENT "",
  `NextAttributeDataId` bigint(20) NULL COMMENT "",
  `RawAdId` varchar(1000) NULL COMMENT "",
  `TraceId` varchar(500) NULL COMMENT "s2s的追踪Id",
  `PixelId` varchar(500) NULL COMMENT "fb的像素Id",
  `At` int(11) NULL COMMENT "归因有效期",
  `IsRemarketing` int(11) NULL COMMENT "是否再营销",
  `NextAttributeIsRemarketing` int(11) NULL COMMENT "",
  `PreAttributeIsRemarketing` int(11) NULL COMMENT "",
  `RemarkTimeSendToAppServer` int(11) NULL COMMENT "发送RemarketingTime到AppServer状态",
  `CustomAudiences` varchar(500) NULL COMMENT "",
  `IsDelete` int(11) NULL COMMENT "",
  `row_update_time` datetime NULL COMMENT "",
  `c2rtime` datetime NULL COMMENT "",
  `abtestpageid` int(11) NULL COMMENT "",
  `FirstOpenResId` bigint(20) NULL COMMENT "首次打开的剧的id，默认值应该是0",
  `AdName` varchar(1500) NULL COMMENT "广告名",
  `AdSetName` varchar(1500) NULL COMMENT "广告组名",
  `AdCampName` varchar(1500) NULL COMMENT "广告系列名",
  `AdCampId` varchar(1000) NULL COMMENT "广告系列Id",
  `LastPayTime` datetime NULL COMMENT "归因后最新的充值时间",
  `RawMt` int(11) NULL COMMENT "原始Mt",
  `ReInstallType` int(11) NULL COMMENT "",
  `LastClickTime` datetime NULL COMMENT "",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据注入时间",
  `sr_updatetime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据更新时间"
) ENGINE=OLAP 
PRIMARY KEY(`Id`)
DISTRIBUTED BY HASH(`Id`) BUCKETS 30 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
