CREATE TABLE `ods_tidb_shuangwen_xx_objectauthor` (
  `productid` smallint(6) NOT NULL COMMENT "产品id",
  `AccountId` bigint(20) NOT NULL COMMENT "译员Id",
  `ToLanguage` int(11) NOT NULL COMMENT "语言",
  `PenName` varchar(65533) NULL COMMENT "译名",
  `EMail` varchar(65533) NULL COMMENT "邮箱",
  `QQ` varchar(65533) NULL COMMENT "QQ",
  `Phone` varchar(65533) NULL COMMENT "电话",
  `IDCard` varchar(65533) NULL COMMENT "身份证",
  `IDPostCode` varchar(65533) NULL COMMENT "邮编",
  `IDAddress` varchar(65533) NULL COMMENT "身份证地址",
  `RealName` varchar(65533) NULL COMMENT "真实姓名",
  `Address` varchar(65533) NULL COMMENT "地址",
  `PostCode` varchar(65533) NULL COMMENT "邮编",
  `Status` int(11) NOT NULL COMMENT "状态",
  `BankAccount` varchar(65533) NULL COMMENT "银行账号",
  `BankName` varchar(65533) NULL COMMENT "开户行",
  `GroupId` int(11) NULL COMMENT "组id",
  `BankUserName` varchar(65533) NULL COMMENT "开户行支行名称",
  `IDCardFrontPhoto` varchar(65533) NULL COMMENT "身份证正面",
  `IDCardVersoPhoto` varchar(65533) NULL COMMENT "身份证背面",
  `TollStatus` int(11) NULL COMMENT "TollStatus",
  `RefAccount` varchar(65533) NULL COMMENT "RefAccount",
  `AddTime` datetime NULL COMMENT "添加时间",
  `RefAccountId` varchar(65533) NULL COMMENT "RefAccountId",
  `AccountType` int(11) NULL COMMENT "账号类型",
  `Sex` varchar(65533) NULL COMMENT "性别",
  `HomePhone` varchar(65533) NULL COMMENT "家庭电话",
  `AccountName` varchar(65533) NULL COMMENT "银行账号姓名",
  `AcccountName` varchar(65533) NULL COMMENT "银行账号姓名",
  `GroupPmIds` varchar(65533) NULL COMMENT "GroupPmIds",
  `GroupIds` varchar(65533) NULL COMMENT "GroupIds",
  `Price` decimal(18, 2) NOT NULL COMMENT "Price",
  `Pseudonym` varchar(65533) NULL COMMENT "笔名",
  `RemunerationType` int(11) NOT NULL COMMENT "稿酬类型",
  `TaxType` int(11) NOT NULL COMMENT "",
  `AuthorType` int(11) NOT NULL COMMENT "译员类型",
  `AbroadBank` varchar(65533) NULL COMMENT "外籍银行信息",
  `TranslatedChaptersNumber` int(11) NOT NULL COMMENT "TranslatedChaptersNumber",
  `TranslationAuditTel` varchar(65533) NULL COMMENT "TranslationAuditTel",
  `FDDCustomerId` varchar(65533) NULL COMMENT "法大大用户ID",
  `FDDCustomerVerifyUrl` varchar(65533) NULL COMMENT "法大大用户实名认证地址",
  `FDDVerifyTransactionNo` varchar(65533) NULL COMMENT "法大大认证流水号",
  `FDDVerifyStatus` int(11) NULL COMMENT "企业：status:  0：未认证； 1：管理员资料已提 交； 2：企业基本资料(没 有申请表)已提交； 3：已提交待审核； 4：审核通过； 5：审核不通过； 6 人工初审通过",
  `GroupAuditIds` varchar(65533) NULL COMMENT "GroupAuditIds",
  `ChapterIds` varchar(65533) NULL COMMENT "ChapterIds",
  `IsReader` tinyint(4) NULL COMMENT "IsReader",
  `IsAllWork` tinyint(4) NOT NULL COMMENT "是否全勤",
  `CurrencyType` tinyint(4) NOT NULL COMMENT "货币类型",
  `PaymentDate` int(11) NOT NULL COMMENT "付款日期",
  `IsInvoices` tinyint(4) NOT NULL COMMENT "是否发票",
  `AuditStatus` tinyint(4) NOT NULL COMMENT "审核状态 0：审批未通过、1：审批通过、2：审批中",
  `PayType` int(11) NOT NULL COMMENT "支付方式 0：银行卡、1：paypal、2：Payoneer、3：Upwork、4：Freelancer、5：Fiverr、6：银行卡(华美)、7：PayerMax",
  `RowVersion` bigint(20) NULL COMMENT "数据更新版本",
  `Country` varchar(65533) NULL COMMENT "国家",
  `FirstFeedBack` varchar(65533) NULL COMMENT "试译反馈",
  `Occupation` int(11) NULL COMMENT "职业",
  `Grade` int(11) NULL COMMENT "在读年级",
  `Remarks` varchar(65533) NULL COMMENT "备注",
  `IsSpecial` int(11) NOT NULL DEFAULT "0" COMMENT "特殊译员 1、降准译员",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "数据创建时间",
  `sr_updatetime` datetime NULL COMMENT "数据更新时间"
) ENGINE=OLAP 
PRIMARY KEY(`productid`, `AccountId`, `ToLanguage`)
COMMENT "译员表"
DISTRIBUTED BY HASH(`AccountId`) BUCKETS 3 
PROPERTIES (
"replication_num" = "3",
"bloom_filter_columns" = "AccountId",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
