CREATE TABLE `ods_tidb_sharpengine_ads_hk_bak_if_user_installreferrer_v2` (
  `Id` bigint(20) NOT NULL COMMENT "主键id",
  `ProductId` int(11) NULL COMMENT "产品id",
  `UserId` bigint(20) NULL COMMENT "用户id",
  `Source` varchar(65533) NULL COMMENT "媒体值（广告投放平台）",
  `AdId` varchar(65533) NULL COMMENT "广告id",
  `AdType` int(11) NULL COMMENT "广告类型",
  `InstallDate` datetime NULL COMMENT "激活安装时间",
  `AdAccountId` varchar(65533) NULL COMMENT "广告账户id",
  `AdSetId` varchar(65533) NULL COMMENT "广告系列id",
  `BookId` varchar(65533) NULL COMMENT "书籍id",
  `Creative` varchar(65533) NULL COMMENT "广告创意",
  `InstallOriginalRequest` varchar(65533) NULL COMMENT "安装原始请求",
  `Login` varchar(65533) NULL COMMENT "登录信息",
  `UniqueCdReaderId` varchar(65533) NULL COMMENT "设备信息",
  `Country` varchar(65533) NULL COMMENT "国家",
  `Mt` int(11) NULL COMMENT "终端",
  `Core` int(11) NULL COMMENT "core",
  `DataInsertDate` varchar(65533) NULL COMMENT "插入时间",
  `Networkname` varchar(65533) NULL COMMENT "媒体值",
  `Chl2` varchar(65533) NULL COMMENT "渠道值",
  `CreateTime` datetime NULL COMMENT "新增时间",
  `adgroup_name` varchar(65533) NULL COMMENT "广告组名称",
  `CurrentLanguage2` int(11) NULL COMMENT "注册时语言",
  `RemarketingTime` datetime NULL COMMENT "再营销时间",
  `AdQualityStatus` int(11) NULL COMMENT "广告质量状态",
  `InstallDateEst` date NULL COMMENT "西五区激活安装时间",
  `ReInstallDate` datetime NULL COMMENT "再安装时间",
  `AnalysisServerStatus` int(11) NULL COMMENT "同步sharpengine_analysis_tidb数据服务处理状态 0=未处理|1=已处理",
  `NextAttributeTime` datetime NULL COMMENT "下一次归因时间",
  `NextAttributeAdId` varchar(65533) NULL COMMENT "下一次广告归因id",
  `NextAttributeSource` varchar(65533) NULL COMMENT "下一次归因来源",
  `PreAttributeTime` datetime NULL COMMENT "上一次归因来源时间",
  `PreAttributeAdId` varchar(65533) NULL COMMENT "上一次归因广告id",
  `PreAttributeSource` varchar(65533) NULL COMMENT "上一次归因来源",
  `IsReInstall` int(11) NULL COMMENT "是否再安装",
  `PreAttributeDataId` bigint(20) NULL COMMENT "上一次归因的id",
  `NextAttributeDataId` bigint(20) NULL COMMENT "下一次归因的id",
  `RawAdId` varchar(65533) NULL COMMENT "未处理广告id",
  `TraceId` varchar(65533) NULL COMMENT "s2s的追踪Id",
  `PixelId` varchar(65533) NULL COMMENT "fb的像素Id",
  `At` int(11) NULL COMMENT "归因有效期",
  `IsRemarketing` int(11) NULL COMMENT "是否再营销",
  `NextAttributeIsRemarketing` int(11) NULL COMMENT "下一次归因是否再营销",
  `PreAttributeIsRemarketing` int(11) NULL COMMENT "上一次归因是否再营销",
  `RemarkTimeSendToAppServer` int(11) NULL COMMENT "发送RemarketingTime到AppServer状态",
  `CustomAudiences` varchar(65533) NULL COMMENT "自定义受众",
  `IsDelete` int(11) NULL COMMENT "是否删除",
  `row_update_time` datetime NULL COMMENT "更新时间",
  `c2rtime` datetime NULL COMMENT "广告点击时间",
  `DescInfo` varchar(65533) NULL COMMENT "归因来源",
  `LastClickTime` datetime NULL COMMENT "上次点击时间",
  `LastReadTime` datetime NULL COMMENT "上次阅读时间",
  `AppInstallTime` datetime NULL COMMENT "app安装时间",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "sr_入库时间",
  `sr_updatetime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "sr_更新时间"
) ENGINE=OLAP 
PRIMARY KEY(`Id`)
COMMENT "归因结果v2"
DISTRIBUTED BY HASH(`Id`) BUCKETS 10 
PROPERTIES (
"replication_num" = "3",
"bloom_filter_columns" = "AdId, IsRemarketing, UserId, CreateTime, InstallDateEst, AnalysisServerStatus, row_update_time, RemarkTimeSendToAppServer, TraceId, InstallDate, UniqueCdReaderId",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
