CREATE TABLE `ods_tidb_cdvideo_tidb_xcx_payorder` (
  `Id` bigint(20) NOT NULL COMMENT "主键id",
  `OrderSerialId` varchar(65533) NOT NULL COMMENT "订单流水号全局唯一,写入到业务库使用",
  `OrderId` varchar(65533) NOT NULL COMMENT "订单号,透传给支付合作方",
  `CooOrderId` varchar(65533) NULL COMMENT "支付订单号,合作方回传的",
  `PayChanelId` int(11) NOT NULL COMMENT "渠道号",
  `Account` varchar(65533) NOT NULL COMMENT "账号",
  `UserId` bigint(20) NOT NULL COMMENT "用户Id",
  `ServerId` int(11) NOT NULL COMMENT "服务器id,已废弃",
  `UserIPAddress` varchar(65533) NOT NULL COMMENT "客户端ip",
  `CreateTime` datetime NOT NULL COMMENT "创建时间",
  `CooNotifyTime` datetime NULL COMMENT "收到的付款时间",
  `FinishTime` datetime NULL COMMENT "订单处理完成时间,表示已经发送给业务服务器的时间",
  `Amount` int(11) NOT NULL COMMENT "金额,分为单位",
  `GiveAmount` int(11) NULL COMMENT "赠送金额,一般无用了",
  `BankAmount` int(11) NOT NULL COMMENT "银行金额,一般等同于Amount",
  `OrderStatus` int(11) NOT NULL COMMENT "订单状态1为成功",
  `CooOrderStatus` int(11) NOT NULL COMMENT "合作方扣款状态1为成功",
  `ShopItem` varchar(65533) NULL COMMENT "支付的商品id",
  `ProductId` varchar(65533) NULL COMMENT "充值产品编号",
  `PayType` varchar(65533) NULL COMMENT "支付类型",
  `BankId` varchar(65533) NULL COMMENT "",
  `Ext1` varchar(65533) NULL COMMENT "",
  `Ext2` varchar(65533) NULL COMMENT "",
  `Ext3` varchar(65533) NULL COMMENT "",
  `Ext4` varchar(65533) NULL COMMENT "",
  `Ext5` varchar(65533) NULL COMMENT "",
  `OsType` int(11) NULL COMMENT "相当于Mt",
  `ShopItemId` int(11) NULL COMMENT "商品Id,配置在后台",
  `CouponId` varchar(65533) NULL COMMENT "优惠券Id",
  `PackageId` varchar(65533) NULL COMMENT "客户端透传参数,不同场景用途不一样",
  `Phone` varchar(65533) NULL COMMENT "电话",
  `HasNotifyTimes` int(11) NOT NULL COMMENT "回调次数",
  `PayConfigId` int(11) NULL COMMENT "渠道id",
  `Core` int(11) NOT NULL COMMENT "core",
  `BaseAmount` int(11) NOT NULL COMMENT "统计收入金额字段",
  `UniqueGuid` varchar(65533) NULL COMMENT "",
  `TestFlag` int(11) NOT NULL COMMENT "测试标记1为测试",
  `CooExtStatus` int(11) NOT NULL COMMENT "",
  `CooExtInfo` varchar(65533) NULL COMMENT "",
  `BillInfo` varchar(65533) NULL COMMENT "",
  `RowUpdateTimestamp` bigint(20) NOT NULL COMMENT "",
  `SubPayType` varchar(65533) NULL COMMENT "子渠道类型",
  `AutoRenewTimes` int(11) NULL COMMENT "续订次数",
  `VideoUserId` varchar(65533) NOT NULL COMMENT "短剧AppUserId",
  `PromotionId` varchar(65533) NULL COMMENT "promotion_id",
  `ProjectId` varchar(65533) NULL COMMENT "project_id",
  `AID` varchar(65533) NULL COMMENT "aid",
  `CID` varchar(65533) NULL COMMENT "cid",
  `ADID` varchar(65533) NULL COMMENT "ad_id",
  `VirtualPayment` int(11) NULL COMMENT "虚拟支付类型(0-商务号支付,1-虚拟支付)",
  `TFID` varchar(65533) NULL COMMENT "投放ID",
  `Platform` varchar(100) NULL COMMENT "platform平台,wxpay、tt",
  `OptionType` int(11) NULL COMMENT "1-金豆,2-会员,3-整剧购买",
  `OptionSnapshotId` varchar(100) NULL COMMENT "充值产品镜像id",
  `OptionAmount` int(11) NULL COMMENT "金豆数量,会员天数",
  `Bonus` int(11) NULL COMMENT "赠送金豆,赠送天数",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据注入时间",
  `sr_updatetime` datetime NULL COMMENT "starrocks数据更新时间"
) ENGINE=OLAP 
PRIMARY KEY(`Id`)
COMMENT "国内短剧充值订单表"
DISTRIBUTED BY HASH(`Id`) BUCKETS 8 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
