CREATE TABLE `ods_tidb_sharpengine_ads_global_AdAssetLtv` (
  `Id` bigint(20) NOT NULL COMMENT "主键ID",
  `DateKey` varchar(384) NULL COMMENT "日期",
  `AssetId` varchar(384) NULL COMMENT "素材Id",
  `AdId` varchar(384) NULL COMMENT "广告id",
  `Gender` varchar(384) NULL COMMENT "性别",
  `Age` varchar(384) NULL COMMENT "年龄",
  `AdSetId` varchar(384) NULL COMMENT "广告组Id",
  `AdCampId` varchar(384) NULL COMMENT "广告组Id",
  `FbAccount` varchar(384) NULL COMMENT "广告账号Id",
  `AssetSource` int(11) NULL COMMENT "素材来源 0=fb",
  `AssetType` int(11) NULL COMMENT "素材类型 0=图片|1=视频",
  `Spend` decimal(10, 2) NULL COMMENT "花费金额",
  `Impressions` int(11) NULL COMMENT "展示数",
  `Reach` int(11) NULL COMMENT "覆盖人数",
  `Clicks` int(11) NULL COMMENT "点击数",
  `LinkClicks` int(11) NULL COMMENT "链接点击数action.link_clicks",
  `Installs` int(11) NULL COMMENT "安装（归因）installs",
  `Amount` decimal(10, 2) NULL COMMENT "价值（归因）amount",
  `PayUsers` int(11) NULL COMMENT "付费uv（归因）",
  `PayNum` int(11) NULL COMMENT "付费次数（归因）PayNum",
  `RegNum` int(11) NULL COMMENT "注册数",
  `DevNum` int(11) NULL COMMENT "激活数",
  `LpClicks` int(11) NULL COMMENT "点击次数",
  `LpImpressions` int(11) NULL COMMENT "展示次数",
  `LpInitialization` int(11) NULL COMMENT "LP初始化",
  `Day0Amount` decimal(10, 4) NULL COMMENT "充值收入",
  `Day1Amount` decimal(10, 4) NULL COMMENT "充值收入",
  `Day2Amount` decimal(10, 4) NULL COMMENT "充值收入",
  `Day3Amount` decimal(10, 4) NULL COMMENT "充值收入",
  `Day4Amount` decimal(10, 4) NULL COMMENT "充值收入",
  `Day5Amount` decimal(10, 4) NULL COMMENT "充值收入",
  `Day6Amount` decimal(10, 4) NULL COMMENT "充值收入",
  `CreateTime` datetime NULL COMMENT "创建时间",
  `UpdateTime` datetime NULL COMMENT "更新时间",
  `Day7Amount` decimal(10, 4) NULL COMMENT "充值收入",
  `ProductId` int(11) NULL COMMENT "语言",
  `AssetTitle` varchar(512) NULL COMMENT "素材标题",
  `Day0FirstPayNum` decimal(10, 4) NULL COMMENT "D0付费UV",
  `Day1FirstPayNum` decimal(10, 4) NULL COMMENT "D1付费UV",
  `Day2FirstPayNum` decimal(10, 4) NULL COMMENT "D2付费UV",
  `Day3FirstPayNum` decimal(10, 4) NULL COMMENT "D3付费UV",
  `Day4FirstPayNum` decimal(10, 4) NULL COMMENT "D4付费UV",
  `Day5FirstPayNum` decimal(10, 4) NULL COMMENT "D5付费UV",
  `Day6FirstPayNum` decimal(10, 4) NULL COMMENT "D6付费UV",
  `Day7FirstPayNum` decimal(10, 4) NULL COMMENT "D7付费UV",
  `DataSource` int(11) NULL DEFAULT "0" COMMENT "数据来源 0=素材原生数据|1=广告名匹配",
  `VideoId` varchar(384) NULL COMMENT "视频Id",
  `VideoPlays` decimal(14, 4) NULL COMMENT "播放总数",
  `VideoP100Watcheds` decimal(14, 4) NULL COMMENT "播放100%进度次数",
  `VideoP95Watcheds` decimal(14, 4) NULL COMMENT "播放95%进度次数",
  `VideoP75Watcheds` decimal(14, 4) NULL COMMENT "播放75%进度次数",
  `VideoP50Watcheds` decimal(14, 4) NULL COMMENT "播放50%进度次数",
  `VideoP25Watcheds` decimal(14, 4) NULL COMMENT "播放25%进度次数",
  `VideoAvgTimes` decimal(14, 4) NULL COMMENT "播放时间",
  `ImageHash` varchar(384) NULL COMMENT "图片素材Hash",
  `AssetGuid` varchar(384) NULL COMMENT "素材唯一标识",
  `Hour23Amount` decimal(10, 4) NULL COMMENT "经过时长充值金额",
  `Hour23FirstPayNum` decimal(10, 4) NULL COMMENT "经过时长首次人数",
  `VideoWatched2S` decimal(14, 4) NULL COMMENT "视频播放达2s的次数",
  `VideoWatched6S` decimal(14, 4) NULL COMMENT "视频播放达6s或播放完成的次数",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据注入时间",
  `sr_updatetime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据更新时间"
) ENGINE=OLAP 
PRIMARY KEY(`Id`)
DISTRIBUTED BY HASH(`Id`) BUCKETS 20 
PROPERTIES (
"replication_num" = "3",
"bloom_filter_columns" = "AssetSource, AdId, ProductId, Gender, AssetId, DateKey, Age",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
