CREATE TABLE `ods_tidb_readernovel_xx_mysql_shopgoods` (
  `productid` int(11) NOT NULL COMMENT "",
  `Id` int(11) NOT NULL COMMENT "编号",
  `Title` varchar(600) NOT NULL COMMENT "商品名称",
  `ShopGoodsType` int(11) NOT NULL COMMENT "商品类型",
  `Sort` int(11) NOT NULL COMMENT "商品排序",
  `ListAndDetailImg` varchar(600) NOT NULL COMMENT "列表和详情图片",
  `RecordAndBagImg` varchar(600) NOT NULL COMMENT "兑换记录和背包图片",
  `ExchangeNum` int(11) NULL COMMENT "",
  `SuperExchangeType` int(11) NULL COMMENT "0礼券 1阅币",
  `LimitBuyNum` int(11) NULL DEFAULT "0" COMMENT "限购数量",
  `IsSynExchangeRatio` tinyint(4) NOT NULL DEFAULT "0" COMMENT "",
  `DetailIntro` varchar(600) NULL COMMENT "详情简介",
  `ExpiredDays` int(11) NULL DEFAULT "0" COMMENT "过期天数",
  `BookId` bigint(20) NOT NULL DEFAULT "0" COMMENT "书籍ID",
  `Core` varchar(600) NULL COMMENT "Core",
  `MinVer` int(11) NULL DEFAULT "0" COMMENT "最低版本",
  `MaxVer` int(11) NULL DEFAULT "0" COMMENT "最高版本号",
  `Platform` int(11) NOT NULL COMMENT "平台",
  `StartTime` datetime NOT NULL COMMENT "开始时间",
  `EndTime` datetime NOT NULL COMMENT "结束时间",
  `UserType` int(11) NOT NULL COMMENT "用户类型",
  `UserTypeConfig` varchar(3000) NULL COMMENT "用户类型配置信息",
  `Status` int(11) NOT NULL COMMENT "",
  `TaskId` varchar(150) NULL COMMENT "",
  `DingTaskStatus` int(11) NULL COMMENT "",
  `DelFlag` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `ModifId` varchar(150) NULL COMMENT "",
  `ModifyTime` datetime NULL COMMENT "",
  `CreateId` varchar(150) NOT NULL COMMENT "",
  `CreateTime` datetime NOT NULL COMMENT "",
  `IsVirtual` tinyint(4) NULL COMMENT "",
  `EveryDayLimitNum` int(11) NULL COMMENT "",
  `EveryWeekLimitNum` int(11) NULL COMMENT "",
  `IsDelete` int(11) NULL DEFAULT "0" COMMENT "",
  `row_update_time` datetime NULL COMMENT "",
  `SyncLanguage` varchar(600) NULL COMMENT "",
  `Language` int(11) NULL COMMENT "",
  `IsShowInPointCenter` tinyint(4) NOT NULL COMMENT "是否展示于积分大厅",
  `PointCenterSort` int(11) NOT NULL COMMENT "积分大厅排序",
  `IsSignInReward` tinyint(4) NOT NULL DEFAULT "0" COMMENT "是否签到奖励",
  `IsHot` tinyint(4) NOT NULL DEFAULT "0" COMMENT "是否热门推荐",
  `IsGiveGameCode` tinyint(4) NOT NULL DEFAULT "0" COMMENT "是否发放兑换码",
  `IsNeedGameInfo` tinyint(4) NOT NULL DEFAULT "0" COMMENT "是否提交用户信息",
  `IsShowGameArea` tinyint(4) NOT NULL DEFAULT "0" COMMENT "是否显示游戏区服",
  `WallpaperImg` varchar(1500) NULL COMMENT "壁纸图片",
  `WallpaperSmallImg` varchar(1500) NULL COMMENT "壁纸缩略图片",
  `ReadBgImg` varchar(1500) NULL COMMENT "阅读背景图片",
  `ReadBgId` bigint(20) NOT NULL DEFAULT "0" COMMENT "阅读背景ID",
  `IsLocked` tinyint(4) NOT NULL DEFAULT "0" COMMENT "是否锁定状态",
  `SignInImg` varchar(1500) NULL COMMENT "签到图片",
  `WallpaperImgAndroid` varchar(1500) NULL COMMENT "壁纸图片Android",
  `WallpaperImgIos` varchar(1500) NULL COMMENT "壁纸图片IOS",
  `IsRecommend` tinyint(4) NOT NULL DEFAULT "0" COMMENT "是否默认推荐",
  `IsShow` tinyint(4) NOT NULL DEFAULT "0" COMMENT "是否显示",
  `IsInitData` tinyint(4) NOT NULL DEFAULT "0" COMMENT "是否同步待确认0否1是",
  `IsInvitefriends` tinyint(4) NOT NULL DEFAULT "0" COMMENT "是否邀请好友",
  `IsShowInMall` tinyint(4) NOT NULL DEFAULT "1" COMMENT "是否显示在商城0否1是",
  `ShopGoodsNo` bigint(20) NOT NULL DEFAULT "0" COMMENT "商品编码",
  `ParameterDict` varchar(65533) NULL COMMENT "配置信息",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "",
  `sr_updatetime` datetime NULL COMMENT ""
) ENGINE=OLAP 
PRIMARY KEY(`productid`, `Id`)
DISTRIBUTED BY HASH(`Id`) BUCKETS 3 
PROPERTIES (
"replication_num" = "3",
"bloom_filter_columns" = "Id",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
