CREATE TABLE `ods_tidb_upload_book_xx_shuangwen_book` (
  `productid` int(11) NOT NULL COMMENT "",
  `book_id` bigint(20) NOT NULL COMMENT "",
  `site_id` int(11) NOT NULL COMMENT "",
  `book_name` varchar(300) NULL COMMENT "",
  `author_name` varchar(300) NULL COMMENT "",
  `image_src` varchar(65536) NULL COMMENT "",
  `sumary` varchar(65533) NULL COMMENT "",
  `cname` varchar(150) NULL COMMENT "",
  `c_id` int(11) NULL COMMENT "",
  `fc_id` int(11) NULL COMMENT "",
  `length` bigint(20) NULL COMMENT "",
  `channel` int(11) NULL COMMENT "",
  `update_time` datetime NULL COMMENT "",
  `status` int(11) NULL COMMENT "",
  `sexy` int(11) NULL COMMENT "",
  `size` int(11) NULL COMMENT "",
  `is_full` int(11) NULL COMMENT "",
  `umd_path` varchar(1500) NULL COMMENT "",
  `m_flag` int(11) NULL COMMENT "",
  `NewCID` int(11) NULL COMMENT "",
  `NewCName` varchar(150) NULL COMMENT "",
  `Baidu91BooksId` int(11) NULL COMMENT "",
  `sexy2` int(11) NULL DEFAULT "0" COMMENT "",
  `SetSexy2` int(11) NULL DEFAULT "0" COMMENT "",
  `GrantStatus` int(11) NULL DEFAULT "0" COMMENT "",
  `VipIndex` int(11) NULL DEFAULT "0" COMMENT "",
  `Url` varchar(1500) NULL COMMENT "",
  `RefAccountId` varchar(1500) NULL COMMENT "书城账号id组 根据,号隔开",
  `FontPrice` decimal(18, 0) NULL DEFAULT "0" COMMENT "",
  `SignedType` int(11) NULL COMMENT "签约类型",
  `GrantForCompany` tinyint(4) NULL COMMENT "",
  `SpecialOutput` tinyint(4) NULL COMMENT "",
  `FreeChapterNum` int(11) NULL DEFAULT "0" COMMENT "",
  `OutputStatus` int(11) NULL DEFAULT "0" COMMENT "",
  `UpdateStatus` int(11) NULL DEFAULT "0" COMMENT "",
  `PricePerThousand` int(11) NULL DEFAULT "0" COMMENT "",
  `TranslatorIds` varchar(6000) NULL COMMENT "",
  `SideBookName` varchar(1255) NULL COMMENT "",
  `SideImageSrc` varchar(1500) NULL COMMENT "",
  `Translator` varchar(1255) NULL COMMENT "",
  `Language` int(11) NULL DEFAULT "0" COMMENT "",
  `SideAuthorName` varchar(300) NULL COMMENT "",
  `FullTime` datetime NULL COMMENT "",
  `BookNature` tinyint(4) NULL DEFAULT "0" COMMENT "",
  `IsStop` tinyint(4) NULL DEFAULT "0" COMMENT "",
  `StopTime` datetime NULL COMMENT "",
  `IsEighteen` int(11) NULL DEFAULT "0" COMMENT "",
  `EditorPhone` varchar(150) NULL COMMENT "",
  `AuthorId` bigint(20) NULL COMMENT "作者Id",
  `row_create_time` datetime NULL COMMENT "",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "",
  `sr_updatetime` datetime NULL COMMENT ""
) ENGINE=OLAP 
PRIMARY KEY(`productid`, `book_id`, `site_id`)
DISTRIBUTED BY HASH(`site_id`) BUCKETS 10 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
