CREATE TABLE `ods_tidb_short_video_goods_strategy` (
  `Id` bigint(20) NOT NULL COMMENT "id",
  `StrategyCode` varchar(200) NULL COMMENT "策略代号",
  `Name` varchar(500) NULL COMMENT "商品策略名称",
  `ApplyType` int(11) NULL COMMENT "应用场景（1App,2Edm）",
  `FlowType` int(11) NULL COMMENT "流量类型 1全局流量 2实验流量",
  `MerchandiseType` int(11) NULL COMMENT "商品类型（1充值 2vip 3签到卡）",
  `Sort` int(11) NULL COMMENT "排序",
  `StyleType` int(11) NULL COMMENT "订阅区样式 1:轮播 2:平铺",
  `VipPriceType` int(11) NULL COMMENT "vip价格信息 1:周期价 2:日均价",
  `DataType` int(11) NULL COMMENT "数据类型（1正式，2测试，3IOS审核模式）",
  `BeginTime` datetime NULL COMMENT "开始时间",
  `EndTime` datetime NULL COMMENT "结束时间",
  `Status` int(11) NULL COMMENT "状态（0关闭，1开启）",
  `AuditStatus` int(11) NULL COMMENT "审核状态（0审核中，1通过，2不通过）",
  `GroupIds` varchar(65533) NULL COMMENT "人群包id",
  `ExcludeGroupIds` varchar(65533) NULL COMMENT "剔除人群包",
  `SettingsType` int(11) NULL COMMENT "配置类型 1双模块充值 2双模块订阅 3充值+订阅 4单模块充值 5单模块订阅",
  `CreateTime` datetime NULL COMMENT "创建时间",
  `UpdateTime` datetime NULL COMMENT "更新时间",
  `IsDelete` int(11) NULL COMMENT "是否删除（0否，1是）",
  `ChargeDataSource` int(11) NULL COMMENT "充值数据来源 1人工 2 算法",
  `SubDataSource` int(11) NULL COMMENT "订阅数据来源 1人工 2算法",
  `JGroupIds` varchar(65533) NULL COMMENT "极光人群包",
  `ExcludeJGroupIds` varchar(65533) NULL COMMENT "极光剔除人群包",
  `AppType` int(11) NULL COMMENT "应用类型： 1：短剧，2：阅读",
  `StrategyType` int(11) NULL COMMENT "策略类型： 1：方案，2：购买策略，3：充值挡位(商品策略)，4：定价系统，5：半屏，6：即充即消，7：千字价格系数定投",
  `StrategyAttr` int(11) NULL COMMENT "策略属性： 1：兜底，2：自定义",
  `ProcessInstanceId` varchar(500) NULL COMMENT "钉钉发起审批实例id",
  `IsRechargeBottom` int(11) NULL COMMENT "(半屏策略)是否充值 0不使用，1使用",
  `IsSubscribeBottom` int(11) NULL COMMENT "(半屏策略)是否订阅 0不使用，1使用",
  `SubscribeLocation` int(11) NULL COMMENT "订阅区位置 1在上  2在下",
  `ChargeMode` int(11) NULL COMMENT "档位模式 1完整配置 2活动专区",
  `ActivityZoneId` bigint(20) NULL COMMENT "活动专区模板id",
  `IsBanner` int(11) NULL COMMENT "是否配置banner 0否，1是",
  `BannerSort` varchar(500) NULL COMMENT "banner展示位序 1,2,3,4",
  `JGroupNames` varchar(65533) NULL COMMENT "极光人群包名称",
  `ExcludeJGroupNames` varchar(65533) NULL COMMENT "极光剔除人群包名称",
  `CreateFrom` int(11) NULL COMMENT "创建来源 1 运营后台，2 ads平台 （目前ads的半屏优先级大于运营中台）",
  `UserAccount` varchar(500) NULL COMMENT "ads创建的用户工号,用来做数据过滤",
  `GroupCode` varchar(500) NULL COMMENT "ads创建的组code,用来做数据过滤",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据注入时间",
  `sr_updatetime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据更新时间"
) ENGINE=OLAP 
PRIMARY KEY(`Id`)
COMMENT "海剧-半屏策略表"
DISTRIBUTED BY HASH(`Id`) BUCKETS 2 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
