CREATE TABLE `ods_tidb_readernovel_tidb_xx_h5adconfig` (
  `productid` int(11) NOT NULL COMMENT "",
  `Id` bigint(20) NOT NULL COMMENT "",
  `SlotId` bigint(20) NOT NULL COMMENT "",
  `Name` varchar(300) NOT NULL COMMENT "",
  `Title` varchar(65533) NULL COMMENT "",
  `OpenType` int(11) NOT NULL COMMENT "",
  `Img` varchar(955) NOT NULL COMMENT "",
  `Url` varchar(65533) NOT NULL COMMENT "",
  `Status` int(11) NOT NULL COMMENT "",
  `BeginTime` datetime NULL COMMENT "",
  `EndTime` datetime NULL COMMENT "",
  `ShowType` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `ShowTimes` int(11) NULL COMMENT "",
  `BanArea` varchar(1500) NULL COMMENT "",
  `SmallType` int(11) NULL COMMENT "",
  `SpecialAccount` varchar(1500) NULL COMMENT "",
  `ShowSpan` int(11) NULL COMMENT "",
  `Img2` varchar(955) NULL COMMENT "",
  `Platform` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `ProdIds` varchar(65533) NULL COMMENT "",
  `ThirdAppId` varchar(50) NULL COMMENT "",
  `SmallPT` int(11) NOT NULL DEFAULT "-1" COMMENT "",
  `DailyShowTimes` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `Img3` varchar(955) NULL COMMENT "",
  `Sex` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `BanProdIds` varchar(65533) NULL COMMENT "",
  `MinVer` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `ShowSpanHours` int(11) NULL DEFAULT "0" COMMENT "",
  `MaxVer` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `IsGeneral` tinyint(4) NOT NULL DEFAULT "0" COMMENT "",
  `Province` varchar(1500) NULL COMMENT "",
  `Tag` varchar(65533) NULL COMMENT "",
  `Filters` varchar(65533) NULL COMMENT "",
  `CoreVer` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `AppId` varchar(1512) NULL COMMENT "",
  `BackgroundColor` varchar(150) NOT NULL DEFAULT "" COMMENT "",
  `RuleKey` varchar(300) NULL COMMENT "",
  `IsHide` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `ShowUserType` int(11) NULL COMMENT "",
  `Tip` varchar(1500) NULL COMMENT "",
  `Core3Img` varchar(1500) NULL COMMENT "",
  `Sort` int(11) NULL COMMENT "",
  `IsFilterExposure` tinyint(4) NULL COMMENT "",
  `IsDelete` int(11) NULL DEFAULT "0" COMMENT "",
  `row_update_time` datetime NULL COMMENT "",
  `SyncLanguage` varchar(200) NULL DEFAULT "" COMMENT "",
  `Language` int(11) NULL DEFAULT "0" COMMENT "",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "",
  `sr_updatetime` datetime NULL COMMENT ""
) ENGINE=OLAP 
PRIMARY KEY(`productid`, `Id`)
DISTRIBUTED BY HASH(`Id`) BUCKETS 3 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
