CREATE TABLE `ods_tidb_cdcreator_tidb_cn_story_original` (
  `id` bigint(20) NOT NULL COMMENT "自增ID",
  `uuid` varchar(200) NULL COMMENT "唯一ID",
  `story_name` varchar(500) NULL COMMENT "故事名称",
  `story_code` varchar(500) NULL COMMENT "完整代号，如：X1",
  `story_code_series` varchar(500) NULL COMMENT "代号系列，纯字母开头部分",
  `story_code_sort` bigint(20) NULL COMMENT "代号序号",
  `issue_type` int(11) NULL COMMENT "发行状态(1-首发,2-非首发),非首发则版权方必填",
  `cp_userinfo_uuid` varchar(200) NULL COMMENT "关联版权方用户表,cp_userinfo.uuid",
  `sub_story_type` int(11) NULL COMMENT "短剧类型(1-本土剧,2-译制剧,,4-自制剧,5-自制本土剧)",
  `product_type` int(11) NULL COMMENT "产品类型(1-短剧,2-阅读)",
  `priority_type` int(11) NULL COMMENT "优先级(0-P0,1-P1,2-P2,3-P3)",
  `purchase_type` int(11) NULL COMMENT "采买进度(1-已采买,2-合同中,3-沟通中,9-不采买)",
  `purchase_desc` varchar(6000) NULL COMMENT "采买备注",
  `sub_issue_type` varchar(200) NULL COMMENT "重点信息(1-爆款承制方,2-爆款导演,3-爆款男女主,4-爆款,5-禁投)",
  `channel_type` int(11) NULL COMMENT "频道(1-男频,2-女频)",
  `issue_zone` int(11) NULL COMMENT "授权范围(1-全球,2-中国大陆,3-海外,4-海外小语种)",
  `import_no` varchar(200) NULL COMMENT "导入流水批次",
  `link_url` varchar(2000) NULL COMMENT "链接地址",
  `process_status` int(11) NULL COMMENT "流程状态(0-待审核,1-一审,2-二审,3-国审|海审,5-结果确认)",
  `audit_time_1` datetime NULL COMMENT "一审-审核时间",
  `audit_status_1` int(11) NULL COMMENT "一审状态(0-待审核,1 通过,2 不通过)",
  `audit_result_1` int(11) NULL COMMENT "一审结果(S-1、A-2、B-3、不通过-9)",
  `audit_user_1` varchar(200) NULL COMMENT "一审-审核人工号",
  `audit_user_name_1` varchar(200) NULL COMMENT "一审-审核人名称",
  `audit_time_2` datetime NULL COMMENT "二审-审核时间",
  `audit_status_2` int(11) NULL COMMENT "二审状态(0-待审核,1 通过,2 不通过)",
  `audit_result_2` int(11) NULL COMMENT "二审结果(S-1、A-2、B-3、不通过-9)",
  `audit_user_2` varchar(200) NULL COMMENT "二审-审核人工号",
  `audit_user_name_2` varchar(200) NULL COMMENT "二审-审核人名称",
  `audit_time_3` datetime NULL COMMENT "国审-审核时间",
  `audit_status_3` int(11) NULL COMMENT "国审状态(0-待审核,1 通过,2 不通过)",
  `audit_result_3` int(11) NULL COMMENT "国审结果(S-1、A-2、B-3、不通过-9)",
  `audit_user_3` varchar(200) NULL COMMENT "国审-审核人工号",
  `audit_user_name_3` varchar(200) NULL COMMENT "国审-审核人名称",
  `audit_time_4` datetime NULL COMMENT "海审-审核时间",
  `audit_status_4` int(11) NULL COMMENT "海审状态(0-待审核,1 通过,2 不通过)",
  `audit_result_4` int(11) NULL COMMENT "海审结果(S-1、A-2、B-3、不通过-9)",
  `audit_user_4` varchar(200) NULL COMMENT "海审-审核人工号",
  `audit_user_name_4` varchar(200) NULL COMMENT "海审-审核人名称",
  `audit_time_5` datetime NULL COMMENT "是否引入确认-确认时间",
  `audit_result_5` int(11) NULL COMMENT "结果确认(0-待确认,1 引入,2 不引入)",
  `audit_user_5` varchar(200) NULL COMMENT "结果确认-操作人工号",
  `audit_user_name_5` varchar(200) NULL COMMENT "结果确认-确认人名称",
  `is_finish` int(11) NULL COMMENT "流程是否完成(0-未完成,1 完成)，引入结果确认后为完成",
  `is_toufang_cn` int(11) NULL COMMENT "国内投放(0-待确认,1 投放, 2 不投放)",
  `add_user` varchar(200) NULL COMMENT "添加人工号",
  `add_user_name` varchar(200) NULL COMMENT "添加人用户名",
  `add_time` datetime NULL COMMENT "添加时间",
  `update_user` varchar(200) NULL COMMENT "更新人工号",
  `update_user_name` varchar(200) NULL COMMENT "更新人用户名",
  `update_time` datetime NULL COMMENT "更新时间",
  `sync_update_time` datetime NULL COMMENT "数据更新时间戳",
  `coop_type` int(11) NULL COMMENT "合作模式(1-买断、2-分成、3-保底分成)",
  `coop_rate` int(11) NULL COMMENT "分成比例,计算时需转成百分比除以100",
  `guarantee_fee` decimal(18, 2) NULL COMMENT "保底金(元)",
  `contract_number` varchar(200) NULL COMMENT "合同编号",
  `authorization_time_start` datetime NULL COMMENT "授权时间-开始",
  `authorization_time_end` datetime NULL COMMENT "授权时间-结束",
  `authorization_status` int(11) NULL COMMENT "授权状态 0-未开始授权 1-已授权 2oa审批中 3已驳回",
  `is_concat_audit` int(11) NULL COMMENT "历史采买标识,是否需要合同审批,0不需要不弹窗,1需要弹窗,(用于合同审核悬浮框显示)",
  `is_need_oa_audit` int(11) NULL COMMENT "是否需要提交到钉钉oa流程审批 0-否，1-是",
  `batch_sno` varchar(200) NULL COMMENT "批量确认引入流水号",
  `is_none_audit` int(11) NULL COMMENT "是否免审剧 1-免审 0-需要审核",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据注入时间",
  `sr_updatetime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据更新时间"
) ENGINE=OLAP 
PRIMARY KEY(`id`)
COMMENT "原始短剧信息,author:510161"
DISTRIBUTED BY HASH(`id`) BUCKETS 3 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
