CREATE TABLE ods.ods_tidb_short_video_admob_paid_event (
     Id                        bigint(20)    NOT NULL                                   COMMENT "唯一ID"
    ,CreateTime                datetime      NOT NULL DEFAULT "1970-01-01 00:00:00.000" COMMENT "创建时间"
    ,AccountId                 bigint(20)    NULL                                       COMMENT "账户id"
    ,PrecisionType             int(11)       NULL                                       COMMENT "精准投放类型"
    ,ValueMicros               double        NULL                                       COMMENT "值"
    ,CurrencyCode              varchar(300)  NULL                                       COMMENT "货币代码"
    ,AdUnitId                  varchar(300)  NULL                                       COMMENT "广告id"
    ,MediationAdapterClassName varchar(300)  NULL                                       COMMENT "媒体适配器类名"
    ,UpdateTime                datetime      NULL     DEFAULT "1970-01-01 00:00:00.000" COMMENT "更新时间"
    ,Userid                    bigint(20)    NULL     DEFAULT "0"                       COMMENT "用户ID"
    ,Mt                        varchar(150)  NULL     DEFAULT ""                        COMMENT "类型"
    ,Appver                    varchar(150)  NULL     DEFAULT ""                        COMMENT "版本号"
    ,Appid                     varchar(50)   NULL     DEFAULT "683001001"               COMMENT "应用ID"
    ,Chl                       varchar(655)  NULL     DEFAULT ""                        COMMENT "渠道"
    ,Langid                    varchar(150)  NULL     DEFAULT ""                        COMMENT "语言ID"
    ,position                  int(11)       NULL                                       COMMENT "广告位置"
    ,adchannel                 varchar(500)  NULL                                       COMMENT "广告商，218 max广告版本开始上报，旧版本为空"
    ,adsPlatform               varchar(500)  NULL                                       COMMENT "广告商，218 max广告版本开始上报，旧版本为空"
    ,RevenuePrecision          varchar(500)  NULL                                       COMMENT "精准投放类型(String)"
    ,core                      int(11)       NULL                                       COMMENT ""
    ,mainstrategyid            varchar(300)  NULL                                       COMMENT "主策略id"
    ,eventstrategyid           varchar(300)  NULL                                       COMMENT "广告策略id"
    ,sr_createtime             datetime      NULL     DEFAULT CURRENT_TIMESTAMP         COMMENT ""
    ,sr_updatetime             datetime      NULL                                       COMMENT ""
) ENGINE=OLAP
PRIMARY KEY(Id, CreateTime)
DISTRIBUTED BY HASH(Id, CreateTime) BUCKETS 150
PROPERTIES ("replication_num" = "3"
          , "in_memory" = "false"
          , "enable_persistent_index" = "true"
          , "replicated_storage" = "true"
          , "compression" = "LZ4"
);