CREATE TABLE `ods_tidb_sharpengine_ads_global_FbAdRoiInstallReferrerByHour` (
  `Id` bigint(20) NOT NULL COMMENT "id",
  `AdId` varchar(250) NULL COMMENT "广告id",
  `CreateTime` varchar(50) NULL COMMENT "创建时间",
  `CreateHour` int(11) NULL COMMENT "创建时间",
  `PayList` varchar(65535) NULL COMMENT "充值信息",
  `RegNum` int(11) NULL COMMENT "注册数",
  `Impressions` bigint(20) NULL COMMENT "",
  `LinkClicks` bigint(20) NULL COMMENT "",
  `Installs` bigint(20) NULL COMMENT "",
  `Clicks` bigint(20) NULL COMMENT "",
  `CostAmount` decimal(10, 2) NULL COMMENT "成本",
  `ProductId` int(11) NULL COMMENT "产品id",
  `PayNum` int(11) NULL COMMENT "充值数",
  `UpdateTime` datetime NULL COMMENT "更新时间",
  `PayListByDays` varchar(65535) NULL COMMENT "充值信息列表",
  `CheckSum` bigint(20) NULL COMMENT "检查总数",
  `LoginNum2` int(11) NULL COMMENT "",
  `LoginNum3` int(11) NULL COMMENT "",
  `LoginNum7` int(11) NULL COMMENT "",
  `Core` int(11) NULL COMMENT "core",
  `Mt` int(11) NULL COMMENT "设备类型",
  `FbAccount` varchar(50) NULL COMMENT "fb账户",
  `AdSetId` varchar(255) NULL COMMENT "广告setid",
  `AdCampId` varchar(255) NULL COMMENT "广告campid",
  `DevNum` int(11) NULL COMMENT "",
  `GroupId` int(11) NULL COMMENT "组id",
  `SourceChl` varchar(128) NULL COMMENT "渠道",
  `Chl2` varchar(128) NULL COMMENT "渠道2",
  `RowVersion` bigint(20) NULL COMMENT "版本",
  `CurrentLanguage2` int(11) NULL COMMENT "当前语言",
  `AdsQuality` int(11) NULL COMMENT "质量",
  `Updater` varchar(255) NULL COMMENT "",
  `Hour0Amount` decimal(18, 6) NULL COMMENT "新增时段充值收入,5:00~6:00的充值收入，非累计",
  `Hour1Amount` decimal(18, 6) NULL COMMENT "新增时段+1H的充值收入，例，5点新增用户，6:00~7:00的充值收入，非累计",
  `Hour2Amount` decimal(18, 6) NULL COMMENT "",
  `Hour3Amount` decimal(18, 6) NULL COMMENT "",
  `Hour4Amount` decimal(18, 6) NULL COMMENT "",
  `Hour5Amount` decimal(18, 6) NULL COMMENT "",
  `Hour6Amount` decimal(18, 6) NULL COMMENT "",
  `Hour7Amount` decimal(18, 6) NULL COMMENT "",
  `Hour8Amount` decimal(18, 6) NULL COMMENT "",
  `Hour9Amount` decimal(18, 6) NULL COMMENT "",
  `Hour10Amount` decimal(18, 6) NULL COMMENT "",
  `Hour11Amount` decimal(18, 6) NULL COMMENT "",
  `Hour12Amount` decimal(18, 6) NULL COMMENT "",
  `Hour13Amount` decimal(18, 6) NULL COMMENT "",
  `Hour14Amount` decimal(18, 6) NULL COMMENT "",
  `Hour15Amount` decimal(18, 6) NULL COMMENT "",
  `Hour16Amount` decimal(18, 6) NULL COMMENT "",
  `Hour17Amount` decimal(18, 6) NULL COMMENT "",
  `Hour18Amount` decimal(18, 6) NULL COMMENT "",
  `Hour19Amount` decimal(18, 6) NULL COMMENT "",
  `Hour20Amount` decimal(18, 6) NULL COMMENT "",
  `Hour21Amount` decimal(18, 6) NULL COMMENT "",
  `Hour22Amount` decimal(18, 6) NULL COMMENT "",
  `Hour23Amount` decimal(18, 6) NULL COMMENT "",
  `Hour0AmountByAd` decimal(18, 6) NULL COMMENT "x时段广告收入",
  `Hour1AmountByAd` decimal(18, 6) NULL COMMENT "",
  `Hour2AmountByAd` decimal(18, 6) NULL COMMENT "",
  `Hour3AmountByAd` decimal(18, 6) NULL COMMENT "",
  `Hour4AmountByAd` decimal(18, 6) NULL COMMENT "",
  `Hour5AmountByAd` decimal(18, 6) NULL COMMENT "",
  `Hour6AmountByAd` decimal(18, 6) NULL COMMENT "",
  `Hour7AmountByAd` decimal(18, 6) NULL COMMENT "",
  `Hour8AmountByAd` decimal(18, 6) NULL COMMENT "",
  `Hour9AmountByAd` decimal(18, 6) NULL COMMENT "",
  `Hour10AmountByAd` decimal(18, 6) NULL COMMENT "",
  `Hour11AmountByAd` decimal(18, 6) NULL COMMENT "",
  `Hour12AmountByAd` decimal(18, 6) NULL COMMENT "",
  `Hour13AmountByAd` decimal(18, 6) NULL COMMENT "",
  `Hour14AmountByAd` decimal(18, 6) NULL COMMENT "",
  `Hour15AmountByAd` decimal(18, 6) NULL COMMENT "",
  `Hour16AmountByAd` decimal(18, 6) NULL COMMENT "",
  `Hour17AmountByAd` decimal(18, 6) NULL COMMENT "",
  `Hour18AmountByAd` decimal(18, 6) NULL COMMENT "",
  `Hour19AmountByAd` decimal(18, 6) NULL COMMENT "",
  `Hour20AmountByAd` decimal(18, 6) NULL COMMENT "",
  `Hour21AmountByAd` decimal(18, 6) NULL COMMENT "",
  `Hour22AmountByAd` decimal(18, 6) NULL COMMENT "",
  `Hour23AmountByAd` decimal(18, 6) NULL COMMENT "",
  `Hour0FirstPayNum` int(11) NULL COMMENT "x时段首充用户数",
  `Hour1FirstPayNum` int(11) NULL COMMENT "",
  `Hour2FirstPayNum` int(11) NULL COMMENT "",
  `Hour3FirstPayNum` int(11) NULL COMMENT "",
  `Hour4FirstPayNum` int(11) NULL COMMENT "",
  `Hour5FirstPayNum` int(11) NULL COMMENT "",
  `Hour6FirstPayNum` int(11) NULL COMMENT "",
  `Hour7FirstPayNum` int(11) NULL COMMENT "",
  `Hour8FirstPayNum` int(11) NULL COMMENT "",
  `Hour9FirstPayNum` int(11) NULL COMMENT "",
  `Hour10FirstPayNum` int(11) NULL COMMENT "",
  `Hour11FirstPayNum` int(11) NULL COMMENT "",
  `Hour12FirstPayNum` int(11) NULL COMMENT "",
  `Hour13FirstPayNum` int(11) NULL COMMENT "",
  `Hour14FirstPayNum` int(11) NULL COMMENT "",
  `Hour15FirstPayNum` int(11) NULL COMMENT "",
  `Hour16FirstPayNum` int(11) NULL COMMENT "",
  `Hour17FirstPayNum` int(11) NULL COMMENT "",
  `Hour18FirstPayNum` int(11) NULL COMMENT "",
  `Hour19FirstPayNum` int(11) NULL COMMENT "",
  `Hour20FirstPayNum` int(11) NULL COMMENT "",
  `Hour21FirstPayNum` int(11) NULL COMMENT "",
  `Hour22FirstPayNum` int(11) NULL COMMENT "",
  `Hour23FirstPayNum` int(11) NULL COMMENT "",
  `Hour0PayNum` int(11) NULL COMMENT "x时段付费次数",
  `Hour1PayNum` int(11) NULL COMMENT "",
  `Hour2PayNum` int(11) NULL COMMENT "",
  `Hour3PayNum` int(11) NULL COMMENT "",
  `Hour4PayNum` int(11) NULL COMMENT "",
  `Hour5PayNum` int(11) NULL COMMENT "",
  `Hour6PayNum` int(11) NULL COMMENT "",
  `Hour7PayNum` int(11) NULL COMMENT "",
  `Hour8PayNum` int(11) NULL COMMENT "",
  `Hour9PayNum` int(11) NULL COMMENT "",
  `Hour10PayNum` int(11) NULL COMMENT "",
  `Hour11PayNum` int(11) NULL COMMENT "",
  `Hour12PayNum` int(11) NULL COMMENT "",
  `Hour13PayNum` int(11) NULL COMMENT "",
  `Hour14PayNum` int(11) NULL COMMENT "",
  `Hour15PayNum` int(11) NULL COMMENT "",
  `Hour16PayNum` int(11) NULL COMMENT "",
  `Hour17PayNum` int(11) NULL COMMENT "",
  `Hour18PayNum` int(11) NULL COMMENT "",
  `Hour19PayNum` int(11) NULL COMMENT "",
  `Hour20PayNum` int(11) NULL COMMENT "",
  `Hour21PayNum` int(11) NULL COMMENT "",
  `Hour22PayNum` int(11) NULL COMMENT "",
  `Hour23PayNum` int(11) NULL COMMENT "",
  `PayOrderNum` int(11) NULL DEFAULT "0" COMMENT "充值订单总数",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据注入时间",
  `sr_updatetime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据更新时间"
) ENGINE=OLAP 
PRIMARY KEY(`Id`)
COMMENT "时段充值表"
DISTRIBUTED BY HASH(`Id`) BUCKETS 5 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
