CREATE TABLE `ods_ads_tidb_sharpengine_ads_global_AdsCreationPlanTask` (
  `Id` bigint(20) NOT NULL COMMENT "Id",
  `PlanId` varchar(255) NULL COMMENT "方案Id",
  `PlanTaskId` varchar(255) NULL COMMENT "任务Id",
  `PlanItemId` varchar(255) NULL COMMENT "配置项Id",
  `PlanItemSort` int(11) NULL COMMENT "排序",
  `TemplateId` bigint(20) NULL COMMENT "模板Id",
  `ProjectCode` int(11) NULL COMMENT "项目 1海阅|2海剧",
  `CurrentLanguage` int(11) NULL COMMENT "投放语言",
  `CreativeType` int(11) NULL COMMENT "广告框架",
  `CreativeTotalCount` int(11) NULL COMMENT "素材总数量",
  `CreativeSingleCount` int(11) NULL COMMENT "单广告组最大素材数量",
  `IsSplit` int(11) NULL COMMENT "根据卖点拆分 0 不拆分 1 拆分",
  `AdBudget` decimal(10, 3) NULL COMMENT "广告预算",
  `BuildTotalCount` int(11) NULL COMMENT "广告组数量",
  `CreateTime` datetime NULL COMMENT "创建时间",
  `UpdateTime` datetime NULL COMMENT "更新时间",
  `CreateByUid` varchar(500) NULL COMMENT "创建人",
  `CreateBy` varchar(500) NULL COMMENT "创建人",
  `MarketingPlanLastTaskId` bigint(20) NULL COMMENT "内容任务最终任务ID",
  `AdsCreationAutoTaskId` bigint(20) NULL COMMENT "自动创编任务ID",
  `AssetPlanId` bigint(20) NULL COMMENT "创编素材筛选方案ID",
  `BiAdSetCount` int(11) NULL COMMENT "Bi计算广告组单日创编数量上限",
  `InitAdSetCount` int(11) NULL COMMENT "初始广告组条数",
  `CopyAdSetCount` int(11) NULL COMMENT "复制优质广告组单日条数",
  `RunningAdSetLimit` int(11) NULL COMMENT "广告组单日在跑数量上限",
  `CreatableAdSetLimit` int(11) NULL COMMENT "广告组单日创编数量上限",
  `OldCreativeCount` int(11) NULL COMMENT "旧素材数量",
  `CreatableAdsPerCreative` int(11) NULL COMMENT "同素材单日单模板可创编广告条数",
  `RunningAdSetLimitPerCreative` int(11) NULL COMMENT "同素材单日在跑广告上限",
  `CreatableAdSetLimitPerCreative` int(11) NULL COMMENT "同素材单日创编广告上限",
  `SpendMin` decimal(10, 4) NULL COMMENT "花费最小值",
  `SpendMax` decimal(10, 4) NULL COMMENT "花费最大值",
  `RoasMin` decimal(10, 4) NULL COMMENT "ROAS最小值",
  `RoasMax` decimal(10, 4) NULL COMMENT "ROAS最大值",
  `JhsrRateMin` decimal(10, 4) NULL COMMENT "聚合收入达成率最小值",
  `JhsrRateMax` decimal(10, 4) NULL COMMENT "聚合收入达成率最大值",
  `PjsrRateMin` decimal(10, 4) NULL COMMENT "平均收入最小值",
  `PjsrRateMax` decimal(10, 4) NULL COMMENT "平均收入最大值",
  `ReachRateMin` decimal(10, 4) NULL COMMENT "达标占比最小值",
  `ReachRateMax` decimal(10, 4) NULL COMMENT "达标占比最大值",
  `CreativeNumMin` int(11) NULL COMMENT "创编次数最小值",
  `CreativeNumMax` int(11) NULL COMMENT "创编次数最大值",
  `IrMin` decimal(10, 4) NULL COMMENT "Ir 最小值",
  `IrMax` decimal(10, 4) NULL COMMENT "Ir 最大值",
  `LinkCtrMin` decimal(10, 4) NULL COMMENT "链接点击CTR 最小值",
  `LinkCtrMax` decimal(10, 4) NULL COMMENT "链接点击CTR 最大值",
  `ViolationNumMin` int(11) NULL COMMENT "违规次数最小值",
  `ViolationNumMax` int(11) NULL COMMENT "违规次数最大值",
  `ViolationRateMin` decimal(10, 4) NULL COMMENT "违规率最小值",
  `ViolationRateMax` decimal(10, 4) NULL COMMENT "违规率最大值",
  `Status` int(11) NULL COMMENT "任务状态 0=待执行|1=执行中|2=成功|3=失败",
  `AdSetCountRatio` decimal(10, 4) NULL COMMENT "创编广告数量放大比例",
  `CopiedTotalCount` int(11) NULL COMMENT "广告组复制数量",
  `MinimumAdSetCount` int(11) NULL COMMENT "保底广告组条数",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据注入时间",
  `sr_updatetime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据更新时间"
) ENGINE=OLAP 
PRIMARY KEY(`Id`)
COMMENT "创编广告 任务 author:(742337)"
DISTRIBUTED BY HASH(`Id`) BUCKETS 3 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
