CREATE TABLE `ods_tidb_shuangwen_xx_exclusiverewardnew` (
  `ProductId` smallint(6) NOT NULL COMMENT "产品id",
  `Id` bigint(20) NOT NULL COMMENT "自增id",
  `Language` int(11) NULL COMMENT "语言",
  `BookId` bigint(20) NULL COMMENT "书籍id",
  `AuthorId` bigint(20) NULL COMMENT "作者id",
  `RefUserId` varchar(65533) NULL COMMENT "笔名",
  `RewardType` int(11) NULL COMMENT "奖励类型",
  `RemunerationType` int(11) NULL COMMENT "稿酬类型",
  `ContractRewardType` int(11) NULL COMMENT "合同奖励类型",
  `SignType` int(11) NULL COMMENT "签约类型",
  `AdjustReason` varchar(65533) NULL COMMENT "调整原因",
  `MoneySale` decimal(18, 2) NULL COMMENT "书籍收入",
  `RewardSale` decimal(18, 2) NULL COMMENT "打赏收入",
  `OtherSale` double NULL COMMENT "其它收入",
  `BookSalle` decimal(18, 2) NULL COMMENT "书籍总收入",
  `RemunerationMoney` decimal(18, 2) NULL COMMENT "稿酬金额",
  `CreateTime` datetime NULL COMMENT "创建时间",
  `StaticDate` datetime NULL COMMENT "账期",
  `RemunerationStatus` int(11) NULL COMMENT "稿酬审核状态",
  `EditorRemunerationReason` varchar(65533) NULL COMMENT "责编稿酬审批意见",
  `ManagerRemunerationReason` varchar(65533) NULL COMMENT "经理稿酬审批意见",
  `IsApplyWithDrawals` int(11) NULL COMMENT "作者是否申请了提现",
  `WithDrawalsStatus` int(11) NULL COMMENT "提现审核状态",
  `EditorWithDrawalsReason` varchar(65533) NULL COMMENT "责编提现审批意见",
  `ManagerWithDrawalsReason` varchar(65533) NULL COMMENT "经理稿酬审批意见",
  `FinanceWithDrawalsReason` varchar(65533) NULL COMMENT "财务提现审批意见",
  `PayMonth` datetime NULL COMMENT "支付月份",
  `SiteId` int(11) NULL COMMENT "语言id",
  `BookName` varchar(65533) NULL COMMENT "书籍名字",
  `EditorId` bigint(20) NULL COMMENT "编辑id",
  `EditorName` varchar(65533) NULL COMMENT "编辑名字",
  `AuthorEditorId` bigint(20) NULL COMMENT "网编id",
  `AuthorEditorName` varchar(65533) NULL COMMENT "编辑名称",
  `BusinessId` varchar(65533) NULL COMMENT "钉钉审批号",
  `DailyTime` datetime NULL COMMENT "收入时间",
  `AuthorSaleRate` varchar(65533) NULL COMMENT "第三方阶梯比例",
  `IsBanWithdrawl` int(11) NULL COMMENT "是否禁止提现",
  `RelateBookId` int(11) NULL COMMENT "第三方渠道原书籍id",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "sr数据创建时间",
  `sr_updatetime` datetime NULL COMMENT "sr数据更新时间",
  INDEX index_ProductId (`ProductId`) USING BITMAP COMMENT '产品id索引',
  INDEX index_SiteId (`SiteId`) USING BITMAP COMMENT '语言id索引'
) ENGINE=OLAP 
PRIMARY KEY(`ProductId`, `Id`)
DISTRIBUTED BY HASH(`ProductId`, `Id`) BUCKETS 8 
PROPERTIES (
"replication_num" = "3",
"bloom_filter_columns" = "BookId",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
