CREATE TABLE `ods_tidb_sharpengine_ads_global_FbAdDailyInsightByEstHour` (
  `Id` bigint(20) NOT NULL COMMENT "自增id",
  `AdId` varchar(50) NULL COMMENT "广告id",
  `AdStatus` varchar(50) NULL COMMENT "广告状态",
  `FbAccountId` varchar(128) NULL COMMENT "fb账号id",
  `date_start` varchar(50) NULL COMMENT "投放开始时间",
  `date_stop` varchar(50) NULL COMMENT "投放结束时间",
  `AdName` varchar(500) NULL COMMENT "广告名",
  `Spend` decimal(10, 2) NULL COMMENT "花费金额",
  `PutData` varchar(65533) NULL COMMENT "投放数据",
  `Installs` int(11) NULL COMMENT "安装数",
  `Clicks` int(11) NULL COMMENT "点击数",
  `Impressions` int(11) NULL COMMENT "展示数",
  `Cpc` varchar(50) NULL COMMENT "Cpc",
  `Cpm` varchar(50) NULL COMMENT "Cpm",
  `Cpp` varchar(50) NULL COMMENT "Cpp",
  `Ctr` varchar(50) NULL COMMENT "ctr",
  `UpdateTime` datetime NULL COMMENT "更新时间",
  `Mt` int(11) NULL COMMENT "平台",
  `ProductId` varchar(50) NULL COMMENT "产品id",
  `Roas` decimal(10, 2) NULL COMMENT "Roas",
  `AdSetId` varchar(128) NULL COMMENT "广告组",
  `AdCampId` varchar(128) NULL COMMENT "广告系列",
  `Amount` decimal(10, 2) NULL COMMENT "金额,废弃",
  `FbAmount` decimal(10, 2) NULL COMMENT "没什么用",
  `VideoViewCount` int(11) NULL COMMENT "视频查看数",
  `Video10sViewCount` int(11) NULL COMMENT "10秒查看数",
  `VideoAvgWatchedTime` int(11) NULL COMMENT "平均视频查看时间",
  `Installs2` int(11) NULL COMMENT "没什么用",
  `ImageId` int(11) NULL COMMENT "没什么用",
  `RowVersion` bigint(20) NULL COMMENT "没什么用",
  `CreateTime` datetime NULL COMMENT "采集时间",
  `LinkClick` int(11) NULL DEFAULT "0" COMMENT "Fb链接点击量",
  `video_p100_watched_actions` int(11) NULL DEFAULT "0" COMMENT " 100%播放率",
  `video_p75_watched_actions` int(11) NULL DEFAULT "0" COMMENT " 75%播放率",
  `video_p50_watched_actions` int(11) NULL DEFAULT "0" COMMENT " 50%播放率",
  `video_p25_watched_actions` int(11) NULL DEFAULT "0" COMMENT " 25%播放率",
  `video_p95_watched_actions` int(11) NULL DEFAULT "0" COMMENT " 95%播放率",
  `Conversion` int(11) NULL DEFAULT "0" COMMENT "offsite转换数",
  `Registration` int(11) NULL DEFAULT "0" COMMENT "去重注册数",
  `MobilePurchase` int(11) NULL COMMENT "应用付费次数",
  `PixelPurchase` int(11) NULL COMMENT "像素回传付费次数",
  `MobilePurchaseValue` decimal(10, 2) NULL COMMENT "应用付费值",
  `PixelPurchaseValue` decimal(10, 2) NULL COMMENT "像素回传付费值",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据注入时间",
  `sr_updatetime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据更新时间"
) ENGINE=OLAP 
PRIMARY KEY(`Id`)
COMMENT "海外阅读、海外短剧FB广告投放记录小时表(est西五区时间)"
DISTRIBUTED BY HASH(`Id`) BUCKETS 48 
PROPERTIES (
"replication_num" = "3",
"bloom_filter_columns" = "date_start, CreateTime",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
