CREATE TABLE `ods_tidb_sharpengine_ads_global_FbAdDailyInsightByHour` (
  `Id` bigint(20) NOT NULL COMMENT "",
  `AdId` varchar(255) NOT NULL COMMENT "",
  `AdStatus` varchar(255) NOT NULL COMMENT "",
  `FbAccountId` varchar(755) NOT NULL COMMENT "",
  `date_start` varchar(255) NOT NULL COMMENT "",
  `date_stop` varchar(255) NOT NULL COMMENT "",
  `AdName` varchar(1500) NULL COMMENT "",
  `Spend` decimal(10, 2) NOT NULL COMMENT "",
  `PutData` varchar(65533) NULL COMMENT "",
  `Installs` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `Clicks` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `Impressions` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `Cpc` varchar(255) NULL COMMENT "",
  `Cpm` varchar(255) NULL COMMENT "",
  `Cpp` varchar(255) NULL COMMENT "",
  `Ctr` varchar(255) NULL COMMENT "",
  `UpdateTime` datetime NOT NULL COMMENT "",
  `Mt` int(11) NOT NULL COMMENT "",
  `ProductId` varchar(255) NULL COMMENT "",
  `Roas` decimal(10, 2) NOT NULL DEFAULT "0" COMMENT "",
  `AdSetId` varchar(755) NULL COMMENT "",
  `AdCampId` varchar(755) NULL COMMENT "",
  `Amount` decimal(10, 2) NOT NULL DEFAULT "0" COMMENT "",
  `FbAmount` decimal(10, 2) NOT NULL DEFAULT "0" COMMENT "",
  `VideoViewCount` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `Video10sViewCount` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `VideoAvgWatchedTime` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `Installs2` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `ImageId` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `RowVersion` bigint(20) NULL COMMENT "",
  `CreateTime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "",
  `LinkClick` int(11) NULL DEFAULT "0" COMMENT "",
  `video_p100_watched_actions` int(11) NULL DEFAULT "0" COMMENT " 100%播放率",
  `video_p75_watched_actions` int(11) NULL DEFAULT "0" COMMENT " 75%播放率",
  `video_p50_watched_actions` int(11) NULL DEFAULT "0" COMMENT " 50%播放率",
  `video_p25_watched_actions` int(11) NULL DEFAULT "0" COMMENT " 25%播放率",
  `video_p95_watched_actions` int(11) NULL DEFAULT "0" COMMENT " 95%播放率",
  `Conversion` int(11) NOT NULL DEFAULT "0" COMMENT "offsite转换数",
  `Registration` int(11) NOT NULL DEFAULT "0" COMMENT "去重注册数",
  `MobilePurchase` int(11) NULL COMMENT "应用付费次数",
  `PixelPurchase` int(11) NULL COMMENT "像素回传付费次数",
  `MobilePurchaseValue` decimal(10, 2) NULL COMMENT "应用付费值",
  `PixelPurchaseValue` decimal(10, 2) NULL COMMENT "像素回传付费值",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据注入时间",
  `sr_updatetime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据更新时间"
) ENGINE=OLAP 
PRIMARY KEY(`Id`)
COMMENT "海外阅读、短剧广告投放记录小时表"
DISTRIBUTED BY HASH(`Id`) BUCKETS 20 
PROPERTIES (
"replication_num" = "3",
"bloom_filter_columns" = "CreateTime",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
