CREATE TABLE `ods_tidb_readernovel_tidb_xx_official_notice2` (
  `productid` int(11) NOT NULL COMMENT "",
  `id` bigint(20) NOT NULL COMMENT "",
  `title` varchar(100) NULL COMMENT "",
  `flag` int(11) NULL COMMENT "",
  `image_src1` varchar(1500) NULL COMMENT "",
  `image_src2` varchar(1500) NULL COMMENT "",
  `image_src3` varchar(1500) NULL COMMENT "",
  `image_src4` varchar(1500) NULL COMMENT "",
  `detail` varchar(65533) NULL COMMENT "",
  `create_time` datetime NULL COMMENT "",
  `publish_time_begin` datetime NULL COMMENT "",
  `publish_time_end` datetime NULL COMMENT "",
  `link_dataurl` varchar(65533) NULL COMMENT "",
  `mt` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `Chl` varchar(955) NULL COMMENT "",
  `IsTop` tinyint(4) NOT NULL DEFAULT "0" COMMENT "",
  `ver` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `ProdId` varchar(950) NULL COMMENT "",
  `image_src5` varchar(1500) NULL DEFAULT "" COMMENT "",
  `image_src6` varchar(1500) NULL COMMENT "",
  `lessver` int(11) NULL DEFAULT "0" COMMENT "",
  `UserList` varchar(150) NULL COMMENT "",
  `IsSpecial` tinyint(4) NULL COMMENT "",
  `IsHide` int(11) NULL COMMENT "",
  `BookType` int(11) NOT NULL DEFAULT "0" COMMENT "",
  `BanChl` varchar(1500) NULL COMMENT "",
  `SmallPT` int(11) NOT NULL DEFAULT "-1" COMMENT "",
  `Country` varchar(955) NULL COMMENT "",
  `ExcludeCountry` varchar(955) NULL COMMENT "",
  `BanProdId` varchar(1500) NULL COMMENT "",
  `Filters` varchar(65533) NULL COMMENT "",
  `IsGeneral` tinyint(4) NULL COMMENT "",
  `Province` varchar(1500) NULL COMMENT "",
  `Tag` varchar(65533) NULL COMMENT "",
  `ActivitySchedulingTimeId` int(11) NULL COMMENT "",
  `AppId` varchar(1512) NULL COMMENT "",
  `RuleKey` varchar(300) NULL COMMENT "",
  `ShowUserType` int(11) NULL COMMENT "用户显示类型：0：全部显示，1：旧充值用户，2，新充值用户",
  `Sort` int(11) NULL COMMENT "",
  `IsFilterExposure` tinyint(4) NULL COMMENT "",
  `IsDelete` int(11) NULL DEFAULT "0" COMMENT "",
  `row_update_time` datetime NULL COMMENT "",
  `SyncLanguage` varchar(600) NULL DEFAULT "" COMMENT "",
  `Language` int(11) NULL DEFAULT "0" COMMENT "",
  `RecommendType` int(11) NULL COMMENT "",
  `ConfigId` bigint(20) NULL COMMENT "",
  `VerticalImg` varchar(955) NULL COMMENT "",
  `image_src7` varchar(955) NULL COMMENT "",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "",
  `sr_updatetime` datetime NULL COMMENT ""
) ENGINE=OLAP 
PRIMARY KEY(`productid`, `id`)
DISTRIBUTED BY HASH(`id`) BUCKETS 3 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
