CREATE TABLE `ods_tidb_source_series` (
  `SeriesId` bigint(20) NOT NULL DEFAULT "0" COMMENT "剧集ID",
  `SeriesName` varchar(1000) NULL COMMENT "剧集名称",
  `Language` int(11) NULL COMMENT "语言id",
  `CreateTime` datetime NULL COMMENT "创建时间",
  `UpdateTime` datetime NULL COMMENT "更新时间",
  `IsComplete` tinyint(4) NULL DEFAULT "1" COMMENT "分集是否完整 1 完整 0 缺失",
  `IsDelete` tinyint(4) NULL DEFAULT "0" COMMENT "是否删除 1 删除 0 未删除",
  `SeriesCode` varchar(300) NULL COMMENT "代码",
  `CooperateType` int(11) NULL COMMENT "作方式(1买断、2分成、3保底分成)",
  `RightsHolderId` bigint(20) NULL COMMENT "版权方Id",
  `ShareRatio` decimal(18, 2) NULL DEFAULT "0.00" COMMENT "分成比例",
  `BeginDate` date NULL COMMENT "开始日期",
  `EndDate` date NULL COMMENT "结束日期",
  `IsHidden` int(11) NULL DEFAULT "1" COMMENT "是否隐藏 1是 0不是",
  `RelationshipsUrl` varchar(1500) NULL COMMENT "人物关系",
  `LangIds` varchar(150) NULL COMMENT "结算语言id,逗号分隔 ",
  `Coef` decimal(18, 2) NULL COMMENT "分成系数",
  `IsMain` tinyint(4) NOT NULL DEFAULT "1" COMMENT "是否是主剧",
  `MainSeriesId` bigint(20) NULL COMMENT "主原始剧id",
  `AllEpis` int(11) NULL COMMENT "总集数",
  `HasSubTitle` tinyint(4) NOT NULL DEFAULT "1" COMMENT "是否有字幕",
  `EnableLowPriority` tinyint(4) NULL COMMENT "是否开启闲时转码任务，true：开启，false：关闭",
  `RemoveSubtitleEnableLowPriority` tinyint(4) NULL COMMENT "抹除字幕，是否开启闲时转码任务，true：开启，false：关闭",
  `MigrationStatus` tinyint(4) NULL COMMENT "迁移状态，-1新剧 0未迁移 1已迁移",
  `IsOcr` tinyint(4) NULL DEFAULT "1" COMMENT "是否提取字幕",
  `LocalType` int(11) NULL COMMENT "类型 1外文剧 2 中文剧",
  `LocalSubType` int(11) NULL DEFAULT "0" COMMENT "短剧子类型：1-本土剧-ai短剧",
  `VectorTime` datetime NULL COMMENT "向量化 时间",
  `AwsSyncStatus` tinyint(4) NULL DEFAULT "0" COMMENT "AWS同步状态：0未同步，1发起同步",
  `CdnSwitch` tinyint(4) NULL DEFAULT "0" COMMENT "CDN切换：0默认腾讯的CDN，1AWS的CDN",
  `AudioType` int(11) NOT NULL DEFAULT "1" COMMENT "音轨类型 1 原声剧 2 配音剧",
  `AudioLanguage` int(11) NULL COMMENT "音轨语言",
  `DubbedType` int(11) NULL COMMENT "配音类型 1 人工配音 2 AI配音",
  `IsRemoveSubtitle` tinyint(4) NOT NULL DEFAULT "1" COMMENT "是否发起抹除任务",
  `LimitIAAds` tinyint(4) NULL DEFAULT "0" COMMENT "是否限制IAA解锁",
  `LimitIAAdsPercent` int(11) NULL COMMENT "IAA集数上限百分比",
  `FirstPublicationTime` datetime NULL COMMENT "首发时间",
  `SeriesLevel` int(11) NULL COMMENT "等级 1.S 2.A 3.B 4.C",
  `WorkType` int(11) NULL COMMENT "作品类型 1.男频  2.女频 3.双番",
  `Core` varchar(300) NOT NULL DEFAULT "1core1" COMMENT "多个用逗号隔开(1core1，2core2，3core3，4core4)",
  `sr_createtime` datetime NULL COMMENT "数据创建时间",
  `sr_updatetime` datetime NULL COMMENT "数据更新时间"
) ENGINE=OLAP 
PRIMARY KEY(`SeriesId`)
COMMENT "剧集库,author:311315"
DISTRIBUTED BY HASH(`SeriesId`) BUCKETS 1 
PROPERTIES (
"replication_num" = "3",
"bloom_filter_columns" = "SeriesId, Language",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
