CREATE TABLE `ods_koc_bookinfo` (
  `Id` bigint(20) NOT NULL COMMENT "主键ID",
  `BookId` bigint(20) NOT NULL COMMENT "",
  `BookName` varchar(65533) NOT NULL COMMENT "",
  `BookNo` varchar(1024) NULL COMMENT "书号",
  `Score` int(11) NOT NULL COMMENT "评级",
  `AuthorId` bigint(20) NOT NULL COMMENT "",
  `AuthorName` varchar(1024) NOT NULL COMMENT "",
  `BookNature` int(11) NOT NULL COMMENT "来源",
  `Channel` int(11) NOT NULL COMMENT "男女频",
  `CId` int(11) NOT NULL COMMENT "分类ID",
  `CName` varchar(1024) NULL COMMENT "分类名称",
  `TotalLength` int(11) NOT NULL COMMENT "总字数",
  `ChapterCount` int(11) NOT NULL COMMENT "总章节数",
  `VipChapterCount` int(11) NOT NULL COMMENT "收费章节数",
  `PublishChapterCount` int(11) NOT NULL COMMENT "发布章节数",
  `PricePerThousand` int(11) NOT NULL COMMENT "千字价格",
  `IsFull` int(11) NOT NULL COMMENT "是否完本",
  `IsPutaway` int(11) NOT NULL COMMENT "是否上架",
  `IsMutex` int(11) NOT NULL COMMENT "是否AB策",
  `SignType` int(11) NOT NULL COMMENT "签约类型",
  `LangId` int(11) NOT NULL COMMENT "语言",
  `ImgSrc` varchar(65533) NULL COMMENT "封面",
  `CreateTime` datetime NOT NULL COMMENT "Tag创建时间",
  `UpdateTime` datetime NULL COMMENT "Tag更新时间",
  `TagIds` varchar(65533) NULL COMMENT "标签ID",
  `TagNames` varchar(65533) NULL COMMENT "标签名称",
  `FreeChapterNum` int(11) NOT NULL DEFAULT "0" COMMENT "免费章节数",
  `TotalPublishLength` int(11) NOT NULL DEFAULT "0" COMMENT "书籍总发布字数",
  `SiteId` int(11) NOT NULL DEFAULT "0" COMMENT "合作商Id",
  `Sexy2` int(11) NOT NULL DEFAULT "0" COMMENT "涉黄等级",
  `SpeedChapterNum` int(11) NOT NULL DEFAULT "0" COMMENT "超点章节数",
  `StoryType` int(11) NOT NULL DEFAULT "0" COMMENT "类型0长篇小说 1短篇小说",
  `SynchCreateTime` datetime NOT NULL COMMENT "创建时间",
  `SynchUpdateTime` datetime NULL COMMENT "更新时间",
  `Introduce` varchar(65533) NULL COMMENT "简介",
  `IsHide` int(11) NOT NULL DEFAULT "0" COMMENT "是否隐藏 0=不隐藏|1=隐藏",
  `IsMainPush` int(11) NOT NULL DEFAULT "0" COMMENT "是否推荐 0否 1是",
  `MainPushTime` varchar(255) NULL COMMENT "推荐时间 yyyy-MM-dd",
  `PushRemark` varchar(65533) NULL COMMENT "主推备注",
  `PushReason` varchar(65533) NULL COMMENT "主推原因",
  `PushGrade` varchar(65533) NULL COMMENT "主推评级",
  `sr_createtime` datetime NULL COMMENT "同步时间",
  `sr_updatetime` datetime NULL COMMENT "更新时间"
) ENGINE=OLAP 
PRIMARY KEY(`Id`)
COMMENT "koc书籍表"
DISTRIBUTED BY HASH(`Id`) BUCKETS 1 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
