----------------------------------------------------------------
-- 目标表： ods.ods_tidb_short_video_admin_novel_book
-- 来源实例： old_tidb_source
-- 来源表： short_video_admin.novel_book
-- 来源负责：
-- 采集工具： SeaTunnel
-- 开发人：
-- 开发日期： 2026-06-22
----------------------------------------------------------------

drop table if exists ods.ods_tidb_short_video_admin_novel_book;
create table ods.ods_tidb_short_video_admin_novel_book (
     bookid                    bigint           not null                    comment "书籍id，主键"
    ,siteid                    int                                          comment "站点id"
    ,mappedbookid              bigint                                       comment "映射书id，用于隔离海阅/海剧id空间"
    ,samebookid                varchar(150)                                 comment "同源书id"
    ,fcid                      int                                          comment "一级分类id"
    ,cid                       int                                          comment "二级分类id"
    ,cname                     varchar(300)                                 comment "分类名称"
    ,bookname                  varchar(300)                                 comment "书名"
    ,authorname                varchar(300)                                 comment "作者名称"
    ,clicknum                  int                                          comment "总点击数"
    ,weekclicknum              int                                          comment "周点击数"
    ,monthclicknum             int                                          comment "月点击数"
    ,recommendnum              int                                          comment "推荐数"
    ,length                    int                                          comment "书籍字数"
    ,updatetime                datetime                                     comment "更新时间"
    ,latestupdatetime          datetime                                     comment "最新更新时间"
    ,updatechapterid           bigint                                       comment "更新章节id"
    ,updatechaptername         varchar(1536)                                comment "更新章节名称"
    ,latestupdatechaptername   varchar(1536)                                comment "最新更新章节名称"
    ,imgsrc                    varchar(750)                                 comment "封面图片地址"
    ,introduce                 string                                       comment "书籍简介"
    ,allchapterurl             varchar(750)                                 comment "全部章节列表页url"
    ,indexurl                  varchar(450)                                 comment "书籍详情页url"
    ,vip                       int                                          comment "是否vip书籍"
    ,status                    int                                          comment "书籍状态"
    ,buildtime                 datetime                                     comment "入库时间"
    ,chapterstatus             int                                          comment "章节状态"
    ,chapterurl                varchar(150)                                 comment "章节url模板"
    ,normalchapternum          int              not null                    comment "普通章节数"
    ,vipchapternum             int              not null                    comment "vip章节数"
    ,normalchapternum_f        int              not null                    comment "免费普通章节数"
    ,vipchapternum_f           int              not null                    comment "免费vip章节数"
    ,collectcount              int              not null                    comment "收藏数"
    ,sexy                      int              not null                    comment "一级性别分类"
    ,ratingnum                 int              not null                    comment "评分人数"
    ,ratingscore               int              not null                    comment "评分总分"
    ,original                  tinyint          not null                    comment "是否原创"
    ,authorid                  bigint           not null                    comment "作者id"
    ,isclub                    tinyint          not null                    comment "是否加入俱乐部"
    ,ndclicknum                int              not null                    comment "内地点击数"
    ,size                      int              not null                    comment "书籍大小(字节)"
    ,isfull                    int                                          comment "是否完结"
    ,channel                   int                                          comment "频道"
    ,tagflag                   int                                          comment "标签标记位"
    ,tagplatform               int                                          comment "标签适用平台,1全平台"
    ,dataupdatetime            datetime                                     comment "数据更新时间"
    ,authorcode                string                                       comment "作者编码"
    ,bookcode                  string                                       comment "书籍编码"
    ,authorlength              int                                          comment "作者名长度"
    ,booknamelength            int                                          comment "书名长度"
    ,priceperthousand          int              not null                    comment "千字价格(分)"
    ,source                    int              not null                    comment "来源,0自采1抓取"
    ,hasupdate                 tinyint          not null                    comment "是否有更新,1是0否"
    ,newcid                    int                                          comment "新分类id"
    ,newcname                  varchar(300)                                 comment "新分类名称"
    ,sexy2                     int                                          comment "二级性别分类"
    ,fullprice                 int                                          comment "完结价格(分)"
    ,setsexy2                  int              not null                    comment "是否手动设置二级性别分类"
    ,haschapterupdate          tinyint          not null                    comment "是否有章节更新"
    ,grantstatus               int              not null                    comment "授权状态"
    ,voicechapternum           int              not null                    comment "有声章节数"
    ,hasvoiceupdate            tinyint          not null                    comment "是否有有声更新"
    ,url                       varchar(1536)                                comment "书籍来源url"
    ,isepub                    tinyint                                      comment "是否有epub版本"
    ,epub_path                 varchar(1500)                                comment "epub文件路径"
    ,epub_price                int                                          comment "epub价格(分)"
    ,freechapternum            int                                          comment "免费章节数"
    ,bookno                    bigint           not null                    comment "自增序号"
    ,manualrating              varchar(150)                                 comment "人工评分"
    ,pushchapternum            int                                          comment "推送章节数"
    ,voicebookid               bigint                                       comment "有声书关联id"
    ,iseighteen                tinyint          not null                    comment "是否18禁,1是0否"
    ,alias                     varchar(1500)                                comment "书籍别名"
    ,bannerimg                 varchar(1500)                                comment "banner图片地址"
    ,defaultfavnum             int              not null                    comment "默认收藏数(初始值)"
    ,ncartoonid                bigint                                       comment "关联漫画id"
    ,vcartoonid                bigint                                       comment "关联动态漫画id"
    ,translator                varchar(765)                                 comment "译者"
    ,verifier                  varchar(765)                                 comment "审核人"
    ,chaptergiftbuyhour        int              not null                    comment "章节礼物购买时长(小时)"
    ,keyword                   varchar(6000)                                comment "关键词"
    ,titleword                 varchar(6000)                                comment "标题词"
    ,descriptionword           varchar(6000)                                comment "描述词"
    ,fsexy                     int                                          comment "过滤后性别分类"
    ,pushxztime                datetime                                     comment "推送下架时间"
    ,baidupushstatus           int                                          comment "百度推送状态"
    ,backsexy                  int                                          comment "备用一级性别分类"
    ,backsexy2                 int                                          comment "备用二级性别分类"
    ,roles                     varchar(1500)                                comment "角色列表"
    ,smalliosfreechapternum    int                                          comment "ios小程序免费章节数"
    ,smallandfreechapternum    int                                          comment "安卓小程序免费章节数"
    ,hasrobotvoice             int              not null                    comment "是否有ai语音"
    ,isbn                      varchar(150)                                 comment "isbn编号"
    ,language                  int                                          comment "语言"
    ,fulltime                  datetime                                     comment "完结时间"
    ,ftcovercheck              int                                          comment "封面对审状态"
    ,booknature                tinyint          not null                    comment "书籍性质"
    ,riv                       bigint           not null                    comment "阅读收入版本号"
    ,isstop                    tinyint          not null                    comment "是否停更"
    ,stoptime                  datetime                                     comment "停更时间"
    ,signtype                  int                                          comment "签约类型"
    ,row_create_time           datetime                                     comment "记录创建时间"
    ,storytype                 int              not null                    comment "类型"
    ,seriesid                  bigint                                       comment "关联短剧id"
    ,iseighteentag             int              not null                    comment "是否18禁标签"
    ,tags                      varchar(3000)                                comment "书籍标签,多个之间半角逗号分隔"
    ,bookalias                 varchar(300)                                 comment "取自爽文库的书籍代号"
    ,tagids                    varchar(3000)                                comment "书籍标签id,多个之间半角逗号分隔"
    ,audiobookinfo             varchar(765)                                 comment "音频信息列表，以逗号分隔"
    ,sr_createtime             datetime         default current_timestamp   comment "starrocks数据注入时间"
    ,sr_updatetime             datetime         default current_timestamp   comment "starrocks数据更新时间"
)
primary key(bookid)
comment "小说书籍表"
distributed by hash(bookid) buckets 3
properties (
    "replication_num" = "3"
   ,"in_memory" = "false"
   ,"enable_persistent_index" = "true"
   ,"replicated_storage" = "true"
   ,"compression" = "LZ4"
)
;
