CREATE TABLE `ads_ab_strategy_core_index` (
  `strategyId` bigint(20) NOT NULL COMMENT "策略id",
  `dt` date NOT NULL COMMENT "日期分区",
  `projectId` int(11) NOT NULL COMMENT "项目id",
  `windowNum` int(11) NOT NULL COMMENT "窗口大小(过去n天)",
  `statisticType` int(11) NOT NULL COMMENT "统计类型，1日期维度，2日期+策略类型，3日期+策略类型+策略",
  `strategyType` int(11) NOT NULL COMMENT "策略类型",
  `strategySecondType` int(11) NOT NULL COMMENT "策略子类型",
  `totalNumber` bigint(20) NULL COMMENT "实验的总的样本量",
  `totalNumberGroup` bigint(20) NULL COMMENT "实验组的总的样本量",
  `groupNum` bigint(20) NULL COMMENT "进组人数",
  `includeGroupNum` bigint(20) NULL COMMENT "入包人数",
  `divideTrafficNum` bigint(20) NULL COMMENT "分流人数",
  `strategyHitNum` bigint(20) NULL COMMENT "策略命中人数",
  `exposureNum` bigint(20) NULL COMMENT "曝光人数",
  `clickNum` bigint(20) NULL COMMENT "点击人数",
  `viewNum` bigint(20) NULL COMMENT "观看人数",
  `unlockNum` bigint(20) NULL COMMENT "解锁人数",
  `viewEpisodeNum` bigint(20) NULL COMMENT "观看集数",
  `payUnlockEpisodeNum` bigint(20) NULL COMMENT "付费解锁集数",
  `estimatedRevenue` varchar(50) NULL COMMENT "预估收益",
  `arpu` varchar(50) NULL COMMENT "ARPU",
  `payRate` varchar(50) NULL COMMENT "付费率",
  `payRateFenzi` varchar(50) NULL COMMENT "付费率分子(成功人数)",
  `payRateFenMu` varchar(50) NULL COMMENT "付费率分母(上一步人数)",
  `arppu` varchar(50) NULL COMMENT "ARPPU",
  `unitPrice` varchar(50) NULL COMMENT "客单价",
  `rechargeAvg` decimal(16, 4) NULL COMMENT "人均充值次数",
  `totalArppu` varchar(50) NULL COMMENT "总消费ARPPU",
  `readCoinsArppu` varchar(50) NULL COMMENT "阅币消费ARPPU",
  `rechargePeopleNum` bigint(20) NULL COMMENT "充值人数",
  `rechargeNum` bigint(20) NULL COMMENT "充值次数",
  `rechargeAmount` varchar(50) NULL COMMENT "充值金额",
  `threePartiesAcount` varchar(50) NULL COMMENT "三方实收",
  `threePartiesPercent` varchar(50) NULL COMMENT "三方实收占比",
  `amountRate` varchar(50) NULL COMMENT "费率",
  `consumNum` bigint(20) NULL COMMENT "消费人数",
  `readCoinsConsumAmount` varchar(50) NULL COMMENT "阅币消费金额",
  `voucherConsumAmount` varchar(50) NULL COMMENT "礼券消费金额",
  `readCoinsAndVoucherApru` varchar(50) NULL COMMENT "阅币礼券消费ARPU",
  `consumeRate` varchar(50) NULL COMMENT "消费率",
  `adverArpu` varchar(50) NULL COMMENT "广告ARPU",
  `totalAdverArpu` varchar(50) NULL COMMENT "总广告ARPU",
  `adverUnlockRate` varchar(50) NULL COMMENT "广告解锁率",
  `adverUnlockRateFenzi` varchar(50) NULL COMMENT "广告解锁率分子(成功人数)",
  `adverUnlockRateFenmu` varchar(50) NULL COMMENT "广告解锁率分母(上一步人数)",
  `adverUnlockEpisodeNum` varchar(50) NULL COMMENT "人均广告解锁剧集",
  `oneExposureArpu` decimal(20, 6) NULL COMMENT "单人曝光ARPU",
  `oneExposureArpuDingYue` decimal(20, 6) NULL COMMENT "单人曝光ARPU(订阅)",
  `oneRechargePercent` decimal(20, 6) NULL COMMENT "单次充值占比",
  `oneRechargePercentFenzi` decimal(20, 2) NULL COMMENT "单次充值占比分子(普通充值金额)",
  `oneRechargePercentFenmu` decimal(20, 2) NULL COMMENT "单次充值占比分母(充值金额)",
  `dingYueAmountPercent` decimal(20, 6) NULL COMMENT "订阅金额占比",
  `dingYueAmountPercentFenzi` decimal(20, 2) NULL COMMENT "订阅金额占比分子(订阅金额)",
  `dingYueAmountPercentFenmu` decimal(20, 2) NULL COMMENT "订阅金额占比分母(充值金额)",
  `orderCreateRate` decimal(20, 6) NULL COMMENT "订单创建率",
  `orderCreateRateFenzi` int(11) NULL COMMENT "订单创建率分子（订单创建人数）",
  `orderCreateRateFenmu` int(11) NULL COMMENT "订单创建率分母（曝光人数）",
  `predictARPU` decimal(20, 6) NULL COMMENT "预估ARPU",
  `buyersNum` int(11) NULL COMMENT "购买人数",
  `buyAmount` decimal(12, 2) NULL COMMENT "购买金额",
  `saveTime` datetime NULL COMMENT "入库时间",
  `updateTime` datetime NULL COMMENT "更新时间"
) ENGINE=OLAP 
PRIMARY KEY(`strategyId`, `dt`, `projectId`, `windowNum`, `statisticType`, `strategyType`, `strategySecondType`)
DISTRIBUTED BY HASH(`strategyId`) BUCKETS 3 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"fast_schema_evolution" = "true",
"compression" = "LZ4"
);