CREATE TABLE ads.`ads_ab_exp_core_index` (
  `experimentId` bigint(20) NOT NULL COMMENT "实验id",
  `experimentGroupId` bigint(20) NOT NULL COMMENT "实验组id",
  `dt` date NOT NULL COMMENT "日期分区",
  `projectId` int(11) NOT NULL COMMENT "项目id",
  `trackficVersion` varchar(500) NOT NULL COMMENT "流量版本",
  `windowNum` int(11) NOT NULL COMMENT "窗口大小(过去n天)",
  `experimentName` varchar(500) NULL COMMENT "实验名称",
  `experimentGroupName` varchar(500) NULL COMMENT "实验组名称",
  `experimentType` int(11) NOT NULL COMMENT "实验类型(1对照组、2实验组)",
  `totalNumber` bigint(20) NULL COMMENT "实验的总的样本量",
  `totalNumberGroup` bigint(20) NULL COMMENT "实验组的总的样本量",
  `groupNum` bigint(20) NULL COMMENT "进组人数",
  `includeGroupNum` bigint(20) NULL COMMENT "入包人数",
  `divideTrafficNum` bigint(20) NULL COMMENT "分流人数",
  `strategyHitNum` bigint(20) NULL COMMENT "策略命中人数",
  `exposureNum` bigint(20) NULL COMMENT "曝光人数",
  `clickNum` bigint(20) NULL COMMENT "点击人数",
  `viewNum` bigint(20) NULL COMMENT "观看人数",
  `unlockNum` bigint(20) NULL COMMENT "解锁人数",
  `payUnlockNum` bigint(20) NULL COMMENT "付费解锁人数",
  `viewEpisodeNum` bigint(20) NULL COMMENT "观看集数",
  `unlockEpisodeNum` bigint(20) NULL COMMENT "解锁集数",
  `payUnlockEpisodeNum` bigint(20) NULL COMMENT "付费解锁集数",
  `estimatedRevenue` varchar(50) NULL COMMENT "预估收益",
  `arpu` varchar(50) NULL COMMENT "ARPU",
  `payRate` varchar(50) NULL COMMENT "付费率",
  `payRateFenzi` varchar(50) NULL COMMENT "付费率分子(成功人数)",
  `payRateFenMu` varchar(50) NULL COMMENT "付费率分母(上一步人数)",
  `payAllRate` varchar(50) NULL COMMENT "付费率(总)",
  `payAllRateFenzi` varchar(50) NULL COMMENT "付费率分子(成功人数)(总)",
  `payAllRateFenmu` varchar(50) NULL COMMENT "付费率分母(上一步人数)(总)",
  `arppu` varchar(50) NULL COMMENT "ARPPU",
  `unitPrice` varchar(50) NULL COMMENT "客单价",
  `rechargeAvg` decimal(16, 4) NULL COMMENT "人均充值次数",
  `totalArppu` varchar(50) NULL COMMENT "总消费ARPPU",
  `readCoinsArppu` varchar(50) NULL COMMENT "阅币消费ARPPU",
  `rechargePeopleNum` bigint(20) NULL COMMENT "充值人数",
  `rechargeNum` bigint(20) NULL COMMENT "充值次数",
  `rechargeAmount` varchar(50) NULL COMMENT "充值金额",
  `threePartiesAcount` varchar(50) NULL COMMENT "三方实收",
  `threePartiesPercent` varchar(50) NULL COMMENT "三方实收占比",
  `amountRate` varchar(50) NULL COMMENT "费率",
  `consumNum` bigint(20) NULL COMMENT "消费人数",
  `readCoinsConsumAmount` varchar(50) NULL COMMENT "阅币消费金额",
  `voucherConsumAmount` varchar(50) NULL COMMENT "礼券消费金额",
  `readCoinsAndVoucherApru` varchar(50) NULL COMMENT "阅币礼券消费ARPU",
  `consumeRate` varchar(50) NULL COMMENT "消费率",
  `adverArpu` varchar(50) NULL COMMENT "广告ARPU",
  `totalAdverArpu` varchar(50) NULL COMMENT "总广告ARPU",
  `adverUnlockRate` varchar(50) NULL COMMENT "广告解锁率",
  `adverUnlockRateFenzi` varchar(50) NULL COMMENT "广告解锁率分子(成功人数)",
  `adverUnlockRateFenmu` varchar(50) NULL COMMENT "广告解锁率分母(上一步人数)",
  `adverUnlockEpisodeNum` varchar(50) NULL COMMENT "人均广告解锁剧集",
  `oneExposureArpu` decimal(20, 6) NULL COMMENT "单人曝光ARPU",
  `oneExposureAllArpu` decimal(20, 6) NULL COMMENT "单人曝光ARPU(总)",
  `oneExposureAllArpuFenzi` decimal(20, 6) NULL COMMENT "单人曝光ARPU分子(总)",
  `oneExposureAllArpuFenmu` decimal(20, 6) NULL COMMENT "单人曝光ARPU分母(总)",
  `oneExposureArpuDingYue` decimal(20, 6) NULL COMMENT "单人曝光ARPU(订阅)",
  `oneRechargePercent` decimal(20, 6) NULL COMMENT "单次充值占比",
  `oneRechargePercentFenzi` decimal(20, 2) NULL COMMENT "单次充值占比分子(普通充值金额)",
  `oneRechargePercentFenmu` decimal(20, 2) NULL COMMENT "单次充值占比分母(充值金额)",
  `dingYueAmountPercent` decimal(20, 6) NULL COMMENT "订阅金额占比",
  `dingYueAmountPercentFenzi` decimal(20, 2) NULL COMMENT "订阅金额占比分子(订阅金额)",
  `dingYueAmountPercentFenmu` decimal(20, 2) NULL COMMENT "订阅金额占比分母(充值金额)",
  `dingYueAmountAllPercent` decimal(20, 6) NULL COMMENT "订阅金额占比(总)",
  `dingYueAmountAllPercentFenzi` decimal(20, 6) NULL COMMENT "订阅金额占比分子(订阅金额)(总)",
  `dingYueAmountAllPercentFenmu` decimal(20, 6) NULL COMMENT "订阅金额占比分母(充值金额)(总)",
  `orderCreateRate` decimal(20, 6) NULL COMMENT "订单创建率",
  `orderCreateRateFenzi` int(11) NULL COMMENT "订单创建率分子（订单创建人数）",
  `orderCreateRateFenmu` int(11) NULL COMMENT "订单创建率分母（曝光人数）",
  `predictARPU` decimal(20, 6) NULL COMMENT "预估ARPU",
  `buyersNum` int(11) NULL COMMENT "购买人数",
  `buyAmount` decimal(12, 2) NULL COMMENT "购买金额",
  `episodeExposureNum` int(11) NULL COMMENT "曝光人数",
  `clickCTR` decimal(20, 6) NULL COMMENT "点击率CTR",
  `ctr` decimal(20, 6) NULL COMMENT "CTR（点击ctr：点击pv/曝光pv）",
  `unlockArppu` decimal(20, 4) NULL COMMENT "人均解锁ARPPU",
  `unlockArpu` decimal(20, 4) NULL COMMENT "人均解锁ARPU",
  `saveTime` datetime NULL COMMENT "入库时间",
  `updateTime` datetime NULL COMMENT "更新时间",
  `version_start_time` datetime NULL COMMENT "版本开始时间",
  `version_end_time` datetime NULL COMMENT "版本结束时间"
) ENGINE=OLAP 
PRIMARY KEY(`experimentId`, `experimentGroupId`, `dt`, `projectId`, `trackficVersion`, `windowNum`)
DISTRIBUTED BY HASH(`experimentId`) BUCKETS 6 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"fast_schema_evolution" = "true",
"compression" = "LZ4"
);