drop table if exists ads.ads_book_read_consume;
create table ads.ads_book_read_consume (
     dt                       datetime    not null                     comment "统计日期"
    ,book_id                  bigint      not null                     comment "书籍id"
    ,site_id                  int         not null                     comment "书籍语言 "
    ,new_cid                  int                                      comment "书籍分类id"
    ,channel                  int                                      comment "频道"
    ,is_full                  tinyint                                  comment "完结状态"
    ,full_time                datetime                                 comment "完结时间"
    ,sexy2                    int                                      comment "上架状态"
    ,build_time               datetime                                 comment "上架时间"
    ,sign_type                int                                      comment "签约状态"
    ,languageid               int                                      comment "书籍语言"
    ,public_fontlength        int                                      comment "书籍发布总字数"
    ,book_update_time         datetime                                 comment "书籍更新时间"
    ,consume_1d               int                                      comment "近1日阅币加礼券消耗"
    ,consume_7d               int                                      comment "近7日阅币加礼券消耗"
    ,consume_30d              int                                      comment "近30日阅币加礼券消耗"
    ,consume_td               int                                      comment "历史阅币加礼券消耗"
    ,full_consume_1d          int                                      comment "近1日阅币+礼券+赠送币+VIP消费消耗"
    ,full_consume_7d          int                                      comment "近7日阅币+礼券+赠送币+VIP消费消耗"
    ,full_consume_30d         int                                      comment "近30日阅币+礼券+赠送币+VIP消费消耗"
    ,full_consume_td          int                                      comment "历史阅币+礼券+赠送币+VIP消费消耗"
    ,read_1d                  int                                      comment "近1日阅读人数"
    ,read_7d                  int                                      comment "近7日阅读人数"
    ,read_30d                 int                                      comment "近30日阅读人数"
    ,read_td                  int                                      comment "历史阅读人数"
    ,update_word_count_1d     int                                      comment "近1日更新字数"
    ,update_word_count_7d     int                                      comment "近7日更新字数"
    ,update_word_count_30d    int                                      comment "近30日更新字数"
    ,etl_time                 datetime    default current_timestamp    comment "etl清洗时间"
    ,book_nature              int                                      comment "书籍来源 1：机翻 2：人工 3：原创 4：cp 5：原创拆章 6：翻译拆章 7：原创图书 8：有声书籍 9：cp翻译 0：未知 AFTER update_word_count_30d"
    ,score_type               int                                      comment "书籍评级  未评级 = 0, S = 1, A = 2, B = 3, C = 4"
    ,index index_book_id (book_id) using bitmap comment "index_book_id"
)
primary key(dt, book_id, site_id)
comment "书籍维度阅读消耗人数"
distributed by hash(book_id, site_id) buckets 1
properties (
    "replication_num" = "3"
    ,"bloom_filter_columns" = "site_id, book_id"
    ,"in_memory" = "false"
    ,"enable_persistent_index" = "true"
    ,"replicated_storage" = "true"
    ,"compression" = "LZ4"
);
