CREATE TABLE `ads_temp_stripe_efw` (
  `id` varchar(30) NOT NULL COMMENT "id",
  `created_date` datetime NULL COMMENT "created_date",
  `amount` double NULL COMMENT "amount",
  `amount_refunded` double NULL COMMENT "amount_refunded",
  `currency` varchar(10) NULL COMMENT "currency",
  `captured` boolean NULL COMMENT "captured",
  `converted_amount` double NULL COMMENT "converted_amount",
  `converted_amount_refunded` double NULL COMMENT "converted_amount_refunded",
  `converted_currency` varchar(10) NULL COMMENT "converted_currency",
  `decline_reason` varchar(30) NULL COMMENT "decline_reason",
  `description` varchar(30) NULL COMMENT "description",
  `fee` double NULL COMMENT "fee",
  `is_link` boolean NULL COMMENT "is_link",
  `link_funding` varchar(10) NULL COMMENT "link_funding",
  `mode` varchar(10) NULL COMMENT "mode",
  `paymentintent_id` varchar(30) NULL COMMENT "paymentintent_id",
  `payment_source_type` varchar(10) NULL COMMENT "payment_source_type",
  `refunded_date` datetime NULL COMMENT "refunded_date",
  `statement_descriptor` varchar(30) NULL COMMENT "statement_descriptor",
  `status` varchar(10) NULL COMMENT "status",
  `seller_message` varchar(30) NULL COMMENT "seller_message",
  `taxes_on_fee` int(11) NULL COMMENT "taxes_on_fee",
  `card_id` varchar(30) NULL COMMENT "card_id",
  `card_name` varchar(40) NULL COMMENT "card_name",
  `card_address_line1` varchar(45) NULL COMMENT "card_address_line1",
  `card_address_line2` varchar(45) NULL COMMENT "card_address_line2",
  `card_address_city` varchar(30) NULL COMMENT "card_address_city",
  `card_address_state` varchar(20) NULL COMMENT "card_address_state",
  `card_address_country` varchar(10) NULL COMMENT "card_address_country",
  `card_address_zip` varchar(20) NULL COMMENT "card_address_zip",
  `card_avs_line1_status` varchar(20) NULL COMMENT "card_avs_line1_status",
  `card_avs_zip_status` varchar(20) NULL COMMENT "card_avs_zip_status",
  `card_brand` varchar(20) NULL COMMENT "card_brand",
  `card_cvc_status` varchar(20) NULL COMMENT "card_cvc_status",
  `card_exp_month` int(11) NULL COMMENT "card_exp_month",
  `card_exp_year` int(11) NULL COMMENT "card_exp_year",
  `card_fingerprint` varchar(30) NULL COMMENT "card_fingerprint",
  `card_funding` varchar(20) NULL COMMENT "card_funding",
  `card_issue_country` varchar(20) NULL COMMENT "card_issue_country",
  `card_last4` int(11) NULL COMMENT "card_last4",
  `card_tokenization_method` varchar(20) NULL COMMENT "card_tokenization_method",
  `customer_id` varchar(30) NULL COMMENT "customer_id",
  `customer_description` varchar(30) NULL COMMENT "customer_description",
  `customer_email` varchar(30) NULL COMMENT "customer_email",
  `customer_phone` varchar(30) NULL COMMENT "customer_phone",
  `shipping_name` varchar(30) NULL COMMENT "shipping_name",
  `shipping_address_line1` varchar(30) NULL COMMENT "shipping_address_line1",
  `shipping_address_line2` varchar(30) NULL COMMENT "shipping_address_line2",
  `shipping_address_city` varchar(30) NULL COMMENT "shipping_address_city",
  `shipping_address_state` varchar(30) NULL COMMENT "shipping_address_state",
  `shipping_address_country` varchar(30) NULL COMMENT "shipping_address_country",
  `shipping_address_postal_code` varchar(30) NULL COMMENT "shipping_address_postal_code",
  `disputed_amount` double NULL COMMENT "disputed_amount",
  `dispute_date` datetime NULL COMMENT "dispute_date",
  `dispute_evidence_due` datetime NULL COMMENT "dispute_evidence_due",
  `dispute_reason` varchar(30) NULL COMMENT "dispute_reason",
  `dispute_status` varchar(30) NULL COMMENT "dispute_status",
  `invoice_id` varchar(30) NULL COMMENT "invoice_id",
  `invoice_number` varchar(30) NULL COMMENT "invoice_number",
  `checkout_session_id` varchar(80) NULL COMMENT "checkout_session_id",
  `checkout_custom_field_1_key` varchar(20) NULL COMMENT "checkout_custom_field_1_key",
  `checkout_custom_field_1_value` varchar(20) NULL COMMENT "checkout_custom_field_1_value",
  `checkout_custom_field_2_key` varchar(20) NULL COMMENT "checkout_custom_field_2_key",
  `checkout_custom_field_2_value` varchar(20) NULL COMMENT "checkout_custom_field_2_value",
  `checkout_custom_field_3_key` varchar(20) NULL COMMENT "checkout_custom_field_3_key",
  `checkout_custom_field_3_value` varchar(20) NULL COMMENT "checkout_custom_field_3_value",
  `checkout_line_item_summary` varchar(70) NULL COMMENT "checkout_line_item_summary",
  `checkout_promotional_consent` varchar(20) NULL COMMENT "checkout_promotional_consent",
  `checkout_terms_of_service_consent` varchar(20) NULL COMMENT "checkout_terms_of_service_consent",
  `client_reference_id` int(11) NULL COMMENT "client_reference_id",
  `payment_link_id` int(11) NULL COMMENT "payment_link_id",
  `utm_campaign` varchar(20) NULL COMMENT "utm_campaign",
  `utm_content` varchar(20) NULL COMMENT "utm_content",
  `utm_medium` varchar(20) NULL COMMENT "utm_medium",
  `utm_source` varchar(20) NULL COMMENT "utm_source",
  `utm_term` varchar(20) NULL COMMENT "utm_term",
  `terminal_location_id` varchar(20) NULL COMMENT "terminal_location_id",
  `terminal_reader_id` varchar(20) NULL COMMENT "terminal_reader_id",
  `application_fee` varchar(20) NULL COMMENT "application_fee",
  `application_id` varchar(20) NULL COMMENT "application_id",
  `destination` varchar(20) NULL COMMENT "destination",
  `transfer` varchar(40) NULL COMMENT "transfer",
  `transfer_group` varchar(20) NULL COMMENT "transfer_group",
  `userid` varchar(20) NULL COMMENT "userid",
  `paychannelid` int(11) NULL COMMENT "paychannelid",
  `orderid` int(11) NULL COMMENT "orderid"
) ENGINE=OLAP 
DUPLICATE KEY(`id`)
COMMENT "临时-Stripe EFW"
DISTRIBUTED BY HASH(`id`)
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);