CREATE TABLE `ads_report_book_capacity_rate_stat` (
  `dt` date NOT NULL COMMENT "查询日期",
  `site_id` smallint(6) NOT NULL COMMENT "语言id",
  `book_id` bigint(20) NOT NULL COMMENT "书籍id",
  `book_code` varchar(65533) NULL COMMENT "书籍代号",
  `from_book_name` varchar(65533) NULL COMMENT "源书籍名称",
  `to_book_name` varchar(65533) NULL COMMENT "目标书籍名称",
  `object_book_type` int(11) NULL COMMENT "图书书籍类型,0-网文 1-短剧",
  `publish_length` bigint(20) NULL COMMENT "发布字数",
  `avg_chapter_length` bigint(20) NULL COMMENT "章节平均字数",
  `daily_number` decimal(24, 8) NULL COMMENT "日更章节数",
  `proofread_length` bigint(20) NULL COMMENT "精修字数",
  `update_day_left` bigint(20) NULL COMMENT "预计可更天数",
  `edit_publish_number` bigint(20) NULL COMMENT "已发布章节数",
  `left_number` bigint(20) NULL COMMENT "最新囤稿",
  `cn_chapter_publish` bigint(20) NULL COMMENT "中文已发布",
  `cn_font_length` bigint(20) NULL COMMENT "中文已发布字数",
  `interpreter_number` bigint(20) NULL COMMENT "章节质检进度",
  `foreign_number` bigint(20) NULL COMMENT "章节一校进度",
  `proofread_number` bigint(20) NULL COMMENT "章节二校进度",
  `translate_left` bigint(20) NULL COMMENT "翻译章节差额",
  `foreign_left` bigint(20) NULL COMMENT "待一校章节",
  `proofread_left` bigint(20) NULL COMMENT "待二校章节",
  `remark` varchar(65533) NULL COMMENT "卡章提示",
  `font_length_curmonth` bigint(20) NULL COMMENT "本月精修字数",
  `interpreter_font_length` bigint(20) NULL COMMENT "字数质检进度",
  `foreign_font_length` bigint(20) NULL COMMENT "字数一校进度",
  `proofread_font_length` bigint(20) NULL COMMENT "字数二校进度",
  `w3_reach_dt` date NULL COMMENT "达到3W字日期",
  `w5_reach_dt` date NULL COMMENT "达到5W字日期",
  `w10_reach_dt` date NULL COMMENT "达到10W字日期",
  `w15_reach_dt` date NULL COMMENT "达到15W字日期",
  `w20_reach_dt` date NULL COMMENT "达到20W字日期",
  `w25_reach_dt` date NULL COMMENT "达到25W字日期",
  `w30_reach_dt` date NULL COMMENT "达到30W字日期",
  `w35_reach_dt` date NULL COMMENT "达到30W字日期",
  `font_inc_day` bigint(20) NULL COMMENT "精修较昨日增长字数",
  `font_inc_week` bigint(20) NULL COMMENT "精修较上周增长字数",
  `publish_time` datetime NULL COMMENT "上架日期",
  `publish_days` bigint(20) NULL COMMENT "距离上架天数",
  `first_translate_day` date NULL COMMENT "首次翻译日期",
  `to_firstday_num` bigint(20) NULL COMMENT "距离首翻天数",
  `cost_back_dt` date NULL COMMENT "费率回本日期",
  `cost_amt_7` decimal(18, 4) NULL COMMENT "近7天成本金额，单位：人民币",
  `amount_7` decimal(18, 4) NULL COMMENT "近7天收入，单位：人民币",
  `cost_back_rate_7` decimal(18, 4) NULL COMMENT "7天费率",
  `cost_amt_curmon` decimal(18, 4) NULL COMMENT "本月成本金额，单位：人民币",
  `amount_curmon` decimal(18, 4) NULL COMMENT "本月收入，单位：人民币",
  `cost_back_rate_curmon` decimal(18, 4) NULL COMMENT "本月费率",
  `amount_curmon_sort` varchar(65533) NULL COMMENT "同语言本月收入排序",
  `amount_YTD_sort` varchar(65533) NULL COMMENT "同语言累计收入排序",
  `etl_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "etl清洗时间",
  INDEX index_site_id (`site_id`) USING BITMAP COMMENT '语言id索引'
) ENGINE=OLAP 
PRIMARY KEY(`dt`, `site_id`, `book_id`)
COMMENT "翻译书籍产能费率综合统计表"
DISTRIBUTED BY HASH(`site_id`, `book_id`) BUCKETS 1 
PROPERTIES (
"replication_num" = "3",
"bloom_filter_columns" = "book_id",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);