CREATE VIEW `ads_bi_read_book_chapter_view` (`dt`, `site_id`, `book_id`, `chapter_id`, `product_id`, `corever`, `mt`, `ver`, `current_language`, `current_language2`, `reg_date`, `reg_days`, `reg_country`, `appver`, `sex`, `user_id`, `user_tp`, `is_new`, `etl_time`) AS SELECT `dws`.`dws_read_book_chapter_ed`.`dt`, `dws`.`dws_read_book_chapter_ed`.`site_id`, `dws`.`dws_read_book_chapter_ed`.`book_id`, `dws`.`dws_read_book_chapter_ed`.`chapter_id`, `dws`.`dws_read_book_chapter_ed`.`product_id`, `dws`.`dws_read_book_chapter_ed`.`corever`, `dws`.`dws_read_book_chapter_ed`.`mt`, `dws`.`dws_read_book_chapter_ed`.`ver`, `dws`.`dws_read_book_chapter_ed`.`current_language`, `dws`.`dws_read_book_chapter_ed`.`current_language2`, `dws`.`dws_read_book_chapter_ed`.`reg_date`, `dws`.`dws_read_book_chapter_ed`.`reg_days`, `dws`.`dws_read_book_chapter_ed`.`reg_country`, `dws`.`dws_read_book_chapter_ed`.`appver`, `dws`.`dws_read_book_chapter_ed`.`sex`, `dws`.`dws_read_book_chapter_ed`.`user_id`, 1 AS `user_tp`, CASE WHEN (`dws`.`dws_read_book_chapter_ed`.`reg_days` > 0) THEN 0 WHEN (`dws`.`dws_read_book_chapter_ed`.`reg_days` = 0) THEN 1 END AS `is_new`, `dws`.`dws_read_book_chapter_ed`.`etl_time`
FROM `dws`.`dws_read_book_chapter_ed`
WHERE `dws`.`dws_read_book_chapter_ed`.`dt` >= '2023-01-01' UNION ALL SELECT `dws`.`dws_read_book_chapter_ed`.`dt`, `dws`.`dws_read_book_chapter_ed`.`site_id`, `dws`.`dws_read_book_chapter_ed`.`book_id`, `dws`.`dws_read_book_chapter_ed`.`chapter_id`, `dws`.`dws_read_book_chapter_ed`.`product_id`, `dws`.`dws_read_book_chapter_ed`.`corever`, `dws`.`dws_read_book_chapter_ed`.`mt`, `dws`.`dws_read_book_chapter_ed`.`ver`, `dws`.`dws_read_book_chapter_ed`.`current_language`, `dws`.`dws_read_book_chapter_ed`.`current_language2`, `dws`.`dws_read_book_chapter_ed`.`reg_date`, `dws`.`dws_read_book_chapter_ed`.`reg_days`, `dws`.`dws_read_book_chapter_ed`.`reg_country`, `dws`.`dws_read_book_chapter_ed`.`appver`, `dws`.`dws_read_book_chapter_ed`.`sex`, `dws`.`dws_read_book_chapter_ed`.`user_id`, 2 AS `user_tp`, CASE WHEN (`dws`.`dws_read_book_chapter_ed`.`reg_days` > 0) THEN 0 WHEN (`dws`.`dws_read_book_chapter_ed`.`reg_days` = 0) THEN 1 END AS `is_new`, `dws`.`dws_read_book_chapter_ed`.`etl_time`
FROM `dws`.`dws_read_book_chapter_ed`
WHERE (`dws`.`dws_read_book_chapter_ed`.`dt` >= '2023-01-01') AND (`dws`.`dws_read_book_chapter_ed`.`reg_days` <= 30) UNION ALL SELECT `a`.`dt`, `a`.`site_id`, `a`.`book_id`, `a`.`chapter_id`, `a`.`product_id`, `a`.`corever`, `a`.`mt`, `a`.`ver`, `a`.`current_language`, `a`.`current_language2`, `a`.`reg_date`, `a`.`reg_days`, `a`.`reg_country`, `a`.`appver`, `a`.`sex`, ``.bitmap_agg(`a`.`user_id`) AS `user_id`, `a`.`user_tp`, `a`.`is_new`, `a`.`etl_time`
FROM (SELECT `a`.`dt`, `a`.`site_id`, `a`.`book_id`, `a`.`chapter_id`, `a`.`product_id`, `a`.`corever`, `a`.`mt`, `a`.`ver`, `a`.`current_language`, `a`.`current_language2`, `a`.`reg_date`, `a`.`reg_days`, `a`.`reg_country`, `a`.`appver`, `a`.`sex`, `t`.`UNNEST` AS `user_id`, 3 AS `user_tp`, CASE WHEN (`a`.`reg_days` > 0) THEN 0 WHEN (`a`.`reg_days` = 0) THEN 1 END AS `is_new`, `a`.`etl_time`
FROM (SELECT `dws`.`a`.`dt`, `dws`.`a`.`site_id`, `dws`.`a`.`book_id`, `dws`.`a`.`chapter_id`, `dws`.`a`.`product_id`, `dws`.`a`.`corever`, `dws`.`a`.`mt`, `dws`.`a`.`ver`, `dws`.`a`.`current_language`, `dws`.`a`.`current_language2`, `dws`.`a`.`reg_date`, `dws`.`a`.`reg_days`, `dws`.`a`.`reg_country`, `dws`.`a`.`appver`, `dws`.`a`.`sex`, bitmap_to_array(`dws`.`a`.`user_id`) AS `user_id`, 3 AS `user_tp`, CASE WHEN (`dws`.`a`.`reg_days` > 0) THEN 0 WHEN (`dws`.`a`.`reg_days` = 0) THEN 1 END AS `is_new`, `dws`.`a`.`etl_time`
FROM `dws`.`dws_read_book_chapter_ed` AS `a`
WHERE `dws`.`a`.`dt` >= '2023-01-01') `a` , LATERAL unnest(`a`.`user_id`) t(`unnest`) ) `a` INNER JOIN `dws`.`dws_read_90_first_all_read_mid1` AS `y` ON (((`a`.`dt` = `dws`.`y`.`dt`) AND (`a`.`site_id` = `dws`.`y`.`site_id`)) AND (`a`.`book_id` = `dws`.`y`.`book_id`)) AND (`a`.`user_id` = `dws`.`y`.`user_id`)
GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19;