CREATE TABLE `ads_srsv_bi_ad_optimizer_template_target_data_test` (
  `dt` date NOT NULL COMMENT "",
  `book_id` bigint(20) NOT NULL COMMENT "",
  `template_id` int(11) NOT NULL COMMENT "",
  `source2` varchar(255) NOT NULL COMMENT "",
  `project_code` int(11) NOT NULL COMMENT "",
  `core` int(11) NOT NULL COMMENT "",
  `product` varchar(255) NULL COMMENT "",
  `days` int(11) NULL COMMENT "",
  `weekdays` int(11) NULL COMMENT "",
  `book_code` varchar(255) NULL COMMENT "",
  `languageid` int(11) NULL COMMENT "",
  `current_language2` varchar(255) NULL COMMENT "",
  `template_name` varchar(255) NULL COMMENT "",
  `adset_num` int(11) NULL COMMENT "",
  `spend` decimal(10, 2) NULL COMMENT "",
  `d0_amt` decimal(10, 2) NULL COMMENT "",
  `std_amt` decimal(10, 2) NULL COMMENT "",
  `reg_num` int(11) NULL COMMENT "",
  `reg_num_all` decimal(10, 2) NULL COMMENT "",
  `reg_num_new` decimal(10, 2) NULL COMMENT "",
  `new_amt_rate` decimal(10, 2) NULL COMMENT "",
  `old_spend` decimal(10, 2) NULL COMMENT "",
  `old_d0_amt` decimal(10, 2) NULL COMMENT "",
  `old_std_amt` decimal(10, 2) NULL COMMENT "",
  `days_book` int(11) NULL COMMENT "",
  `regnum_new_7d` decimal(10, 2) NULL COMMENT "",
  `regnum_all_7d` decimal(10, 2) NULL COMMENT "",
  `spend_10d` decimal(10, 2) NULL COMMENT "",
  `adset_num_10d` decimal(10, 2) NULL COMMENT "",
  `days_10d` decimal(10, 2) NULL COMMENT "",
  `d0_amt_10d` decimal(10, 2) NULL COMMENT "",
  `std_amt_10d` decimal(10, 2) NULL COMMENT "",
  `d0_amt_all` decimal(10, 2) NULL COMMENT "",
  `std_amt_all` decimal(10, 2) NULL COMMENT "",
  `d0_amt_pow` decimal(10, 2) NULL COMMENT "",
  `std_amt_pow` decimal(10, 2) NULL COMMENT "",
  `d0_amt_pow_old` decimal(10, 2) NULL COMMENT "",
  `std_amt_pow_old` decimal(10, 2) NULL COMMENT "",
  `d0_amt_af` decimal(10, 2) NULL COMMENT "",
  `std_amt_af` decimal(10, 2) NULL COMMENT "",
  `code_stage` int(11) NULL COMMENT "",
  `code_lv` varchar(255) NULL COMMENT "",
  `test_status` int(11) NULL COMMENT "",
  `begin_date` date NULL COMMENT "",
  `end_date` date NULL COMMENT "",
  `off_begindate` date NULL COMMENT "",
  `off_enddate` date NULL COMMENT "",
  `lang` varchar(255) NULL COMMENT "",
  `lang_rate` int(11) NULL COMMENT "",
  `group_spend` int(11) NULL COMMENT "",
  `sunday_rate` decimal(10, 2) NULL COMMENT "",
  `friday_rate` decimal(10, 2) NULL COMMENT "",
  `base_rate` decimal(10, 2) NULL COMMENT "",
  `new_std` decimal(10, 2) NULL COMMENT "",
  `old_std` decimal(10, 2) NULL COMMENT "",
  `log_num` int(11) NULL COMMENT "",
  `log_num_median` decimal(10, 2) NULL COMMENT "",
  `exp_a` decimal(10, 2) NULL COMMENT "",
  `new_r0_rate` decimal(10, 2) NULL COMMENT "",
  `non_compliance_exp` decimal(10, 2) NULL COMMENT "",
  `spend_exp` decimal(10, 2) NULL COMMENT "",
  `weekdays_p` decimal(10, 2) NULL COMMENT "",
  `newamt_rate` decimal(10, 2) NULL COMMENT "",
  `R0_new` decimal(10, 2) NULL COMMENT "",
  `R0_old` decimal(10, 2) NULL COMMENT "",
  `R0_bf1` decimal(10, 2) NULL COMMENT "",
  `old_R0_bf1` decimal(10, 2) NULL COMMENT "",
  `growth_base` decimal(10, 2) NULL COMMENT "",
  `growth_exp` decimal(10, 2) NULL COMMENT "",
  `spend_rate` decimal(10, 2) NULL COMMENT "",
  `growth_rate` decimal(10, 2) NULL COMMENT "",
  `adsetnum_1` int(11) NULL COMMENT "",
  `adsetnum_2` int(11) NULL COMMENT "",
  `has_plan` int(11) NULL COMMENT "",
  `adsetnum_plan` int(11) NULL COMMENT "",
  `etl_tm` datetime NULL COMMENT "数据清洗时间"
) ENGINE=OLAP 
PRIMARY KEY(`dt`, `book_id`, `template_id`, `source2`, `project_code`, `core`)
COMMENT "模板维度基建上限"
DISTRIBUTED BY HASH(`dt`) BUCKETS 3 
PROPERTIES (
"replication_num" = "3",
"bloom_filter_columns" = "dt, core, template_id, project_code, book_id, source2",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);