CREATE TABLE `ads_adset_info` (
  `adset_id` varchar(500) NOT NULL COMMENT "",
  `product` varchar(500) NOT NULL COMMENT "",
  `core` int(11) NOT NULL COMMENT "",
  `mt` int(11) NOT NULL COMMENT "",
  `source_chl` varchar(500) NOT NULL COMMENT "",
  `account_tz` int(11) NOT NULL COMMENT "",
  `dt` date NOT NULL COMMENT "",
  `is_frt` int(11) NOT NULL COMMENT "",
  `days` varchar(500) NOT NULL COMMENT "",
  `hour2` int(11) NOT NULL COMMENT "",
  `language` varchar(500) NOT NULL COMMENT "",
  `code` varchar(500) NOT NULL COMMENT "",
  `book_id` int(11) NOT NULL COMMENT "",
  `d0_std` decimal(24, 4) NULL COMMENT "",
  `reg_num` int(11) NULL COMMENT "",
  `cost_amount` decimal(24, 2) NULL COMMENT "",
  `impressions` int(11) NULL COMMENT "",
  `LinkClicks` int(11) NULL COMMENT "",
  `hn_hour` int(11) NULL COMMENT "",
  `hn_cost` decimal(24, 2) NULL COMMENT "",
  `hn_impressions` int(11) NULL COMMENT "",
  `hn_LinkClicks` int(11) NULL COMMENT "",
  `hn_regnum` int(11) NULL COMMENT "",
  `hn_amount` decimal(24, 6) NULL COMMENT "",
  `hn_payers` int(11) NULL COMMENT "",
  `af_cost` decimal(24, 2) NULL COMMENT "",
  `af_regnum` int(11) NULL COMMENT "",
  `af_amount` decimal(24, 6) NULL COMMENT "",
  `af_payers` int(11) NULL COMMENT "",
  `d0_cost` decimal(24, 2) NULL COMMENT "",
  `d0_regnum` int(11) NULL COMMENT "",
  `d0_amount` decimal(24, 6) NULL COMMENT "",
  `d0_payers` int(11) NULL COMMENT "",
  `min_hour` int(11) NULL COMMENT "",
  `r0_bf1` decimal(24, 12) NULL COMMENT "",
  `d0_impressions` int(11) NULL COMMENT "",
  `d0_LinkClicks` int(11) NULL COMMENT "",
  `max_hour` int(11) NULL COMMENT "",
  `drt_dt` date NULL COMMENT "",
  `r0_af15` decimal(24, 12) NULL COMMENT "",
  `af15_cost` decimal(24, 2) NULL COMMENT "",
  `af15_days` int(11) NULL COMMENT "",
  `hn_cac` decimal(24, 8) NULL COMMENT "",
  `hn_r0` decimal(24, 12) NULL COMMENT "",
  `hn_ir` decimal(24, 17) NULL COMMENT "",
  `af_r0` decimal(24, 12) NULL COMMENT "",
  `d0_hours` int(11) NULL COMMENT "",
  `d0_r0` decimal(24, 12) NULL COMMENT "",
  `etl_time` datetime NULL COMMENT "处理时间"
) ENGINE=OLAP 
PRIMARY KEY(`adset_id`, `product`, `core`, `mt`, `source_chl`, `account_tz`, `dt`, `is_frt`, `days`, `hour2`, `language`, `code`, `book_id`)
DISTRIBUTED BY HASH(`adset_id`, `product`, `core`, `mt`, `source_chl`, `account_tz`, `dt`, `is_frt`, `days`, `hour2`, `language`, `code`, `book_id`) BUCKETS 30 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);