CREATE TABLE `ads_sr_ad_book_promotion_arpu` (
  `dt` date NOT NULL COMMENT "日期-活动时间",
  `product_id` int(11) NOT NULL COMMENT "产品id",
  `book_id` bigint(20) NOT NULL COMMENT "书籍id",
  `chl2` varchar(755) NOT NULL COMMENT "渠道值",
  `campaign` varchar(755) NOT NULL COMMENT "广告系列",
  `source_chl` varchar(755) NOT NULL COMMENT "媒体渠道值",
  `current_language2` int(11) NOT NULL COMMENT "投放语言",
  `mt` int(11) NULL COMMENT "平台（终端）",
  `core` int(11) NULL COMMENT "corever包体",
  `adcamp_id` varchar(755) NULL COMMENT "广告系列id",
  `active_unt` int(11) NULL DEFAULT "0" COMMENT "参与活动用户数",
  `D0_money_amt` int(11) NULL DEFAULT "0" COMMENT "D0阅币消耗",
  `D1_money_amt` int(11) NULL DEFAULT "0" COMMENT "D1阅币消耗",
  `D2_money_amt` int(11) NULL DEFAULT "0" COMMENT "D2阅币消耗",
  `D3_money_amt` int(11) NULL DEFAULT "0" COMMENT "D3阅币消耗",
  `D4_money_amt` int(11) NULL DEFAULT "0" COMMENT "D4阅币消耗",
  `D5_money_amt` int(11) NULL DEFAULT "0" COMMENT "D5阅币消耗",
  `D6_money_amt` int(11) NULL DEFAULT "0" COMMENT "D6阅币消耗",
  `D7_money_amt` int(11) NULL DEFAULT "0" COMMENT "D7阅币消耗",
  `D8_money_amt` int(11) NULL DEFAULT "0" COMMENT "D8阅币消耗",
  `D9_money_amt` int(11) NULL DEFAULT "0" COMMENT "D9阅币消耗",
  `D10_money_amt` int(11) NULL DEFAULT "0" COMMENT "D10阅币消耗",
  `D11_money_amt` int(11) NULL DEFAULT "0" COMMENT "D11阅币消耗",
  `D12_money_amt` int(11) NULL DEFAULT "0" COMMENT "D12阅币消耗",
  `D13_money_amt` int(11) NULL DEFAULT "0" COMMENT "D13阅币消耗",
  `D14_money_amt` int(11) NULL DEFAULT "0" COMMENT "D14阅币消耗",
  `D15_money_amt` int(11) NULL DEFAULT "0" COMMENT "D15阅币消耗",
  `D0_gift_amt` int(11) NULL DEFAULT "0" COMMENT "D0礼券消耗",
  `D1_gift_amt` int(11) NULL DEFAULT "0" COMMENT "D1礼券消耗",
  `D2_gift_amt` int(11) NULL DEFAULT "0" COMMENT "D2礼券消耗",
  `D3_gift_amt` int(11) NULL DEFAULT "0" COMMENT "D3礼券消耗",
  `D4_gift_amt` int(11) NULL DEFAULT "0" COMMENT "D4礼券消耗",
  `D5_gift_amt` int(11) NULL DEFAULT "0" COMMENT "D5礼券消耗",
  `D6_gift_amt` int(11) NULL DEFAULT "0" COMMENT "D6礼券消耗",
  `D7_gift_amt` int(11) NULL DEFAULT "0" COMMENT "D7礼券消耗",
  `D8_gift_amt` int(11) NULL DEFAULT "0" COMMENT "D8礼券消耗",
  `D9_gift_amt` int(11) NULL DEFAULT "0" COMMENT "D9礼券消耗",
  `D10_gift_amt` int(11) NULL DEFAULT "0" COMMENT "D10礼券消耗",
  `D11_gift_amt` int(11) NULL DEFAULT "0" COMMENT "D11礼券消耗",
  `D12_gift_amt` int(11) NULL DEFAULT "0" COMMENT "D12礼券消耗",
  `D13_gift_amt` int(11) NULL DEFAULT "0" COMMENT "D13礼券消耗",
  `D14_gift_amt` int(11) NULL DEFAULT "0" COMMENT "D14礼券消耗",
  `D15_gift_amt` int(11) NULL DEFAULT "0" COMMENT "D15礼券消耗",
  `etl_tm` datetime NOT NULL COMMENT "清洗时间"
) ENGINE=OLAP 
DUPLICATE KEY(`dt`, `product_id`)
COMMENT "海阅-记录在站外针对全量用户进行推书，书籍arpu数据，应用在ads后台"
DISTRIBUTED BY HASH(`dt`, `product_id`) BUCKETS 3 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"storage_medium" = "SSD",
"compression" = "ZSTD"
);