CREATE TABLE `ads_user_info_wide_a` (
  `dt` date NOT NULL COMMENT "统计日期",
  `product_id` int(11) NOT NULL COMMENT "产品id",
  `user_id` bigint(20) NOT NULL COMMENT "用户id",
  `account` varchar(65533) NULL COMMENT "账户id",
  `nick` varchar(65533) NULL COMMENT "昵称",
  `birthday` datetime NULL COMMENT "",
  `sex` int(11) NULL COMMENT "性别0未知 1男 2女 3保密",
  `reg_tm` datetime NULL COMMENT "用户的注册时间",
  `mt` int(11) NULL COMMENT "平台 0未知 1iphone 4安卓 9书城",
  `corever` int(11) NULL COMMENT "core",
  `app_ver` varchar(65533) NULL COMMENT "app版本",
  `ver` int(11) NULL COMMENT "客户端版本号",
  `current_language` int(11) NULL COMMENT "用户当前语言",
  `current_language2` int(11) NULL COMMENT "注册时语言",
  `reg_country` varchar(65533) NULL COMMENT "注册时国家，不会变化",
  `country` varchar(65533) NULL COMMENT "最近一次登录国家",
  `email` varchar(65533) NULL COMMENT "电子邮箱",
  `money` int(11) NULL COMMENT "当前剩余阅币",
  `gift_money` int(11) NULL COMMENT "当前剩余礼券",
  `email_bound_status` int(11) NULL COMMENT "是否绑定邮箱",
  `is_negative_user` int(11) NULL COMMENT "是否白嫖用户",
  `level_country` varchar(65533) NULL COMMENT "reg_country注册时国家等级",
  `user_type` varchar(100) NULL COMMENT "1IAA 2纯白嫖 3付费白嫖 4非白嫖",
  `points` int(11) NULL COMMENT "积分",
  `jifen` int(11) NULL COMMENT "积分余额",
  `ads_type` int(11) NULL COMMENT "用户广告标签adstype",
  `ads_quality` int(11) NULL COMMENT "用户广告质量标签",
  `first_book_id` bigint(20) NULL COMMENT "首次引流书籍",
  `last_book_id` bigint(20) NULL COMMENT "最新引流书籍",
  `last_source` varchar(100) NULL COMMENT "最新媒体值",
  `is_remarket` int(11) NULL COMMENT "是否再营销用户 1：再营销用户  0 非再营销用户",
  `install_date` datetime NULL COMMENT "最新安装激活时间",
  `remarketing_time_days` int(11) NULL COMMENT "归因天数",
  `con_amount` decimal(20, 4) NULL COMMENT "累计消耗",
  `first_tm` datetime NULL COMMENT "首次消费时间",
  `last_tm` datetime NULL COMMENT "最近一次消费时间",
  `consume_cnt` int(11) NULL COMMENT "消费次数",
  `con_chapter_nums` int(11) NULL COMMENT "消费章节数",
  `total_bat_ulk_cnt` int(11) NULL COMMENT "累计批量解锁次数",
  `total_fix_ulk_cnt` int(11) NULL COMMENT "累计一口价解锁次数",
  `sup_ulk_cnt` int(11) NULL COMMENT "超点解锁次数",
  `sup_ulk_sum` decimal(14, 4) NULL COMMENT "超点解锁金额",
  `total_bat_ulk_money` decimal(14, 4) NULL COMMENT "批量解锁阅币金额",
  `start_sup_ulk_chp_cnt` int(11) NULL COMMENT "首次超点解锁章节数（不分货币类型）",
  `start_sup_ulk_chp_money` decimal(14, 4) NULL COMMENT "首次超点解锁金额",
  `start_bat_ulk_gear` int(11) NULL COMMENT "首次批量解锁档位（不分阅币礼券赠送币）：例如用户一次性批量解锁了10章 档位即为10",
  `start_bat_ulk_chp_cnt` int(11) NULL COMMENT "首次批量解锁章节数（不分阅币礼券赠送币）",
  `start_bat_ulk_money` decimal(14, 4) NULL COMMENT "首次批量解锁阅币金额(只包含阅币的)",
  `start_bat_ulk_giftmoney` decimal(14, 4) NULL COMMENT "首次批量解锁礼券金额(只包含礼券的)",
  `total_read_bookids` bigint(20) NULL COMMENT "累计阅读书本数",
  `total_read_chp_ids` bigint(20) NULL COMMENT "累计阅读章节章节数",
  `total_read_days` int(11) NULL COMMENT "累计阅读天数",
  `new_chp_book_cnt` int(11) NULL COMMENT "阅读到了最新章节的书本数",
  `total_read_tm` bigint(20) NULL COMMENT "累计阅读时长",
  `first_subscribe` decimal(18, 2) NULL COMMENT "首次订阅金额",
  `first_subscribe_type` varchar(65533) NULL COMMENT "首次订阅类型",
  `first_subscribe_tm` datetime NULL COMMENT "首次订阅时间",
  `last_subscribe` decimal(18, 2) NULL COMMENT "最后订阅金额",
  `last_subscribe_type` varchar(65533) NULL COMMENT "最后订阅类型",
  `last_subscribe_tm` datetime NULL COMMENT "最后订阅时间",
  `subscribe_cnt` int(11) NULL COMMENT "续订次数",
  `mul_subscribe` int(11) NULL COMMENT "有无多项订阅",
  `has_subscribe` int(11) NULL COMMENT "历史有无订阅",
  `first_recharge` decimal(18, 2) NULL COMMENT "首次充值金额",
  `first_recharge_tm` datetime NULL COMMENT "首次充值时间",
  `total_recharge` decimal(18, 2) NULL COMMENT "累计充值金额",
  `recharge_cnt` int(11) NULL COMMENT "累计充值次数",
  `recharge_avg` double NULL COMMENT "平均充值金额",
  `recharge_max` decimal(18, 2) NULL COMMENT "最大充值金额",
  `month_recharge_max` decimal(18, 2) NULL COMMENT "近一个月最大充值金额",
  `last_recharge` decimal(18, 2) NULL COMMENT "最后充值金额",
  `last_recharge_tm` datetime NULL COMMENT "最近充值时间",
  `charge_mode` decimal(18, 2) NULL COMMENT "充值众数",
  `first_login_tm` datetime NULL COMMENT "首次登录时间",
  `last_login_tm` datetime NULL COMMENT "上次登录时间",
  `new_login_tm` datetime NULL COMMENT "最新登录时间",
  `login_days` int(11) NULL COMMENT "登录天数",
  `login_tms` int(11) NULL COMMENT "登录次数",
  `etl_tm` datetime NULL COMMENT "清洗时间"
) ENGINE=OLAP 
PRIMARY KEY(`dt`, `product_id`, `user_id`)
COMMENT "用户各业务域累计型指标宽表，按统计时间分区，只保留7天的数据"
PARTITION BY RANGE(`dt`)
(PARTITION p20260507 VALUES [("2026-05-07"), ("2026-05-08")),
PARTITION p20260508 VALUES [("2026-05-08"), ("2026-05-09")),
PARTITION p20260509 VALUES [("2026-05-09"), ("2026-05-10")),
PARTITION p20260510 VALUES [("2026-05-10"), ("2026-05-11")),
PARTITION p20260511 VALUES [("2026-05-11"), ("2026-05-12")),
PARTITION p20260512 VALUES [("2026-05-12"), ("2026-05-13")),
PARTITION p20260513 VALUES [("2026-05-13"), ("2026-05-14")),
PARTITION p20260514 VALUES [("2026-05-14"), ("2026-05-15")),
PARTITION p20260515 VALUES [("2026-05-15"), ("2026-05-16")),
PARTITION p20260516 VALUES [("2026-05-16"), ("2026-05-17")),
PARTITION p20260517 VALUES [("2026-05-17"), ("2026-05-18")))
DISTRIBUTED BY HASH(`dt`, `product_id`, `user_id`) BUCKETS 25 
PROPERTIES (
"replication_num" = "2",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "DAY",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.start" = "-7",
"dynamic_partition.end" = "3",
"dynamic_partition.prefix" = "p",
"dynamic_partition.buckets" = "40",
"dynamic_partition.history_partition_num" = "0",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);