CREATE TABLE `ads_srsv_material_rating_probability_new` (
  `dt` date NOT NULL COMMENT "更新日期，按西五区更新数据",
  `project_code` int(11) NOT NULL COMMENT "",
  `asset_guid` varchar(65533) NOT NULL COMMENT "",
  `source_chl_type` int(11) NOT NULL COMMENT "",
  `book_id` bigint(20) NOT NULL COMMENT "书籍id",
  `material_name` varchar(65533) NULL COMMENT "素材名称",
  `language_name` varchar(65533) NULL COMMENT "语言",
  `code` varchar(65533) NULL COMMENT "短剧code",
  `language_asset` varchar(255) NULL COMMENT "素材语言或语言分类",
  `asset_type` varchar(255) NULL COMMENT "是否定制",
  `code_type` varchar(255) NULL COMMENT "素材分类",
  `material_type` varchar(255) NULL COMMENT "素材类型",
  `bm_compelete_time` datetime NULL COMMENT "",
  `date_key` date NULL COMMENT "投放日期",
  `grade_date` date NULL COMMENT "满足评级条件的首日:花费>50的日期，null说明没有",
  `first_date` date NULL COMMENT "首次投放日期",
  `days` int(11) NULL COMMENT "满足评级条件的第N天，0~3",
  `level` int(11) NULL COMMENT "评级类型，1=日花费大于50的评级样本，2=不满足日花费大于50  但累计花费大于150的评级样本，99=无评级",
  `is_old_asset` int(11) NULL COMMENT "",
  `spend_dt_sum` decimal(16, 6) NULL COMMENT "评级首日到截止日期的累计花费",
  `spend_sum` decimal(16, 6) NULL COMMENT "截止当前累计花费",
  `impressions_sum` int(11) NULL COMMENT "截止当前累计展示量",
  `clicks_sum` int(11) NULL COMMENT "截止当前累计点击互动",
  `link_clicks_sum` int(11) NULL COMMENT "截止当前累计链接点击",
  `installs_sum` int(11) NULL COMMENT "截止当前累计激活",
  `amount_sum` decimal(16, 6) NULL COMMENT "",
  `grade_score_sum_raw` decimal(16, 6) NULL COMMENT "",
  `grade_score_sum2` decimal(16, 6) NULL COMMENT "",
  `odds` decimal(16, 6) NULL COMMENT "",
  `need_mai` int(11) NULL COMMENT "",
  `odds_aeo` decimal(16, 6) NULL COMMENT "",
  `grade_date_mai` date NULL COMMENT "",
  `first_date_mai` date NULL COMMENT "",
  `level_mai` int(11) NULL COMMENT "",
  `odds_mai` decimal(16, 6) NULL COMMENT "",
  `spend_dt_sum_mai` decimal(16, 6) NULL COMMENT "",
  `spend_sum_mai` decimal(16, 6) NULL COMMENT "",
  `impressions_sum_mai` int(11) NULL COMMENT "",
  `clicks_sum_mai` int(11) NULL COMMENT "",
  `link_clicks_sum_mai` int(11) NULL COMMENT "",
  `installs_sum_mai` int(11) NULL COMMENT "",
  `amount_sum_mai` decimal(16, 6) NULL COMMENT "",
  `grade_score_sum_raw_mai` decimal(16, 6) NULL COMMENT "",
  `channel` varchar(2000) NULL COMMENT "频道",
  `new_cid_name` varchar(2000) NULL COMMENT "分类",
  `is_general_score` int(11) NULL COMMENT "",
  `etl_tm` datetime NULL COMMENT "清洗时间"
) ENGINE=OLAP 
PRIMARY KEY(`dt`, `project_code`, `asset_guid`, `source_chl_type`, `book_id`)
COMMENT "海阅海剧-素材评分和概率"
DISTRIBUTED BY HASH(`asset_guid`) BUCKETS 10 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"storage_medium" = "SSD",
"compression" = "ZSTD"
);