DROP TABLE IF EXISTS ads.ads_srsv_bi_ad_optimizer_template_target_data_pre_1;
CREATE TABLE ads.ads_srsv_bi_ad_optimizer_template_target_data_pre_1 (
     source2           VARCHAR(255)   NOT NULL COMMENT '媒体'
    ,project_code      INT(11)        NOT NULL COMMENT '产品代号'
    ,core              INT(11)        NOT NULL COMMENT ''
    ,dt                DATE           NOT NULL COMMENT '日期'
    ,book_id           BIGINT(20)     NOT NULL COMMENT '作品id'
    ,template_id       INT(11)        NOT NULL COMMENT '模板id'
    ,product           VARCHAR(255)            COMMENT ''
    ,days              INT(11)                 COMMENT ''
    ,weekdays          INT(11)                 COMMENT ''
    ,book_code         VARCHAR(255)            COMMENT ''
    ,languageid        INT(11)                 COMMENT ''
    ,current_language2 VARCHAR(255)            COMMENT ''
    ,template_name     VARCHAR(255)            COMMENT ''
    ,adset_num         INT(11)                 COMMENT ''
    ,spend             DECIMAL(10, 2)          COMMENT ''
    ,d0_amt            DECIMAL(10, 2)          COMMENT ''
    ,std_amt           DECIMAL(10, 2)          COMMENT ''
    ,reg_num           INT(11)                 COMMENT ''
    ,reg_num_all       DECIMAL(10, 2)          COMMENT ''
    ,reg_num_new       DECIMAL(10, 2)          COMMENT ''
    ,new_amt_rate      DECIMAL(10, 2)          COMMENT ''
    ,old_spend         DECIMAL(10, 2)          COMMENT ''
    ,old_d0_amt        DECIMAL(10, 2)          COMMENT ''
    ,old_std_amt       DECIMAL(10, 2)          COMMENT ''
    ,days_book         INT(11)                 COMMENT ''
    ,regnum_new_7d     DECIMAL(10, 2)          COMMENT ''
    ,regnum_all_7d     DECIMAL(10, 2)          COMMENT ''
    ,spend_10d         DECIMAL(10, 2)          COMMENT ''
    ,adset_num_10d     DECIMAL(10, 2)          COMMENT ''
    ,days_10d          DECIMAL(10, 2)          COMMENT ''
    ,d0_amt_10d        DECIMAL(10, 2)          COMMENT ''
    ,std_amt_10d       DECIMAL(10, 2)          COMMENT ''
    ,d0_amt_all        DECIMAL(10, 2)          COMMENT ''
    ,std_amt_all       DECIMAL(10, 2)          COMMENT ''
    ,d0_amt_pow        DECIMAL(10, 2)          COMMENT ''
    ,std_amt_pow       DECIMAL(10, 2)          COMMENT ''
    ,d0_amt_pow_old    DECIMAL(10, 2)          COMMENT ''
    ,std_amt_pow_old   DECIMAL(10, 2)          COMMENT ''
    ,d0_amt_af         DECIMAL(10, 2)          COMMENT ''
    ,std_amt_af        DECIMAL(10, 2)          COMMENT ''
    ,code_stage        INT(11)                 COMMENT ''
    ,code_lv           VARCHAR(255)            COMMENT ''
    ,test_status       INT(11)                 COMMENT ''
    ,begin_date        DATE                    COMMENT ''
    ,end_date          DATE                    COMMENT ''
    ,off_begindate     DATE                    COMMENT ''
    ,off_enddate       DATE                    COMMENT ''
    ,opt_eid           VARCHAR(200)            COMMENT '优化师工号'
    ,opt_name          VARCHAR(60)             COMMENT '优化师姓名'
    ,auto_ce_type_cd   INT(11)                 COMMENT '自动创编类型编码'
    ,auto_ce_type_name VARCHAR(100)            COMMENT '自动创编类型名称'
    ,is_fst_infra      INT(11)                 COMMENT '是否首日基建'
    ,init_infra_num    INT(11)                 COMMENT '初始基建条数'
    ,is_new_group_ce   INT(11)                 COMMENT '是否有创编新组'
    ,spend1            DECIMAL(12, 2)          COMMENT ''
    ,d0_amt1           DECIMAL(12, 2)          COMMENT ''
    ,std_amt1          DECIMAL(12, 2)          COMMENT ''
    ,d0_amt_pow1       DECIMAL(12, 2)          COMMENT ''
    ,std_amt_pow1      DECIMAL(12, 2)          COMMENT ''
    ,etl_tm            DATETIME                COMMENT '数据清洗时间'
)
PRIMARY KEY(source2, project_code, core, dt, book_id, template_id)
COMMENT '模板维度基建上限前置表-底表一'
DISTRIBUTED BY HASH(dt) BUCKETS 3
PROPERTIES (
    "replication_num" = "3",
    "bloom_filter_columns" = "dt, core, project_code, template_id, source2, book_id",
    "in_memory" = "false",
    "enable_persistent_index" = "true",
    "replicated_storage" = "true",
    "compression" = "LZ4"
)
;