CREATE TABLE `ads_srsv_bi_ad_optimizer_target_data` (
  `dt` datetime NULL COMMENT "统计日期，广告账户时区",
  `product` varchar(50) NULL COMMENT "项目：海剧，海阅",
  `source2` varchar(255) NULL COMMENT "媒体平台：meta，tiktok",
  `code_id` varchar(500) NULL COMMENT "书籍id",
  `code_stage` varchar(255) NULL COMMENT "投放阶段",
  `code_lv` varchar(255) NULL COMMENT "阶段等级",
  `test_status` varchar(255) NULL COMMENT "投放状态，1=投放中，0=停投",
  `begin_date` datetime NULL COMMENT "投放阶段开始时间",
  `end_date` datetime NULL COMMENT "投放阶段结束时间",
  `book_code` varchar(255) NULL COMMENT "书籍代号",
  `languageid` int(11) NULL COMMENT "投放语言",
  `weekdays` int(11) NULL COMMENT "星期",
  `current_language` varchar(255) NULL COMMENT "语言缩写",
  `nick_name` varchar(255) NULL COMMENT "优化师名称",
  `ad_optimizer_uid` varchar(255) NULL COMMENT "优化师id",
  `ad_optimizer_group` varchar(255) NULL COMMENT "优化师分组",
  `adset_num` int(11) NULL COMMENT "统计日期的新广告组数",
  `spend` decimal(18, 4) NULL COMMENT "新广告组的花费",
  `d0_amt` decimal(18, 4) NULL COMMENT "D0收入",
  `std_amt` decimal(18, 4) NULL COMMENT "D0收入目标",
  `reg_num` int(11) NULL COMMENT "注册数",
  `reg_num_all` decimal(18, 4) NULL COMMENT "注册D0收入，est时区",
  `reg_num_new` decimal(18, 4) NULL COMMENT "新注册D0收入，est时区",
  `regnum_new_7d` decimal(18, 4) NULL COMMENT "近7天注册D0收入，est时区",
  `regnum_all_7d` decimal(18, 4) NULL COMMENT "近7天新注册D0收入，est时区",
  `spend_10d` decimal(18, 4) NULL COMMENT "近10天花费",
  `adset_num_10d` int(11) NULL COMMENT "近10天新建广告组数",
  `days_10d` int(11) NULL COMMENT "近10天投放天数",
  `d0_amt_10d` decimal(18, 4) NULL COMMENT "近10天新广告组D0收入",
  `std_amt_10d` decimal(18, 4) NULL COMMENT "近10天新广告组D0收入目标",
  `d0_amt_all` decimal(18, 4) NULL COMMENT "历史新老广告组D0收入",
  `std_amt_all` decimal(18, 4) NULL COMMENT "历史新老广告组D0收入目标",
  `d0_amt_pow` decimal(18, 4) NULL COMMENT "近3日新组D0收入",
  `std_amt_pow` decimal(18, 4) NULL COMMENT "近3日新组D0收入目标",
  `d0_amt_pow_old` decimal(18, 4) NULL COMMENT "近3日老组D0收入",
  `std_amt_pow_old` decimal(18, 4) NULL COMMENT "近3日老组D0收入目标",
  `frt_nickname` varchar(255) NULL COMMENT "首个测试优化师",
  `nick_name_max` varchar(255) NULL COMMENT "截止当前花费最大的优化师",
  `frt_group` varchar(255) NULL COMMENT "首个测试优化师组",
  `is_frt_group` varchar(255) NULL COMMENT "专属组",
  `off_begindate` datetime NULL COMMENT "优化师被淘汰开始时间",
  `off_enddate` datetime NULL COMMENT "优化师被淘汰结束时间",
  `etl_tm` datetime NULL COMMENT "清洗时间"
) ENGINE=OLAP 
DUPLICATE KEY(`dt`, `product`)
COMMENT "海阅海剧 广告基建，优化师每日基建达标情况2"
DISTRIBUTED BY HASH(`dt`, `product`) BUCKETS 3 
PROPERTIES (
"replication_num" = "2",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"storage_medium" = "SSD",
"compression" = "ZSTD"
);