CREATE TABLE `ads_offline_label_stat` (
  `product_id` int(11) NOT NULL COMMENT "产品id",
  `user_id` bigint(20) NOT NULL COMMENT "用户ID",
  `nick_name` varchar(65533) NULL COMMENT "昵称",
  `sex` varchar(65533) NULL COMMENT "性别",
  `age` int(11) NULL COMMENT "年龄",
  `nation` varchar(65533) NULL COMMENT "国家",
  `province` varchar(65533) NULL COMMENT "省份",
  `city` varchar(65533) NULL COMMENT "城市",
  `group_hash` bigint(20) NOT NULL COMMENT "productid和userid拼接后的分组哈希",
  `group_id_1` int(11) NOT NULL COMMENT "分组取模1",
  `group_id_2` int(11) NOT NULL COMMENT "分组取模2",
  `group_id_3` int(11) NOT NULL COMMENT "分组取模3",
  `group_id_4` int(11) NOT NULL COMMENT "分组取模4",
  `server_version` int(11) NULL COMMENT "服务器版本",
  `continous_sign_days` int(11) NULL COMMENT "连续签到天数",
  `reg_nation` varchar(65533) NULL COMMENT "国家",
  `reg_province` varchar(65533) NULL COMMENT "省份",
  `reg_city` varchar(65533) NULL COMMENT "城市",
  `reg_time` datetime NULL COMMENT "注册时间",
  `reg_language` int(11) NULL COMMENT "注册语言",
  `cur_language` int(11) NULL COMMENT "当前语言",
  `coin_cnt` int(11) NULL COMMENT "阅币数",
  `certificate_cnt` int(11) NULL COMMENT "礼券数",
  `medal_cnt` int(11) NULL COMMENT "勋章数",
  `register_day` int(11) NULL COMMENT "注册天数",
  `is_new_user` int(11) NULL COMMENT "是否新用户(1是0否)",
  `recharged` int(11) NULL COMMENT "是否充值(1是0否)",
  `is_nopay` int(11) NULL COMMENT "是否白嫖(1是0否)",
  `is_iaa` int(11) NULL COMMENT "是否IAA(1是0否)",
  `is_invite` int(11) NULL COMMENT "是否邀请(1是0否)",
  `medal_expire_time` datetime NULL COMMENT "勋章最早过期时间",
  `last_welfare_purcharse_time` datetime NULL COMMENT "上次购买福利包时间",
  `last_plus_purcharse_time` datetime NULL COMMENT "上次购买plus福利包时间",
  `welfare_expire_time` datetime NULL COMMENT "福利包到期时间",
  `plus_expire_time` datetime NULL COMMENT "plus福利包到期时间",
  `highest_recharge` decimal(19, 4) NULL COMMENT "最高充值档位",
  `auto_change_tag` decimal(20, 4) NULL COMMENT "每日积分自动兑换礼券标记",
  `ad_tag` varchar(65533) NULL COMMENT "广告标签",
  `ad_quality` int(11) NULL COMMENT "广告质量",
  `imei` varchar(65533) NULL COMMENT "imei",
  `imes` varchar(65533) NULL COMMENT "imes",
  `guid` varchar(65533) NULL COMMENT "guid",
  `mac` varchar(65533) NULL COMMENT "mac",
  `model` varchar(65533) NULL COMMENT "机型",
  `manufacturer` varchar(65533) NULL COMMENT "厂商",
  `price_level` varchar(65533) NULL COMMENT "价格层次",
  `screen_width` int(11) NULL COMMENT "分辨率-宽",
  `screen_height` int(11) NULL COMMENT "分辨率-高",
  `os_type` varchar(65533) NULL COMMENT "操作系统类型",
  `os_verison` varchar(65533) NULL COMMENT "操作系统版本",
  `app_id` int(11) NULL COMMENT "APP版本",
  `first_login_time` datetime NULL COMMENT "首次登录时间",
  `last_login_time` datetime NULL COMMENT "上次登录时间",
  `new_login_time` datetime NULL COMMENT "最新登录时间",
  `first_login_ip` varchar(65533) NULL COMMENT "首次登录ip",
  `last_login_ip` varchar(65533) NULL COMMENT "上次登录ip",
  `new_login_ip` varchar(65533) NULL COMMENT "最新登录ip",
  `first_login_location` varchar(65533) NULL COMMENT "首次登录地",
  `last_login_location` varchar(65533) NULL COMMENT "上一次登录地",
  `new_login_location` varchar(65533) NULL COMMENT "最新登录地",
  `remain_day` int(11) NULL COMMENT "留存天数(登录留存天数)",
  `login_days` int(11) NULL COMMENT "登录天数",
  `login_times` bigint(20) NULL COMMENT "登录次数",
  `user_login_type` varchar(65533) NULL COMMENT "用户活跃类型",
  `start_read_chapters` bigint(20) NULL COMMENT "首次阅读章节数",
  `start_read_time` bigint(20) NULL COMMENT "首次阅读时长",
  `start_day_read_chapters` bigint(20) NULL COMMENT "首天阅读章节数",
  `start_day_read_time` bigint(20) NULL COMMENT "首天阅读时长",
  `total_read_chp` bigint(20) NULL COMMENT "累计阅读章节数",
  `total_read_time` bigint(20) NULL COMMENT "累计阅读时长",
  `total_read_bookid` array<bigint(20)> NULL COMMENT "累计阅读过的数据id",
  `total_read_books` bigint(20) NULL COMMENT "累计阅读数本书",
  `more_onem_total_read_bookid` array<bigint(20)> NULL COMMENT "累计阅读大于1分钟的书籍id",
  `more_onem_total_read_books` bigint(20) NULL COMMENT "累计阅读大于1分钟的数本书",
  `total_read_days` bigint(20) NULL COMMENT "累计阅读天数",
  `new_chp_book_cnt` bigint(20) NULL COMMENT "阅读到最新章节的书本数",
  `new_chp_bookid_chpid` array<varchar(65533)> NULL COMMENT "阅读的最新章节",
  `read_time_da_avg` decimal(15, 2) NULL COMMENT "日均阅读时长",
  `start_subscribe` int(11) NULL COMMENT "首次订阅金额",
  `start_subscribe_type` varchar(65533) NULL COMMENT "首次订阅类型",
  `start_subscribe_time` datetime NULL COMMENT "首次订阅时间",
  `last_subscribe` int(11) NULL COMMENT "最后订阅金额",
  `last_subscribe_type` varchar(65533) NULL COMMENT "最后订阅类型",
  `last_subscribe_time` datetime NULL COMMENT "最后订阅时间",
  `is_month_card` int(11) NULL COMMENT "是否月卡生效用户(1是0否)",
  `is_subscribeing` int(11) NULL COMMENT "有无订阅(还在订阅期内,1有0无)",
  `subscribe_cnt` int(11) NULL COMMENT "续订次数",
  `shopitems` array<varchar(65533)> NULL COMMENT "订购类型",
  `mul_subscribe` int(11) NULL COMMENT "有无多项订阅",
  `his_subscribe` int(11) NULL COMMENT "历史有无订阅",
  `first_recharge` int(11) NULL COMMENT "首次充值金额",
  `first_recharge_time` datetime NULL COMMENT "首次充值时间",
  `total_recharge` int(11) NULL COMMENT "累计充值金额",
  `recharge_cnt` int(11) NULL COMMENT "累计充值次数",
  `recharge_avg` double NULL COMMENT "平均充值金额",
  `recharge_max` int(11) NULL COMMENT "最大充值金额",
  `month_recharge_max` int(11) NULL COMMENT "近一个月最大充值金额",
  `last_recharge` int(11) NULL COMMENT "最后充值金额",
  `last_recharge_time` datetime NULL COMMENT "最近充值时间",
  `start_bat_ulk_gear` varchar(65533) NULL COMMENT "首次批量解锁档位",
  `start_bat_ulk_chp_cnt` int(11) NULL COMMENT "首次批量解锁章节数",
  `total_bat_ulk_cnt` int(11) NULL COMMENT "累计批量解锁次数",
  `total_fix_ulk_cnt` int(11) NULL COMMENT "累计一口价解锁次数",
  `start_sup_ulk_chp_cnt` int(11) NULL COMMENT "首次超点解锁章数",
  `sup_ulk_cnt` int(11) NULL COMMENT "超点解锁次数",
  `sup_ulk_sum` decimal(16, 2) NULL COMMENT "超点解锁消费金额",
  `coin_consumption` decimal(18, 2) NULL COMMENT "阅币消费金额",
  `certificate_consumption` decimal(18, 2) NULL COMMENT "礼券消费金额",
  `purcharse_cnt` int(11) NULL COMMENT "累计消费次数",
  `last_purcharse_time` datetime NULL COMMENT "最近消费时间",
  `total_consumption` int(11) NULL COMMENT "消费章节数",
  `recency` varchar(65533) NULL COMMENT "Recency",
  `frequency` varchar(65533) NULL COMMENT "Frequency",
  `monetary` varchar(65533) NULL COMMENT "Monetary",
  `r_score` varchar(65533) NULL COMMENT "R_Score",
  `f_score` varchar(65533) NULL COMMENT "F_Score",
  `m_score` varchar(65533) NULL COMMENT "M_Score",
  `rfm_customer_tag` varchar(65533) NULL COMMENT "客户标签",
  `rfm_value_tag` varchar(65533) NULL COMMENT "价值标签",
  `rfm_vocational_tag` varchar(65533) NULL COMMENT "业务标签",
  `cac` double NULL COMMENT "CAC 获客成本",
  `pbp` varchar(65533) NULL COMMENT "PBP 回报周期",
  `ltv1` double NULL COMMENT "LTV1",
  `ltv2` double NULL COMMENT "LTV2",
  `ltv3` double NULL COMMENT "LTV3",
  `ltv4` double NULL COMMENT "LTV4",
  `ltv5` double NULL COMMENT "LTV5",
  `ltv6` double NULL COMMENT "LTV6",
  `ltv7` double NULL COMMENT "LTV7",
  `ltv15` double NULL COMMENT "LTV15",
  `ltv30` double NULL COMMENT "LTV30",
  `ltv45` double NULL COMMENT "LTV45",
  `ltv60` double NULL COMMENT "LTV60",
  `ltv90` double NULL COMMENT "LTV90",
  `recent_frequency_1d` double NULL COMMENT "最近一天消费的次数",
  `recent_frequency_2d` double NULL COMMENT "最近两天消费的次数",
  `recent_frequency_3d` double NULL COMMENT "最近三天消费的次数",
  `recent_frequency_4d` double NULL COMMENT "最近四天消费的次数",
  `recent_frequency_5d` double NULL COMMENT "最近五天消费的次数",
  `recent_frequency_6d` double NULL COMMENT "最近六天消费的次数",
  `recent_frequency_7d` double NULL COMMENT "最近七天消费的次数",
  `recent_frequency_15d` double NULL COMMENT "最近十五天消费的次数",
  `recent_frequency_30d` double NULL COMMENT "最近三十消费的次数",
  `recent_frequency_60d` double NULL COMMENT "最近六十天消费的次数",
  `recent_frequency_90d` double NULL COMMENT "最近九十天消费的次数",
  `recent_monetary_1d` double NULL COMMENT "最近一天消费的金额",
  `recent_monetary_2d` double NULL COMMENT "最近两天消费的金额",
  `recent_monetary_3d` double NULL COMMENT "最近三天消费的金额",
  `recent_monetary_4d` double NULL COMMENT "最近四天消费的金额",
  `recent_monetary_5d` double NULL COMMENT "最近五天消费的金额",
  `recent_monetary_6d` double NULL COMMENT "最近六天消费的金额",
  `recent_monetary_7d` double NULL COMMENT "最近七天消费的金额",
  `recent_monetary_15d` double NULL COMMENT "最近十五天消费的金额",
  `recent_monetary_30d` double NULL COMMENT "最近三十消费的金额",
  `recent_monetary_60d` double NULL COMMENT "最近六十天消费的金额",
  `recent_monetary_90d` double NULL COMMENT "最近九十天消费的金额",
  `mt` int(11) NULL COMMENT "终端",
  `corever` int(11) NULL COMMENT "core",
  `currentlanguage2` int(11) NULL COMMENT "注册时的语言",
  `country` varchar(65533) NULL COMMENT "国家",
  `country_level` varchar(65533) NULL COMMENT "国家等级",
  `first_book` bigint(20) NULL COMMENT "首次引流书籍",
  `last_book` bigint(20) NULL COMMENT "最新引流书籍",
  `first_adid` varchar(65533) NULL COMMENT "首次引流广告id",
  `last_adid` varchar(65533) NULL COMMENT "最新一次引流广告id",
  `dt` date NULL COMMENT "分区(日)",
  `account` varchar(100) NULL COMMENT "用户账号",
  `last_active_dt` varchar(65533) NULL COMMENT "最新活跃日期",
  `user_ad_source` int(11) NULL COMMENT "广告投流用户：0：正常用户，1：vip投流用户",
  `cancel_shop_item_type` varchar(100) NULL COMMENT "最后一次取消订阅类型",
  `cancel_subscription_time` datetime NULL COMMENT "最后一次取消订阅时间",
  `vip_expire_time` date NULL COMMENT "vip到期时间",
  `svip_expire_time` date NULL COMMENT "svip到期时间",
  `sign_expire_time` date NULL COMMENT "签到到期时间"
) ENGINE=OLAP 
DUPLICATE KEY(`product_id`)
COMMENT "标签数据宽表"
PARTITION BY RANGE(`dt`)
(PARTITION p20260507 VALUES [("2026-05-07"), ("2026-05-08")),
PARTITION p20260508 VALUES [("2026-05-08"), ("2026-05-09")),
PARTITION p20260509 VALUES [("2026-05-09"), ("2026-05-10")),
PARTITION p20260510 VALUES [("2026-05-10"), ("2026-05-11")),
PARTITION p20260511 VALUES [("2026-05-11"), ("2026-05-12")),
PARTITION p20260512 VALUES [("2026-05-12"), ("2026-05-13")),
PARTITION p20260513 VALUES [("2026-05-13"), ("2026-05-14")),
PARTITION p20260514 VALUES [("2026-05-14"), ("2026-05-15")),
PARTITION p20260515 VALUES [("2026-05-15"), ("2026-05-16")),
PARTITION p20260516 VALUES [("2026-05-16"), ("2026-05-17")),
PARTITION p20260517 VALUES [("2026-05-17"), ("2026-05-18")))
DISTRIBUTED BY HASH(`group_hash`) BUCKETS 90 
PROPERTIES (
"replication_num" = "2",
"bloom_filter_columns" = "recharged, country, last_recharge, first_recharge, is_subscribeing, country_level, last_book, corever, start_subscribe, month_recharge_max, cur_language, is_nopay, product_id, his_subscribe, is_iaa, start_bat_ulk_gear, is_invite, mt, mul_subscribe, is_month_card, recharge_max, user_login_type, currentlanguage2, is_new_user, first_book",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "DAY",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.start" = "-7",
"dynamic_partition.end" = "3",
"dynamic_partition.prefix" = "p",
"dynamic_partition.buckets" = "90",
"dynamic_partition.history_partition_num" = "0",
"in_memory" = "true",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);