drop table if exists ads.ads_ab_exp_core_index;
create table ads.ads_ab_exp_core_index (
     experimentId                    bigint          not null comment "实验id"
    ,experimentGroupId               bigint          not null comment "实验组id"
    ,dt                              date            not null comment "日期分区"
    ,projectId                       int             not null comment "项目id"
    ,trackficVersion                 varchar(500)    not null comment "流量版本"
    ,windowNum                       int             not null comment "窗口大小(过去n天)"
    ,experimentName                  varchar(500)             comment "实验名称"
    ,experimentGroupName             varchar(500)             comment "实验组名称"
    ,experimentType                  int             not null comment "实验类型(1对照组、2实验组)"
    ,totalNumber                     bigint                   comment "实验的总的样本量"
    ,totalNumberGroup                bigint                   comment "实验组的总的样本量"
    ,groupNum                        bigint                   comment "进组人数"
    ,includeGroupNum                 bigint                   comment "入包人数"
    ,divideTrafficNum                bigint                   comment "分流人数"
    ,strategyHitNum                  bigint                   comment "策略命中人数"
    ,exposureNum                     bigint                   comment "曝光人数"
    ,clickNum                        bigint                   comment "点击人数"
    ,viewNum                         bigint                   comment "观看人数"
    ,unlockNum                       bigint                   comment "解锁人数"
    ,payUnlockNum                    bigint                   comment "付费解锁人数"
    ,viewEpisodeNum                  bigint                   comment "观看集数"
    ,unlockEpisodeNum                bigint                   comment "解锁集数"
    ,payUnlockEpisodeNum             bigint                   comment "付费解锁集数"
    ,estimatedRevenue                varchar(50)              comment "预估收益"
    ,arpu                            varchar(50)              comment "ARPU"
    ,payRate                         varchar(50)              comment "付费率"
    ,payRateFenzi                    varchar(50)              comment "付费率分子(成功人数)"
    ,payRateFenMu                    varchar(50)              comment "付费率分母(上一步人数)"
    ,payAllRate                      varchar(50)              comment "付费率(总)"
    ,payAllRateFenzi                 varchar(50)              comment "付费率分子(成功人数)(总)"
    ,payAllRateFenmu                 varchar(50)              comment "付费率分母(上一步人数)(总)"
    ,arppu                           varchar(50)              comment "ARPPU"
    ,unitPrice                       varchar(50)              comment "客单价"
    ,rechargeAvg                     decimal(16, 4)           comment "人均充值次数"
    ,totalArppu                      varchar(50)              comment "总消费ARPPU"
    ,readCoinsArppu                  varchar(50)              comment "阅币消费ARPPU"
    ,rechargePeopleNum               bigint                   comment "充值人数"
    ,rechargeNum                     bigint                   comment "充值次数"
    ,rechargeAmount                  varchar(50)              comment "充值金额"
    ,threePartiesAcount              varchar(50)              comment "三方实收"
    ,threePartiesPercent             varchar(50)              comment "三方实收占比"
    ,amountRate                      varchar(50)              comment "费率"
    ,consumNum                       bigint                   comment "消费人数"
    ,readCoinsConsumAmount           varchar(50)              comment "阅币消费金额"
    ,voucherConsumAmount             varchar(50)              comment "礼券消费金额"
    ,readCoinsAndVoucherApru         varchar(50)              comment "阅币礼券消费ARPU"
    ,consumeRate                     varchar(50)              comment "消费率"
    ,adverArpu                       varchar(50)              comment "广告ARPU"
    ,totalAdverArpu                  varchar(50)              comment "总广告ARPU"
    ,adverUnlockRate                 varchar(50)              comment "广告解锁率"
    ,adverUnlockRateFenzi            varchar(50)              comment "广告解锁率分子(成功人数)"
    ,adverUnlockRateFenmu            varchar(50)              comment "广告解锁率分母(上一步人数)"
    ,adverUnlockEpisodeNum           varchar(50)              comment "人均广告解锁剧集"
    ,oneExposureArpu                 decimal(20, 6)           comment "单人曝光ARPU"
    ,oneExposureAllArpu              decimal(20, 6)           comment "单人曝光ARPU(总)"
    ,oneExposureAllArpuFenzi         decimal(20, 6)           comment "单人曝光ARPU分子(总)"
    ,oneExposureAllArpuFenmu         decimal(20, 6)           comment "单人曝光ARPU分母(总)"
    ,oneExposureArpuDingYue          decimal(20, 6)           comment "单人曝光ARPU(订阅)"
    ,oneRechargePercent              decimal(20, 6)           comment "单次充值占比"
    ,oneRechargePercentFenzi         decimal(20, 2)           comment "单次充值占比分子(普通充值金额)"
    ,oneRechargePercentFenmu         decimal(20, 2)           comment "单次充值占比分母(充值金额)"
    ,dingYueAmountPercent            decimal(20, 6)           comment "订阅金额占比"
    ,dingYueAmountPercentFenzi       decimal(20, 2)           comment "订阅金额占比分子(订阅金额)"
    ,dingYueAmountPercentFenmu       decimal(20, 2)           comment "订阅金额占比分母(充值金额)"
    ,dingYueAmountAllPercent         decimal(20, 6)           comment "订阅金额占比(总)"
    ,dingYueAmountAllPercentFenzi    decimal(20, 6)           comment "订阅金额占比分子(订阅金额)(总)"
    ,dingYueAmountAllPercentFenmu    decimal(20, 6)           comment "订阅金额占比分母(充值金额)(总)"
    ,orderCreateRate                 decimal(20, 6)           comment "订单创建率"
    ,orderCreateRateFenzi            int                      comment "订单创建率分子（订单创建人数）"
    ,orderCreateRateFenmu            int                      comment "订单创建率分母（曝光人数）"
    ,predictARPU                     decimal(20, 6)           comment "预估ARPU"
    ,buyersNum                       int                      comment "购买人数"
    ,buyAmount                       decimal(12, 2)           comment "购买金额"
    ,episodeExposureNum              int                      comment "曝光人数"
    ,clickCTR                        decimal(20, 6)           comment "点击率CTR"
    ,ctr                             decimal(20, 6)           comment "CTR（点击ctr：点击pv/曝光pv）"
    ,unlockArppu                     decimal(20, 4)           comment "人均解锁ARPPU"
    ,unlockArpu                      decimal(20, 4)           comment "人均解锁ARPU"
    ,saveTime                        datetime                 comment "入库时间"
    ,updateTime                      datetime                 comment "更新时间"
    ,version_start_time              datetime                 comment "版本开始时间"
    ,version_end_time                datetime                 comment "版本结束时间"
    ,watchEpisodeNumAvg              decimal(20, 6)           comment "人均观看集数"
    ,unlockCvr                       varchar(50)              comment "解锁转化率"
    ,unlockCvrFenzi                  varchar(50)              comment "解锁转化率分子"
    ,unlockCvrFenmu                  varchar(50)              comment "解锁转化率分母"
    ,viewCvr                         varchar(50)              comment "观看转化率"
    ,viewCvrFenzi                    varchar(50)              comment "观看转化率分子"
    ,viewCvrFenmu                    varchar(50)              comment "观看转化率分母"
    ,unlockedEpisodesPerExposedUser  varchar(50)              comment "每曝光用户解锁集数"
    ,viewEpisodesPerExposedUser      varchar(50)              comment "每曝光用户观看集数"
primary key(experimentId, experimentGroupId, dt, projectId, trackficVersion, windowNum)
comment "AB实验核心指标表"
distributed by hash(experimentId) buckets 6
properties (
    "replication_num" = "3",
    "in_memory" = "false",
    "enable_persistent_index" = "true",
    "replicated_storage" = "true",
    "fast_schema_evolution" = "true",
    "compression" = "LZ4"
)
;