CREATE VIEW `ads_advertisement_roi_early_warning_view_full` (`time_step` COMMENT "统计区间", `ad_id` COMMENT "广告id", `ad_name` COMMENT "广告名", `nick_name` COMMENT "昵称", `product_name` COMMENT "产品", `campaign_name`, `account_id` COMMENT "账户id", `hour_consume_amt` COMMENT "近一小时消耗（投放）", `day_consume_amt` COMMENT "当日消耗（投放）", `hour_recharge_amt` COMMENT "近一小时充值", `day_recharge_amt` COMMENT "当日充值", `hour_roi` COMMENT "近一小时roi", `day_roi` COMMENT "当日roi", `tf_h` COMMENT "近一小时投放预警 阈值", `hour_roi_rate` COMMENT "roi预警阈值", `day_roi_rate` COMMENT "roi预警阈值", `etl_tm` COMMENT "数据etl时间", `ding_user_id` COMMENT "at人id")
COMMENT "三方支付日报&渠道充值统计ads 视图" AS WITH `hour_consume` (`ad_name`, `ad_id`, `hour_consume_amt`) AS (SELECT `res`.`ad_name`, `res`.`ad_id`, sum(CASE WHEN `res`.`is_now_hour` THEN `res`.`max_spend` ELSE (`res`.`max_spend` - `res`.`flag_spend`) END) AS `hour_consume_amt`
FROM (SELECT `res`.`ad_name`, `res`.`ad_id`, `res`.`date_start`, max(`res`.`spend_sum`) AS `max_spend`, max(CASE WHEN (`res`.`snap_time` < (date_sub(current_time(), INTERVAL 1 HOUR))) THEN `res`.`spend_sum` ELSE 0 END) AS `flag_spend`, CASE WHEN ((date_format(min(`res`.`snap_time`), '%Y-%m-%d %H:00:00')) = (date_format(current_time(), '%Y-%m-%d %H:00:00'))) THEN TRUE ELSE FALSE END AS `is_now_hour`
FROM (SELECT `dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_snap_view`.`ad_name`, `dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_snap_view`.`ad_id`, `dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_snap_view`.`date_start`, `dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_snap_view`.`snap_time`, sum(`dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_snap_view`.`spend`) AS `spend_sum`
FROM `dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_snap_view`
WHERE (((`dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_snap_view`.`dt` >= (date_format(date_sub(current_time(), INTERVAL 1 HOUR), '%Y-%m-%d'))) AND (`dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_snap_view`.`spend` > 0)) AND (`dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_snap_view`.`date_start` >= (date_format(date_sub(current_time(), INTERVAL 1 HOUR), '%Y-%m-%d %H:00:00')))) AND (`dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_snap_view`.`snap_time` <= (date_sub(current_time(), INTERVAL 30 MINUTE)))
GROUP BY `dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_snap_view`.`ad_name`, `dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_snap_view`.`ad_id`, `dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_snap_view`.`date_start`, `dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_snap_view`.`snap_time`) `res`
GROUP BY `res`.`ad_name`, `res`.`ad_id`, `res`.`date_start`) `res`
GROUP BY `res`.`ad_name`, `res`.`ad_id`) , `day_consume` (`ad_name`, `ad_id`, `day_consume_amt`) AS (SELECT `dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_view`.`ad_name`, `dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_view`.`ad_id`, sum(`dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_view`.`spend`) AS `day_consume_amt`
FROM `dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_view`
WHERE (`dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_view`.`spend` > 0) AND (`dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_view`.`dt` = (current_date()))
GROUP BY `dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_view`.`ad_name`, `dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_view`.`ad_id`) , `recharge` (`ad_id`, `day_recharge_amt`, `hour_recharge_amt`) AS (SELECT `a`.`ad_id`, sum(CASE WHEN (`a`.`install_date` >= (current_date())) THEN `a`.`amount` ELSE 0 END) AS `day_recharge_amt`, sum(CASE WHEN (`a`.`install_date` >= (date_format(date_sub(current_time(), INTERVAL 1 HOUR), '%Y-%m-%d %H:00:00'))) THEN `a`.`amount` ELSE 0 END) AS `hour_recharge_amt`
FROM (SELECT `dwd`.`pay`.`base_amount_rmb` AS `amount`, `dwd`.`pay`.`video_user_id`, `attribution`.`install_date`, `attribution`.`ad_id`
FROM `dwd`.`dwd_trade_video_cn_payorder_view` AS `pay` INNER JOIN (SELECT `dwd`.`dwd_user_install_info_ed_view`.`user_id`, `dwd`.`dwd_user_install_info_ed_view`.`core`, `dwd`.`dwd_user_install_info_ed_view`.`install_date`, `dwd`.`dwd_user_install_info_ed_view`.`remarketing_time`, CASE WHEN ((`dwd`.`dwd_user_install_info_ed_view`.`ad_id` IS NULL) OR (`dwd`.`dwd_user_install_info_ed_view`.`ad_id` = '')) THEN (concat('AdId=none|SourceChl=', CASE WHEN ((`dwd`.`dwd_user_install_info_ed_view`.`Source` IS NULL) OR (`dwd`.`dwd_user_install_info_ed_view`.`Source` = '')) THEN 'none' ELSE `dwd`.`dwd_user_install_info_ed_view`.`Source` END, '|Mt=', concat(`dwd`.`dwd_user_install_info_ed_view`.`Mt`, ''), '|Core=', concat(`dwd`.`dwd_user_install_info_ed_view`.`Core`, ''), '|Chl2=', CASE WHEN ((`dwd`.`dwd_user_install_info_ed_view`.`Chl2` IS NULL) OR (`dwd`.`dwd_user_install_info_ed_view`.`Chl2` = '')) THEN 'none' ELSE `dwd`.`dwd_user_install_info_ed_view`.`Chl2` END, '|CurrentLanguage2=', concat(`dwd`.`dwd_user_install_info_ed_view`.`Current_Language2`, ''))) ELSE `dwd`.`dwd_user_install_info_ed_view`.`ad_id` END AS `ad_id`, `dwd`.`dwd_user_install_info_ed_view`.`next_attribute_time`, `dwd`.`dwd_user_install_info_ed_view`.`Unique_CdReaderId`
FROM `dwd`.`dwd_user_install_info_ed_view`
WHERE ((((`dwd`.`dwd_user_install_info_ed_view`.`is_remarketing` = 0) AND (`dwd`.`dwd_user_install_info_ed_view`.`adaccount_id` NOT IN ('6498009b0c801c4baafeb622'))) AND (`dwd`.`dwd_user_install_info_ed_view`.`product_id` = '6883')) AND (`dwd`.`dwd_user_install_info_ed_view`.`user_id` > 0)) AND (`dwd`.`dwd_user_install_info_ed_view`.`dt` >= (date_format(date_sub(current_time(), INTERVAL 1 HOUR), '%Y-%m-%d')))) `attribution` ON ((((`dwd`.`pay`.`video_user_id` = `attribution`.`Unique_CdReaderId`) AND (`dwd`.`pay`.`core` = `attribution`.`core`)) AND (`dwd`.`pay`.`create_time` >= `attribution`.`install_date`)) AND (`dwd`.`pay`.`create_time` <= `attribution`.`next_attribute_time`)) AND (`dwd`.`pay`.`create_time` <= `attribution`.`remarketing_time`)
WHERE (((`dwd`.`pay`.`dt` >= (date_format(date_sub(current_time(), INTERVAL 1 HOUR), '%Y-%m-%d'))) AND (`dwd`.`pay`.`coo_order_status` = 1)) AND (`dwd`.`pay`.`test_flag` = 0)) AND (`dwd`.`pay`.`product_id` = '6883')) `a`
GROUP BY `a`.`ad_id`) , `ad_info` (`ad_id`, `nick_name`, `campaign_name`, `product_name`, `fb_account`, `ding_user_id`) AS (SELECT `a`.`ad_id`, `dim`.`b`.`nick_name`, `c`.`campaign_name`, `d`.`product_name`, `a`.`fb_account`, `f`.`ding_user_id`
FROM (SELECT `dwd`.`dwd_advertisement_adext_view`.`ad_id`, `dwd`.`dwd_advertisement_adext_view`.`create_time`, `dwd`.`dwd_advertisement_adext_view`.`ad_name`, `dwd`.`dwd_advertisement_adext_view`.`invite_code`, `dwd`.`dwd_advertisement_adext_view`.`ad_camp_id`, `dwd`.`dwd_advertisement_adext_view`.`fb_account`
FROM `dwd`.`dwd_advertisement_adext_view`
WHERE `dwd`.`dwd_advertisement_adext_view`.`product_id` = 6883) `a` LEFT OUTER JOIN `dim`.`dim_ads_role_users_view` AS `b` ON `a`.`invite_code` = `dim`.`b`.`ref_id` LEFT OUTER JOIN (SELECT `dim`.`dim_advertisement_third_ad_campaign_view`.`campaign_name`, `dim`.`dim_advertisement_third_ad_campaign_view`.`camp_id`
FROM `dim`.`dim_advertisement_third_ad_campaign_view`
WHERE `dim`.`dim_advertisement_third_ad_campaign_view`.`ad_platform_id` > 0) `c` ON `a`.`ad_camp_id` = `c`.`camp_id` LEFT OUTER JOIN (SELECT `dim`.`dim_advertisement_third_ad_account_view`.`account`, `dim`.`dim_advertisement_third_ad_account_view`.`product_name`
FROM `dim`.`dim_advertisement_third_ad_account_view`
WHERE (`dim`.`dim_advertisement_third_ad_account_view`.`ad_platform_id` > 0) AND (`dim`.`dim_advertisement_third_ad_account_view`.`product_id` = 6883)) `d` ON `a`.`fb_account` = `d`.`account` LEFT OUTER JOIN (SELECT `dim`.`dim_ads_thirdadset_view`.`adset_id` AS `ad_id`
FROM `dim`.`dim_ads_thirdadset_view`
WHERE `dim`.`dim_ads_thirdadset_view`.`status` = 'OK') `e` ON `a`.`ad_id` = `e`.`ad_id` LEFT OUTER JOIN (SELECT `dim`.`dim_kpi_user_info_view`.`nick_name`, `dim`.`dim_kpi_user_info_view`.`ding_user_id`
FROM `dim`.`dim_kpi_user_info_view`
WHERE (`dim`.`dim_kpi_user_info_view`.`del_flag` = 0) AND (`dim`.`dim_kpi_user_info_view`.`ding_user_id` IS NOT NULL)) `f` ON `dim`.`b`.`nick_name` = `f`.`nick_name`) SELECT `res`.`time_step`, `res`.`ad_id`, `res`.`ad_name`, `res`.`nick_name`, `res`.`product_name`, `res`.`campaign_name`, `res`.`account_id`, `res`.`hour_consume_amt`, `res`.`day_consume_amt`, `res`.`hour_recharge_amt`, `res`.`day_recharge_amt`, `res`.`hour_roi`, `res`.`day_roi`, `res`.`tf_h`, `res`.`hour_roi_rate`, `res`.`day_roi_rate`, `res`.`etl_tm`, `res`.`ding_user_id`
FROM (SELECT concat(date_format(date_sub(current_time(), INTERVAL 1 HOUR), '%Y-%m-%d  %H:%i'), '~', date_format(current_time(), '%H:%i')) AS `time_step`, `hour_consume`.`ad_id`, `hour_consume`.`ad_name`, `ad_info`.`nick_name`, `ad_info`.`product_name`, `ad_info`.`campaign_name`, `ad_info`.`fb_account` AS `account_id`, ifnull(round(`hour_consume`.`hour_consume_amt`, 2), 0.00) AS `hour_consume_amt`, ifnull(round(`day_consume`.`day_consume_amt`, 2), 0.00) AS `day_consume_amt`, ifnull(round(`recharge`.`hour_recharge_amt`, 2), 0.00) AS `hour_recharge_amt`, ifnull(round(`recharge`.`day_recharge_amt`, 2), 0.00) AS `day_recharge_amt`, ifnull(round((`recharge`.`hour_recharge_amt` / `hour_consume`.`hour_consume_amt`) * 100, 2), 0.00) AS `hour_roi`, ifnull(round((`recharge`.`day_recharge_amt` / `day_consume`.`day_consume_amt`) * 100, 2), 0.00) AS `day_roi`, 100 AS `tf_h`, 50 AS `hour_roi_rate`, 100 AS `day_roi_rate`, now() AS `etl_tm`, `ad_info`.`ding_user_id`
FROM `hour_consume` LEFT OUTER JOIN `day_consume` ON `hour_consume`.`ad_id` = `day_consume`.`ad_id` LEFT OUTER JOIN `recharge` ON `hour_consume`.`ad_id` = `recharge`.`ad_id` LEFT OUTER JOIN `ad_info` ON `hour_consume`.`ad_id` = `ad_info`.`ad_id`) `res`;