CREATE VIEW `ads_bi_consume_book_chapter_view` (`dt` COMMENT "createtime 分区", `site_id` COMMENT "语言id", `book_id` COMMENT "书籍id", `chapter_id` COMMENT "章节id", `product_id` COMMENT "产品id", `types` COMMENT "1:阅币 2：礼券 3：赠送币 4：vip", `corever` COMMENT "core的版本号", `mt` COMMENT "平台 0未知 1 iphone 4安卓 9书城", `ver` COMMENT "客户端版本号", `current_language` COMMENT "当前语言", `current_language2` COMMENT "注册时语言", `reg_date` COMMENT "注册时间保留时分秒", `reg_days` COMMENT "距离注册时间时长", `reg_country` COMMENT "注册国家", `appver` COMMENT "app版本", `sex` COMMENT "性别0未知 1男 2女 3保密", `user_id` COMMENT "用户id", `amount` COMMENT "消耗数额", `user_tp` COMMENT "1：所有用户 2：事件时间-注册时间<=30天 3:90天内新增的阅读用户", `is_new` COMMENT "1：新用户（当天注册且当天有阅读的） 2：老用户", `etl_time` COMMENT "处理时间") AS SELECT `dws`.`dws_consume_book_chapter_ed`.`dt`, `dws`.`dws_consume_book_chapter_ed`.`site_id`, `dws`.`dws_consume_book_chapter_ed`.`book_id`, `dws`.`dws_consume_book_chapter_ed`.`chapter_id`, `dws`.`dws_consume_book_chapter_ed`.`product_id`, `dws`.`dws_consume_book_chapter_ed`.`types`, `dws`.`dws_consume_book_chapter_ed`.`corever`, `dws`.`dws_consume_book_chapter_ed`.`mt`, `dws`.`dws_consume_book_chapter_ed`.`ver`, `dws`.`dws_consume_book_chapter_ed`.`current_language`, `dws`.`dws_consume_book_chapter_ed`.`current_language2`, `dws`.`dws_consume_book_chapter_ed`.`reg_date`, `dws`.`dws_consume_book_chapter_ed`.`reg_days`, `dws`.`dws_consume_book_chapter_ed`.`reg_country`, `dws`.`dws_consume_book_chapter_ed`.`appver`, `dws`.`dws_consume_book_chapter_ed`.`sex`, `dws`.`dws_consume_book_chapter_ed`.`user_id`, `dws`.`dws_consume_book_chapter_ed`.`amound` AS `amount`, 1 AS `user_tp`, CASE WHEN (`dws`.`dws_consume_book_chapter_ed`.`reg_days` > 0) THEN 0 WHEN (`dws`.`dws_consume_book_chapter_ed`.`reg_days` = 0) THEN 1 END AS `is_new`, `dws`.`dws_consume_book_chapter_ed`.`etl_time`
FROM `dws`.`dws_consume_book_chapter_ed`
WHERE `dws`.`dws_consume_book_chapter_ed`.`dt` >= '2023-01-01' UNION ALL SELECT `dws`.`dws_consume_book_chapter_ed`.`dt`, `dws`.`dws_consume_book_chapter_ed`.`site_id`, `dws`.`dws_consume_book_chapter_ed`.`book_id`, `dws`.`dws_consume_book_chapter_ed`.`chapter_id`, `dws`.`dws_consume_book_chapter_ed`.`product_id`, `dws`.`dws_consume_book_chapter_ed`.`types`, `dws`.`dws_consume_book_chapter_ed`.`corever`, `dws`.`dws_consume_book_chapter_ed`.`mt`, `dws`.`dws_consume_book_chapter_ed`.`ver`, `dws`.`dws_consume_book_chapter_ed`.`current_language`, `dws`.`dws_consume_book_chapter_ed`.`current_language2`, `dws`.`dws_consume_book_chapter_ed`.`reg_date`, `dws`.`dws_consume_book_chapter_ed`.`reg_days`, `dws`.`dws_consume_book_chapter_ed`.`reg_country`, `dws`.`dws_consume_book_chapter_ed`.`appver`, `dws`.`dws_consume_book_chapter_ed`.`sex`, `dws`.`dws_consume_book_chapter_ed`.`user_id`, `dws`.`dws_consume_book_chapter_ed`.`amound` AS `amount`, 2 AS `user_tp`, CASE WHEN (`dws`.`dws_consume_book_chapter_ed`.`reg_days` > 0) THEN 0 WHEN (`dws`.`dws_consume_book_chapter_ed`.`reg_days` = 0) THEN 1 END AS `is_new`, `dws`.`dws_consume_book_chapter_ed`.`etl_time`
FROM `dws`.`dws_consume_book_chapter_ed`
WHERE (`dws`.`dws_consume_book_chapter_ed`.`dt` >= '2023-01-01') AND (`dws`.`dws_consume_book_chapter_ed`.`reg_days` <= 30) UNION ALL SELECT `a`.`dt`, `a`.`site_id`, `a`.`book_id`, `a`.`chapter_id`, `a`.`product_id`, `a`.`types`, `a`.`corever`, `a`.`mt`, `a`.`ver`, `a`.`current_language`, `a`.`current_language2`, `a`.`reg_date`, `a`.`reg_days`, `a`.`reg_country`, `a`.`appver`, `a`.`sex`, ``.bitmap_agg(`a`.`user_id`) AS `user_id`, `a`.`amount`, `a`.`user_tp`, `a`.`is_new`, `a`.`etl_time`
FROM (SELECT `a`.`dt`, `a`.`site_id`, `a`.`book_id`, `a`.`chapter_id`, `a`.`product_id`, `a`.`types`, `a`.`corever`, `a`.`mt`, `a`.`ver`, `a`.`current_language`, `a`.`current_language2`, `a`.`reg_date`, `a`.`reg_days`, `a`.`reg_country`, `a`.`appver`, `a`.`sex`, `t`.`UNNEST` AS `user_id`, `a`.`amount`, `a`.`user_tp`, CASE WHEN (`a`.`reg_days` > 0) THEN 0 WHEN (`a`.`reg_days` = 0) THEN 1 END AS `is_new`, `a`.`etl_time`
FROM (SELECT `dws`.`a`.`dt`, `dws`.`a`.`site_id`, `dws`.`a`.`book_id`, `dws`.`a`.`chapter_id`, `dws`.`a`.`product_id`, `dws`.`a`.`types`, `dws`.`a`.`corever`, `dws`.`a`.`mt`, `dws`.`a`.`ver`, `dws`.`a`.`current_language`, `dws`.`a`.`current_language2`, `dws`.`a`.`reg_date`, `dws`.`a`.`reg_days`, `dws`.`a`.`reg_country`, `dws`.`a`.`appver`, `dws`.`a`.`sex`, bitmap_to_array(`dws`.`a`.`user_id`) AS `user_id`, `dws`.`a`.`amound` AS `amount`, 3 AS `user_tp`, CASE WHEN (`dws`.`a`.`reg_days` > 0) THEN 0 WHEN (`dws`.`a`.`reg_days` = 0) THEN 1 END AS `is_new`, `dws`.`a`.`etl_time`
FROM `dws`.`dws_consume_book_chapter_ed` AS `a`
WHERE `dws`.`a`.`dt` >= '2023-01-01') `a` , LATERAL unnest(`a`.`user_id`) t(`unnest`) ) `a` INNER JOIN `dws`.`dws_comsume_book_user_l90d` AS `y` ON (((`a`.`dt` = `dws`.`y`.`dt`) AND (`a`.`site_id` = `dws`.`y`.`site_id`)) AND (`a`.`book_id` = `dws`.`y`.`book_id`)) AND (`a`.`user_id` = `dws`.`y`.`user_id`)
GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 18, 19, 20, 21;