CREATE TABLE `ads_sv_series_roi_growth_metrics` (
  `current_language2` int(11) NOT NULL COMMENT "投放语言",
  `book_id` varchar(255) NOT NULL COMMENT "书籍id",
  `code` varchar(255) NOT NULL COMMENT "源剧代码",
  `mt` int(11) NOT NULL COMMENT "终端id",
  `mt2` varchar(255) NOT NULL COMMENT "终端",
  `days_max` int(11) NULL COMMENT "最大投放天数",
  `amount_d0` decimal(12, 4) NULL COMMENT "累计D0收入",
  `amount_d0_days60` decimal(12, 4) NULL COMMENT "最近60天累计D0收入",
  `inc0` decimal(14, 4) NULL COMMENT "H24/D0，预处理，与实际ROI存在偏差",
  `inc1` decimal(14, 4) NULL COMMENT "D1/D0，预处理",
  `inc3` decimal(14, 4) NULL COMMENT "D3/D0，预处理",
  `inc7` decimal(14, 4) NULL COMMENT "D7/D0，预处理",
  `inc30` decimal(14, 4) NULL COMMENT "D30/D0，预处理",
  `inc60` decimal(14, 4) NULL COMMENT "D60/D0，预处理",
  `inc90` decimal(14, 4) NULL COMMENT "D90/D0，预处理",
  `inc120` decimal(14, 4) NULL COMMENT "D120/D0，预处理",
  `dpt0_rate` decimal(14, 4) NULL COMMENT "剧维度，dpt归因用户收入占D0收入的比例",
  `cost_sum` decimal(14, 4) NULL COMMENT "累计花费，不区分终端和媒体",
  `cost_7d` decimal(14, 4) NULL COMMENT "近7日花费，不区分终端和媒体",
  `last_date` date NULL COMMENT "最后一次日花费>100的日期，用户相似度指标计算",
  `roi_0to1` decimal(14, 4) NULL COMMENT "D1/D0",
  `roi_0to3` decimal(14, 4) NULL COMMENT "D3/D0",
  `roi_0to7` decimal(14, 4) NULL COMMENT "D7/D0",
  `rt_rate` decimal(14, 4) NULL COMMENT "次留率= 次日有观看记录用户/ 首日新增用户数",
  `new_amt_rate` decimal(14, 4) NULL COMMENT "new收入（new收入+rmt收入）",
  `dpt90_rate` decimal(14, 4) NULL COMMENT "",
  `new_amt_rate_dpt` decimal(14, 4) NULL COMMENT "new收入（new收入+rmt收入+dpt收入）",
  `nrate` decimal(14, 4) NULL COMMENT "新用户ltvD0/ RMT用户LTVD0",
  `ltv0` decimal(14, 4) NULL COMMENT "D0 LTV",
  `new_amtrate_sum` decimal(14, 4) NULL COMMENT "D0大盘new收入（new收入+rmt收入）",
  `new0_rate_sum` decimal(14, 4) NULL COMMENT "D0大盘new收入（new收入+rmt收入+dpt收入）",
  `dpt0_rate_sum` decimal(14, 4) NULL COMMENT "D0大盘dpt收入（new收入+rmt收入+dpt收入）",
  `dpt90_rate_sum` decimal(14, 4) NULL COMMENT "D90大盘dpt收入（new收入+rmt收入+dpt收入）",
  `organic_rate0` decimal(14, 4) NULL COMMENT "D0自然收入占比",
  `organic_rate90` decimal(14, 4) NULL COMMENT "D90自然收入占比（英语为120天）",
  `newstd_diff` decimal(14, 4) NULL COMMENT "新用户回本目标_降幅",
  `oldstd_add` decimal(14, 4) NULL COMMENT "老用户回本目标_增幅",
  `inc_ad` decimal(14, 4) NULL COMMENT "大盘广告回本涨幅",
  `inc_dpt` decimal(14, 4) NULL COMMENT "大盘DPT回本涨幅",
  `code_stage` int(11) NULL COMMENT "投放阶段",
  `has_std` int(11) NULL COMMENT "是否有标准，1=有，0=无",
  `r0_std` decimal(14, 4) NULL COMMENT "现有D0标准",
  `r7_std` decimal(14, 4) NULL COMMENT "现有D7标准",
  `h24_std` decimal(14, 4) NULL COMMENT "现有H24标准",
  `consume_rate` decimal(14, 4) NULL COMMENT "推广剧首日消费占比",
  `language` varchar(255) NULL COMMENT "投放语言id",
  `book_target` decimal(14, 4) NULL COMMENT "回本目标",
  `r0_std2` decimal(14, 4) NULL COMMENT "新D0标准",
  `r7_std2` decimal(14, 4) NULL COMMENT "新D7标准",
  `h24_std2` decimal(14, 4) NULL COMMENT "新H24标准",
  `std_new_diff_d0` decimal(14, 4) NULL COMMENT "新标准-之前标准D0",
  `std_new_diff_d7` decimal(14, 4) NULL COMMENT "新标准-之前标准D7",
  `etl_tm` datetime NULL COMMENT "数据清洗时间"
) ENGINE=OLAP 
PRIMARY KEY(`current_language2`, `book_id`, `code`, `mt`, `mt2`)
COMMENT "短剧ROI涨幅和相关影响指标"
DISTRIBUTED BY HASH(`current_language2`) BUCKETS 3 
PROPERTIES (
"replication_num" = "3",
"bloom_filter_columns" = "current_language2",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);