CREATE EXTERNAL TABLE `ads_srsv_bi_ad_optimizer_template_target_data_1_external` (
  `dt` date NOT NULL COMMENT "dt",
  `book_id` bigint(20) NOT NULL COMMENT "book_id",
  `template_id` int(11) NOT NULL COMMENT "template_id",
  `source2` varchar(255) NOT NULL COMMENT "source2",
  `project_code` int(11) NOT NULL COMMENT "project_code",
  `core` int(11) NOT NULL COMMENT "core",
  `product` varchar(255) NULL COMMENT "product",
  `days` int(11) NULL COMMENT "days",
  `weekdays` int(11) NULL COMMENT "weekdays",
  `book_code` varchar(255) NULL COMMENT "book_code",
  `languageid` int(11) NULL COMMENT "languageid",
  `current_language2` varchar(255) NULL COMMENT "current_language2",
  `template_name` varchar(255) NULL COMMENT "template_name",
  `adset_num` int(11) NULL COMMENT "adset_num",
  `spend` decimal(10, 2) NULL COMMENT "spend",
  `d0_amt` decimal(10, 2) NULL COMMENT "d0_amt",
  `std_amt` decimal(10, 2) NULL COMMENT "std_amt",
  `reg_num` int(11) NULL COMMENT "reg_num",
  `reg_num_all` decimal(10, 2) NULL COMMENT "reg_num_all",
  `reg_num_new` decimal(10, 2) NULL COMMENT "reg_num_new",
  `new_amt_rate` decimal(10, 2) NULL COMMENT "new_amt_rate",
  `old_spend` decimal(10, 2) NULL COMMENT "old_spend",
  `old_d0_amt` decimal(10, 2) NULL COMMENT "old_d0_amt",
  `old_std_amt` decimal(10, 2) NULL COMMENT "old_std_amt",
  `days_book` int(11) NULL COMMENT "days_book",
  `regnum_new_7d` decimal(10, 2) NULL COMMENT "regnum_new_7d",
  `regnum_all_7d` decimal(10, 2) NULL COMMENT "regnum_all_7d",
  `spend_10d` decimal(10, 2) NULL COMMENT "spend_10d",
  `adset_num_10d` decimal(10, 2) NULL COMMENT "adset_num_10d",
  `days_10d` decimal(10, 2) NULL COMMENT "days_10d",
  `d0_amt_10d` decimal(10, 2) NULL COMMENT "d0_amt_10d",
  `std_amt_10d` decimal(10, 2) NULL COMMENT "std_amt_10d",
  `d0_amt_all` decimal(10, 2) NULL COMMENT "d0_amt_all",
  `std_amt_all` decimal(10, 2) NULL COMMENT "std_amt_all",
  `d0_amt_pow` decimal(10, 2) NULL COMMENT "d0_amt_pow",
  `std_amt_pow` decimal(10, 2) NULL COMMENT "std_amt_pow",
  `d0_amt_pow_old` decimal(10, 2) NULL COMMENT "d0_amt_pow_old",
  `std_amt_pow_old` decimal(10, 2) NULL COMMENT "std_amt_pow_old",
  `d0_amt_af` decimal(10, 2) NULL COMMENT "d0_amt_af",
  `std_amt_af` decimal(10, 2) NULL COMMENT "std_amt_af",
  `code_stage` int(11) NULL COMMENT "code_stage",
  `code_lv` varchar(255) NULL COMMENT "code_lv",
  `test_status` int(11) NULL COMMENT "test_status",
  `begin_date` date NULL COMMENT "begin_date",
  `end_date` date NULL COMMENT "end_date",
  `off_begindate` date NULL COMMENT "off_begindate",
  `off_enddate` date NULL COMMENT "off_enddate",
  `lang` varchar(255) NULL COMMENT "lang",
  `lang_rate` int(11) NULL COMMENT "lang_rate",
  `group_spend` int(11) NULL COMMENT "group_spend",
  `sunday_rate` decimal(10, 2) NULL COMMENT "sunday_rate",
  `friday_rate` decimal(10, 2) NULL COMMENT "friday_rate",
  `base_rate` decimal(10, 2) NULL COMMENT "base_rate",
  `new_std` decimal(10, 2) NULL COMMENT "new_std",
  `old_std` decimal(10, 2) NULL COMMENT "old_std",
  `log_num` int(11) NULL COMMENT "log_num",
  `log_num_median` decimal(10, 2) NULL COMMENT "log_num_median",
  `exp_a` decimal(10, 2) NULL COMMENT "exp_a",
  `new_r0_rate` decimal(10, 2) NULL COMMENT "new_r0_rate",
  `non_compliance_exp` decimal(10, 2) NULL COMMENT "non_compliance_exp",
  `spend_exp` decimal(10, 2) NULL COMMENT "spend_exp",
  `weekdays_p` decimal(10, 2) NULL COMMENT "weekdays_p",
  `newamt_rate` decimal(10, 2) NULL COMMENT "newamt_rate",
  `R0_new` decimal(10, 2) NULL COMMENT "R0_new",
  `R0_old` decimal(10, 2) NULL COMMENT "R0_old",
  `R0_bf1` decimal(10, 2) NULL COMMENT "R0_bf1",
  `old_R0_bf1` decimal(10, 2) NULL COMMENT "old_R0_bf1",
  `growth_base` decimal(10, 2) NULL COMMENT "growth_base",
  `growth_exp` decimal(10, 2) NULL COMMENT "growth_exp",
  `spend_rate` decimal(10, 2) NULL COMMENT "spend_rate",
  `growth_rate` decimal(10, 2) NULL COMMENT "growth_rate",
  `adsetnum_1` int(11) NULL COMMENT "adsetnum_1",
  `adsetnum_2` int(11) NULL COMMENT "adsetnum_2",
  `has_plan` int(11) NULL COMMENT "has_plan",
  `adsetnum_plan` int(11) NULL COMMENT "adsetnum_plan",
  `opt_eid` varchar(200) NULL COMMENT "优化师工号",
  `opt_name` varchar(60) NULL COMMENT "优化师姓名",
  `auto_ce_type_cd` int(11) NULL COMMENT "自动创编类型编码",
  `auto_ce_type_name` varchar(100) NULL COMMENT "自动创编类型名称",
  `is_fst_infra` int(11) NULL COMMENT "是否首日基建",
  `init_infra_num` int(11) NULL COMMENT "初始基建条数",
  `is_new_group_ce` int(11) NULL COMMENT "是否有创编新组",
  `spend1` decimal(12, 2) NULL COMMENT "spend1",
  `d0_amt1` decimal(12, 2) NULL COMMENT "d0_amt1",
  `std_amt1` decimal(12, 2) NULL COMMENT "std_amt1",
  `d0_amt_pow1` decimal(12, 2) NULL COMMENT "d0_amt_pow1",
  `std_amt_pow1` decimal(12, 2) NULL COMMENT "std_amt_pow1",
  `etl_tm` datetime NULL COMMENT "数据清洗时间"
) ENGINE=OLAP_EXTERNAL 
PRIMARY KEY(`dt`, `book_id`, `template_id`, `source2`, `project_code`, `core`)
COMMENT "模板维度基建上限"
DISTRIBUTED BY HASH(`dt`) BUCKETS 3 
PROPERTIES (
"replication_num" = "3",
"bloom_filter_columns" = "dt, core, template_id, project_code, book_id, source2",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4",
"host" = "ads-starrocks-in.changdu.vip",
"port" = "19020",
"user" = "ztt",
"password" = "",
"database" = "ads",
"table" = "ads_srsv_bi_ad_optimizer_template_target_data_1"
);