CREATE VIEW `ads_short_video_admin_series_test_view` (`SeriesId` COMMENT "id", `series_code` COMMENT "代号", `Language` COMMENT "语言", `SeriesName`, `Description` COMMENT "短剧简介", `CoverUrl` COMMENT "封面", `CreateTime` COMMENT "创建时间", `Up` COMMENT "修改时间", `CreateUser` COMMENT "上传人", `PublishStatus` COMMENT "上架状态(1上架 2下架)", `PublishedAt` COMMENT "上架时间", `UnPublishedAt` COMMENT "下架时间", `LastEpis` COMMENT "更新至第几集", `AllEpis` COMMENT "总集数", `PayEpisFrom` COMMENT "收费起始集数", `IsDelete` COMMENT "是否删除", `Producer`, `Recommend`, `SourceSeriesId` COMMENT "源语言短剧", `Price` COMMENT "单集价格（分）", `MinutePrice` COMMENT "分钟价格", `Ending` COMMENT "完结状态（1连载中 2已完结）", `SeriesNameKey`, `DescriptionKey` COMMENT "短剧简介转换key", `RecommendKey`, `IsSubtitles` COMMENT "是否需要字幕 1 需要 0 不需要", `SubtitlesStatus` COMMENT "字幕是否完整 1 完整 0 缺失", `EpisStatus` COMMENT "分集是否完成 1 完整 0 缺失", `VideoStatus` COMMENT "分集视频是否完整 1 完整 0 缺失", `SeriesLevel` COMMENT "等级 1.S 2.A 3.B 4.C", `OperateLevel` COMMENT "运营等级 1.S 2.A 3.B 4.C", `WorkType` COMMENT "作品类型 1.男频  2.女频 3.双番", `ImageKey` COMMENT "轮播榜单配图id", `ListRecommendKey` COMMENT "轮播榜单推荐语key", `ListRecommend` COMMENT "轮播榜单推荐语", `AdsBeginTime` COMMENT "测推时间", `Core` COMMENT "Core ，多个用逗号隔开(1core1，2core2，3core3，4core4)", `IsScheduledPublish` COMMENT "是否定时上架", `ScheduledPublishTime` COMMENT "定时上架时间", `HighLightPlot` COMMENT "高光剧情", `TurningPoint` COMMENT "转折点", `import_time` COMMENT "引入时间", `plan_status` COMMENT "跑出状态（-1无状态，0待定，1跑出，2未跑出）", `run_out_time` COMMENT "跑出时间", `multilingual_status` COMMENT "当前状态") AS SELECT `a`.`SeriesId`, `a`.`series_code`, `a`.`Language`, `a`.`SeriesName`, `a`.`Description`, `a`.`CoverUrl`, `a`.`CreateTime`, `a`.`UpdateTime`, `a`.`CreateUser`, `a`.`PublishStatus`, `a`.`PublishedAt`, `a`.`UnPublishedAt`, `a`.`LastEpis`, `a`.`AllEpis`, `a`.`PayEpisFrom`, `a`.`IsDelete`, `a`.`Producer`, `a`.`Recommend`, `a`.`SourceSeriesId`, `a`.`Price`, `a`.`MinutePrice`, `a`.`Ending`, `a`.`SeriesNameKey`, `a`.`DescriptionKey`, `a`.`RecommendKey`, `a`.`IsSubtitles`, `a`.`SubtitlesStatus`, `a`.`EpisStatus`, `a`.`VideoStatus`, `a`.`SeriesLevel`, `a`.`OperateLevel`, `a`.`WorkType`, `a`.`ImageKey`, `a`.`ListRecommendKey`, `a`.`ListRecommend`, `a`.`AdsBeginTime`, `a`.`Core`, `a`.`IsScheduledPublish`, `a`.`ScheduledPublishTime`, `a`.`HighLightPlot`, `a`.`TurningPoint`, `a`.`import_time`, `a`.`plan_status`, `a`.`run_out_time`, `a`.`multilingual_status`
FROM (SELECT `ods`.`a`.`SeriesId`, ifnull(`dim`.`b`.`series_code`, `e`.`BookCode`) AS `series_code`, ifnull(`ods`.`a`.`Language`, `e`.`language_id`) AS `Language`, `ods`.`a`.`SeriesName`, `ods`.`a`.`Description`, `ods`.`a`.`CoverUrl`, `ods`.`a`.`CreateTime`, `ods`.`a`.`UpdateTime`, `ods`.`a`.`CreateUser`, `ods`.`a`.`PublishStatus`, `ods`.`a`.`PublishedAt`, `ods`.`a`.`UnPublishedAt`, `ods`.`a`.`LastEpis`, `ods`.`a`.`AllEpis`, `ods`.`a`.`PayEpisFrom`, `ods`.`a`.`IsDelete`, `ods`.`a`.`Producer`, `ods`.`a`.`Recommend`, `ods`.`a`.`SourceSeriesId`, `ods`.`a`.`Price`, `ods`.`a`.`MinutePrice`, `ods`.`a`.`Ending`, `ods`.`a`.`SeriesNameKey`, `ods`.`a`.`DescriptionKey`, `ods`.`a`.`RecommendKey`, `ods`.`a`.`IsSubtitles`, `ods`.`a`.`SubtitlesStatus`, `ods`.`a`.`EpisStatus`, `ods`.`a`.`VideoStatus`, `ods`.`a`.`SeriesLevel`, `ods`.`a`.`OperateLevel`, `ods`.`a`.`WorkType`, `ods`.`a`.`ImageKey`, `ods`.`a`.`ListRecommendKey`, `ods`.`a`.`ListRecommend`, `ods`.`a`.`AdsBeginTime`, `ods`.`a`.`Core`, `ods`.`a`.`IsScheduledPublish`, `ods`.`a`.`ScheduledPublishTime`, `ods`.`a`.`HighLightPlot`, `ods`.`a`.`TurningPoint`, `ods`.`c`.`add_time` AS `import_time`, if(`d`.`DateKey` IS NOT NULL, 1, 2) AS `plan_status`, `d`.`DateKey` AS `run_out_time`, if(`ods`.`a`.`PublishedAt` <= (current_date()), '已上架', `e`.`status`) AS `multilingual_status`, row_number() OVER (PARTITION BY ifnull(`dim`.`b`.`series_code`, `e`.`BookCode`), ifnull(`ods`.`a`.`Language`, `e`.`language_id`) ORDER BY `f`.`weight` ASC ) AS `rn`
FROM `ods`.`ods_tidb_short_video_admin_series` AS `a` LEFT OUTER JOIN `dim`.`dim_short_video_source_series_view` AS `b` ON `ods`.`a`.`SourceSeriesId` = `dim`.`b`.`series_id` LEFT OUTER JOIN `ods`.`ods_tidb_cdcreator_tidb_cn_story_original` AS `c` ON `dim`.`b`.`series_code` = `ods`.`c`.`story_code` LEFT OUTER JOIN (SELECT `ods`.`ods_ads_tidb_sharpengine_ads_global_MarketingPlanAutoStage`.`CodeId`, min(`ods`.`ods_ads_tidb_sharpengine_ads_global_MarketingPlanAutoStage`.`DateKey`) AS `DateKey`
FROM `ods`.`ods_ads_tidb_sharpengine_ads_global_MarketingPlanAutoStage`
GROUP BY `ods`.`ods_ads_tidb_sharpengine_ads_global_MarketingPlanAutoStage`.`CodeId`) `d` ON `ods`.`a`.`SeriesId` = `d`.`CodeId` FULL OUTER JOIN (SELECT `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`BookCode`, 3 AS `language_id`, `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`EnStatus` AS `status`
FROM `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`
WHERE (ifnull(`ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`EnStatus`, '')) != '' UNION ALL SELECT `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`BookCode`, 4 AS `language_id`, `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`SpStatus`
FROM `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`
WHERE (ifnull(`ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`SpStatus`, '')) != '' UNION ALL SELECT `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`BookCode`, 5 AS `language_id`, `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`PtStatus`
FROM `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`
WHERE (ifnull(`ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`PtStatus`, '')) != '' UNION ALL SELECT `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`BookCode`, 6 AS `language_id`, `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`FrStatus`
FROM `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`
WHERE (ifnull(`ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`FrStatus`, '')) != '' UNION ALL SELECT `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`BookCode`, 7 AS `language_id`, `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`RuStatus`
FROM `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`
WHERE (ifnull(`ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`RuStatus`, '')) != '' UNION ALL SELECT `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`BookCode`, 11 AS `language_id`, `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`IdStatus`
FROM `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`
WHERE (ifnull(`ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`IdStatus`, '')) != '' UNION ALL SELECT `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`BookCode`, 12 AS `language_id`, `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`ThStatus`
FROM `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`
WHERE (ifnull(`ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`ThStatus`, '')) != '' UNION ALL SELECT `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`BookCode`, 9 AS `language_id`, `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`JpStatus`
FROM `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`
WHERE (ifnull(`ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`JpStatus`, '')) != '' UNION ALL SELECT `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`BookCode`, 14 AS `language_id`, `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`KoStatus`
FROM `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`
WHERE (ifnull(`ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`KoStatus`, '')) != '' UNION ALL SELECT `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`BookCode`, 16 AS `language_id`, `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`DeStatus`
FROM `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`
WHERE (ifnull(`ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`DeStatus`, '')) != '' UNION ALL SELECT `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`BookCode`, 8 AS `language_id`, `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`ItStatus`
FROM `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`
WHERE (ifnull(`ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`ItStatus`, '')) != '' UNION ALL SELECT `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`BookCode`, 10 AS `language_id`, `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`ArStatus`
FROM `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`
WHERE (ifnull(`ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`ArStatus`, '')) != '' UNION ALL SELECT `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`BookCode`, 22 AS `language_id`, `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`TrStatus`
FROM `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`
WHERE (ifnull(`ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`TrStatus`, '')) != '' UNION ALL SELECT `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`BookCode`, 21 AS `language_id`, `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`MyStatus`
FROM `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`
WHERE (ifnull(`ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`MyStatus`, '')) != '' UNION ALL SELECT `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`BookCode`, 15 AS `language_id`, `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`TlStatus`
FROM `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`
WHERE (ifnull(`ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`TlStatus`, '')) != '' UNION ALL SELECT `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`BookCode`, 13 AS `language_id`, `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`ViStatus`
FROM `ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`
WHERE (ifnull(`ods`.`ods_tidb_shuangwen_tidb_en_shortvideomultilingual`.`ViStatus`, '')) != '') `e` ON (`dim`.`b`.`series_code` = `e`.`BookCode`) AND (`ods`.`a`.`Language` = `e`.`language_id`) LEFT OUTER JOIN (SELECT '已上架' AS `multilingual_type`, 1 AS `weight` UNION ALL SELECT '已完成' AS `multilingual_type`, 2 AS `weight` UNION ALL SELECT '进行中' AS `multilingual_type`, 3 AS `weight` UNION ALL SELECT '待处理' AS `multilingual_type`, 4 AS `weight`) `f` ON (if(`ods`.`a`.`PublishedAt` <= (current_date()), '已上架', `e`.`status`)) = `f`.`multilingual_type`) `a`
WHERE `a`.`rn` = 1;