drop table if exists ads.syncbi_video_userdata;
create table ads.syncbi_video_userdata (
     product_id                   int            not null                  comment "产品id"
    ,Id                           bigint         not null                  comment "用户id"
    ,HasDeviceCharge              tinyint                                  comment "设备是否充值"
    ,FirstChargeTime              datetime                                 comment "首次充值时间"
    ,ChargeCount                  int                                      comment "充值次数"
    ,LastBuyBookId                bigint                                   comment "最后一次购买的书籍id"
    ,LastChapterId                bigint                                   comment "最后一次获取的章节id"
    ,HasSendGift                  tinyint                                  comment "是否已赠送复充优惠券"
    ,GiftExpireTime               datetime                                 comment "复充优惠券过期时间"
    ,VipExpireTime                datetime                                 comment "会员过期时间"
    ,IsContinuityVip              tinyint                                  comment "是否为连续包月会员"
    ,GetGiftTime                  datetime                                 comment "会员领取礼券时间"
    ,VipType                      int                                      comment "会员类型"
    ,VipType2                     int                                      comment "会员类型"
    ,NextVipTypeRetryTime         datetime                                 comment "下次会员类型重算时间"
    ,SmallInviteAwardExpireTime   datetime                                 comment "小程序邀请奖励过期时间"
    ,ExchangeNewUserTime          datetime                                 comment "新用户免费到期时间"
    ,TotalSignCount               int                                      comment "累计签到次数"
    ,NoAdExpireTime               datetime                                 comment "无广告过期时间"
    ,Device                       string                                   comment "设备号"
    ,SysReleaseVer                string                                   comment "固件版本"
    ,VipDeviceGuid                string                                   comment "会员设备号"
    ,VipFirstBuyTime              datetime                                 comment "首次购买会员时间"
    ,BlockDevices                 string                                   comment "黑名单设备号"
    ,Coin                         int                                      comment "金币"
    ,TodayReadTime                int                                      comment "今日阅读时长"
    ,TotalReadTime                bigint                                   comment "累计阅读时长"
    ,FreeNovelNoAdTime            datetime                                 comment "免广告时间"
    ,Today                        datetime                                 comment "当天时间"
    ,TodayCharge                  int                                      comment "今日充值"
    ,HeadFrame                    varchar(512)                             comment "新人福利头像框"
    ,ReadPageLastTime             datetime                                 comment "阅读页上次弹出新人福利时间"
    ,LastAddBookshelfTime         datetime                                 comment "上次加入书架时间"
    ,LowVipExpireTime             datetime                                 comment "VIP过期时间"
    ,NextLowVipTypeRetryTime      datetime                                 comment "下次普通会员类型重算时间"
    ,LastBuySvipTime              datetime                                 comment "上次购买SVIP时间"
    ,LastAllFreeShowTime          datetime                                 comment "上次新人免费弹窗时间"
    ,SVipCardPrice                int            not null                  comment "SVIP卡价格"
    ,VipExpireTimeSeconds         bigint                                   comment "SVIP剩余秒数"
    ,LowVipExpireTimeSeconds      bigint                                   comment "VIP剩余秒数"
    ,NewVipModel                  int                                      comment "VIP是否转换为新模式"
    ,NewSvipModel                 int                                      comment "SVIP是否转换为新模式"
    ,LastVipToken                 varchar(512)                             comment "上次购买VIP或SVIP的token"
    ,LastItemId                   varchar(512)                             comment "上次购买VIP或SVIP的itemid"
    ,LowVipSecondsStartTime       datetime                                 comment "VIP赠送开始时间"
    ,VipSecondsStartTime          datetime                                 comment "SVIP赠送开始时间"
    ,VipDeviceId                  bigint                                   comment "VIP设备id"
    ,BlockedDeviceIdList          varchar(1024)                            comment "黑名单设备id列表"
    ,VipCardPrice                 int            not null                  comment "VIP卡价格"
    ,DeepLinkPlatform             int                                      comment "DeepLink来源平台"
    ,AdjustId                     varchar(250)                             comment "AdjustId"
    ,TodayItemCount               int                                      comment "今日充值美元"
    ,EnergyRipeRemind             tinyint                                  comment "能量成熟提醒"
    ,EnergyStolenRemind           tinyint                                  comment "能量被偷提醒"
    ,EnergyExpireRemind           tinyint                                  comment "能量过期提醒"
    ,EnergyWeekRankTimes          int                                      comment "周公益大使获取次数"
    ,EnergyMedalWear              varchar(512)                             comment "能量勋章佩戴"
    ,BonusSignCardTime            datetime                                 comment "阅币福利包到期时间"
    ,BonusSignCardPlusTime        datetime                                 comment "阅币福利包Plus到期时间"
    ,UserShopType                 int                                      comment "用户商城类型"
    ,LastBuyBonusSignCardTime     datetime                                 comment "上次购买福利包时间"
    ,LastBuyBonusSignCardPlusTime datetime                                 comment "上次购买Plus时间"
    ,UserMaxChargeAmount          decimal(10, 0) not null                  comment "最高充值档位"
    ,LastPaymentId                varchar(50)                              comment "上次第三方支付信息"
    ,ActHeadFrame                 varchar(500)                             comment "活动头像框"
    ,LastChargeTime               datetime                                 comment "上次充值时间"
    ,row_update_time              datetime                                 comment "更新时间"
    ,IsNewJiFenUser               tinyint                                  comment "是否进入过新积分UI"
    ,UserUseHeadFrame             varchar(512)                             comment "当前佩戴头像框"
    ,UserUseHeadFrameExpireTime   datetime                                 comment "头像框过期时间"
    ,UserUseHeadFrameType         varchar(50)                              comment "头像框类型"
    ,Ram                          int                                      comment "手机内存"
    ,Brand                        varchar(255)                             comment "手机品牌"
    ,row_create_time              datetime                                 comment "创建时间"
    ,VipCardType                  int                                      comment "VIP卡类型"
    ,VipCardActualPrice           decimal(18, 2)                           comment "VIP卡实际价格"
    ,SVipCardActualPrice          decimal(18, 2)                           comment "SVIP卡实际价格"
    ,Device2                      varchar(765)                             comment "设备2"
    ,UserSource                   int                                      comment "海剧PWA用户来源标签"
    ,etl_tm                       datetime       default current_timestamp comment "清洗时间"
    ,index index_product_id (product_id) using bitmap comment "产品id索引"
)
primary key(product_id, Id)
comment "海阅PWA用户阅读时长同步表"
distributed by hash(product_id, Id) buckets 20
properties (
    "replication_num" = "3",
    "bloom_filter_columns" = "row_create_time, Id",
    "in_memory" = "false",
    "enable_persistent_index" = "true",
    "replicated_storage" = "true",
    "compression" = "LZ4"
)
;
