CREATE VIEW `ads_cv_ad_roi_warning_view` (`stat_start_time` COMMENT "统计区间,开始时间", `stat_end_time` COMMENT "统计区间,结束时间", `ad_id` COMMENT "广告id", `ad_name` COMMENT "广告名", `nick_name` COMMENT "昵称", `product_name` COMMENT "产品", `campaign_name` COMMENT "活动名称", `account_id` COMMENT "账户id", `hour_consume_amt` COMMENT "近一小时消耗（投放）", `day_consume_amt` COMMENT "当日消耗（投放）", `hour_recharge_amt` COMMENT "近一小时充值", `hour_ad_income_amt` COMMENT "近一小时广告收入", `day_recharge_amt` COMMENT "当日充值收入", `day_ad_income_amt` COMMENT "当日广告收入", `day_total_income_amt` COMMENT "当日总收入", `hour_roi` COMMENT "近一小时roi", `day_roi` COMMENT "当日roi", `tf_h_conf` COMMENT "近一小时投放预警 阈值", `hour_roi_rate_conf` COMMENT "roi预警阈值", `day_roi_rate_conf` COMMENT "roi预警阈值", `ding_user_id` COMMENT "at人id", `etl_tm` COMMENT "数据etl时间")
COMMENT "国剧--广告投放消耗告警统计-视图" AS WITH `hour_consume` (`ad_name`, `ad_id`, `hour_consume_amt`) AS (SELECT `res`.`ad_name`, `res`.`ad_id`, sum(CASE WHEN `res`.`is_now_hour` THEN `res`.`max_spend` ELSE (`res`.`max_spend` - `res`.`flag_spend`) END) AS `hour_consume_amt`
FROM (SELECT `res`.`ad_name`, `res`.`ad_id`, `res`.`date_start`, max(`res`.`spend_sum`) AS `max_spend`, max(CASE WHEN (`res`.`snap_time` < (date_sub(current_time(), INTERVAL 1 HOUR))) THEN `res`.`spend_sum` ELSE 0 END) AS `flag_spend`, CASE WHEN ((date_format(min(`res`.`snap_time`), '%Y-%m-%d %H:00:00')) = (date_format(current_time(), '%Y-%m-%d %H:00:00'))) THEN TRUE ELSE FALSE END AS `is_now_hour`
FROM (SELECT `dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_snap_view`.`ad_name`, `dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_snap_view`.`ad_id`, `dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_snap_view`.`date_start`, `dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_snap_view`.`snap_time`, sum(`dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_snap_view`.`spend`) AS `spend_sum`
FROM `dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_snap_view`
WHERE (((`dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_snap_view`.`dt` >= (date_format(date_sub(current_time(), INTERVAL 1 HOUR), '%Y-%m-%d'))) AND (`dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_snap_view`.`spend` > 0)) AND ((date_format(`dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_snap_view`.`date_start`, '%Y-%m-%d %H:%i:%s')) >= (date_format(date_sub(current_time(), INTERVAL 1 HOUR), '%Y-%m-%d %H:00:00')))) AND (`dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_snap_view`.`snap_time` <= (date_sub(current_time(), INTERVAL 30 MINUTE)))
GROUP BY `dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_snap_view`.`ad_name`, `dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_snap_view`.`ad_id`, `dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_snap_view`.`date_start`, `dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_snap_view`.`snap_time`) `res`
GROUP BY `res`.`ad_name`, `res`.`ad_id`, `res`.`date_start`) `res`
GROUP BY `res`.`ad_name`, `res`.`ad_id`) , `day_consume` (`ad_name`, `ad_id`, `day_consume_amt`) AS (SELECT `dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_view`.`ad_name`, `dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_view`.`ad_id`, sum(`dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_view`.`spend`) AS `day_consume_amt`
FROM `dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_view`
WHERE (`dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_view`.`spend` > 0) AND (`dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_view`.`dt` = (current_date()))
GROUP BY `dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_view`.`ad_name`, `dwd`.`dwd_advertisement_video_cn_dailyinsightbyhour_view`.`ad_id`) , `user_ad_ecpm` (`VideoUserId`, `AdId`, `CreateTime`, `Amount`) AS (SELECT `ods`.`ods_tidb_cdvideo_tidb_xcx_sync_ad_reward_video_log_da`.`user_id` AS `VideoUserId`, `ods`.`ods_tidb_cdvideo_tidb_xcx_sync_ad_reward_video_log_da`.`promotion_id` AS `AdId`, `ods`.`ods_tidb_cdvideo_tidb_xcx_sync_ad_reward_video_log_da`.`ad_event_time` AS `CreateTime`, sum(`ods`.`ods_tidb_cdvideo_tidb_xcx_sync_ad_reward_video_log_da`.`ecpm`) AS `Amount`
FROM `ods`.`ods_tidb_cdvideo_tidb_xcx_sync_ad_reward_video_log_da`
WHERE (`ods`.`ods_tidb_cdvideo_tidb_xcx_sync_ad_reward_video_log_da`.`ecpm` > 0) AND (`ods`.`ods_tidb_cdvideo_tidb_xcx_sync_ad_reward_video_log_da`.`ad_event_time` > (date_add(current_date(), INTERVAL -2 DAY)))
GROUP BY 1, 2, 3) , `ad_income` (`ad_id`, `day_income_amt`, `hour_income_amt`) AS (SELECT `a`.`ad_id`, sum(CASE WHEN (`a`.`install_date` >= (current_date())) THEN `a`.`amount` ELSE 0 END) AS `day_income_amt`, sum(CASE WHEN (`a`.`install_date` >= (date_format(date_sub(current_time(), INTERVAL 1 HOUR), '%Y-%m-%d %H:%i:00'))) THEN `a`.`amount` ELSE 0 END) AS `hour_income_amt`
FROM (SELECT `i`.`Amount` / 100000 AS `amount`, `i`.`VideoUserId`, `attribution`.`install_date`, `attribution`.`ad_id`
FROM `user_ad_ecpm` AS i INNER JOIN (SELECT `dwd`.`dwd_user_install_info_ed_view`.`user_id`, `dwd`.`dwd_user_install_info_ed_view`.`core`, `dwd`.`dwd_user_install_info_ed_view`.`install_date`, `dwd`.`dwd_user_install_info_ed_view`.`remarketing_time`, CASE WHEN ((`dwd`.`dwd_user_install_info_ed_view`.`ad_id` IS NULL) OR (`dwd`.`dwd_user_install_info_ed_view`.`ad_id` = '')) THEN (concat('AdId=none|SourceChl=', CASE WHEN ((`dwd`.`dwd_user_install_info_ed_view`.`Source` IS NULL) OR (`dwd`.`dwd_user_install_info_ed_view`.`Source` = '')) THEN 'none' ELSE `dwd`.`dwd_user_install_info_ed_view`.`Source` END, '|Mt=', concat(`dwd`.`dwd_user_install_info_ed_view`.`Mt`, ''), '|Core=', concat(`dwd`.`dwd_user_install_info_ed_view`.`Core`, ''), '|Chl2=', CASE WHEN ((`dwd`.`dwd_user_install_info_ed_view`.`Chl2` IS NULL) OR (`dwd`.`dwd_user_install_info_ed_view`.`Chl2` = '')) THEN 'none' ELSE `dwd`.`dwd_user_install_info_ed_view`.`Chl2` END, '|CurrentLanguage2=', concat(`dwd`.`dwd_user_install_info_ed_view`.`Current_Language2`, ''))) ELSE `dwd`.`dwd_user_install_info_ed_view`.`ad_id` END AS `ad_id`, `dwd`.`dwd_user_install_info_ed_view`.`next_attribute_time`, `dwd`.`dwd_user_install_info_ed_view`.`Unique_CdReaderId`
FROM `dwd`.`dwd_user_install_info_ed_view`
WHERE ((((`dwd`.`dwd_user_install_info_ed_view`.`is_remarketing` = 0) AND (`dwd`.`dwd_user_install_info_ed_view`.`adaccount_id` NOT IN ('6498009b0c801c4baafeb622'))) AND (`dwd`.`dwd_user_install_info_ed_view`.`product_id` = '6883')) AND (`dwd`.`dwd_user_install_info_ed_view`.`user_id` > 0)) AND (`dwd`.`dwd_user_install_info_ed_view`.`dt` >= (date_format(date_sub(current_time(), INTERVAL 1 HOUR), '%Y-%m-%d')))) `attribution` ON (((`i`.`VideoUserId` = `attribution`.`Unique_CdReaderId`) AND (`i`.`CreateTime` >= `attribution`.`install_date`)) AND (`i`.`CreateTime` <= `attribution`.`next_attribute_time`)) AND (`i`.`CreateTime` <= `attribution`.`remarketing_time`)
WHERE `i`.`CreateTime` >= (date_format(date_sub(current_time(), INTERVAL 1 HOUR), '%Y-%m-%d'))) `a`
GROUP BY `a`.`ad_id`) , `recharge` (`ad_id`, `day_recharge_amt`, `hour_recharge_amt`) AS (SELECT `a`.`ad_id`, sum(CASE WHEN (`a`.`install_date` >= (current_date())) THEN `a`.`amount` ELSE 0 END) AS `day_recharge_amt`, sum(CASE WHEN (`a`.`install_date` >= (date_format(date_sub(current_time(), INTERVAL 1 HOUR), '%Y-%m-%d %H:%i:00'))) THEN `a`.`amount` ELSE 0 END) AS `hour_recharge_amt`
FROM (SELECT `dwd`.`pay`.`base_amount_rmb` AS `amount`, `dwd`.`pay`.`video_user_id`, `attribution`.`install_date`, `attribution`.`ad_id`
FROM `dwd`.`dwd_trade_video_cn_payorder_view` AS `pay` INNER JOIN (SELECT `dwd`.`dwd_user_install_info_ed_view`.`user_id`, `dwd`.`dwd_user_install_info_ed_view`.`core`, `dwd`.`dwd_user_install_info_ed_view`.`install_date`, `dwd`.`dwd_user_install_info_ed_view`.`remarketing_time`, CASE WHEN ((`dwd`.`dwd_user_install_info_ed_view`.`ad_id` IS NULL) OR (`dwd`.`dwd_user_install_info_ed_view`.`ad_id` = '')) THEN (concat('AdId=none|SourceChl=', CASE WHEN ((`dwd`.`dwd_user_install_info_ed_view`.`Source` IS NULL) OR (`dwd`.`dwd_user_install_info_ed_view`.`Source` = '')) THEN 'none' ELSE `dwd`.`dwd_user_install_info_ed_view`.`Source` END, '|Mt=', concat(`dwd`.`dwd_user_install_info_ed_view`.`Mt`, ''), '|Core=', concat(`dwd`.`dwd_user_install_info_ed_view`.`Core`, ''), '|Chl2=', CASE WHEN ((`dwd`.`dwd_user_install_info_ed_view`.`Chl2` IS NULL) OR (`dwd`.`dwd_user_install_info_ed_view`.`Chl2` = '')) THEN 'none' ELSE `dwd`.`dwd_user_install_info_ed_view`.`Chl2` END, '|CurrentLanguage2=', concat(`dwd`.`dwd_user_install_info_ed_view`.`Current_Language2`, ''))) ELSE `dwd`.`dwd_user_install_info_ed_view`.`ad_id` END AS `ad_id`, `dwd`.`dwd_user_install_info_ed_view`.`next_attribute_time`, `dwd`.`dwd_user_install_info_ed_view`.`Unique_CdReaderId`
FROM `dwd`.`dwd_user_install_info_ed_view`
WHERE ((((`dwd`.`dwd_user_install_info_ed_view`.`is_remarketing` = 0) AND (`dwd`.`dwd_user_install_info_ed_view`.`adaccount_id` NOT IN ('6498009b0c801c4baafeb622'))) AND (`dwd`.`dwd_user_install_info_ed_view`.`product_id` = '6883')) AND (`dwd`.`dwd_user_install_info_ed_view`.`user_id` > 0)) AND (`dwd`.`dwd_user_install_info_ed_view`.`dt` >= (date_format(date_sub(current_time(), INTERVAL 1 HOUR), '%Y-%m-%d')))) `attribution` ON ((((`dwd`.`pay`.`video_user_id` = `attribution`.`Unique_CdReaderId`) AND (`dwd`.`pay`.`core` = `attribution`.`core`)) AND (`dwd`.`pay`.`create_time` >= `attribution`.`install_date`)) AND (`dwd`.`pay`.`create_time` <= `attribution`.`next_attribute_time`)) AND (`dwd`.`pay`.`create_time` <= `attribution`.`remarketing_time`)
WHERE (((`dwd`.`pay`.`dt` >= (date_format(date_sub(current_time(), INTERVAL 1 HOUR), '%Y-%m-%d'))) AND (`dwd`.`pay`.`coo_order_status` = 1)) AND (`dwd`.`pay`.`test_flag` = 0)) AND (`dwd`.`pay`.`product_id` = '6883')) `a`
GROUP BY `a`.`ad_id`) , `ad_info` (`ad_id`, `nick_name`, `campaign_name`, `product_name`, `fb_account`, `ding_user_id`) AS (SELECT `a`.`ad_id`, `dim`.`b`.`nick_name`, `c`.`campaign_name`, `d`.`product_name`, `a`.`fb_account`, `f`.`ding_user_id`
FROM (SELECT `dwd`.`dwd_advertisement_adext_view`.`ad_id`, `dwd`.`dwd_advertisement_adext_view`.`create_time`, `dwd`.`dwd_advertisement_adext_view`.`ad_name`, `dwd`.`dwd_advertisement_adext_view`.`invite_code`, `dwd`.`dwd_advertisement_adext_view`.`ad_camp_id`, `dwd`.`dwd_advertisement_adext_view`.`fb_account`
FROM `dwd`.`dwd_advertisement_adext_view`
WHERE `dwd`.`dwd_advertisement_adext_view`.`product_id` = 6883) `a` LEFT OUTER JOIN `dim`.`dim_ads_role_users_view` AS `b` ON `a`.`invite_code` = `dim`.`b`.`ref_id` LEFT OUTER JOIN (SELECT `dim`.`dim_advertisement_third_ad_campaign_view`.`campaign_name`, `dim`.`dim_advertisement_third_ad_campaign_view`.`camp_id`
FROM `dim`.`dim_advertisement_third_ad_campaign_view`
WHERE `dim`.`dim_advertisement_third_ad_campaign_view`.`ad_platform_id` > 0) `c` ON `a`.`ad_camp_id` = `c`.`camp_id` LEFT OUTER JOIN (SELECT `dim`.`dim_advertisement_third_ad_account_view`.`account`, `dim`.`dim_advertisement_third_ad_account_view`.`product_name`
FROM `dim`.`dim_advertisement_third_ad_account_view`
WHERE (`dim`.`dim_advertisement_third_ad_account_view`.`ad_platform_id` > 0) AND (`dim`.`dim_advertisement_third_ad_account_view`.`product_id` = 6883)) `d` ON `a`.`fb_account` = `d`.`account` LEFT OUTER JOIN (SELECT `dim`.`dim_kpi_user_info_view`.`nick_name`, `dim`.`dim_kpi_user_info_view`.`ding_user_id`
FROM `dim`.`dim_kpi_user_info_view`
WHERE (`dim`.`dim_kpi_user_info_view`.`del_flag` = 0) AND (`dim`.`dim_kpi_user_info_view`.`ding_user_id` IS NOT NULL)) `f` ON `dim`.`b`.`nick_name` = `f`.`nick_name`) SELECT `res`.`stat_start_time`, `res`.`stat_end_time`, `res`.`ad_id`, `res`.`ad_name`, `res`.`nick_name`, `res`.`product_name`, `res`.`campaign_name`, `res`.`account_id`, `res`.`hour_consume_amt`, `res`.`day_consume_amt`, `res`.`hour_recharge_amt`, `res`.`hour_ad_income_amt`, `res`.`day_recharge_amt`, `res`.`day_ad_income_amt`, ifnull(round(`res`.`day_recharge_amt` + `res`.`day_ad_income_amt`, 2), 0.00) AS `day_total_amt`, ifnull(round(((`res`.`hour_recharge_amt` + `res`.`hour_ad_income_amt`) / `res`.`hour_consume_amt`) * 100, 2), 0.00) AS `hour_roi`, ifnull(round(((`res`.`day_recharge_amt` + `res`.`day_ad_income_amt`) / `res`.`day_consume_amt`) * 100, 2), 0.00) AS `day_roi`, 100 AS `tf_h_conf`, 50 AS `hour_roi_rate_conf`, 70 AS `day_roi_rate_conf`, `res`.`ding_user_id`, now() AS `etl_tm`
FROM (SELECT date_format(date_sub(current_time(), INTERVAL 1 HOUR), '%Y-%m-%d  %H:%i') AS `stat_start_time`, date_format(date_sub(current_time(), INTERVAL 30 MINUTE), '%Y-%m-%d  %H:%i') AS `stat_end_time`, `hour_consume`.`ad_id`, `hour_consume`.`ad_name`, `ad_info`.`nick_name`, `ad_info`.`product_name`, `ad_info`.`campaign_name`, `ad_info`.`fb_account` AS `account_id`, ifnull(round(`hour_consume`.`hour_consume_amt`, 2), 0.00) AS `hour_consume_amt`, ifnull(round(`day_consume`.`day_consume_amt`, 2), 0.00) AS `day_consume_amt`, ifnull(round(`recharge`.`hour_recharge_amt`, 2), 0.00) AS `hour_recharge_amt`, ifnull(round(`ad_income`.`hour_income_amt`, 2), 0.00) AS `hour_ad_income_amt`, ifnull(round(`recharge`.`day_recharge_amt`, 2), 0.00) AS `day_recharge_amt`, ifnull(round(`ad_income`.`day_income_amt`, 2), 0.00) AS `day_ad_income_amt`, `ad_info`.`ding_user_id`
FROM `hour_consume` LEFT OUTER JOIN `day_consume` ON `hour_consume`.`ad_id` = `day_consume`.`ad_id` LEFT OUTER JOIN `recharge` ON `hour_consume`.`ad_id` = `recharge`.`ad_id` LEFT OUTER JOIN `ad_income` ON `hour_consume`.`ad_id` = `ad_income`.`ad_id` LEFT OUTER JOIN `ad_info` ON `hour_consume`.`ad_id` = `ad_info`.`ad_id`) `res`;