drop table if exists ads.ads_sv_act_user_stat_mi;
create table ads.ads_sv_act_user_stat_mi (
     dt                          date            not null comment "日期分区(月)"
    ,projectId                   int             not null comment "项目id"
    ,totalUsers                  int             not null comment "总的用户数"
    ,arpuMean                    varchar(50)              comment "ARPU均值"
    ,arpuSt                      varchar(50)              comment "ARPU标准差"
    ,arpuVar                     varchar(50)              comment "ARPU方差"
    ,payRateMean                 varchar(50)              comment "付费率均值"
    ,payRateSt                   varchar(50)              comment "付费率标准差"
    ,payRateVar                  varchar(50)              comment "付费率方差"
    ,payAllRateMean              varchar(50)              comment "单人转化率均值(总)"
    ,payAllRateSt                varchar(50)              comment "单人转化率标准差(总)"
    ,payAllRateVar               varchar(50)              comment "单人转化率方差(总)"
    ,adverArpuMean               varchar(50)              comment "广告ARPU均值"
    ,adverArpuSt                 varchar(50)              comment "广告ARPU标准差"
    ,adverArpuVar                varchar(50)              comment "广告ARPU方差"
    ,totalAdverArpuMean          varchar(50)              comment "总广告ARPU均值"
    ,totalAdverArpuSt            varchar(50)              comment "总广告ARPU标准差"
    ,totalAdverArpuVar           varchar(50)              comment "总广告ARPU方差"
    ,adverUnlockRateMean         varchar(50)              comment "广告解锁率均值"
    ,adverUnlockRateSt           varchar(50)              comment "广告解锁率标准差"
    ,adverUnlockRateVar          varchar(50)              comment "广告解锁率方差"
    ,adverUnlockEpisodeNumMean   varchar(50)              comment "人均广告解锁剧集均值"
    ,adverUnlockEpisodeNumSt     varchar(50)              comment "人均广告解锁剧集标准差"
    ,adverUnlockEpisodeNumVar    varchar(50)              comment "人均广告解锁剧集方差"
    ,oneExposureArpuMean         decimal(20, 6)           comment "单人曝光ARPU均值"
    ,oneExposureArpuSt           decimal(20, 6)           comment "单人曝光ARPU标准差"
    ,oneExposureArpuVar          decimal(20, 6)           comment "单人曝光ARPU方差"
    ,oneExposureAllArpuMean      varchar(50)              comment "单人ARPU均值(总)"
    ,oneExposureAllArpuSt        varchar(50)              comment "单人ARPU标准差(总)"
    ,oneExposureAllArpuVar       varchar(50)              comment "单人ARPU方差(总)"
    ,oneExposureArpuDingYueMean  decimal(20, 6)           comment "单人曝光ARPU(订阅)均值"
    ,oneExposureArpuDingYueSt    decimal(20, 6)           comment "单人曝光ARPU(订阅)标准差"
    ,oneExposureArpuDingYueVar   decimal(20, 6)           comment "单人曝光ARPU(订阅)方差"
    ,oneRechargePercentMean      decimal(20, 6)           comment "单次充值占比均值"
    ,oneRechargePercentSt        decimal(20, 6)           comment "单次充值占比标准差"
    ,oneRechargePercentVar       decimal(20, 6)           comment "单次充值占比方差"
    ,dingYueAmountPercentMean    decimal(20, 6)           comment "订阅金额占比均值"
    ,dingYueAmountPercentSt      decimal(20, 6)           comment "订阅金额占比标准差"
    ,dingYueAmountPercentVar     decimal(20, 6)           comment "订阅金额占比方差"
    ,dingYueAmountAllPercentMean decimal(20, 6)           comment "订阅金额占比(总)均值(总)"
    ,dingYueAmountAllPercentSt   decimal(20, 6)           comment "订阅金额占比(总)标准差(总)"
    ,dingYueAmountAllPercentVar  decimal(20, 6)           comment "订阅金额占比(总)方差(总)"
    ,orderCreateRateMean         decimal(20, 6)           comment "订单创建率均值"
    ,orderCreateRateSt           decimal(20, 6)           comment "订单创建率标准差"
    ,orderCreateRateVar          decimal(20, 6)           comment "订单创建率方差"
    ,predictARPUMean             decimal(20, 6)           comment "预估ARPU均值"
    ,predictARPUSt               decimal(20, 6)           comment "预估ARPU标准差"
    ,predictARPUVar              decimal(20, 6)           comment "预估ARPU方差"
    ,buyersNum                   int                      comment "购买总人数"
    ,buyAmount                   decimal(12, 2)           comment "购买总金额"
    ,unlockArppuMean             decimal(20, 6)           comment "人均解锁ARPPU均值"
    ,unlockArppuSt               decimal(20, 6)           comment "人均解锁ARPPU标准差"
    ,unlockArppuVar              decimal(20, 6)           comment "人均解锁ARPPU方差"
    ,unlockArpuMean              decimal(20, 6)           comment "人均解锁ARPU均值"
    ,unlockArpuSt                decimal(20, 6)           comment "人均解锁ARPU标准差"
    ,unlockArpuVar               decimal(20, 6)           comment "人均解锁ARPU方差"
    ,saveTime                    datetime                 comment "入库时间"
    ,updateTime                  datetime                 comment "更新时间"
    ,watchEpisodeNumAvgMean      decimal(20, 6)           comment "人均观看集数均值"
    ,watchEpisodeNumAvgSt        decimal(20, 6)           comment "人均观看集数标准差"
    ,watchEpisodeNumAvgVar       decimal(20, 6)           comment "人均观看集数方差"
)
primary key(dt, projectId)
comment "用户统计月度表"
distributed by hash(dt) buckets 6
properties (
    "replication_num" = "3",
    "in_memory" = "false",
    "enable_persistent_index" = "true",
    "replicated_storage" = "true",
    "fast_schema_evolution" = "true",
    "compression" = "LZ4"
)
;