CREATE VIEW `ads_ad_html5_abtest_config_view` (`book_id`, `book_code`, `put_url`, `id`, `abtest_title`, `config_id`, `file_name`, `update_time`, `end_time`) AS SELECT `a`.`book_id`, `a`.`book_code`, `a`.`put_url`, `a`.`id`, `a`.`abtest_title`, `a`.`config_id`, `a`.`file_name`, `a`.`update_time`, lead(`a`.`update_time`, 1, '2099-01-01 00:00:00') OVER (PARTITION BY `a`.`id`, `a`.`config_id` ORDER BY `a`.`update_time` ASC ) AS `end_time`
FROM (SELECT `url`.`book_id`, `url`.`book_code`, `url`.`put_url`, `url`.`id`, `url`.`abtest_title`, `url`.`config_id`, `url`.`file_name`, `url`.`update_time`
FROM (SELECT `ads`.`ads_ad_html5_ab_test_config_log_view`.`book_id`, `ads`.`ads_ad_html5_ab_test_config_log_view`.`book_code`, `ads`.`ads_ad_html5_ab_test_config_log_view`.`put_url`, `ads`.`ads_ad_html5_ab_test_config_log_view`.`id`, `ads`.`ads_ad_html5_ab_test_config_log_view`.`title` AS `abtest_title`, get_json_string(`ads`.`ads_ad_html5_ab_test_config_log_view`.`Page1`, '$.PageId') AS `config_id`, get_json_string(`ads`.`ads_ad_html5_ab_test_config_log_view`.`Page1`, '$.FileName') AS `file_name`, `ads`.`ads_ad_html5_ab_test_config_log_view`.`update_time`
FROM `ads`.`ads_ad_html5_ab_test_config_log_view`
WHERE `ads`.`ads_ad_html5_ab_test_config_log_view`.`ModifyType` = 3 UNION ALL SELECT `ads`.`ads_ad_html5_ab_test_config_log_view`.`book_id`, `ads`.`ads_ad_html5_ab_test_config_log_view`.`book_code`, `ads`.`ads_ad_html5_ab_test_config_log_view`.`put_url`, `ads`.`ads_ad_html5_ab_test_config_log_view`.`id`, `ads`.`ads_ad_html5_ab_test_config_log_view`.`title` AS `abtest_title`, get_json_string(`ads`.`ads_ad_html5_ab_test_config_log_view`.`Page2`, '$.PageId') AS `config_id`, get_json_string(`ads`.`ads_ad_html5_ab_test_config_log_view`.`Page2`, '$.FileName') AS `file_name`, `ads`.`ads_ad_html5_ab_test_config_log_view`.`update_time`
FROM `ads`.`ads_ad_html5_ab_test_config_log_view`
WHERE `ads`.`ads_ad_html5_ab_test_config_log_view`.`ModifyType` = 3 UNION ALL SELECT `ads`.`ads_ad_html5_ab_test_config_log_view`.`book_id`, `ads`.`ads_ad_html5_ab_test_config_log_view`.`book_code`, `ads`.`ads_ad_html5_ab_test_config_log_view`.`put_url`, `ads`.`ads_ad_html5_ab_test_config_log_view`.`id`, `ads`.`ads_ad_html5_ab_test_config_log_view`.`title` AS `abtest_title`, get_json_string(`ads`.`ads_ad_html5_ab_test_config_log_view`.`Page3`, '$.PageId') AS `config_id`, get_json_string(`ads`.`ads_ad_html5_ab_test_config_log_view`.`Page3`, '$.FileName') AS `file_name`, `ads`.`ads_ad_html5_ab_test_config_log_view`.`update_time`
FROM `ads`.`ads_ad_html5_ab_test_config_log_view`
WHERE `ads`.`ads_ad_html5_ab_test_config_log_view`.`ModifyType` = 3) `url`
WHERE `url`.`config_id` > 0
GROUP BY 1, 2, 3, 4, 5, 6, 7, 8 UNION ALL SELECT `url`.`book_id`, `url`.`book_code`, `url`.`put_url`, `url`.`id`, `url`.`abtest_title`, `url`.`config_id`, `url`.`file_name`, `url`.`update_time`
FROM (SELECT `ods`.`ods_tidb_sharpengine_ads_global_AdHtml5AbTestConfig_history`.`BookId` AS `book_id`, `ods`.`ods_tidb_sharpengine_ads_global_AdHtml5AbTestConfig_history`.`BookCode` AS `book_code`, `ods`.`ods_tidb_sharpengine_ads_global_AdHtml5AbTestConfig_history`.`PutUrl` AS `put_url`, `ods`.`ods_tidb_sharpengine_ads_global_AdHtml5AbTestConfig_history`.`id`, `ods`.`ods_tidb_sharpengine_ads_global_AdHtml5AbTestConfig_history`.`title` AS `abtest_title`, get_json_string(`ods`.`ods_tidb_sharpengine_ads_global_AdHtml5AbTestConfig_history`.`Page1`, '$.PageId') AS `config_id`, get_json_string(`ods`.`ods_tidb_sharpengine_ads_global_AdHtml5AbTestConfig_history`.`Page1`, '$.FileName') AS `file_name`, `ods`.`ods_tidb_sharpengine_ads_global_AdHtml5AbTestConfig_history`.`CreateTime` AS `update_time`
FROM `ods`.`ods_tidb_sharpengine_ads_global_AdHtml5AbTestConfig_history` UNION ALL SELECT `ods`.`ods_tidb_sharpengine_ads_global_AdHtml5AbTestConfig_history`.`BookId` AS `book_id`, `ods`.`ods_tidb_sharpengine_ads_global_AdHtml5AbTestConfig_history`.`BookCode` AS `book_code`, `ods`.`ods_tidb_sharpengine_ads_global_AdHtml5AbTestConfig_history`.`PutUrl` AS `put_url`, `ods`.`ods_tidb_sharpengine_ads_global_AdHtml5AbTestConfig_history`.`id`, `ods`.`ods_tidb_sharpengine_ads_global_AdHtml5AbTestConfig_history`.`title` AS `abtest_title`, get_json_string(`ods`.`ods_tidb_sharpengine_ads_global_AdHtml5AbTestConfig_history`.`Page2`, '$.PageId') AS `config_id`, get_json_string(`ods`.`ods_tidb_sharpengine_ads_global_AdHtml5AbTestConfig_history`.`Page2`, '$.FileName') AS `file_name`, `ods`.`ods_tidb_sharpengine_ads_global_AdHtml5AbTestConfig_history`.`CreateTime` AS `update_time`
FROM `ods`.`ods_tidb_sharpengine_ads_global_AdHtml5AbTestConfig_history` UNION ALL SELECT `ods`.`ods_tidb_sharpengine_ads_global_AdHtml5AbTestConfig_history`.`BookId` AS `book_id`, `ods`.`ods_tidb_sharpengine_ads_global_AdHtml5AbTestConfig_history`.`BookCode` AS `book_code`, `ods`.`ods_tidb_sharpengine_ads_global_AdHtml5AbTestConfig_history`.`PutUrl` AS `put_url`, `ods`.`ods_tidb_sharpengine_ads_global_AdHtml5AbTestConfig_history`.`id`, `ods`.`ods_tidb_sharpengine_ads_global_AdHtml5AbTestConfig_history`.`title` AS `abtest_title`, get_json_string(`ods`.`ods_tidb_sharpengine_ads_global_AdHtml5AbTestConfig_history`.`Page3`, '$.PageId') AS `config_id`, get_json_string(`ods`.`ods_tidb_sharpengine_ads_global_AdHtml5AbTestConfig_history`.`Page3`, '$.FileName') AS `file_name`, `ods`.`ods_tidb_sharpengine_ads_global_AdHtml5AbTestConfig_history`.`CreateTime` AS `update_time`
FROM `ods`.`ods_tidb_sharpengine_ads_global_AdHtml5AbTestConfig_history`) `url`
WHERE `url`.`config_id` > 0
GROUP BY 1, 2, 3, 4, 5, 6, 7, 8) `a`
GROUP BY 1, 2, 3, 4, 5, 6, 7, 8;