CREATE TABLE `ads_bi_charge_ltv_est` (
  `md5_key` varchar(255) NOT NULL COMMENT "md5_key",
  `dt` date NULL COMMENT "日期,来自stat_period",
  `user_period` int(11) NULL COMMENT "用户类型 1：新用户 3：rmt(拉活用户)",
  `product_id` int(11) NULL COMMENT "产品id",
  `which_weeks` int(11) NULL COMMENT "第几周",
  `which_months` int(11) NULL COMMENT "第几月",
  `corever` int(11) NULL COMMENT "core",
  `mt` int(11) NULL COMMENT "终端",
  `reg_country` varchar(255) NULL COMMENT "国家",
  `country_level` int(11) NULL COMMENT "国家等级",
  `current_language2` int(11) NULL COMMENT "注册语言",
  `source` int(11) NULL COMMENT "3是付费 2是官网  1 是自然和其他 ",
  `chl2` varchar(255) NULL COMMENT "注册时渠道",
  `chl` varchar(255) NULL COMMENT "最新渠道",
  `source_chl` varchar(255) NULL COMMENT "最新引流渠道",
  `user_ad_source` int(11) NULL COMMENT "广告投流用户：0：正常用户，1：vip投流用户",
  `unt` int(11) NULL COMMENT "",
  `pay_user_cnt0` int(11) NULL COMMENT "",
  `ltv0` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt1` int(11) NULL COMMENT "",
  `ltv1` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt2` int(11) NULL COMMENT "",
  `ltv2` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt3` int(11) NULL COMMENT "",
  `ltv3` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt4` int(11) NULL COMMENT "",
  `ltv4` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt5` int(11) NULL COMMENT "",
  `ltv5` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt6` int(11) NULL COMMENT "",
  `ltv6` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt7` int(11) NULL COMMENT "",
  `ltv7` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt8` int(11) NULL COMMENT "",
  `ltv8` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt9` int(11) NULL COMMENT "",
  `ltv9` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt10` int(11) NULL COMMENT "",
  `ltv10` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt11` int(11) NULL COMMENT "",
  `ltv11` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt12` int(11) NULL COMMENT "",
  `ltv12` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt13` int(11) NULL COMMENT "",
  `ltv13` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt14` int(11) NULL COMMENT "",
  `ltv14` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt15` int(11) NULL COMMENT "",
  `ltv15` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt16` int(11) NULL COMMENT "",
  `ltv16` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt17` int(11) NULL COMMENT "",
  `ltv17` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt18` int(11) NULL COMMENT "",
  `ltv18` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt19` int(11) NULL COMMENT "",
  `ltv19` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt20` int(11) NULL COMMENT "",
  `ltv20` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt21` int(11) NULL COMMENT "",
  `ltv21` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt22` int(11) NULL COMMENT "",
  `ltv22` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt23` int(11) NULL COMMENT "",
  `ltv23` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt24` int(11) NULL COMMENT "",
  `ltv24` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt25` int(11) NULL COMMENT "",
  `ltv25` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt26` int(11) NULL COMMENT "",
  `ltv26` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt27` int(11) NULL COMMENT "",
  `ltv27` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt28` int(11) NULL COMMENT "",
  `ltv28` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt29` int(11) NULL COMMENT "",
  `ltv29` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt30` int(11) NULL COMMENT "",
  `ltv30` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt45` int(11) NULL COMMENT "",
  `ltv45` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt60` int(11) NULL COMMENT "",
  `ltv60` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt90` int(11) NULL COMMENT "",
  `ltv90` decimal(12, 2) NULL COMMENT "",
  `pay_user_cnt120` int(11) NULL COMMENT "",
  `ltv120` decimal(12, 2) NULL COMMENT "",
  `etl_tm` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "etl清洗时间"
) ENGINE=OLAP 
PRIMARY KEY(`md5_key`)
COMMENT "海剧档位充值ltv（西五区）"
DISTRIBUTED BY HASH(`md5_key`) BUCKETS 3 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);