----------------------------------------------------------------
-- project_name     : starrocks
-- workflow_name    : tbl_ads_bi_user_book_consume_info
-- workflow_version : 7
-- create_user      : yanxh
-- task_name        : delete from ads.ads_bi_user_book_consume_info where dt = '${bf_1_dt}';
-- task_version     : 1
-- update_time      : 2025-09-18 14:23:59
-- sql_path         : \starrocks\tbl_ads_bi_user_book_consume_info\delete from ads.ads_bi_user_book_consume_info where dt = '${bf_1_dt}';
----------------------------------------------------------------
-- SQL语句
delete from ads.ads_bi_user_book_consume_info where dt = '${bf_1_dt}';
