----------------------------------------------------------------
-- project_name     : starrocks
-- workflow_name    : tbl_ads_ad_time_partitioned_data
-- workflow_version : 17
-- create_user      : chenmo
-- task_name        : sr_to_ads_sr_ads_ad_time_partitioned_data
-- task_version     : 13
-- update_time      : 2025-04-02 15:10:36
-- sql_path         : \starrocks\tbl_ads_ad_time_partitioned_data\sr_to_ads_sr_ads_ad_time_partitioned_data
----------------------------------------------------------------
-- SQL语句
insert into ads.ads_ad_time_partitioned_data_external
select dt,
       ad_set_id,
       source_chl,
       product_id,
       core,
       create_time,
       product,
       language,
       book_id,
       code,
       dn,
       first_budget,
       mt,
       d0_cost,
       d0_impressions,
       d0_link_clicks,
       d0_regnum,
       d0_payers_num,
       d0_amt,
       d0_std,
       cost_bf1,
       impressions_bf1,
       link_clicks_bf1,
       reg_num_bf1,
       payers_num_bf1,
       d0_amt_bf1,
       amt_std_bf1,
       cost_bf2_pow,
       impressions_bf2_pow,
       link_clicks_bf2_pow,
       reg_num_bf2_pow,
       payers_num_bf2_pow,
       d0_amt_bf2_pow,
       amt_std_bf2_pow,
       cost_af1,
       reg_num_af1,
       d0_amt_af1,
       d0_amt_af1_sum,
       amt_std_af1,
       cost_af2,
       reg_num_af2,
       d0_amt_af2,
       d0_amt_af2_sum,
       amt_std_af2,
       cost_af3,
       reg_num_af3,
       d0_amt_af3,
       d0_amt_af3_sum,
       amt_std_af3,
       cost_af7d,
       reg_num_af7d,
       d0_amt_af7d,
       d0_amt_af7d_sum,
       amt_std_af7d,
       hour,
       hours_spend,
       cost_amount,
       reg_num,
       impressions,
       LinkClicks,
       hn_cost,
       hn_regnum,
       hn_amount,
       hn_payers,
       hn_impressions,
       hn_LinkClicks,
       week_day,
       spend_prop,
       hn_R0,
       hn_CAC,
       hn_ir,
       hn_cpm,
       R0_bf1,
       R0_bf2_n,
       func,
       ir_rate,
       h_d0_amt,
       h_d0_payers,
       hn_d0_amt,
       hn_d0_payers,
       etl_time
from ads.ads_ad_time_partitioned_data
where dt >= days_add('${bf_1_dt}',-60);
