CREATE TABLE `ads_short_video_series_feature_di_core4` (
  `dt` date NOT NULL COMMENT "分区日期",
  `series_id` bigint(20) NOT NULL COMMENT "剧ID",
  `language` int(11) NULL COMMENT "语言",
  `publish_status` int(11) NULL COMMENT "上下架状态",
  `published_at` datetime NULL COMMENT "上架时间",
  `un_published_at` datetime NULL COMMENT "下架时间",
  `is_new_series7d` tinyint(4) NULL COMMENT "是否新剧（上架7天内）",
  `series_age_days` int(11) NULL COMMENT "上架天数",
  `ending` int(11) NULL COMMENT "完结状态",
  `all_epis` int(11) NULL COMMENT "总集数",
  `last_epis` int(11) NULL COMMENT "最新集数",
  `pay_epis_from` int(11) NULL COMMENT "付费起始集数",
  `price` int(11) NULL COMMENT "单集价格（分）",
  `series_level` int(11) NULL COMMENT "内容等级",
  `operate_level` int(11) NULL COMMENT "运营等级",
  `work_type` int(11) NULL COMMENT "作品类型",
  `producer` varchar(255) NULL COMMENT "制作方",
  `source_series_id` bigint(20) NULL COMMENT "源语言短剧ID",
  `content_country` varchar(255) NULL COMMENT "内容国家/地区",
  `genre_tag_list` varchar(2000) NULL COMMENT "题材标签列表",
  `main_actor_list` varchar(2000) NULL COMMENT "主演员列表",
  `director_list` varchar(2000) NULL COMMENT "导演列表",
  `exp_uv_1d` bigint(20) NULL COMMENT "近1天曝光UV",
  `exp_uv_3d` bigint(20) NULL COMMENT "近3天曝光UV",
  `exp_uv_7d` bigint(20) NULL COMMENT "近7天曝光UV",
  `exp_uv_30d` bigint(20) NULL COMMENT "近30天曝光UV",
  `exp_pv_1d` bigint(20) NULL COMMENT "近1天曝光PV",
  `exp_pv_7d` bigint(20) NULL COMMENT "近7天曝光PV",
  `exp_pv_30d` bigint(20) NULL COMMENT "近30天曝光PV",
  `click_uv_1d` bigint(20) NULL COMMENT "近1天点击UV",
  `click_uv_3d` bigint(20) NULL COMMENT "近3天点击UV",
  `click_uv_7d` bigint(20) NULL COMMENT "近7天点击UV",
  `click_uv_30d` bigint(20) NULL COMMENT "近30天点击UV",
  `click_pv_1d` bigint(20) NULL COMMENT "近1天点击PV",
  `click_pv_7d` bigint(20) NULL COMMENT "近7天点击PV",
  `click_pv_30d` bigint(20) NULL COMMENT "近30天点击PV",
  `like_uv_7d` bigint(20) NULL COMMENT "近7天点赞UV",
  `like_uv_30d` bigint(20) NULL COMMENT "近30天点赞UV",
  `follow_uv_7d` bigint(20) NULL COMMENT "近7天追剧UV",
  `follow_uv_30d` bigint(20) NULL COMMENT "近30天追剧UV",
  `ctr_7d` decimal(18, 6) NULL COMMENT "近7天点击率",
  `ctr_30d` decimal(18, 6) NULL COMMENT "近30天点击率",
  `like_rate_30d` decimal(18, 6) NULL COMMENT "近30天点赞率",
  `follow_rate_30d` decimal(18, 6) NULL COMMENT "近30天追剧率",
  `play_uv_1d` bigint(20) NULL COMMENT "近1天播放UV",
  `play_uv_7d` bigint(20) NULL COMMENT "近7天播放UV",
  `avg_watch_duration_7d` decimal(18, 2) NULL COMMENT "近7天平均播放时长",
  `avg_finish_rate_7d` decimal(18, 6) NULL COMMENT "近7天完播率",
  `avg_finish_rate_30d` decimal(18, 6) NULL COMMENT "近30天完播率",
  `retention_3s_7d` decimal(18, 6) NULL COMMENT "近7天前3秒留存",
  `bounce_rate_7d` decimal(18, 6) NULL COMMENT "近7天跳出率",
  `pay_convert_rate_30d` decimal(18, 6) NULL COMMENT "近30天付费转化率",
  `hot_score_1h` decimal(18, 6) NULL COMMENT "近1小时实时热度分",
  `hot_score_6h` decimal(18, 6) NULL COMMENT "近6小时实时热度分",
  `hot_score_1d` decimal(18, 6) NULL COMMENT "近1天热度分",
  `last_exp_tm` datetime NULL COMMENT "最近曝光时间",
  `last_click_tm` datetime NULL COMMENT "最近点击时间",
  `last_play_tm` datetime NULL COMMENT "最近播放时间",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据注入时间",
  `sr_updatetime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据更新时间",
  `avg_watch_epis_per_user_7d` decimal(18, 4) NULL COMMENT "近7天人均观看集数",
  `avg_watch_epis_per_user_15d` decimal(18, 4) NULL COMMENT "近15天人均观看集数",
  `avg_watch_epis_per_user_30d` decimal(18, 4) NULL COMMENT "近30天人均观看集数",
  `total_watch_epis_7d` bigint(20) NULL COMMENT "近7天总观看集数",
  `total_watch_epis_15d` bigint(20) NULL COMMENT "近15天总观看集数",
  `total_watch_epis_30d` bigint(20) NULL COMMENT "近30天总观看集数",
  `cover_ctr_7d` decimal(18, 6) NULL COMMENT "近7天封面点击率",
  `cover_ctr_15d` decimal(18, 6) NULL COMMENT "近15天封面点击率",
  `cover_ctr_30d` decimal(18, 6) NULL COMMENT "近30天封面点击率",
  `first_epis_loss_rate_7d` decimal(18, 6) NULL COMMENT "近7天首集流失率",
  `first_epis_loss_rate_15d` decimal(18, 6) NULL COMMENT "近15天首集流失率",
  `first_epis_loss_rate_30d` decimal(18, 6) NULL COMMENT "近30天首集流失率",
  `loss_5s_rate_7d` decimal(18, 6) NULL COMMENT "近7天前5秒流失率",
  `loss_5s_rate_15d` decimal(18, 6) NULL COMMENT "近15天前5秒流失率",
  `loss_5s_rate_30d` decimal(18, 6) NULL COMMENT "近30天前5秒流失率",
  `first_epis_retain_rate_7d` decimal(18, 6) NULL COMMENT "近7天首集留存率",
  `first_epis_retain_rate_15d` decimal(18, 6) NULL COMMENT "近15天首集留存率",
  `first_epis_retain_rate_30d` decimal(18, 6) NULL COMMENT "近30天首集留存率",
  `retain_5s_rate_7d` decimal(18, 6) NULL COMMENT "近7天前5秒留存率",
  `retain_5s_rate_15d` decimal(18, 6) NULL COMMENT "近15天前5秒留存率",
  `retain_5s_rate_30d` decimal(18, 6) NULL COMMENT "近30天前5秒留存率",
  `local_type` int(11) NULL COMMENT "Source series LocalType from ods_tidb_source_series",
  `cores` varchar(255) NULL COMMENT "Core ，多个用逗号隔开(1core1，2core2，3core3，4core4)"
) ENGINE=OLAP 
PRIMARY KEY(`dt`, `series_id`)
COMMENT "短剧维度及效果特征日报表"
DISTRIBUTED BY HASH(`series_id`) BUCKETS 32 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);