CREATE TABLE `ads_short_video_user_series_feature_di` (
  `dt` date NOT NULL COMMENT "分区日期",
  `account_id` bigint(20) NOT NULL COMMENT "用户ID",
  `series_id` bigint(20) NOT NULL COMMENT "剧ID",
  `exp_cnt_1d` bigint(20) NULL COMMENT "近1天该用户对该剧曝光次数",
  `exp_cnt_3d` bigint(20) NULL COMMENT "近3天曝光次数",
  `exp_cnt_7d` bigint(20) NULL COMMENT "近7天曝光次数",
  `exp_cnt_14d` bigint(20) NULL COMMENT "近14天曝光次数",
  `exp_cnt_30d` bigint(20) NULL COMMENT "近30天曝光次数",
  `click_cnt_1d` bigint(20) NULL COMMENT "近1天点击次数",
  `click_cnt_3d` bigint(20) NULL COMMENT "近3天点击次数",
  `click_cnt_7d` bigint(20) NULL COMMENT "近7天点击次数",
  `click_cnt_14d` bigint(20) NULL COMMENT "近14天点击次数",
  `click_cnt_30d` bigint(20) NULL COMMENT "近30天点击次数",
  `like_cnt_30d` bigint(20) NULL COMMENT "近30天点赞次数",
  `follow_cnt_30d` bigint(20) NULL COMMENT "近30天追剧次数",
  `is_like_30d` tinyint(4) NULL COMMENT "近30天是否点赞过",
  `is_follow_30d` tinyint(4) NULL COMMENT "近30天是否追过",
  `has_exp_hist` tinyint(4) NULL COMMENT "历史是否曝光过",
  `has_click_hist` tinyint(4) NULL COMMENT "历史是否点击过",
  `has_like_hist` tinyint(4) NULL COMMENT "历史是否点赞过",
  `has_follow_hist` tinyint(4) NULL COMMENT "历史是否追过",
  `days_since_last_exp` int(11) NULL COMMENT "距最近曝光天数",
  `days_since_last_click` int(11) NULL COMMENT "距最近点击天数",
  `days_since_last_like` int(11) NULL COMMENT "距最近点赞天数",
  `days_since_last_follow` int(11) NULL COMMENT "距最近追剧天数",
  `ctr_7d` decimal(18, 6) NULL COMMENT "近7天点击率",
  `ctr_30d` decimal(18, 6) NULL COMMENT "近30天点击率",
  `intensity_score_30d` decimal(18, 6) NULL COMMENT "近30天交互强度分",
  `play_cnt_7d` bigint(20) NULL COMMENT "近7天播放次数",
  `avg_watch_duration_7d` decimal(18, 2) NULL COMMENT "近7天该用户对该剧平均播放时长",
  `avg_finish_rate_7d` decimal(18, 6) NULL COMMENT "近7天该用户对该剧完播率",
  `is_finish_any_30d` tinyint(4) NULL COMMENT "近30天是否完播过该剧",
  `fav_genre_top1_30d` varchar(255) NULL COMMENT "近30天偏好题材Top1",
  `fav_director_top1_30d` varchar(255) NULL COMMENT "近30天偏好导演Top1",
  `fav_actor_top1_30d` varchar(255) NULL COMMENT "近30天偏好演员Top1",
  `genre_match_score` decimal(18, 6) NULL COMMENT "用户题材偏好与剧题材匹配度",
  `actor_match_score` decimal(18, 6) NULL COMMENT "用户偏好演员与剧演员匹配度",
  `language_match_flag` tinyint(4) NULL COMMENT "用户语言与剧语言是否匹配",
  `country_language_match_flag` tinyint(4) NULL COMMENT "用户国家与剧语言是否匹配",
  `user_active_level_x_series_hot_score` decimal(18, 6) NULL COMMENT "用户活跃度×剧热度交叉分",
  `user_finish_pref_x_series_finish_rate` decimal(18, 6) NULL COMMENT "用户完播偏好×剧完播率",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据注入时间",
  `sr_updatetime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据更新时间"
) ENGINE=OLAP 
PRIMARY KEY(`dt`, `account_id`, `series_id`)
COMMENT "短剧用户-剧交叉特征日报表"
DISTRIBUTED BY HASH(`account_id`, `series_id`) BUCKETS 32 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);