CREATE TABLE `ads_short_video_user_feature_di` (
  `dt` date NOT NULL COMMENT "分区日期",
  `account_id` bigint(20) NOT NULL COMMENT "用户ID",
  `reg_days` int(11) NULL COMMENT "注册天数",
  `is_new_user_7d` tinyint(4) NULL COMMENT "是否7日内新用户",
  `country` varchar(255) NULL COMMENT "当前国家",
  `reg_country` varchar(255) NULL COMMENT "注册国家",
  `current_language` int(11) NULL COMMENT "当前语言",
  `init_language` int(11) NULL COMMENT "初始语言",
  `chl` varchar(255) NULL COMMENT "最新渠道ID",
  `init_chl` varchar(255) NULL COMMENT "初始渠道ID",
  `mt` int(11) NULL COMMENT "最新平台",
  `init_mt` int(11) NULL COMMENT "初始平台",
  `app_version` varchar(255) NULL COMMENT "App版本",
  `account_version` int(11) NULL COMMENT "账户版本号",
  `os_type` varchar(64) NULL COMMENT "操作系统类型",
  `os_version` varchar(255) NULL COMMENT "系统版本",
  `device_type` varchar(255) NULL COMMENT "设备类型",
  `network_type` varchar(255) NULL COMMENT "网络环境",
  `region_id` int(11) NULL COMMENT "区域ID",
  `is_vip` tinyint(4) NULL COMMENT "是否VIP",
  `is_svip` tinyint(4) NULL COMMENT "是否SVIP",
  `vip_expire_time` datetime NULL COMMENT "VIP/SVIP过期时间",
  `vip_level` int(11) NULL COMMENT "VIP等级",
  `vip_status` int(11) NULL COMMENT "VIP状态",
  `ban_shopping` tinyint(4) NULL COMMENT "是否禁购",
  `iaa_tag` tinyint(4) NULL COMMENT "是否IAA用户",
  `pay_user_flag` tinyint(4) NULL COMMENT "是否付费用户",
  `registry_first_recharge_duration` int(11) NULL COMMENT "注册到首充分钟数",
  `first_recharge_watch_series_num` int(11) NULL COMMENT "首充前观看剧数",
  `first_recharge_watch_epis_num` int(11) NULL COMMENT "首充前观看集数",
  `first_vip_price` decimal(18, 2) NULL COMMENT "首次VIP金额",
  `first_svip_price` decimal(18, 2) NULL COMMENT "首次SVIP金额",
  `vip_total_price` decimal(18, 2) NULL COMMENT "累计VIP金额",
  `svip_total_price` decimal(18, 2) NULL COMMENT "累计SVIP金额",
  `active_level_30d` int(11) NULL COMMENT "活跃度等级",
  `login_days_7d` int(11) NULL COMMENT "近7天活跃天数",
  `login_days_30d` int(11) NULL COMMENT "近30天活跃天数",
  `exp_cnt_1d` bigint(20) NULL COMMENT "近1天曝光次数",
  `exp_cnt_3d` bigint(20) NULL COMMENT "近3天曝光次数",
  `exp_cnt_7d` bigint(20) NULL COMMENT "近7天曝光次数",
  `exp_cnt_14d` bigint(20) NULL COMMENT "近14天曝光次数",
  `exp_cnt_30d` bigint(20) NULL COMMENT "近30天曝光次数",
  `click_cnt_1d` bigint(20) NULL COMMENT "近1天点击次数",
  `click_cnt_3d` bigint(20) NULL COMMENT "近3天点击次数",
  `click_cnt_7d` bigint(20) NULL COMMENT "近7天点击次数",
  `click_cnt_14d` bigint(20) NULL COMMENT "近14天点击次数",
  `click_cnt_30d` bigint(20) NULL COMMENT "近30天点击次数",
  `like_cnt_7d` bigint(20) NULL COMMENT "近7天点赞次数",
  `like_cnt_30d` bigint(20) NULL COMMENT "近30天点赞次数",
  `follow_cnt_7d` bigint(20) NULL COMMENT "近7天追剧次数",
  `follow_cnt_30d` bigint(20) NULL COMMENT "近30天追剧次数",
  `active_series_cnt_7d` bigint(20) NULL COMMENT "近7天交互剧数",
  `active_series_cnt_30d` bigint(20) NULL COMMENT "近30天交互剧数",
  `ctr_7d` decimal(18, 6) NULL COMMENT "近7天点击率",
  `ctr_30d` decimal(18, 6) NULL COMMENT "近30天点击率",
  `last_exp_tm` datetime NULL COMMENT "最近曝光时间",
  `last_click_tm` datetime NULL COMMENT "最近点击时间",
  `last_like_tm` datetime NULL COMMENT "最近点赞时间",
  `last_follow_tm` datetime NULL COMMENT "最近追剧时间",
  `fav_work_type_7d` int(11) NULL COMMENT "近7天偏好作品类型",
  `fav_work_type_30d` int(11) NULL COMMENT "近30天偏好作品类型",
  `fav_genre_top1_30d` varchar(255) NULL COMMENT "近30天偏好题材Top1",
  `fav_genre_top2_30d` varchar(255) NULL COMMENT "近30天偏好题材Top2",
  `fav_actor_top1_30d` varchar(255) NULL COMMENT "近30天偏好演员Top1",
  `fav_director_top1_30d` varchar(255) NULL COMMENT "近30天偏好导演Top1",
  `avg_watch_duration_7d` decimal(18, 2) NULL COMMENT "近7天平均播放时长",
  `avg_watch_duration_30d` decimal(18, 2) NULL COMMENT "近30天平均播放时长",
  `avg_finish_rate_30d` decimal(18, 6) NULL COMMENT "近30天平均完播率",
  `neg_feedback_cnt_7d` bigint(20) NULL COMMENT "近7天负反馈次数",
  `neg_feedback_cnt_30d` bigint(20) NULL COMMENT "近30天负反馈次数",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据注入时间",
  `sr_updatetime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据更新时间",
  `CoreVer` int(11) NULL COMMENT "Core",
  `CoreVer2` int(11) NULL COMMENT "Core"
) ENGINE=OLAP 
PRIMARY KEY(`dt`, `account_id`)
COMMENT "短剧用户特征日报表"
DISTRIBUTED BY HASH(`account_id`) BUCKETS 32 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);