CREATE TABLE `ads_short_video_series_rank_7d_di` (
  `dt` date NOT NULL COMMENT "分区日期",
  `series_id` bigint(20) NOT NULL COMMENT "剧ID",
  `language` int(11) NOT NULL COMMENT "语言",
  `total_score` decimal(18, 6) NULL COMMENT "综合得分",
  `rank_in_language` int(11) NULL COMMENT "语言内排名",
  `total_series_in_language` int(11) NULL COMMENT "该语言总剧数",
  `rank_percentage` decimal(18, 6) NULL COMMENT "排名百分比",
  `exp_uv_score` int(11) NULL COMMENT "曝光UV得分",
  `click_uv_score` int(11) NULL COMMENT "点击UV得分",
  `ctr_score` int(11) NULL COMMENT "点击率得分",
  `like_uv_score` int(11) NULL COMMENT "点赞UV得分",
  `follow_uv_score` int(11) NULL COMMENT "追剧UV得分",
  `play_uv_score` int(11) NULL COMMENT "播放UV得分",
  `duration_score` int(11) NULL COMMENT "播放时长得分",
  `finish_score` int(11) NULL COMMENT "完播率得分",
  `retention_score` int(11) NULL COMMENT "3秒留存得分",
  `hot_score` int(11) NULL COMMENT "热度得分",
  `exp_uv_7d` bigint(20) NULL COMMENT "近7天曝光UV",
  `click_uv_7d` bigint(20) NULL COMMENT "近7天点击UV",
  `ctr_7d` decimal(18, 6) NULL COMMENT "近7天点击率",
  `like_uv_7d` bigint(20) NULL COMMENT "近7天点赞UV",
  `follow_uv_7d` bigint(20) NULL COMMENT "近7天追剧UV",
  `play_uv_7d` bigint(20) NULL COMMENT "近7天播放UV",
  `avg_watch_duration_7d` decimal(18, 2) NULL COMMENT "近7天平均播放时长",
  `avg_finish_rate_7d` decimal(18, 6) NULL COMMENT "近7天完播率",
  `retention_3s_7d` decimal(18, 6) NULL COMMENT "近7天前3秒留存",
  `hot_score_1d` decimal(18, 6) NULL COMMENT "近1天热度分",
  `exp_uv_percentile` decimal(18, 6) NULL COMMENT "曝光UV百分位",
  `click_uv_percentile` decimal(18, 6) NULL COMMENT "点击UV百分位",
  `ctr_percentile` decimal(18, 6) NULL COMMENT "点击率百分位",
  `like_uv_percentile` decimal(18, 6) NULL COMMENT "点赞UV百分位",
  `follow_uv_percentile` decimal(18, 6) NULL COMMENT "追剧UV百分位",
  `play_uv_percentile` decimal(18, 6) NULL COMMENT "播放UV百分位",
  `duration_percentile` decimal(18, 6) NULL COMMENT "播放时长百分位",
  `finish_percentile` decimal(18, 6) NULL COMMENT "完播率百分位",
  `retention_percentile` decimal(18, 6) NULL COMMENT "3秒留存百分位",
  `hot_score_percentile` decimal(18, 6) NULL COMMENT "热度分百分位",
  `sr_createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据注入时间",
  `sr_updatetime` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据更新时间",
  `cores` varchar(255) NULL COMMENT "Core ，多个用逗号隔开(1core1，2core2，3core3，4core4)",
  `depth_score` decimal(18, 6) NULL COMMENT "深度分：综合unlock_uv_7d、unlock_pv_7d、avg_watch_duration_7d、avg_watch_epis_per_user_7d的百分位得分",
  `depth_percentile` decimal(18, 6) NULL COMMENT "深度分在同语言内的百分位排名"
) ENGINE=OLAP 
PRIMARY KEY(`dt`, `series_id`, `language`)
COMMENT "短剧七日排行榜日报表（按语言分组）"
DISTRIBUTED BY HASH(`series_id`) BUCKETS 32 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);