CREATE TABLE `alg_series_feature_fyy` (
  `series_id` bigint(20) NOT NULL COMMENT "",
  `watch_user_con` bigint(20) NULL COMMENT "",
  `watch_epis_num` bigint(20) NULL COMMENT "",
  `end_watch_epis_num` bigint(20) NULL COMMENT "",
  `watch_user_con_1d` bigint(20) NULL COMMENT "",
  `watch_epis_num_1d` bigint(20) NULL COMMENT "",
  `end_watch_epis_num_1d` bigint(20) NULL COMMENT "",
  `watch_user_con_3d` bigint(20) NULL COMMENT "",
  `watch_epis_num_3d` bigint(20) NULL COMMENT "",
  `end_watch_epis_num_3d` bigint(20) NULL COMMENT "",
  `watch_user_con_7d` bigint(20) NULL COMMENT "",
  `watch_epis_num_7d` bigint(20) NULL COMMENT "",
  `end_watch_epis_num_7d` bigint(20) NULL COMMENT "",
  `watch_user_con_15d` bigint(20) NULL COMMENT "",
  `watch_epis_num_15d` bigint(20) NULL COMMENT "",
  `end_watch_epis_num_15d` bigint(20) NULL COMMENT "",
  `watch_user_con_30d` bigint(20) NULL COMMENT "",
  `watch_epis_num_30d` bigint(20) NULL COMMENT "",
  `end_watch_epis_num_30d` bigint(20) NULL COMMENT "",
  `watch_user_con_all` bigint(20) NULL COMMENT "",
  `watch_epis_num_all` bigint(20) NULL COMMENT "",
  `end_watch_epis_num_all` bigint(20) NULL COMMENT "",
  `consume_user_con` bigint(20) NULL COMMENT "",
  `consume_epis_num` bigint(20) NULL COMMENT "",
  `consume_coin_amount` bigint(20) NULL COMMENT "",
  `consume_amount` bigint(20) NULL COMMENT "",
  `consume_user_con_1d` bigint(20) NULL COMMENT "",
  `consume_epis_num_1d` bigint(20) NULL COMMENT "",
  `consume_coin_amount_1d` bigint(20) NULL COMMENT "",
  `consume_amount_1d` bigint(20) NULL COMMENT "",
  `consume_user_con_3d` bigint(20) NULL COMMENT "",
  `consume_epis_num_3d` bigint(20) NULL COMMENT "",
  `consume_coin_amount_3d` bigint(20) NULL COMMENT "",
  `consume_amount_3d` bigint(20) NULL COMMENT "",
  `consume_user_con_7d` bigint(20) NULL COMMENT "",
  `consume_epis_num_7d` bigint(20) NULL COMMENT "",
  `consume_coin_amount_7d` bigint(20) NULL COMMENT "",
  `consume_amount_7d` bigint(20) NULL COMMENT "",
  `consume_user_con_15d` bigint(20) NULL COMMENT "",
  `consume_epis_num_15d` bigint(20) NULL COMMENT "",
  `consume_coin_amount_15d` bigint(20) NULL COMMENT "",
  `consume_amount_15d` bigint(20) NULL COMMENT "",
  `consume_user_con_30d` bigint(20) NULL COMMENT "",
  `consume_epis_num_30d` bigint(20) NULL COMMENT "",
  `consume_coin_amount_30d` bigint(20) NULL COMMENT "",
  `consume_amount_30d` bigint(20) NULL COMMENT "",
  `consume_user_con_all` bigint(20) NULL COMMENT "",
  `consume_epis_num_all` bigint(20) NULL COMMENT "",
  `consume_coin_amount_all` bigint(20) NULL COMMENT "",
  `consume_amount_all` bigint(20) NULL COMMENT "",
  `charge_user_con` bigint(20) NULL COMMENT "",
  `charge_con` bigint(20) NULL COMMENT "",
  `base_amount` decimal(24, 6) NULL COMMENT "",
  `charge_user_con_1d` bigint(20) NULL COMMENT "",
  `charge_con_1d` bigint(20) NULL COMMENT "",
  `base_amount_1d` decimal(24, 6) NULL COMMENT "",
  `charge_user_con_3d` bigint(20) NULL COMMENT "",
  `charge_con_3d` bigint(20) NULL COMMENT "",
  `base_amount_3d` decimal(24, 6) NULL COMMENT "",
  `charge_user_con_7d` bigint(20) NULL COMMENT "",
  `charge_con_7d` bigint(20) NULL COMMENT "",
  `base_amount_7d` decimal(24, 6) NULL COMMENT "",
  `charge_user_con_15d` bigint(20) NULL COMMENT "",
  `charge_con_15d` bigint(20) NULL COMMENT "",
  `base_amount_15d` decimal(24, 6) NULL COMMENT "",
  `charge_user_con_30d` bigint(20) NULL COMMENT "",
  `charge_con_30d` bigint(20) NULL COMMENT "",
  `base_amount_30d` decimal(24, 6) NULL COMMENT "",
  `charge_user_con_all` bigint(20) NULL COMMENT "",
  `charge_con_all` bigint(20) NULL COMMENT "",
  `base_amount_all` decimal(24, 6) NULL COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`series_id`, `watch_user_con`, `watch_epis_num`)
DISTRIBUTED BY HASH(`series_id`) BUCKETS 16 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);