CREATE TABLE `alg_tf_book_amount_agg_7d` (
  `dt` date NULL COMMENT "日期",
  `mt` int(11) NULL COMMENT "设备",
  `book_id` bigint(20) NULL COMMENT "书籍id",
  `ad_num` bigint(20) NULL COMMENT "广告总数",
  `dev_num` bigint(20) NULL COMMENT "注册设备总数",
  `reg_num` bigint(20) NULL COMMENT "总数注册人总数",
  `cost_amount` bigint(20) NULL COMMENT "总花费",
  `day0_paynum` bigint(20) NULL COMMENT "day0付费次数",
  `day1_paynum` bigint(20) NULL COMMENT "day1付费次数",
  `day2_paynum` bigint(20) NULL COMMENT "day2付费次数",
  `day3_paynum` bigint(20) NULL COMMENT "day3付费次数",
  `day4_paynum` bigint(20) NULL COMMENT "day4付费次数",
  `day5_paynum` bigint(20) NULL COMMENT "day5付费次数",
  `day6_paynum` bigint(20) NULL COMMENT "day6付费次数",
  `day7_paynum` bigint(20) NULL COMMENT "day7付费次数",
  `day0_first_paynum` bigint(20) NULL COMMENT "day0首充付费用户数",
  `day1_first_paynum` bigint(20) NULL COMMENT "day1首充付费用户数",
  `day2_first_paynum` bigint(20) NULL COMMENT "day2首充付费用户数",
  `day3_first_paynum` bigint(20) NULL COMMENT "day3首充付费用户数",
  `day4_first_paynum` bigint(20) NULL COMMENT "day4首充付费用户数",
  `day5_first_paynum` bigint(20) NULL COMMENT "day5首充付费用户数",
  `day6_first_paynum` bigint(20) NULL COMMENT "day6首充付费用户数",
  `day7_first_paynum` bigint(20) NULL COMMENT "day7首充付费用户数",
  `day0_first_paytimes` bigint(20) NULL COMMENT "day0首充付费次数",
  `day0_amount` bigint(20) NULL COMMENT "day0充值收入",
  `day1_amount` bigint(20) NULL COMMENT "day1充值收入",
  `day2_amount` bigint(20) NULL COMMENT "day2充值收入",
  `day3_amount` bigint(20) NULL COMMENT "day3充值收入",
  `day4_amount` bigint(20) NULL COMMENT "day4充值收入",
  `day5_amount` bigint(20) NULL COMMENT "day5充值收入",
  `day6_amount` bigint(20) NULL COMMENT "day6充值收入",
  `day7_amount` bigint(20) NULL COMMENT "day7充值收入",
  `day15_amount` bigint(20) NULL COMMENT "day15充值收入",
  `day30_amount` bigint(20) NULL COMMENT "day30充值收入",
  `day40_amount` bigint(20) NULL COMMENT "day40充值收入",
  `day50_amount` bigint(20) NULL COMMENT "day50充值收入",
  `day60_amount` bigint(20) NULL COMMENT "day60充值收入",
  `day70_amount` bigint(20) NULL COMMENT "day70充值收入",
  `day80_amount` bigint(20) NULL COMMENT "day80充值收入",
  `day90_amount` bigint(20) NULL COMMENT "day90充值收入"
) ENGINE=OLAP 
DUPLICATE KEY(`dt`, `mt`, `book_id`)
DISTRIBUTED BY HASH(`dt`) BUCKETS 1 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);