CREATE TABLE `alg_sample_update_repay_feat_v2` (
  `dt` date NULL COMMENT "统计日期",
  `UserId` bigint(20) NULL COMMENT "用户id",
  `label` bigint(20) NULL COMMENT "昨天最大金额",
  `sex` int(11) NULL COMMENT "性别",
  `regcountry` varchar(65533) NULL COMMENT "注册国家",
  `mt` int(11) NULL COMMENT "平台",
  `productid` int(11) NULL COMMENT "产品id",
  `corever` int(11) NULL COMMENT "包体",
  `bookid` varchar(65533) NULL COMMENT "广告bookid",
  `adstype` varchar(65533) NULL COMMENT "用户广告标签ADSTYPE",
  `adsquality` int(11) NULL COMMENT "用户广告标签",
  `last_recharge_time` datetime NULL COMMENT "最后充值时间",
  `pay_total` bigint(20) NULL COMMENT "充值总额",
  `pay_max` int(11) NULL COMMENT "最大充值金额",
  `pay_min` int(11) NULL COMMENT "最小充值金额",
  `pay_avg` decimal(38, 9) NULL COMMENT "平均充值金额",
  `pay_times` decimal(18, 6) NULL COMMENT "充值众数金额",
  `pay_total_30d` bigint(20) NULL COMMENT "近30天累计充值金额",
  `pay_max_30d` int(11) NULL COMMENT "近30天最大充值金额",
  `pay_avg_30d` decimal(38, 9) NULL COMMENT "近30天平均充值金额",
  `pay_total_15d` bigint(20) NULL COMMENT "近15天累计充值金额",
  `pay_max_15d` int(11) NULL COMMENT "近15天最大充值金额",
  `pay_avg_15d` decimal(38, 9) NULL COMMENT "近15天平均充值金额",
  `pay_total_7d` bigint(20) NULL COMMENT "近7天累计充值金额",
  `pay_max_7d` int(11) NULL COMMENT "近7天最大充值金额",
  `pay_avg_7d` decimal(38, 9) NULL COMMENT "近7天平均充值金额",
  `pay_total_3d` bigint(20) NULL COMMENT "近3天累计充值金额",
  `pay_max_3d` int(11) NULL COMMENT "近3天最大充值金额",
  `pay_avg_3d` decimal(38, 9) NULL COMMENT "近3天平均充值金额",
  `pay_total_1d` bigint(20) NULL COMMENT "近1天累计充值金额",
  `pay_max_1d` int(11) NULL COMMENT "近1天最大充值金额",
  `pay_avg_1d` decimal(38, 9) NULL COMMENT "近1天平均充值金额",
  `xbookid_pay_total` bigint(20) NULL COMMENT "",
  `xbookid_pay_max` bigint(20) NULL COMMENT "",
  `xbookid_pay_min` bigint(20) NULL COMMENT "",
  `xbookid_pay_avg` bigint(20) NULL COMMENT "",
  `xbookid_select_max` bigint(20) NULL COMMENT "",
  `xcountry_pay_total` bigint(20) NULL COMMENT "",
  `xcountry_pay_max` bigint(20) NULL COMMENT "",
  `xcountry_pay_min` bigint(20) NULL COMMENT "",
  `xcountry_pay_avg` bigint(20) NULL COMMENT "",
  `xcountry_select_max` bigint(20) NULL COMMENT "",
  `xproductid_pay_total` bigint(20) NULL COMMENT "",
  `xproductid_pay_max` bigint(20) NULL COMMENT "",
  `xproductid_pay_min` bigint(20) NULL COMMENT "",
  `xproductid_pay_avg` bigint(20) NULL COMMENT "",
  `xproductid_select_max` bigint(20) NULL COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`dt`, `UserId`, `label`)
COMMENT "算法数据 - 充值数据"
DISTRIBUTED BY HASH(`UserId`) BUCKETS 12 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);