----------------------------------------------------------------
-- project_name     : starrocks
-- workflow_name    : tbl_ads_bi_ad_video_income
-- workflow_version : 31
-- create_user      : yanxh
-- task_name        : delete
-- task_version     : 1
-- update_time      : 2025-11-19 15:25:55
-- sql_path         : \starrocks\tbl_ads_bi_ad_video_income\delete
----------------------------------------------------------------
-- SQL语句
delete from ads.ads_bi_ad_video_income where dt >= '${bf_4_dt}';
