----------------------------------------------------------------
-- project_name     : starrocks
-- workflow_name    : tbl_ads_bi_read_first_read_consume_est_ed_export
-- workflow_version : 4
-- create_user      : yanxh
-- task_name        : delete_from_ads_bi_read_first_read_consume_est_ed
-- task_version     : 4
-- update_time      : 2024-10-16 16:22:36
-- sql_path         : \starrocks\tbl_ads_bi_read_first_read_consume_est_ed_export\delete_from_ads_bi_read_first_read_consume_est_ed
----------------------------------------------------------------
-- SQL语句
delete from  ads.`ads_bi_read_first_read_consume_est_ed`  where dt='${bf_1_dt}';
