CREATE TABLE `dwd_trade_sharpenginepaycenter_payorder_test` (
  `dt` date NULL COMMENT "",
  `product_id` varchar(1048576) NULL COMMENT "",
  `id` bigint(20) NULL COMMENT "",
  `order_serial_id` varchar(1048576) NULL COMMENT "",
  `order_id` varchar(1048576) NULL COMMENT "",
  `coo_order_id` varchar(1048576) NULL COMMENT "",
  `pay_chanel_id` bigint(20) NULL COMMENT "",
  `account` varchar(1048576) NULL COMMENT "",
  `user_id` bigint(20) NULL COMMENT "",
  `server_id` bigint(20) NULL COMMENT "",
  `user_ip_address` varchar(1048576) NULL COMMENT "",
  `create_time` datetime NULL COMMENT "",
  `coo_notify_time` datetime NULL COMMENT "",
  `finish_time` datetime NULL COMMENT "",
  `amount` decimal(10, 2) NULL COMMENT "",
  `give_amount` decimal(10, 2) NULL COMMENT "",
  `bank_amount` decimal(10, 2) NULL COMMENT "",
  `order_status` smallint(6) NULL COMMENT "",
  `coo_order_status` smallint(6) NULL COMMENT "",
  `shop_item` varchar(1048576) NULL COMMENT "",
  `pay_type` smallint(6) NULL COMMENT "",
  `bank_id` bigint(20) NULL COMMENT "",
  `Ext1` varchar(1048576) NULL COMMENT "",
  `Ext2` varchar(1048576) NULL COMMENT "",
  `Ext3` varchar(1048576) NULL COMMENT "",
  `Ext4` varchar(1048576) NULL COMMENT "",
  `Ext5` varchar(1048576) NULL COMMENT "",
  `os_type` smallint(6) NULL COMMENT "",
  `shop_item_id` bigint(20) NULL COMMENT "",
  `coupon_id` bigint(20) NULL COMMENT "",
  `package_id` bigint(20) NULL COMMENT "",
  `phone` varchar(1048576) NULL COMMENT "",
  `has_notify_times` bigint(20) NULL COMMENT "",
  `pay_config_id` bigint(20) NULL COMMENT "",
  `core` smallint(6) NULL COMMENT "",
  `base_amount` decimal(10, 2) NULL COMMENT "",
  `unique_guid` varchar(1048576) NULL COMMENT "",
  `test_flag` smallint(6) NULL COMMENT "",
  `coo_ext_status` smallint(6) NULL COMMENT "",
  `coo_ext_info` varchar(1048576) NULL COMMENT "",
  `bill_info` varchar(1048576) NULL COMMENT "",
  `row_update_timestamp` datetime NULL COMMENT "",
  `sub_pay_type` varchar(1048576) NULL COMMENT "",
  `auto_renew_times` smallint(6) NULL COMMENT "",
  `etl_time` datetime NULL COMMENT "",
  `uuid` varchar(1048576) NULL COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`dt`, `product_id`)
DISTRIBUTED BY HASH(`dt`) BUCKETS 12 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);