create or replace view dwd.dwd_flow_apperror_log_cdappclientbiz_view (
      dt                comment "日期"
    , track_id          comment "track_id"
    , rid               comment "rid"
    , project           comment "project"
    , event_tm          comment "时间"
    , type              comment "type"
    , distinct_id       comment "distinct_id"
    , event             comment "事件"
    , login_id          comment "login_id"
    , biz_type          comment "错误类型"
    , biz_ads_type      comment "错误广告类型"
    , biz_msg           comment "内容"
    , biz_error_msg     comment "报错内容"
    , biz_error_code    comment "报错code"
    , biz_url           comment "bizUrl"
    , biz_error_message comment "bizErrorMessage"
    , is_first_day      comment "是否首次"
    , os                comment "os系统"
    , lib               comment "系统"
    , lib_version       comment "系统版本"
    , model             comment "设备型号"
    , brand             comment "设备品牌"
    , app_version       comment "app版本"
    , app_id            comment "appid"
    , app_name          comment "app名称"
    , appcorever        comment "core"
    , app_lang_id       comment "app语言"
    , app_product_x     comment "appproductx"
    , app_channel       comment "渠道"
    , appchannel        comment "渠道"
    , device_lang       comment "设备语言"
    , appid             comment "appid"
    , app_core_ver      comment "core"
    , app_product_id    comment "app_product_id"
    , referrer_title    comment "页面"
    , device_id         comment "设备id"
    , biz_book_id       comment "书籍id"
    , biz_book_id2      comment "书籍id,来自bizbookID"
    , biz_chapter_id    comment "章节id"
    , etl_tm            comment "清洗时间"
)
comment "event=CdAppClientBiz  客户端上报"
as
select dt              as dt
     , track_id        as track_id
     , rid             as rid
     , project         as project
     , event_tm        as event_tm
     , type            as type
     , distinct_id     as distinct_id
     , event           as event
     , login_id        as login_id
     , bizType         as biz_type
     , bizAdsType      as biz_ads_type
     , bizMsg          as biz_msg
     , bizErrorMsg     as biz_error_msg
     , bizErrorCode    as biz_error_code
     , bizUrl          as biz_url
     , bizErrorMessage as biz_error_message
     , is_first_day    as is_first_day
     , os              as os
     , lib             as lib
     , lib_version     as lib_version
     , model           as model
     , brand           as brand
     , app_version     as app_version
     , app_id          as app_id
     , app_name        as app_name
     , appCoreVer      as appcorever
     , appLangId       as app_lang_id
     , appProductX     as app_product_x
     , app_channel     as app_channel
     , appChannel      as appchannel
     , deviceLang      as device_lang
     , appId           as appid
     , app_core_ver    as app_core_ver
     , app_product_id  as app_product_id
     , referrer_title  as referrer_title
     , device_id       as device_id
     , bizBookId       as biz_book_id
     , bizBookId2      as biz_book_id2
     , bizChapterId    as biz_chapter_id
     , etl_tm          as etl_tm
  from ods_log.ods_kafka_apperror_log_cdappclientbiz
;