CREATE TABLE `dwd_koc_adltvitem` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT "主键ID",
  `date_key` varchar(500) NULL COMMENT "日期yyyy-MM-dd(东八区)",
  `product_id` int(11) NULL COMMENT "ProductId",
  `ad_id` varchar(500) NULL COMMENT "koc的广告ID",
  `month_key` varchar(500) NULL COMMENT "月份yyyy-MM(东八区)",
  `dev_num` int(11) NULL COMMENT "激活用户数",
  `new_dev_num` int(11) NULL COMMENT "新用户数",
  `active_dev_num` int(11) NULL COMMENT "活跃用户数",
  `amount` decimal(16, 4) NULL COMMENT "充值金额",
  `base_amount` decimal(16, 4) NULL COMMENT "扣除渠道费充值金额",
  `income` decimal(16, 4) NULL COMMENT "收入金额",
  `real_dev_num` int(11) NULL COMMENT "激活用户数 机构和达人可见的激活用户数",
  `real_income` decimal(16, 4) NULL COMMENT "收入金额 机构和达人可见的收入金额",
  `core` int(11) NULL COMMENT "Core",
  `mt` int(11) NULL COMMENT "终端",
  `source_chl` varchar(500) NULL COMMENT "媒体",
  `chl` varchar(500) NULL COMMENT "渠道",
  `current_language` int(11) NULL COMMENT "投放语言",
  `koc_code` varchar(500) NULL COMMENT "口令",
  `project_type` int(11) NULL COMMENT "项目类型 1=书|2=短剧",
  `data_key` varchar(500) NULL COMMENT "书籍和短剧 项目类型_书籍|短剧ID",
  `data_id` bigint(20) NULL COMMENT "书籍|短剧ID",
  `institution_id` bigint(20) NULL COMMENT "机构ID",
  `institution_status` int(11) NULL COMMENT "状态 0=禁用|1=启用",
  `institution_creator_uid` varchar(500) NULL COMMENT "机构创建人账号ID",
  `star_id` bigint(20) NULL COMMENT "达人ID",
  `star_status` int(11) NULL COMMENT "状态 0=禁用|1=启用",
  `app_type` varchar(500) NULL COMMENT "App类型",
  `cooperation_type` int(11) NULL COMMENT "合作模式 1=分成合作",
  `split_ratio` int(11) NULL COMMENT "机构可获得的分成比例 30=30%",
  `transaction_fee_type` int(11) NULL COMMENT "通道费扣除类型 1=约定统一支付通道费|2=自定义支付通道费|3=约定实际支付通道费|4=免除通道费",
  `transaction_fee` int(11) NULL COMMENT "通通道费 30=30%",
  `cost_factor_type` int(11) NULL COMMENT "成本系数类型 1=约定统一成本系数|2=自定义成本系数|3=免除成本系数",
  `cost_factor` int(11) NULL COMMENT "成本系数 30=30%",
  `cooperation_begin_time` datetime NULL COMMENT "合作开始时间",
  `cooperation_end_time` datetime NULL COMMENT "合作结束时间",
  `create_time` datetime NULL COMMENT "创建时间",
  `update_time` datetime NULL COMMENT "更新时间",
  `leader_id` bigint(20) NULL COMMENT "队长id",
  `distrib_income` decimal(16, 4) NULL COMMENT "分销金额",
  `real_distrib_income` decimal(16, 4) NULL COMMENT "实际分销金额",
  `distribute_type` int(11) NULL COMMENT "分销类型 0=约定统一 1=自定义",
  `distribute_ratio` int(11) NULL COMMENT "分销比例 15=15%",
  `leader_status` int(11) NULL COMMENT "团长状态",
  `business_type` int(11) NULL COMMENT "业务模式 0-tob 1-toc",
  `exchange` decimal(16, 4) NULL COMMENT "汇率",
  `new_real_dev_num` decimal(16, 4) NULL COMMENT "激活用户数-机构和达人可见的激活用户数-新用户",
  `active_real_dev_num` decimal(16, 4) NULL COMMENT "激活用户数-机构和达人可见的激活用户数-活跃用户",
  `new_amount` decimal(16, 4) NULL COMMENT "充值金额-新用户",
  `active_amount` decimal(16, 4) NULL COMMENT "充值金额-活跃用户",
  `new_base_amount` decimal(16, 4) NULL COMMENT "扣除渠道费充值金额-新用户",
  `active_base_amount` decimal(16, 4) NULL COMMENT "扣除渠道费充值金额-活跃用户",
  `new_income` decimal(16, 4) NULL COMMENT "收入金额-新用户",
  `active_income` decimal(16, 4) NULL COMMENT "收入金额-活跃用户",
  `new_real_income` decimal(16, 4) NULL COMMENT "收入金额 机构和达人可见的收入金额-新用户",
  `active_real_income` decimal(16, 4) NULL COMMENT "收入金额 机构和达人可见的收入金额-活跃用户",
  `new_distrib_income` decimal(16, 4) NULL COMMENT "分销金额-新用户",
  `active_distrib_income` decimal(16, 4) NULL COMMENT "分销金额-活跃用户",
  `new_real_distrib_income` decimal(16, 4) NULL COMMENT "实际分销金额-新用户",
  `active_real_distrib_income` decimal(16, 4) NULL COMMENT "实际分销金额-活跃用户",
  `etl_m` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT "starrocks数据更新时间"
) ENGINE=OLAP 
PRIMARY KEY(`id`)
COMMENT "KOC的每日报表数据"
DISTRIBUTED BY HASH(`id`) BUCKETS 3 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "false",
"replicated_storage" = "true",
"compression" = "LZ4"
);