CREATE TABLE `dwd_content_book_capacity_daily` (
  `dt` date NOT NULL COMMENT "日期，根据StatisticsTime转换而来",
  `to_book_id` bigint(20) NOT NULL COMMENT "目标书籍ID",
  `to_language` int(11) NOT NULL COMMENT "目标书籍语言",
  `to_book_name` varchar(65533) NULL COMMENT "目标语言书籍名称",
  `cn_book_name` varchar(65533) NULL COMMENT "中文书籍名称",
  `is_put_down` int(11) NOT NULL COMMENT "是否下架",
  `statistics_time` datetime NOT NULL COMMENT "统计时间",
  `update_time` datetime NULL COMMENT "更新时间",
  `start_time` datetime NULL COMMENT "配置开始时间",
  `end_time` datetime NULL COMMENT "配置结束时间",
  `plan_count` decimal(19, 2) NOT NULL COMMENT "计划完成量",
  `reality_count` decimal(19, 2) NOT NULL COMMENT "实际完成量",
  `publish_number` int(11) NOT NULL COMMENT "累计发布章节数",
  `proofread_number` int(11) NOT NULL COMMENT "累计二校章节数",
  `proofread_length` int(11) NOT NULL COMMENT "累计二校字数",
  `publish_length` int(11) NOT NULL COMMENT "累计发布字数",
  `publish_number_today` int(11) NOT NULL COMMENT "当日发布章节数",
  `proofread_number_today` int(11) NOT NULL COMMENT "当日二校章节数",
  `proofread_length_today` int(11) NOT NULL COMMENT "当日二校字数",
  `book_type` int(11) NULL COMMENT "书籍类型",
  `price` decimal(24, 8) NULL COMMENT "二校千字价",
  `proofread_price_rmb_today` decimal(24, 8) NULL COMMENT "当日二校成本(人民币)",
  `proofread_price_today` decimal(24, 8) NULL COMMENT "当日二校成本(美金)",
  `publish_length_today` int(11) NOT NULL COMMENT "当日发布字数",
  `add_num` varchar(250) NULL COMMENT "加更配置",
  `week_rate` decimal(19, 2) NOT NULL COMMENT "七天费率",
  `month_rate` decimal(19, 2) NOT NULL COMMENT "三十天费率",
  `total_rate` decimal(19, 2) NOT NULL COMMENT "合计费率",
  `book_code` varchar(250) NULL COMMENT "书籍代号",
  `interpreter_start_time` datetime NULL COMMENT "质检开始时间",
  `interpreter_end_time` datetime NULL COMMENT "质检结束时间",
  `interpreter_plan_count` decimal(19, 2) NOT NULL COMMENT "质检计划完成量",
  `interpreter_reality_count` decimal(19, 2) NOT NULL COMMENT "质检实际完成量",
  `foreign_start_time` datetime NULL COMMENT "一校开始时间",
  `foreign_end_time` datetime NULL COMMENT "一校结束时间",
  `foreign_plan_count` decimal(19, 2) NOT NULL COMMENT "一校计划完成量",
  `foreign_reality_count` decimal(19, 2) NOT NULL COMMENT "一校实际完成量",
  `stop_time` datetime NULL COMMENT "停更时间",
  `no_foreign_length` int(11) NOT NULL COMMENT "待一校字数",
  `no_proofread_length` int(11) NOT NULL COMMENT "待二校字数",
  `book_status` int(11) NOT NULL COMMENT "书籍状态",
  `book_create_time` datetime NULL COMMENT "书籍创建时间",
  `amount_7` decimal(19, 2) NOT NULL COMMENT "7天收入",
  `amount_30` decimal(19, 2) NOT NULL COMMENT "30天收入",
  `foreign_name` varchar(250) NULL COMMENT "一校",
  `proofread_name` varchar(250) NULL COMMENT "二校",
  `interpreter_name` varchar(250) NULL COMMENT "译员",
  `start_num` int(11) NOT NULL COMMENT "常规日更",
  `start_plus_num` int(11) NOT NULL COMMENT "周期加更",
  `rowversion` bigint(20) NULL COMMENT "行更新时间",
  `etl_time` datetime NULL COMMENT "数据清洗时间",
  INDEX index_to_language (`to_language`) USING BITMAP COMMENT '语言id索引'
) ENGINE=OLAP 
PRIMARY KEY(`dt`, `to_book_id`, `to_language`)
COMMENT "产能监控表"
DISTRIBUTED BY HASH(`to_book_id`, `to_language`) BUCKETS 3 
PROPERTIES (
"replication_num" = "3",
"bloom_filter_columns" = "to_book_id",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);