CREATE EXTERNAL TABLE `ods_sensors_cd_video_unlockepisode_hive` (
  `rid` varchar(65533) NULL COMMENT "记录ID",
  `track_id` varchar(65533) NULL COMMENT "track_id",
  `event` varchar(65533) NULL COMMENT "事件",
  `event_tm` datetime NULL COMMENT "事件时间",
  `app_channel` varchar(65533) NULL COMMENT "渠道编号",
  `app_id` varchar(65533) NULL COMMENT "app_id",
  `app_lang_id` varchar(65533) NULL COMMENT "界面语言",
  `device_lang` varchar(65533) NULL COMMENT "设备语言",
  `login_id` varchar(65533) NULL COMMENT "用户ID",
  `product_id` varchar(65533) NULL COMMENT "产品ID",
  `send_id` varchar(65533) NULL COMMENT "转化来源",
  `app_version` varchar(65533) NULL COMMENT "应用版本",
  `os` varchar(65533) NULL COMMENT "操作系统",
  `ip` varchar(65533) NULL COMMENT "IP",
  `city` varchar(65533) NULL COMMENT "城市",
  `province` varchar(65533) NULL COMMENT "省份",
  `country` varchar(65533) NULL COMMENT "国家",
  `lib` varchar(65533) NULL COMMENT "lib",
  `shortplay_id` varchar(65533) NULL COMMENT "短剧ID",
  `episode_id` varchar(65533) NULL COMMENT "剧集ID",
  `coin_consume` varchar(65533) NULL COMMENT "消耗充值货币",
  `gift_consume` varchar(65533) NULL COMMENT "消耗赠送货币",
  `current_coin` varchar(65533) NULL COMMENT "当前账户付费货币余额",
  `current_gift` varchar(65533) NULL COMMENT "当前账户免费货币余额",
  `unlock_type` varchar(65533) NULL COMMENT "解锁类型",
  `project_id` varchar(65533) NULL COMMENT "5阅读 8 短剧",
  `dt` varchar(65533) NULL COMMENT ""
) ENGINE=HIVE 
COMMENT "event=unlockEpisode"
PROPERTIES (
"database" = "ods",
"table" = "ods_sensors_cd_video_unlockepisode",
"resource" = "hive0",
"hive.table.serde.lib"  =  "org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe",
"last_modified_time"  =  "1728529656",
"hive.table.column.names"  =  "rid,track_id,event,event_tm,app_channel,app_id,app_lang_id,device_lang,login_id,product_id,app_version,os,ip,city,province,country,lib,shortplay_id,episode_id,coin_consume,gift_consume,current_coin,current_gift,unlock_type,project_id,send_id",
"hive.table.column.types"  =  "string#string#string#timestamp#string#string#string#string#string#string#string#string#string#string#string#string#string#string#string#string#string#string#string#string#string#string",
"transient_lastDdlTime"  =  "1728529656",
"bucketing_version"  =  "2",
"hive.table.input.format"  =  "org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat",
"comment"  =  "event=unlockEpisode ??????",
"last_modified_by"  =  "hadoop",
"hive.metastore.uris"  =  "thrift://node21:9083,thrift://node22:9083"
);