CREATE TABLE `dws_user_allinfo_sensors_a` (
  `userID` bigint(20) NOT NULL COMMENT "",
  `first_book` int(11) NULL COMMENT "",
  `last_book` int(11) NULL COMMENT "",
  `login_days` int(11) NULL COMMENT "",
  `recharged` varchar(65533) NOT NULL COMMENT "",
  `first_recharge` int(11) NULL COMMENT "",
  `total_recharge` bigint(20) NULL COMMENT "",
  `recharge_max` int(11) NULL COMMENT "",
  `month_recharge_max` int(11) NULL COMMENT "",
  `last_recharge` int(11) NULL COMMENT "",
  `recharge_cnt` bigint(20) NULL COMMENT "",
  `last_recharge_time` varchar(65533) NULL COMMENT "",
  `subscribe` varchar(65533) NULL COMMENT "",
  `start_subscribe` int(11) NULL COMMENT "",
  `mul_subscribe` int(11) NULL COMMENT "",
  `purcharseCnt` bigint(20) NULL COMMENT "",
  `last_purcharse_time` varchar(65533) NULL COMMENT "",
  `coin_cnt` int(11) NULL COMMENT "",
  `total_read_time` bigint(20) NULL COMMENT "",
  `more_onem_total_read_books` bigint(20) NULL COMMENT "",
  `total_read_chp` bigint(20) NULL COMMENT "",
  `total_bat_ulk` varchar(65533) NOT NULL COMMENT "",
  `start_bat_ulk_chp_cnt` int(11) NULL COMMENT "",
  `total_bat_ulk_cnt` bigint(20) NULL COMMENT "",
  `total_fix_ulk` varchar(65533) NOT NULL COMMENT "",
  `total_fix_ulk_cnt` bigint(20) NULL COMMENT "",
  `start_sup_ulk_chp` varchar(65533) NOT NULL COMMENT "",
  `start_sup_ulk_chp_cnt` int(11) NULL COMMENT "",
  `sup_ulk_cnt` bigint(20) NULL COMMENT "",
  `sup_ulk_sum` bigint(20) NULL COMMENT "",
  `total_consumption` bigint(20) NULL COMMENT "",
  `first_currentlanguage2` int(11) NULL COMMENT "",
  `last_currentlanguage2` int(11) NULL COMMENT "",
  `certificate_cnt` int(11) NULL COMMENT "",
  `last_login_time` varchar(65533) NULL COMMENT "",
  `createtime` varchar(65533) NULL COMMENT "",
  `createtime_hours` decimal(1, 1) NOT NULL COMMENT "",
  `coin_consumption` bigint(20) NULL COMMENT "",
  `certificate_consumption` bigint(20) NULL COMMENT "",
  `purcharse_cnt` bigint(20) NULL COMMENT "",
  `is_left` int(11) NULL COMMENT "",
  `is_remarketing` varchar(65533) NULL COMMENT "",
  `ads_quality` int(11) NULL COMMENT "",
  `first_media_name` varchar(65533) NULL COMMENT "",
  `last_media_name` varchar(65533) NULL COMMENT "",
  `charge_mode` int(11) NULL COMMENT "",
  `total_bat_ulk_money` bigint(20) NULL COMMENT "",
  `subscribe_all_money` varchar(65533) NULL COMMENT "",
  `subscribe_svip_money` int(11) NULL COMMENT "",
  `subscribe_signcardplus_money` varchar(65533) NULL COMMENT "",
  `subscribe_signcardplusplus_money` varchar(65533) NULL COMMENT "",
  `his_subscribe_svip_money` varchar(65533) NULL COMMENT "",
  `his_mul_subscribe` int(11) NULL COMMENT "",
  `start_bat_ulk_money` decimal(14, 4) NULL COMMENT "",
  `his_subscribe_all_money` varchar(65533) NULL COMMENT "",
  `remarketingtime` varchar(65533) NULL COMMENT "",
  `first_recharge_time` datetime NULL COMMENT "",
  `first_read_time` datetime NULL COMMENT "",
  `timecount` tinyint(4) NOT NULL COMMENT "",
  `last_save_time` datetime NULL COMMENT "",
  `last_common_time` varchar(65533) NULL COMMENT "",
  `productid` int(11) NULL COMMENT "",
  `last_country` varchar(65533) NULL COMMENT "",
  `n` bigint(20) NULL COMMENT "",
  `mt` int(11) NULL COMMENT ""
) ENGINE=OLAP 
PRIMARY KEY(`userID`)
DISTRIBUTED BY HASH(`userID`) BUCKETS 12 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "ZSTD"
);
