CREATE TABLE `dws_user_allinfo_sensors_end_a` (
  `userID` varchar(65533) NOT NULL COMMENT "",
  `first_book` varchar(65533) NULL COMMENT "",
  `last_book` varchar(65533) NULL COMMENT "",
  `login_days` int(11) NULL COMMENT "",
  `recharged` varchar(1048576) NULL COMMENT "",
  `last_recharge_time` varchar(1048576) NULL COMMENT "",
  `subscribe` varchar(65533) NULL COMMENT "",
  `purcharse` varchar(1048576) NULL COMMENT "",
  `last_purcharse_time` varchar(1048576) NULL COMMENT "",
  `coin_cnt` int(11) NULL COMMENT "",
  `is_read` varchar(1048576) NULL COMMENT "",
  `total_read_time` decimal(38, 9) NULL COMMENT "",
  `first_currentlanguage2` varchar(65533) NULL COMMENT "",
  `last_currentlanguage2` varchar(65533) NULL COMMENT "",
  `certificate_cnt` int(11) NULL COMMENT "",
  `last_login_time` varchar(65533) NULL COMMENT "",
  `createtime` varchar(65533) NULL COMMENT "",
  `createtime_hours` decimal(38, 9) NULL COMMENT "",
  `is_left` int(11) NULL COMMENT "",
  `is_remarketing` varchar(1048576) NULL COMMENT "",
  `ads_quality` varchar(65533) NULL COMMENT "",
  `first_media_name` varchar(65533) NULL COMMENT "",
  `last_media_name` varchar(65533) NULL COMMENT "",
  `charge_mode` int(11) NULL COMMENT "",
  `subscribe_svip_money` int(11) NULL COMMENT "",
  `his_subscribe_svip_money` varchar(1048576) NULL COMMENT "",
  `his_subscribe_all_money` varchar(1048576) NULL COMMENT "",
  `remarketingTimeDays` int(11) NULL COMMENT "",
  `first_recharge_time` datetime NULL COMMENT "",
  `first_read_time` datetime NULL COMMENT "",
  `timecount` tinyint(4) NULL COMMENT "",
  `last_save_time` varchar(65533) NULL COMMENT "",
  `last_common_time` varchar(65533) NULL COMMENT "",
  `first_recharge` int(11) NULL COMMENT "",
  `total_recharge` int(11) NULL COMMENT "",
  `recharge_avg` decimal(38, 9) NULL COMMENT "",
  `recharge_max` int(11) NULL COMMENT "",
  `month_recharge_max` int(11) NULL COMMENT "",
  `last_recharge` int(11) NULL COMMENT "",
  `recharge_cnt` int(11) NULL COMMENT "",
  `start_subscribe` int(11) NULL COMMENT "",
  `mul_subscribe` varchar(1048576) NULL COMMENT "",
  `his_subscribe` varchar(1048576) NULL COMMENT "",
  `more_onem_total_read_books` int(11) NULL COMMENT "",
  `total_read_chp` int(11) NULL COMMENT "",
  `read_time_da_avg` decimal(38, 9) NULL COMMENT "",
  `total_bat_ulk` varchar(1048576) NULL COMMENT "",
  `start_bat_ulk_chp_cnt` int(11) NULL COMMENT "",
  `total_bat_ulk_cnt` int(11) NULL COMMENT "",
  `total_fix_ulk` varchar(1048576) NULL COMMENT "",
  `total_fix_ulk_cnt` int(11) NULL COMMENT "",
  `start_sup_ulk_chp` varchar(1048576) NULL COMMENT "",
  `start_sup_ulk_chp_cnt` int(11) NULL COMMENT "",
  `sup_ulk_cnt` int(11) NULL COMMENT "",
  `sup_ulk_sum` int(11) NULL COMMENT "",
  `total_consumption` int(11) NULL COMMENT "",
  `coin_consumption` int(11) NULL COMMENT "",
  `certificate_consumption` int(11) NULL COMMENT "",
  `purcharse_cnt` int(11) NULL COMMENT "",
  `total_bat_ulk_money` int(11) NULL COMMENT "",
  `subscribe_all_money` varchar(1048576) NULL COMMENT "",
  `subscribe_signcardplus_money` varchar(1048576) NULL COMMENT "",
  `subscribe_signcardplusplus_money` varchar(1048576) NULL COMMENT "",
  `total_subscribe_money` varchar(1048576) NULL COMMENT "",
  `his_subscribe_signcardplus_money` varchar(1048576) NULL COMMENT "",
  `his_subscribe_signcardplusplus_money` varchar(1048576) NULL COMMENT "",
  `his_mul_subscribe` varchar(1048576) NULL COMMENT "",
  `start_bat_ulk_money` decimal(14, 4) NULL COMMENT "",
  `last_country` varchar(1048576) NULL COMMENT "",
  `is_yesterday` int(11) NULL COMMENT ""
) ENGINE=OLAP 
PRIMARY KEY(`userID`)
DISTRIBUTED BY HASH(`userID`) BUCKETS 12 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "ZSTD"
);
