CREATE TABLE `dws_video_cn_adroi_install_referrer_eh` (
  `ad_id` varchar(250) NOT NULL COMMENT "广告id",
  `create_time` varchar(50) NOT NULL COMMENT "创建时间",
  `create_hour` int(11) NULL COMMENT "创建时间 小时",
  `pay_list` varchar(65533) NULL COMMENT "",
  `reg_num` int(11) NOT NULL COMMENT "注册次数",
  `cost_amount` decimal(10, 2) NOT NULL COMMENT "消耗金额",
  `product_id` int(11) NOT NULL COMMENT "产品id",
  `pay_num` int(11) NOT NULL COMMENT "支付人数",
  `update_time` datetime NOT NULL COMMENT "更新时间",
  `pay_list_bydays` varchar(65533) NULL COMMENT "空值",
  `check_sum` bigint(20) NOT NULL DEFAULT "0" COMMENT "空值",
  `login_num2` int(11) NOT NULL DEFAULT "0" COMMENT "空值",
  `login_num3` int(11) NOT NULL DEFAULT "0" COMMENT "空值",
  `login_num7` int(11) NOT NULL DEFAULT "0" COMMENT "空值",
  `core` int(11) NOT NULL COMMENT "core",
  `mt` int(11) NOT NULL COMMENT "mt",
  `fb_account` varchar(50) NULL COMMENT "空值",
  `ad_set_id` varchar(255) NULL COMMENT "广告系列",
  `ad_camp_id` varchar(255) NULL COMMENT "广告组",
  `dev_num` int(11) NOT NULL COMMENT "安装次数",
  `group_id` int(11) NOT NULL DEFAULT "0" COMMENT "空值",
  `source_chl` varchar(128) NULL COMMENT "来源渠道",
  `chl2` varchar(128) NULL COMMENT "chl2",
  `row_version` bigint(20) NULL COMMENT "数据更新版本",
  `current_language2` int(11) NULL COMMENT "注册时语言",
  `ads_quality` int(11) NULL DEFAULT "0" COMMENT "空值",
  `updater` varchar(255) NULL COMMENT "更新时间",
  `hour_0amount` decimal(10, 4) NULL DEFAULT "0" COMMENT "[0,1) 小时支付金额",
  `hour_halfamount` decimal(10, 4) NULL DEFAULT "0" COMMENT "[0,0.5) 小时支付金额",
  `hour_1amount` decimal(10, 4) NULL DEFAULT "0" COMMENT "[1,2) 小时支付金额",
  `hour_2amount` decimal(10, 4) NULL DEFAULT "0" COMMENT "[2,3) 小时支付金额",
  `hour_3amount` decimal(10, 4) NULL DEFAULT "0" COMMENT "[3,4) 小时支付金额",
  `hour_4amount` decimal(10, 4) NULL DEFAULT "0" COMMENT "[4,5) 小时支付金额",
  `hour_5amount` decimal(10, 4) NULL DEFAULT "0" COMMENT "[5,6) 小时支付金额",
  `hour_6amount` decimal(10, 4) NULL DEFAULT "0" COMMENT "[6,7) 小时支付金额",
  `hour_7amount` decimal(10, 4) NULL DEFAULT "0" COMMENT "[7,8) 小时支付金额",
  `hour_8amount` decimal(10, 4) NULL DEFAULT "0" COMMENT "[8,9) 小时支付金额",
  `hour_9amount` decimal(10, 4) NULL DEFAULT "0" COMMENT "[9,10) 小时支付金额",
  `hour_10amount` decimal(10, 4) NULL DEFAULT "0" COMMENT "[10,11) 小时支付金额",
  `hour_11amount` decimal(10, 4) NULL DEFAULT "0" COMMENT "[11,12) 小时支付金额",
  `hour_12amount` decimal(10, 4) NULL DEFAULT "0" COMMENT "[12,13) 小时支付金额",
  `hour_13amount` decimal(10, 4) NULL DEFAULT "0" COMMENT "[13,14) 小时支付金额",
  `hour_14amount` decimal(10, 4) NULL DEFAULT "0" COMMENT "[14,15) 小时支付金额",
  `hour_15amount` decimal(10, 4) NULL DEFAULT "0" COMMENT "[15,16) 小时支付金额",
  `hour_16amount` decimal(10, 4) NULL DEFAULT "0" COMMENT "[16,17) 小时支付金额",
  `hour_17amount` decimal(10, 4) NULL DEFAULT "0" COMMENT "[17,18) 小时支付金额",
  `hour_18amount` decimal(10, 4) NULL DEFAULT "0" COMMENT "[18,19) 小时支付金额",
  `hour_19amount` decimal(10, 4) NULL DEFAULT "0" COMMENT "[19,20) 小时支付金额",
  `hour_20amount` decimal(10, 4) NULL DEFAULT "0" COMMENT "[20,21) 小时支付金额",
  `hour_21amount` decimal(10, 4) NULL DEFAULT "0" COMMENT "[21,22) 小时支付金额",
  `hour_22amount` decimal(10, 4) NULL DEFAULT "0" COMMENT "[22,23) 小时支付金额",
  `hour_23amount` decimal(10, 4) NULL DEFAULT "0" COMMENT "[23,24) 小时支付金额",
  `hour_0amountbyad` decimal(10, 4) NULL DEFAULT "0" COMMENT "空值",
  `hour_1amountbyad` decimal(10, 4) NULL DEFAULT "0" COMMENT "空值",
  `hour_2amountbyad` decimal(10, 4) NULL DEFAULT "0" COMMENT "空值",
  `hour_3amountbyad` decimal(10, 4) NULL DEFAULT "0" COMMENT "空值",
  `hour_4amountbyad` decimal(10, 4) NULL DEFAULT "0" COMMENT "空值",
  `hour_5amountbyad` decimal(10, 4) NULL DEFAULT "0" COMMENT "空值",
  `hour_6amountbyad` decimal(10, 4) NULL DEFAULT "0" COMMENT "空值",
  `hour_7amountbyad` decimal(10, 4) NULL DEFAULT "0" COMMENT "空值",
  `hour_8amountbyad` decimal(10, 4) NULL DEFAULT "0" COMMENT "空值",
  `hour_9amountbyad` decimal(10, 4) NULL DEFAULT "0" COMMENT "空值",
  `hour_10amountbyad` decimal(10, 4) NULL DEFAULT "0" COMMENT "空值",
  `hour_11amountbyad` decimal(10, 4) NULL DEFAULT "0" COMMENT "空值",
  `hour_12amountbyad` decimal(10, 4) NULL DEFAULT "0" COMMENT "空值",
  `hour_13amountbyad` decimal(10, 4) NULL DEFAULT "0" COMMENT "空值",
  `hour_14amountbyad` decimal(10, 4) NULL DEFAULT "0" COMMENT "空值",
  `hour_15amountbyad` decimal(10, 4) NULL DEFAULT "0" COMMENT "空值",
  `hour_16amountbyad` decimal(10, 4) NULL DEFAULT "0" COMMENT "空值",
  `hour_17amountbyad` decimal(10, 4) NULL DEFAULT "0" COMMENT "空值",
  `hour_18amountbyad` decimal(10, 4) NULL DEFAULT "0" COMMENT "空值",
  `hour_19amountbyad` decimal(10, 4) NULL DEFAULT "0" COMMENT "空值",
  `hour_20amountbyad` decimal(10, 4) NULL DEFAULT "0" COMMENT "空值",
  `hour_21amountbyad` decimal(10, 4) NULL DEFAULT "0" COMMENT "空值",
  `hour_22amountbyad` decimal(10, 4) NULL DEFAULT "0" COMMENT "空值",
  `hour_23amountbyad` decimal(10, 4) NULL DEFAULT "0" COMMENT "空值",
  `hour_0firstpaynum` int(11) NULL DEFAULT "0" COMMENT "空值",
  `hour_1firstpaynum` int(11) NULL DEFAULT "0" COMMENT "空值",
  `hour_2firstpaynum` int(11) NULL DEFAULT "0" COMMENT "空值",
  `hour_3firstpaynum` int(11) NULL DEFAULT "0" COMMENT "空值",
  `hour_4firstpaynum` int(11) NULL DEFAULT "0" COMMENT "空值",
  `hour_5firstpaynum` int(11) NULL DEFAULT "0" COMMENT "空值",
  `hour_6firstpaynum` int(11) NULL DEFAULT "0" COMMENT "空值",
  `hour_7firstpaynum` int(11) NULL DEFAULT "0" COMMENT "空值",
  `hour_8firstpaynum` int(11) NULL DEFAULT "0" COMMENT "空值",
  `hour_9firstpaynum` int(11) NULL DEFAULT "0" COMMENT "空值",
  `hour_10firstpaynum` int(11) NULL DEFAULT "0" COMMENT "空值",
  `hour_11firstpaynum` int(11) NULL DEFAULT "0" COMMENT "空值",
  `hour_12firstpaynum` int(11) NULL DEFAULT "0" COMMENT "空值",
  `hour_13firstpaynum` int(11) NULL DEFAULT "0" COMMENT "空值",
  `hour_14firstpaynum` int(11) NULL DEFAULT "0" COMMENT "空值",
  `hour_15firstpaynum` int(11) NULL DEFAULT "0" COMMENT "空值",
  `hour_16firstpaynum` int(11) NULL DEFAULT "0" COMMENT "空值",
  `hour_17firstpaynum` int(11) NULL DEFAULT "0" COMMENT "空值",
  `hour_18firstpaynum` int(11) NULL DEFAULT "0" COMMENT "空值",
  `hour_19firstpaynum` int(11) NULL DEFAULT "0" COMMENT "空值",
  `hour_20firstpaynum` int(11) NULL DEFAULT "0" COMMENT "空值",
  `hour_21firstpaynum` int(11) NULL DEFAULT "0" COMMENT "空值",
  `hour_22firstpaynum` int(11) NULL DEFAULT "0" COMMENT "空值",
  `hour_23firstpaynum` int(11) NULL DEFAULT "0" COMMENT "空值",
  `hour_0paynum` int(11) NULL DEFAULT "0" COMMENT "[0,1) 小时支付次数",
  `hour_1paynum` int(11) NULL DEFAULT "0" COMMENT "[1,2) 小时支付次数",
  `hour_2paynum` int(11) NULL DEFAULT "0" COMMENT "[2,3) 小时支付次数",
  `hour_3paynum` int(11) NULL DEFAULT "0" COMMENT "[3,4) 小时支付次数",
  `hour_4paynum` int(11) NULL DEFAULT "0" COMMENT "[4,5) 小时支付次数",
  `hour_5paynum` int(11) NULL DEFAULT "0" COMMENT "[5,6) 小时支付次数",
  `hour_6paynum` int(11) NULL DEFAULT "0" COMMENT "[6,7) 小时支付次数",
  `hour_7paynum` int(11) NULL DEFAULT "0" COMMENT "[7,8) 小时支付次数",
  `hour_8paynum` int(11) NULL DEFAULT "0" COMMENT "[8,9) 小时支付次数",
  `hour_9paynum` int(11) NULL DEFAULT "0" COMMENT "[9,10) 小时支付次数",
  `hour_10paynum` int(11) NULL DEFAULT "0" COMMENT "[10,11) 小时支付次数",
  `hour_11paynum` int(11) NULL DEFAULT "0" COMMENT "[11,12) 小时支付次数",
  `hour_12paynum` int(11) NULL DEFAULT "0" COMMENT "[12,13) 小时支付次数",
  `hour_13paynum` int(11) NULL DEFAULT "0" COMMENT "[13,14) 小时支付次数",
  `hour_14paynum` int(11) NULL DEFAULT "0" COMMENT "[14,15) 小时支付次数",
  `hour_15paynum` int(11) NULL DEFAULT "0" COMMENT "[15,16) 小时支付次数",
  `hour_16paynum` int(11) NULL DEFAULT "0" COMMENT "[16,17) 小时支付次数",
  `hour_17paynum` int(11) NULL DEFAULT "0" COMMENT "[17,18) 小时支付次数",
  `hour_18paynum` int(11) NULL DEFAULT "0" COMMENT "[18,19) 小时支付次数",
  `hour_19paynum` int(11) NULL DEFAULT "0" COMMENT "[19,20) 小时支付次数",
  `hour_20paynum` int(11) NULL DEFAULT "0" COMMENT "[20,21) 小时支付次数",
  `hour_21paynum` int(11) NULL DEFAULT "0" COMMENT "[21,22) 小时支付次数",
  `hour_22paynum` int(11) NULL DEFAULT "0" COMMENT "[22,23) 小时支付次数",
  `hour_23paynum` int(11) NULL DEFAULT "0" COMMENT "[23,24) 小时支付次数",
  `payordernum` int(11) NULL DEFAULT "0" COMMENT "充值订单总数",
  `ad_name` varchar(350) NULL COMMENT "广告名称",
  `nick_name` varchar(350) NULL COMMENT "昵称",
  `campaign_name` varchar(350) NULL COMMENT "",
  `product_name` varchar(350) NULL COMMENT "",
  `account_id` varchar(65533) NULL COMMENT "账户id",
  `etl_time` datetime NULL COMMENT "清洗时间"
) ENGINE=OLAP 
PRIMARY KEY(`ad_id`, `create_time`)
COMMENT "国剧消费收入小时数据"
DISTRIBUTED BY HASH(`ad_id`) BUCKETS 1 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
