CREATE TABLE `dws_advertisement_ad_cost_recharge_byhour_cst_ed` (
  `dt` date NOT NULL COMMENT "日期，广告投放日期",
  `product_id` smallint(6) NULL COMMENT "产品id",
  `ad_id` varchar(65533) NULL COMMENT "广告id",
  `fb_account` varchar(65533) NULL COMMENT "Facebook账户",
  `source_chl` varchar(65533) NULL COMMENT "投放渠道",
  `ads_type` varchar(65533) NULL COMMENT "广告类型",
  `ads_quality` varchar(65533) NULL COMMENT "广告质量",
  `ad_name` varchar(65533) NULL COMMENT "广告名称",
  `product_name` varchar(65533) NULL COMMENT "产品账号名",
  `ad_campname` varchar(65533) NULL COMMENT "广告系列名称",
  `ad_camp_id` varchar(65533) NULL COMMENT "广告系列",
  `ad_set_id` varchar(65533) NULL COMMENT "广告组id",
  `ad_setname` varchar(65533) NULL COMMENT "广告组名称",
  `book_id` bigint(20) NULL COMMENT "书籍id",
  `book_name` varchar(65533) NULL COMMENT "书籍名称",
  `book_channel` int(11) NULL COMMENT "书籍类型",
  `book_nature` int(11) NULL COMMENT "书籍来源",
  `ads_optimizer` varchar(65533) NULL COMMENT "优化师",
  `ads_optimizer_group` varchar(65533) NULL COMMENT "优化师组",
  `corever` int(11) NULL COMMENT "core",
  `mt` int(11) NULL COMMENT "平台",
  `current_language2` int(11) NULL COMMENT "投放语言",
  `reg_num` bigint(20) NULL COMMENT "注册数",
  `dev_num` bigint(20) NULL COMMENT "激活数",
  `cost_amount` decimal(24, 8) NULL COMMENT "花费",
  `hour0_amount` decimal(24, 8) NULL COMMENT "新增时段+1h的充值收入，例，23点新增用户，0:00~1:00的充值收入，非累计",
  `hour1_amount` decimal(24, 8) NULL COMMENT "新增时段+1h的充值收入，例，0点新增用户，1:00~2:00的充值收入，非累计",
  `hour2_amount` decimal(24, 8) NULL COMMENT " ",
  `hour3_amount` decimal(24, 8) NULL COMMENT " ",
  `hour4_amount` decimal(24, 8) NULL COMMENT " ",
  `hour5_amount` decimal(24, 8) NULL COMMENT " ",
  `hour6_amount` decimal(24, 8) NULL COMMENT " ",
  `hour7_amount` decimal(24, 8) NULL COMMENT " ",
  `hour8_amount` decimal(24, 8) NULL COMMENT " ",
  `hour9_amount` decimal(24, 8) NULL COMMENT " ",
  `hour10_amount` decimal(24, 8) NULL COMMENT " ",
  `hour11_amount` decimal(24, 8) NULL COMMENT " ",
  `hour12_amount` decimal(24, 8) NULL COMMENT " ",
  `hour13_amount` decimal(24, 8) NULL COMMENT " ",
  `hour14_amount` decimal(24, 8) NULL COMMENT " ",
  `hour15_amount` decimal(24, 8) NULL COMMENT " ",
  `hour16_amount` decimal(24, 8) NULL COMMENT " ",
  `hour17_amount` decimal(24, 8) NULL COMMENT " ",
  `hour18_amount` decimal(24, 8) NULL COMMENT " ",
  `hour19_amount` decimal(24, 8) NULL COMMENT " ",
  `hour20_amount` decimal(24, 8) NULL COMMENT " ",
  `hour21_amount` decimal(24, 8) NULL COMMENT " ",
  `hour22_amount` decimal(24, 8) NULL COMMENT " ",
  `hour23_amount` decimal(24, 8) NULL COMMENT " ",
  `etl_tm` datetime NULL COMMENT "数据清洗时间",
  INDEX index_product_id (`product_id`) USING BITMAP COMMENT '产品id索引'
) ENGINE=OLAP 
DUPLICATE KEY(`dt`, `product_id`, `ad_id`)
COMMENT "投放广告用户24小时段充值收入表-CST时区"
DISTRIBUTED BY HASH(`dt`, `product_id`, `ad_id`) BUCKETS 5 
PROPERTIES (
"replication_num" = "3",
"bloom_filter_columns" = "dt",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
);
