----------------------------------------------------------------
-- 程序功能： 公共码表
-- 程序名： P_dim_pub_code_mapping_dict
-- 目标表： dim.dim_pub_code_mapping_dict
-- 负责人： qhr
-- 开发日期： 2023-08-24
-- 备注： 更新（修改 / 新增）请联系qhr！！！
----------------------------------------------------------------

insert into dim.dim_pub_code_mapping_dict
(app_plat,cd_col,cd_val,cd_col_desc,cd_val_desc,p_cd_col,p_cd_col_desc,p_cd_val,p_cd_desc)
values
 ('beidou', 'biz_type_cd', '2', '业务类型编码', '国剧',NULL,NULL,NULL,NULL)
,('beidou', 'biz_type_cd', '3', '业务类型编码', '海剧',NULL,NULL,NULL,NULL)
,('beidou', 'product_id', '1111', 'product_id', '小程序',NULL,NULL,NULL,NULL)
,('beidou', 'product_id', '2311', 'product_id', '圣经项目',NULL,NULL,NULL,NULL)
,('beidou', 'product_id', '3311', 'product_id', '法语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3322', 'product_id', '葡语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3333', 'product_id', '繁体畅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3366', 'product_id', '英文阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3371', 'product_id', '俄语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3388', 'product_id', '西语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3399', 'product_id', '日语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3501', 'product_id', '印尼语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3511', 'product_id', '泰语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3521', 'product_id', '越南语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3531', 'product_id', '韩语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3541', 'product_id', '菲律宾语', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3561', 'product_id', '德语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3571', 'product_id', '意大利语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3581', 'product_id', '阿拉伯语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3591', 'product_id', '印地语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3611', 'product_id', '孟加拉语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3621', 'product_id', '土耳其语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3631', 'product_id', '马来西亚语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '6773', 'product_id', '国内阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '6833', 'product_id', '海外短剧', 'biz_type_cd', '业务类型编码', '3', '海剧')
,('beidou', 'product_id', '6883', 'product_id', '国内短剧', 'biz_type_cd', '业务类型编码', '2', '国剧')
,('beidou', 'product_id', '7757', 'product_id', '新安卓读书',NULL,NULL,NULL,NULL)
,('beidou', 'product_id', '7777', 'product_id', '安卓读书',NULL,NULL,NULL,NULL)
,('beidou', 'product_id', '8211', 'product_id',NULL, 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '8858', 'product_id', '新畅读读书',NULL,NULL,NULL,NULL)
,('beidou', 'product_id', '8888', 'product_id', '畅读书城',NULL,NULL,NULL,NULL)
,('pub', 'biz_type_cd', '1', '业务类型编码', '海阅',NULL,NULL,NULL,NULL)
,('pub', 'biz_type_cd', '2', '业务类型编码', '海剧',NULL,NULL,NULL,NULL)
,('pub', 'biz_type_cd', '3', '业务类型编码', '国剧',NULL,NULL,NULL,NULL)
,('pub', 'book_lang_cd', '322', '书籍语言编号', '英语', 'lang_cd', '语言编号', '3', '英语')
,('pub', 'book_lang_cd', '333', '书籍语言编号', '繁体', 'lang_cd', '语言编号', '2', '繁体')
,('pub', 'book_lang_cd', '375', '书籍语言编号', '西语', 'lang_cd', '语言编号', '4', '西语')
,('pub', 'book_lang_cd', '409', '书籍语言编号', '葡语', 'lang_cd', '语言编号', '5', '葡语')
,('pub', 'book_lang_cd', '410', '书籍语言编号', '法语', 'lang_cd', '语言编号', '6', '法语')
,('pub', 'book_lang_cd', '412', '书籍语言编号', '德语', 'lang_cd', '语言编号', '16', '德语')
,('pub', 'book_lang_cd', '413', '书籍语言编号', '意大利语', 'lang_cd', '语言编号', '8', '意大利语')
,('pub', 'book_lang_cd', '414', '书籍语言编号', '印尼语', 'lang_cd', '语言编号', '11', '印尼语')
,('pub', 'book_lang_cd', '415', '书籍语言编号', '阿拉伯语', 'lang_cd', '语言编号', '10', '阿拉伯语')
,('pub', 'book_lang_cd', '418', '书籍语言编号', '俄语', 'lang_cd', '语言编号', '7', '俄语')
,('pub', 'book_lang_cd', '419', '书籍语言编号', '日语', 'lang_cd', '语言编号', '9', '日语')
,('pub', 'book_lang_cd', '433', '书籍语言编号', '泰语', 'lang_cd', '语言编号', '12', '泰语')
,('pub', 'book_lang_cd', '435', '书籍语言编号', '越南语', 'lang_cd', '语言编号', '13', '越南语')
,('pub', 'book_lang_cd', '436', '书籍语言编号', '韩语', 'lang_cd', '语言编号', '14', '韩语')
,('pub', 'book_lang_cd', '445', '书籍语言编号', '菲律宾语', 'lang_cd', '语言编号', '15', '菲律宾语')
,('pub', 'book_lang_cd', '447', '书籍语言编号', '印地语', 'lang_cd', '语言编号', '17', '印地语')
,('pub', 'book_lang_cd', '448', '书籍语言编号', '孟加拉语', 'lang_cd', '语言编号', '18', '孟加拉语')
,('pub', 'book_lang_cd', '495', '书籍语言编号', '马来西亚语', 'lang_cd', '语言编号', '21', '马来西亚语')
,('pub', 'book_lang_cd', '497', '书籍语言编号', '土耳其语', 'lang_cd', '语言编号', '22', '土耳其语')
,('pub', 'lang_abbr', 'ar', '语言缩写', '阿拉伯语', 'lang_cd', '语言编号', '10', '阿拉伯语')
,('pub', 'lang_abbr', 'bn', '语言缩写', '孟加拉语', 'lang_cd', '语言编号', '18', '孟加拉语')
,('pub', 'lang_abbr', 'de', '语言缩写', '德语', 'lang_cd', '语言编号', '16', '德语')
,('pub', 'lang_abbr', 'en', '语言缩写', '英语', 'lang_cd', '语言编号', '3', '英语')
,('pub', 'lang_abbr', 'fr', '语言缩写', '法语', 'lang_cd', '语言编号', '6', '法语')
,('pub', 'lang_abbr', 'ft', '语言缩写', '繁体', 'lang_cd', '语言编号', '2', '繁体')
,('pub', 'lang_abbr', 'hi', '语言缩写', '印地语', 'lang_cd', '语言编号', '17', '印地语')
,('pub', 'lang_abbr', 'id', '语言缩写', '印尼语', 'lang_cd', '语言编号', '11', '印尼语')
,('pub', 'lang_abbr', 'it', '语言缩写', '意大利语', 'lang_cd', '语言编号', '8', '意大利语')
,('pub', 'lang_abbr', 'jp', '语言缩写', '日语', 'lang_cd', '语言编号', '9', '日语')
,('pub', 'lang_abbr', 'kr', '语言缩写', '韩语', 'lang_cd', '语言编号', '14', '韩语')
,('pub', 'lang_abbr', 'my', '语言缩写', '马来西亚语', 'lang_cd', '语言编号', '21', '马来西亚语')
,('pub', 'lang_abbr', 'pt', '语言缩写', '葡语', 'lang_cd', '语言编号', '5', '葡语')
,('pub', 'lang_abbr', 'ru', '语言缩写', '俄语', 'lang_cd', '语言编号', '7', '俄语')
,('pub', 'lang_abbr', 'sp', '语言缩写', '西语', 'lang_cd', '语言编号', '4', '西语')
,('pub', 'lang_abbr', 'th', '语言缩写', '泰语', 'lang_cd', '语言编号', '12', '泰语')
,('pub', 'lang_abbr', 'tl', '语言缩写', '菲律宾语', 'lang_cd', '语言编号', '15', '菲律宾语')
,('pub', 'lang_abbr', 'tr', '语言缩写', '土耳其语', 'lang_cd', '语言编号', '22', '土耳其语')
,('pub', 'lang_abbr', 'vi', '语言缩写', '越南语', 'lang_cd', '语言编号', '13', '越南语')
,('pub', 'lang_cd', '1', '语言编号', '简体',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '10', '语言编号', '阿拉伯语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '11', '语言编号', '印尼语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '12', '语言编号', '泰语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '13', '语言编号', '越南语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '14', '语言编号', '韩语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '15', '语言编号', '菲律宾语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '16', '语言编号', '德语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '17', '语言编号', '印地语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '18', '语言编号', '孟加拉语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '2', '语言编号', '繁体',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '21', '语言编号', '马来西亚语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '22', '语言编号', '土耳其语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '3', '语言编号', '英语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '4', '语言编号', '西语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '5', '语言编号', '葡语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '6', '语言编号', '法语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '7', '语言编号', '俄语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '8', '语言编号', '意大利语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '9', '语言编号', '日语',NULL,NULL,NULL,NULL)
,('pub', 'mt', '0', '移动终端', '其他',NULL,NULL,NULL,NULL)
,('pub', 'mt', '1', '移动终端', 'iOS',NULL,NULL,NULL,NULL)
,('pub', 'mt', '12', '移动终端', '小程序',NULL,NULL,NULL,NULL)
,('pub', 'mt', '13', '移动终端', 'h5漫画',NULL,NULL,NULL,NULL)
,('pub', 'mt', '14', '移动终端', '轻应用',NULL,NULL,NULL,NULL)
,('pub', 'mt', '15', '移动终端', '百度小程序',NULL,NULL,NULL,NULL)
,('pub', 'mt', '16', '移动终端', '支付宝小程序',NULL,NULL,NULL,NULL)
,('pub', 'mt', '17', '移动终端', 'QQ小程序',NULL,NULL,NULL,NULL)
,('pub', 'mt', '4', '移动终端', 'Android',NULL,NULL,NULL,NULL)
,('pub', 'mt', '7', '移动终端', 'ipad',NULL,NULL,NULL,NULL)
,('pub', 'mt', '9', '移动终端', 'h5书城',NULL,NULL,NULL,NULL)
,('pub', 'product_id', '1111', 'product_id', '小程序',NULL,NULL,NULL,NULL)
,('pub', 'product_id', '2311', 'product_id', '圣经项目',NULL,NULL,NULL,NULL)
,('pub', 'product_id', '3311', 'product_id', '法语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3322', 'product_id', '葡语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3333', 'product_id', '繁体畅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3366', 'product_id', '英文阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3371', 'product_id', '俄语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3388', 'product_id', '西语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3399', 'product_id', '日语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3501', 'product_id', '印尼语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3511', 'product_id', '泰语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3521', 'product_id', '越南语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3531', 'product_id', '韩语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3541', 'product_id', '菲律宾语', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3561', 'product_id', '德语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3571', 'product_id', '意大利语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3581', 'product_id', '阿拉伯语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3591', 'product_id', '印地语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3611', 'product_id', '孟加拉语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3621', 'product_id', '土耳其语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3631', 'product_id', '马来西亚语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '6773', 'product_id', '国内阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '6833', 'product_id', '海外短剧', 'biz_type_cd', '业务类型编码', '2', '海剧')
,('pub', 'product_id', '6883', 'product_id', '国内短剧', 'biz_type_cd', '业务类型编码', '3', '国剧')
,('pub', 'product_id', '7757', 'product_id', '新安卓读书',NULL,NULL,NULL,NULL)
,('pub', 'product_id', '7777', 'product_id', '安卓读书',NULL,NULL,NULL,NULL)
,('pub', 'product_id', '8211', 'product_id',NULL, 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '8858', 'product_id', '新畅读读书',NULL,NULL,NULL,NULL)
,('pub', 'product_id', '8888', 'product_id', '畅读书城',NULL,NULL,NULL,NULL)
,('pub', 'ad_src', '4', '广告来源', 'Starmobi', NULL, NULL, NULL, NULL)
,('pub', 'ad_src', '5', '广告来源', 'MobKing', NULL, NULL, NULL, NULL)
,('pub', 'ad_src', '6', '广告来源', 'pengpai', NULL, NULL, NULL, NULL)
,('pub', 'ad_src', '7', '广告来源', 'Starmobi_2', NULL, NULL, NULL, NULL)
,('pub', 'ad_src', '8', '广告来源', 'synjoy', NULL, NULL, NULL, NULL)
;