----------------------------------------------------------------
-- 程序功能： 公共码表
-- 程序名： P_dim_pub_code_mapping_dict
-- 目标表： dim.dim_pub_code_mapping_dict
-- 负责人： qhr
-- 开发日期： 2023-08-24
-- 备注： 更新（修改 / 新增）请联系qhr！！！
----------------------------------------------------------------

insert into dim.dim_pub_code_mapping_dict
(app_plat,cd_col,cd_val,cd_col_desc,cd_val_desc,p_cd_col,p_cd_col_desc,p_cd_val,p_cd_desc)
values
 ('beidou', 'biz_type_cd', '2', '业务类型编码', '国剧',NULL,NULL,NULL,NULL)
,('beidou', 'biz_type_cd', '3', '业务类型编码', '海剧',NULL,NULL,NULL,NULL)
,('beidou', 'product_id', '1111', 'product_id', '小程序',NULL,NULL,NULL,NULL)
,('beidou', 'product_id', '2311', 'product_id', '圣经项目',NULL,NULL,NULL,NULL)
,('beidou', 'product_id', '3311', 'product_id', '法语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3322', 'product_id', '葡语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3333', 'product_id', '繁体畅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3366', 'product_id', '英文阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3371', 'product_id', '俄语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3388', 'product_id', '西语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3399', 'product_id', '日语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3501', 'product_id', '印尼语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3511', 'product_id', '泰语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3521', 'product_id', '越南语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3531', 'product_id', '韩语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3541', 'product_id', '菲律宾语', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3561', 'product_id', '德语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3571', 'product_id', '意大利语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3581', 'product_id', '阿拉伯语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3591', 'product_id', '印地语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3611', 'product_id', '孟加拉语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3621', 'product_id', '土耳其语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '3631', 'product_id', '马来西亚语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '6773', 'product_id', '国内阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '6833', 'product_id', '海外短剧', 'biz_type_cd', '业务类型编码', '3', '海剧')
,('beidou', 'product_id', '6883', 'product_id', '国内短剧', 'biz_type_cd', '业务类型编码', '2', '国剧')
,('beidou', 'product_id', '7757', 'product_id', '新安卓读书',NULL,NULL,NULL,NULL)
,('beidou', 'product_id', '7777', 'product_id', '安卓读书',NULL,NULL,NULL,NULL)
,('beidou', 'product_id', '8211', 'product_id',NULL, 'biz_type_cd', '业务类型编码', '1', '海阅')
,('beidou', 'product_id', '8858', 'product_id', '新畅读读书',NULL,NULL,NULL,NULL)
,('beidou', 'product_id', '8888', 'product_id', '畅读书城',NULL,NULL,NULL,NULL)
,('pub', 'biz_type_cd', '1', '业务类型编码', '海阅',NULL,NULL,NULL,NULL)
,('pub', 'biz_type_cd', '2', '业务类型编码', '海剧',NULL,NULL,NULL,NULL)
,('pub', 'biz_type_cd', '3', '业务类型编码', '国剧',NULL,NULL,NULL,NULL)
,('pub', 'book_lang_cd', '322', '书籍语言编号', '英语', 'lang_cd', '语言编号', '3', '英语')
,('pub', 'book_lang_cd', '333', '书籍语言编号', '繁体', 'lang_cd', '语言编号', '2', '繁体')
,('pub', 'book_lang_cd', '375', '书籍语言编号', '西语', 'lang_cd', '语言编号', '4', '西语')
,('pub', 'book_lang_cd', '409', '书籍语言编号', '葡语', 'lang_cd', '语言编号', '5', '葡语')
,('pub', 'book_lang_cd', '410', '书籍语言编号', '法语', 'lang_cd', '语言编号', '6', '法语')
,('pub', 'book_lang_cd', '412', '书籍语言编号', '德语', 'lang_cd', '语言编号', '16', '德语')
,('pub', 'book_lang_cd', '413', '书籍语言编号', '意大利语', 'lang_cd', '语言编号', '8', '意大利语')
,('pub', 'book_lang_cd', '414', '书籍语言编号', '印尼语', 'lang_cd', '语言编号', '11', '印尼语')
,('pub', 'book_lang_cd', '415', '书籍语言编号', '阿拉伯语', 'lang_cd', '语言编号', '10', '阿拉伯语')
,('pub', 'book_lang_cd', '418', '书籍语言编号', '俄语', 'lang_cd', '语言编号', '7', '俄语')
,('pub', 'book_lang_cd', '419', '书籍语言编号', '日语', 'lang_cd', '语言编号', '9', '日语')
,('pub', 'book_lang_cd', '433', '书籍语言编号', '泰语', 'lang_cd', '语言编号', '12', '泰语')
,('pub', 'book_lang_cd', '435', '书籍语言编号', '越南语', 'lang_cd', '语言编号', '13', '越南语')
,('pub', 'book_lang_cd', '436', '书籍语言编号', '韩语', 'lang_cd', '语言编号', '14', '韩语')
,('pub', 'book_lang_cd', '445', '书籍语言编号', '菲律宾语', 'lang_cd', '语言编号', '15', '菲律宾语')
,('pub', 'book_lang_cd', '447', '书籍语言编号', '印地语', 'lang_cd', '语言编号', '17', '印地语')
,('pub', 'book_lang_cd', '448', '书籍语言编号', '孟加拉语', 'lang_cd', '语言编号', '18', '孟加拉语')
,('pub', 'book_lang_cd', '495', '书籍语言编号', '马来西亚语', 'lang_cd', '语言编号', '21', '马来西亚语')
,('pub', 'book_lang_cd', '497', '书籍语言编号', '土耳其语', 'lang_cd', '语言编号', '22', '土耳其语')
,('pub', 'lang_abbr', 'ar', '语言缩写', '阿拉伯语', 'lang_cd', '语言编号', '10', '阿拉伯语')
,('pub', 'lang_abbr', 'bn', '语言缩写', '孟加拉语', 'lang_cd', '语言编号', '18', '孟加拉语')
,('pub', 'lang_abbr', 'de', '语言缩写', '德语', 'lang_cd', '语言编号', '16', '德语')
,('pub', 'lang_abbr', 'en', '语言缩写', '英语', 'lang_cd', '语言编号', '3', '英语')
,('pub', 'lang_abbr', 'fr', '语言缩写', '法语', 'lang_cd', '语言编号', '6', '法语')
,('pub', 'lang_abbr', 'ft', '语言缩写', '繁体', 'lang_cd', '语言编号', '2', '繁体')
,('pub', 'lang_abbr', 'hi', '语言缩写', '印地语', 'lang_cd', '语言编号', '17', '印地语')
,('pub', 'lang_abbr', 'id', '语言缩写', '印尼语', 'lang_cd', '语言编号', '11', '印尼语')
,('pub', 'lang_abbr', 'it', '语言缩写', '意大利语', 'lang_cd', '语言编号', '8', '意大利语')
,('pub', 'lang_abbr', 'jp', '语言缩写', '日语', 'lang_cd', '语言编号', '9', '日语')
,('pub', 'lang_abbr', 'kr', '语言缩写', '韩语', 'lang_cd', '语言编号', '14', '韩语')
,('pub', 'lang_abbr', 'my', '语言缩写', '马来西亚语', 'lang_cd', '语言编号', '21', '马来西亚语')
,('pub', 'lang_abbr', 'pt', '语言缩写', '葡语', 'lang_cd', '语言编号', '5', '葡语')
,('pub', 'lang_abbr', 'ru', '语言缩写', '俄语', 'lang_cd', '语言编号', '7', '俄语')
,('pub', 'lang_abbr', 'sp', '语言缩写', '西语', 'lang_cd', '语言编号', '4', '西语')
,('pub', 'lang_abbr', 'th', '语言缩写', '泰语', 'lang_cd', '语言编号', '12', '泰语')
,('pub', 'lang_abbr', 'tl', '语言缩写', '菲律宾语', 'lang_cd', '语言编号', '15', '菲律宾语')
,('pub', 'lang_abbr', 'tr', '语言缩写', '土耳其语', 'lang_cd', '语言编号', '22', '土耳其语')
,('pub', 'lang_abbr', 'vi', '语言缩写', '越南语', 'lang_cd', '语言编号', '13', '越南语')
,('pub', 'lang_cd', '1', '语言编号', '简体',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '10', '语言编号', '阿拉伯语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '11', '语言编号', '印尼语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '12', '语言编号', '泰语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '13', '语言编号', '越南语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '14', '语言编号', '韩语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '15', '语言编号', '菲律宾语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '16', '语言编号', '德语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '17', '语言编号', '印地语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '18', '语言编号', '孟加拉语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '2', '语言编号', '繁体',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '21', '语言编号', '马来西亚语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '22', '语言编号', '土耳其语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '3', '语言编号', '英语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '4', '语言编号', '西语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '5', '语言编号', '葡语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '6', '语言编号', '法语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '7', '语言编号', '俄语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '8', '语言编号', '意大利语',NULL,NULL,NULL,NULL)
,('pub', 'lang_cd', '9', '语言编号', '日语',NULL,NULL,NULL,NULL)
,('pub', 'mt', '0', '移动终端', '其他',NULL,NULL,NULL,NULL)
,('pub', 'mt', '1', '移动终端', 'iOS',NULL,NULL,NULL,NULL)
,('pub', 'mt', '12', '移动终端', '小程序',NULL,NULL,NULL,NULL)
,('pub', 'mt', '13', '移动终端', 'h5漫画',NULL,NULL,NULL,NULL)
,('pub', 'mt', '14', '移动终端', '轻应用',NULL,NULL,NULL,NULL)
,('pub', 'mt', '15', '移动终端', '百度小程序',NULL,NULL,NULL,NULL)
,('pub', 'mt', '16', '移动终端', '支付宝小程序',NULL,NULL,NULL,NULL)
,('pub', 'mt', '17', '移动终端', 'QQ小程序',NULL,NULL,NULL,NULL)
,('pub', 'mt', '4', '移动终端', 'Android',NULL,NULL,NULL,NULL)
,('pub', 'mt', '7', '移动终端', 'ipad',NULL,NULL,NULL,NULL)
,('pub', 'mt', '9', '移动终端', 'h5书城',NULL,NULL,NULL,NULL)
,('pub', 'product_id', '1111', 'product_id', '小程序',NULL,NULL,NULL,NULL)
,('pub', 'product_id', '2311', 'product_id', '圣经项目',NULL,NULL,NULL,NULL)
,('pub', 'product_id', '3311', 'product_id', '法语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3322', 'product_id', '葡语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3333', 'product_id', '繁体畅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3366', 'product_id', '英文阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3371', 'product_id', '俄语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3388', 'product_id', '西语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3399', 'product_id', '日语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3501', 'product_id', '印尼语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3511', 'product_id', '泰语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3521', 'product_id', '越南语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3531', 'product_id', '韩语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3541', 'product_id', '菲律宾语', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3561', 'product_id', '德语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3571', 'product_id', '意大利语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3581', 'product_id', '阿拉伯语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3591', 'product_id', '印地语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3611', 'product_id', '孟加拉语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3621', 'product_id', '土耳其语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '3631', 'product_id', '马来西亚语阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '6773', 'product_id', '国内阅读', 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '6833', 'product_id', '海外短剧', 'biz_type_cd', '业务类型编码', '2', '海剧')
,('pub', 'product_id', '6883', 'product_id', '国内短剧', 'biz_type_cd', '业务类型编码', '3', '国剧')
,('pub', 'product_id', '7757', 'product_id', '新安卓读书',NULL,NULL,NULL,NULL)
,('pub', 'product_id', '7777', 'product_id', '安卓读书',NULL,NULL,NULL,NULL)
,('pub', 'product_id', '8211', 'product_id',NULL, 'biz_type_cd', '业务类型编码', '1', '海阅')
,('pub', 'product_id', '8858', 'product_id', '新畅读读书',NULL,NULL,NULL,NULL)
,('pub', 'product_id', '8888', 'product_id', '畅读书城',NULL,NULL,NULL,NULL)
,('pub', 'ad_src', '4', '广告来源', 'Starmobi', NULL, NULL, NULL, NULL)
,('pub', 'ad_src', '5', '广告来源', 'MobKing', NULL, NULL, NULL, NULL)
,('pub', 'ad_src', '6', '广告来源', 'pengpai', NULL, NULL, NULL, NULL)
,('pub', 'ad_src', '7', '广告来源', 'Starmobi_2', NULL, NULL, NULL, NULL)
,('pub', 'ad_src', '8', '广告来源', 'synjoy', NULL, NULL, NULL, NULL)
,('pub', 'prd_lang_cd', '7757', '产品语言编码', '简体中文', 'product_id', '7757', 'product_id', '新安卓读书')
,('pub', 'prd_lang_cd', '3311', '产品语言编码', '法语', 'product_id', '3311', 'product_id', '法语阅读')
,('pub', 'prd_lang_cd', '3333', '产品语言编码', '繁体', 'product_id', '3333', 'product_id', '繁体畅读')
,('pub', 'prd_lang_cd', '3399', '产品语言编码', '日语', 'product_id', '3399', 'product_id', '日语阅读')
,('pub', 'prd_lang_cd', '3501', '产品语言编码', '印尼语', 'product_id', '3501', 'product_id', '印尼语阅读')
,('pub', 'prd_lang_cd', '3511', '产品语言编码', '泰语', 'product_id', '3511', 'product_id', '泰语阅读')
,('pub', 'prd_lang_cd', '8858', '产品语言编码', '简体中文', 'product_id', '8858', 'product_id', '新畅读读书')
,('pub', 'prd_lang_cd', '8888', '产品语言编码', '简体中文', 'product_id', '8888', 'product_id', '畅读书城')
,('pub', 'prd_lang_cd', '6833', '产品语言编码', '海外短剧', 'product_id', '6833', 'product_id', '海外短剧')
,('pub', 'prd_lang_cd', '6883', '产品语言编码', '国内短剧', 'product_id', '6883', 'product_id', '国内短剧')
,('pub', 'prd_lang_cd', '3322', '产品语言编码', '葡语', 'product_id', '3322', 'product_id', '葡语阅读')
,('pub', 'prd_lang_cd', '3366', '产品语言编码', '英语', 'product_id', '3366', 'product_id', '英文阅读')
,('pub', 'prd_lang_cd', '3371', '产品语言编码', '俄语', 'product_id', '3371', 'product_id', '俄语阅读')
,('pub', 'prd_lang_cd', '3388', '产品语言编码', '西语', 'product_id', '3388', 'product_id', '西语阅读')
,('pub', 'prd_lang_cd', '1111', '产品语言编码', '小程序', 'product_id', '1111', 'product_id', '小程序')
,('pub', 'prd_lang_cd', '7777', '产品语言编码', '安卓读书', 'product_id', '7777', 'product_id', '安卓读书')
,('pub', 'prd_lang_cd', '3581', '产品语言编码', '阿拉伯语', 'product_id', '3581', 'product_id', '阿拉伯语阅读')
,('pub', 'prd_lang_cd', '3631', '产品语言编码', '马来西亚语', 'product_id', '3631', 'product_id', '马来西亚语阅读')
,('pub', 'ctry_cd', 'BT', '国家编码', '不丹', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'TL', '国家编码', '东帝汶', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'CN', '国家编码', '中国', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'CF', '国家编码', '中非', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'DK', '国家编码', '丹麦', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'UA', '国家编码', '乌克兰', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'UZ', '国家编码', '乌兹别克斯坦', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'UG', '国家编码', '乌干达', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'UY', '国家编码', '乌拉圭', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'TD', '国家编码', '乍得', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'YE', '国家编码', '也门', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'AM', '国家编码', '亚美尼亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'IL', '国家编码', '以色列', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'IQ', '国家编码', '伊拉克', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'IR', '国家编码', '伊朗', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'BZ', '国家编码', '伯利兹', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'CV', '国家编码', '佛得角', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'RU', '国家编码', '俄罗斯联邦', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'BG', '国家编码', '保加利亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'HR', '国家编码', '克罗地亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'GU', '国家编码', '关岛', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'GM', '国家编码', '冈比亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'IS', '国家编码', '冰岛', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'GN', '国家编码', '几内亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'GW', '国家编码', '几内亚比绍', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'LI', '国家编码', '列支敦士登', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'CG', '国家编码', '刚果（布）', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'CD', '国家编码', '刚果（金）', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'LY', '国家编码', '利比亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'LR', '国家编码', '利比里亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'MK', '国家编码', '前南马其顿', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'CA', '国家编码', '加拿大', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'GH', '国家编码', '加纳', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'GA', '国家编码', '加蓬', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'HU', '国家编码', '匈牙利', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'MP', '国家编码', '北马里亚纳', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'GS', '国家编码', '南乔治亚岛和南桑德韦奇岛', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'AQ', '国家编码', '南极洲', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'SS', '国家编码', '南苏丹', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'ZA', '国家编码', '南非', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'BW', '国家编码', '博茨瓦纳', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'QA', '国家编码', '卡塔尔', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'RW', '国家编码', '卢旺达', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'LU', '国家编码', '卢森堡', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'IN', '国家编码', '印度', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'ID', '国家编码', '印度尼西亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'GT', '国家编码', '危地马拉', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'EC', '国家编码', '厄瓜多尔', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'ER', '国家编码', '厄立特里亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'SY', '国家编码', '叙利亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'CU', '国家编码', '古巴', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'TW', '国家编码', '中国台湾', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'KG', '国家编码', '吉尔吉斯斯坦', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'DJ', '国家编码', '吉布提', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'KZ', '国家编码', '哈萨克斯坦', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'CO', '国家编码', '哥伦比亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'CR', '国家编码', '哥斯达黎加', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'CM', '国家编码', '喀麦隆', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'TV', '国家编码', '图瓦卢', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'TM', '国家编码', '土库曼斯坦', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'TR', '国家编码', '土耳其', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'LC', '国家编码', '圣卢西亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'KN', '国家编码', '圣基茨和尼维斯', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'ST', '国家编码', '圣多美和普林西比', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'BL', '国家编码', '圣巴泰勒米', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'VC', '国家编码', '圣文森特和格林纳丁斯', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'PM', '国家编码', '圣皮埃尔和密克隆', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'CX', '国家编码', '圣诞岛', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'SH', '国家编码', '圣赫勒拿', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'SM', '国家编码', '圣马力诺', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'GY', '国家编码', '圭亚那', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'TZ', '国家编码', '坦桑尼亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'EG', '国家编码', '埃及', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'ET', '国家编码', '埃塞俄比亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'KI', '国家编码', '基里巴斯', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'TJ', '国家编码', '塔吉克斯坦', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'SN', '国家编码', '塞内加尔', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'RS', '国家编码', '塞尔维亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'SL', '国家编码', '塞拉利昂', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'CY', '国家编码', '塞浦路斯', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'SC', '国家编码', '塞舌尔', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'MX', '国家编码', '墨西哥', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'TG', '国家编码', '多哥', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'DM', '国家编码', '多米尼克', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'DO', '国家编码', '多米尼加', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'AX', '国家编码', '奥兰群岛', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'AT', '国家编码', '奥地利', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'VE', '国家编码', '委内瑞拉', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'BD', '国家编码', '孟加拉国', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'AO', '国家编码', '安哥拉', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'AI', '国家编码', '安圭拉', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'AG', '国家编码', '安提瓜和巴布达', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'AD', '国家编码', '安道尔', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'FM', '国家编码', '密克罗尼西亚联邦', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'NI', '国家编码', '尼加拉瓜', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'NG', '国家编码', '尼日利亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'NE', '国家编码', '尼日尔', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'NP', '国家编码', '尼泊尔', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'PS', '国家编码', '巴勒斯坦', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'BS', '国家编码', '巴哈马', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'PK', '国家编码', '巴基斯坦', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'BB', '国家编码', '巴巴多斯', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'PG', '国家编码', '巴布亚新几内亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'PY', '国家编码', '巴拉圭', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'PA', '国家编码', '巴拿马', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'BH', '国家编码', '巴林', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'BR', '国家编码', '巴西', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'BF', '国家编码', '布基纳法索', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'BV', '国家编码', '布维岛', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'BI', '国家编码', '布隆迪', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'GR', '国家编码', '希腊', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'PW', '国家编码', '帕劳', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'CK', '国家编码', '库克群岛', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'CW', '国家编码', '库拉索', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'KY', '国家编码', '开曼群岛', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'DE', '国家编码', '德国', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'IT', '国家编码', '意大利', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'SB', '国家编码', '所罗门群岛', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'TK', '国家编码', '托克劳', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'LV', '国家编码', '拉脱维亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'NO', '国家编码', '挪威', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'CZ', '国家编码', '捷克', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'MD', '国家编码', '摩尔多瓦', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'MA', '国家编码', '摩洛哥', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'MC', '国家编码', '摩纳哥', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'BN', '国家编码', '文莱', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'FJ', '国家编码', '斐济', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'SZ', '国家编码', '斯威士兰', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'SK', '国家编码', '斯洛伐克', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'SI', '国家编码', '斯洛文尼亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'SJ', '国家编码', '斯瓦尔巴岛和扬马延岛', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'LK', '国家编码', '斯里兰卡', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'SG', '国家编码', '新加坡', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'NC', '国家编码', '新喀里多尼亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'NZ', '国家编码', '新西兰', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'JP', '国家编码', '日本', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'CL', '国家编码', '智利', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'KP', '国家编码', '朝鲜', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'KH', '国家编码', '柬埔寨', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'GG', '国家编码', '格恩西岛', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'GD', '国家编码', '格林纳达', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'GL', '国家编码', '格陵兰', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'GE', '国家编码', '格鲁吉亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'VA', '国家编码', '梵蒂冈', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'BE', '国家编码', '比利时', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'MR', '国家编码', '毛里塔尼亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'MU', '国家编码', '毛里求斯', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'TO', '国家编码', '汤加', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'SA', '国家编码', '沙特阿拉伯', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'FR', '国家编码', '法国', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'TF', '国家编码', '法属南部领地', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'MF', '国家编码', '法属圣马丁', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'GF', '国家编码', '法属圭亚那', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'PF', '国家编码', '法属波利尼西亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'FO', '国家编码', '法罗群岛', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'PL', '国家编码', '波兰', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'PR', '国家编码', '波多黎各', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'BA', '国家编码', '波黑', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'TH', '国家编码', '泰国', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'JE', '国家编码', '泽西岛', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'ZW', '国家编码', '津巴布韦', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'HN', '国家编码', '洪都拉斯', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'HT', '国家编码', '海地', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'AU', '国家编码', '澳大利亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'MO', '国家编码', '中国澳门', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'IE', '国家编码', '爱尔兰', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'EE', '国家编码', '爱沙尼亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'JM', '国家编码', '牙买加', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'TC', '国家编码', '特克斯和凯科斯群岛', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'TT', '国家编码', '特立尼达和多巴哥', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'BO', '国家编码', '玻利维亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'NR', '国家编码', '瑙鲁', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'SE', '国家编码', '瑞典', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'CH', '国家编码', '瑞士', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'GP', '国家编码', '瓜德罗普', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'WF', '国家编码', '瓦利斯和富图纳', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'VU', '国家编码', '瓦努阿图', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'RE', '国家编码', '留尼汪', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'BY', '国家编码', '白俄罗斯', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'BM', '国家编码', '百慕大', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'PN', '国家编码', '皮特凯恩', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'GI', '国家编码', '直布罗陀', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'FK', '国家编码', '福克兰群岛（马尔维纳斯）', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'KW', '国家编码', '科威特', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'KM', '国家编码', '科摩罗', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'CI', '国家编码', '科特迪瓦', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'CC', '国家编码', '科科斯（基林）群岛', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'XK', '国家编码', '科索沃', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'PE', '国家编码', '秘鲁', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'TN', '国家编码', '突尼斯', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'LT', '国家编码', '立陶宛', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'SO', '国家编码', '索马里', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'JO', '国家编码', '约旦', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'NA', '国家编码', '纳米比亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'NU', '国家编码', '纽埃', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'MM', '国家编码', '缅甸', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'RO', '国家编码', '罗马尼亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'US', '国家编码', '美国', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'UM', '国家编码', '美国本土外小岛屿', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'VI', '国家编码', '美属维尔京群岛', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'AS', '国家编码', '美属萨摩亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'LA', '国家编码', '老挝', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'KE', '国家编码', '肯尼亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'FI', '国家编码', '芬兰', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'SD', '国家编码', '苏丹', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'SR', '国家编码', '苏里南', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'GB', '国家编码', '英国', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'IM', '国家编码', '英国属地曼岛', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'IO', '国家编码', '英属印度洋领地', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'VG', '国家编码', '英属维尔京群岛', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'NL', '国家编码', '荷兰', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'BQ', '国家编码', '荷兰加勒比', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'AN', '国家编码', '荷属安的列斯', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'MZ', '国家编码', '莫桑比克', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'LS', '国家编码', '莱索托', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'PH', '国家编码', '菲律宾', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'SV', '国家编码', '萨尔瓦多', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'WS', '国家编码', '萨摩亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'PT', '国家编码', '葡萄牙', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'MN', '国家编码', '蒙古', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'MS', '国家编码', '蒙特塞拉特', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'EH', '国家编码', '西撒哈拉', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'ES', '国家编码', '西班牙', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'NF', '国家编码', '诺福克岛', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'BJ', '国家编码', '贝宁', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'ZM', '国家编码', '赞比亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'GQ', '国家编码', '赤道几内亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'HM', '国家编码', '赫德岛和麦克唐纳岛', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'VN', '国家编码', '越南', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'AZ', '国家编码', '阿塞拜疆', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'AF', '国家编码', '阿富汗', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'DZ', '国家编码', '阿尔及利亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'AL', '国家编码', '阿尔巴尼亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'OM', '国家编码', '阿曼', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'AR', '国家编码', '阿根廷', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'AE', '国家编码', '阿联酋', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'AW', '国家编码', '阿鲁巴', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'KR', '国家编码', '韩国', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'HK', '国家编码', '中国香港', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'MV', '国家编码', '马尔代夫', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'MW', '国家编码', '马拉维', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'MQ', '国家编码', '马提尼克', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'MY', '国家编码', '马来西亚', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'YT', '国家编码', '马约特', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'MH', '国家编码', '马绍尔群岛', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'MT', '国家编码', '马耳他', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'MG', '国家编码', '马达加斯加', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'ML', '国家编码', '马里', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'LB', '国家编码', '黎巴嫩', NULL, NULL, NULL, NULL)
,('pub', 'ctry_cd', 'ME', '国家编码', '黑山', NULL, NULL, NULL, NULL)
;